### DISCUSSION TITLE
hosts匹配的问题

### DISCUSSION THREAD

**Discussion by xczh** [IrineSistiana/mosdns#102] [Q&A] [answered]
部分配置文件如下：
```
plugin:
  - tag: server
    type: server
    args:
      entry:
        - use_cache
        - find_hosts
        - main_sequence
      server:
        - addr: 0.0.0.0:53
          protocol: udp
        - addr: 0.0.0.0:53
          protocol: tcp

  - tag: find_hosts
    type: hosts
    args:
      hosts:
        - 'ext:./hosts.txt'
```

`main_sequence`中负责转发到上游DNS服务器查询。现在的问题是：

1. 私有域名域`*.abc`的解析：例如`hello.abc`

该域名已被写入`hosts`中，但是在日志中发现：

```
2021-03-20T14:33:36.785Z	warn	server	server/server_handler.go:88	entry returned an err	{"query": "hello.abc. 28 1 42528 6", "error": "main_sequence: forward_domestic: context deadline exceeded"}
```

该域名在`find_hosts`中被匹配，不应该进入`main_sequence`啊？是配置有误么？

如何配置`*.abc`域名均不转发上游查询，在`hosts.txt`文件中没有，则返回`NXDOMAIN`？

2. 部分反向解析，不应该被转发到上游DNS服务器

日志中发现：
```
2021-03-20T14:41:31.256Z	warn	server	server/server_handler.go:88	entry returned an err	{"query": "lb._dns-sd._udp.0.0.37.10.in-addr.arpa. 12 1 39847 444", "error": "main_sequence: forward_domestic: context deadline exceeded"}
```

`10.37.0.0`属于私有地址网段，不应该被转发到上游查询，请问如何配置？谢谢！

@IrineSistiana
