### DISCUSSION TITLE
一个关于 CNAME 记录和分流相关的问题

### DISCUSSION THREAD

**Discussion by sixg0000d** [IrineSistiana/mosdns#112] [Q&A] [answered]
请问一下，当一个域名匹配并通过本地的 forward 插件转发查询获取到一条 CNAME 记录时，该 CNAME 记录的域名还会从同一个 forward 插件转发请求吗？

我将 mosdns 当作远程 / 本地域名分流器使用，最近发现 `fonts.gstatic.com` 这个域名会被最终解析到国外，而该域名在 geosite:cn 列表中，其实是可以通过国内 DNS 解析出 国内域名的。但是使用 dig 查询该域名的第一条记录是一条 CNAME 记录：
```
;; ANSWER SECTION:
fonts.gstatic.com.      149     IN      CNAME   gstaticadssl.l.google.com.
```
`gstaticadssl.l.google.com` 这个貌似域名不在 geosite:cn 列表当中。而对该域名进行查询，本地和远程 DNS 会获得不同的结果。（我是不是该给 https://github.com/v2fly/domain-list-community 提个 issue / pr ？）

<details>
<summary>mosdns 配置如下</summary>

```yaml
log:
  level: warn
  file: ""

plugin:
  - tag: main_server
    type: server
    args:
      entry: main_sequence
      server:
        - protocol: udp
          addr: 127.0.0.1:1053
        - protocol: tcp
          addr: 127.0.0.1:1053

  - tag: main_sequence
    type: sequence
    args:
      exec:
        - _default_cache
        - if:
            - direct_domain
            - "!_query_is_common"
          exec:
            - forward_local
            - _end
        - forward_remote

  - tag: forward_local
    type: forward
    args:
      upstream:
        - addr: 119.29.29.29:53

  - tag: forward_remote
    type: forward
    args:
      upstream:
        - addr: 8.8.8.8:53
        - addr: 8.8.4.4:53
        - addr: 1.1.1.1:53

  - tag: direct_domain
    type: query_matcher
    args:
      domain:
        - ext:/usr/share/v2ray/geosite.dat:cn
        - ext:./direct.list

```
</details>

**Comment by rampageX** [comment]
你需要解析后做 IP 分流：（两种任选一种）

```
  ## 两种分流逻辑
  - tag: sequence_bypass_local        # 顺序执行的分流逻辑
    type: sequence
    args:
      exec:
        - forward_local               # 先请求转发至本地服务器
        - if:
            - match_local_ip          # 如果应答包含本地 IP
          goto: _end                  # 就直接采用结果
        - forward_remote              # 否则用远程服务器的结果

  - tag: parallel_bypass_local        # 并发执行的分流的逻辑
    type: parallel
    args:
      parallel:
        - - fast_forward_local             # 并发请求本地和远程服务器
          - if:
              - "!match_local_ip"       # 本地服务器返回的非本地 IP 的应答会被丢弃
            exec:
              - _drop_response
        - - fast_forward_remote
```

匹配：

```
  - tag: match_local_ip # 匹配应答的 IP 是否是本地 IP
    type: response_matcher
    args:
      ip:
        - "ext:/root/cfg/geoip.dat:cn"
```
