### DISCUSSION TITLE
blackhole 插件在仅配置 `rcode` 的情况下使用 ttl 插件不生效

### DISCUSSION THREAD

**Discussion by CalmLong** [IrineSistiana/mosdns#117] [Q&A]
如题

adguard home 是可以在返回 NXDOMAIN 的情况下带有 TTL 的

```yaml
log:
  file: /var/log/mosdns/error.log
  level: debug

plugin:
  - type: ecs
    tag: add_ecs
    args:
      auto: true
      force_overwrite: false

  - tag: "change_ttl"
    type: ttl
    args:
      minimal_ttl: 3600
      maximum_ttl: 0

  - tag: "cache"
    type: cache
    args:
      size: 1024000
      cleaner_interval: 30

  - tag: 'block'
    type: 'blackhole'
    args:
      rcode: 3
 
  - tag: 'main_sequence'
    type: sequence
    args:
      exec:
        - add_ecs
        - cache
        - if:
            - is_allow
          exec:
            - forward_local
            - if:
                - on_cn
              exec:
                - _end
            - forward_remote
            - _end
        - if:
            - is_block
          exec:
            - block
            - change_ttl
            - _end
        - if:
            - is_cn
          exec:
            - forward_local
            - _end
        - forward_remote
        - _end
```
