### DISCUSSION TITLE
一个dnsmasq引发的问题

### DISCUSSION THREAD

**Discussion by stupidloud** [IrineSistiana/mosdns#181] [Q&A]
```yaml
log:
  level: debug
  file: ''

plugin:

  - tag: main_server
    type: server
    args:
      entry:
        - _default_cache
        - main_sequence
      server:
        - protocol: udp
          addr: :6553
        - protocol: tcp
          addr: 127.0.0.1:6553
        #- protocol: udp
        #  addr: '[::1]:6553'
        - protocol: tcp
          addr: '[::1]:6553'

  - tag: main_sequence
    type: sequence
    args:
      exec:
        - if_and:
            - '!query_is_local_domain'
            - _qtype_AAAA
          exec:
            - _block_with_empty_response
            - _end

        - if:
            - query_is_local_domain
            - '!_query_is_common'
          exec:
            - forward_local
            - if:
                - response_has_local_ip
              exec:
                - _end

        - primary:
            - forward_local
            - if:
                - '!response_has_local_ip'
              exec:
                - _drop_response
          secondary:
            - forward_remote
            - if:
                - '!response_has_local_ip'
              exec:
                - blacklist
          fast_fallback: 200
          always_standby: true

  - tag: forward_local
    type: fast_forward
    args:
      upstream:
        - addr: '223.5.5.5'

  - tag: forward_remote
    type: fast_forward
    args:
      upstream:
        - addr: 'tcp://1.1.1.1'
          idle_timeout: 90

  - tag: query_is_local_domain
    type: query_matcher
    args:
      domain:
        - 'ext:./geosite.dat:cn'

  - tag: query_is_non_local_domain
    type: query_matcher
    args:
      domain:
        - 'ext:./geosite.dat:geolocation-!cn'

  - tag: response_has_local_ip
    type: response_matcher
    args:
      ip:
        - 'ext:./geoip.dat:cn'

  - tag: blacklist
    type: 'ipset'
    args:
      set_name4: 'blacklist'
      set_name6: ''
      mask4: 24
      mask6: 32
```

mosdns放置在openwrt内作为dnsmasq上游使用，
配置的简单功能就是屏蔽非国内域名的aaaa记录，给解析到的外网ip打ipset

但是内网客户端在透过dnsmasq解析双栈域名的时候，
a记录迅速应答，aaaa记录会进入等待然后超时错误。
这个问题会导致浏览器解析双栈域名耗时非常长。。

用dig也可以复现这个问题
dig @192.168.100.1 -t aaaa unix.stackexchange.com (超时)
❯ time dig @192.168.100.1 -t aaaa bicycles.stackexchange.com

; <<>> DiG 9.11.5-P4-5.1+deb10u5-Debian <<>> @192.168.100.1 -t aaaa bicycles.stackexchange.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 56939
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1024
;; QUESTION SECTION:
;bicycles.stackexchange.com.    IN      AAAA

;; AUTHORITY SECTION:
stackexchange.com.      3600    IN      SOA     ns-cloud-d1.googledomains.com. cloud-dns-hostmaster.google.com. 1 21600 3600 259200 300

;; Query time: 209 msec
;; SERVER: 192.168.100.1#53(192.168.100.1)
;; WHEN: 六 10月 09 20:33:17 CST 2021
;; MSG SIZE  rcvd: 145

dig @192.168.100.1 -t aaaa bicycles.stackexchange.com  0.00s user 0.01s system 0% cpu 10.220 total

dig @192.168.100.1 -p6553 -t aaaa unix.stackexchange.com (正确返回空记录应答)
❯ time dig @192.168.100.1 -p6553 -t aaaa bicycles.stackexchange.com
; <<>> DiG 9.11.5-P4-5.1+deb10u5-Debian <<>> @192.168.100.1 -p6553 -t aaaa bicycles.stackexchange.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 39741
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;bicycles.stackexchange.com.    IN      AAAA

;; Query time: 2 msec
;; SERVER: 192.168.100.1#6553(192.168.100.1)
;; WHEN: 六 10月 09 20:33:02 CST 2021
;; MSG SIZE  rcvd: 44

dig @192.168.100.1 -p6553 -t aaaa bicycles.stackexchange.com  0.01s user 0.00s system 72% cpu 0.010 total

尝试了_drop_response+end或者_block_with_servfail均不能阻止dnsmasq超时
_block_with_nxdomain可以但是有时会导致a记录解析也出错

附上我的dnsmasq配置档
```ini
# auto-generated config file from /etc/config/dhcp
conf-file=/etc/dnsmasq.conf
dhcp-authoritative
domain-needed
no-resolv
localise-queries
read-ethers
enable-ubus=dnsmasq
expand-hosts
bind-dynamic
local-service
port=53
edns-packet-max=1232
domain=lan
local=/lan/
server=127.0.0.1#6553
addn-hosts=/tmp/hosts
dhcp-leasefile=/tmp/dhcp.leases
stop-dns-rebind
rebind-localhost-ok
dhcp-broadcast=tag:needs-broadcast
conf-dir=/tmp/dnsmasq.d
user=dnsmasq
group=dnsmasq


dhcp-ignore-names=tag:dhcp_bogus_hostname
conf-file=/usr/share/dnsmasq/dhcpbogushostname.conf


bogus-priv
conf-file=/usr/share/dnsmasq/rfc6761.conf
dhcp-range=set:lan,192.168.100.100,192.168.100.254,255.255.255.0,7d
no-dhcp-interface=pppoe-wan
```

**Comment by IrineSistiana** [comment]
~不用 dnsmasq，让 mosdns 来~

**Reply by stupidloud** [reply]
不用dnsmasq的话openwrt有一大票基于dnsmasq-full的插件用不了了呐，一些ip分流、广告过滤什么的。
我另外试了用替换ip的方式屏蔽aaaa
```yaml
- if_and:
    - '!query_is_local_domain'
    - _qtype_AAAA
  exec:
    - blockaaaa
    - _end

  - tag: 'blockaaaa'
    type: 'blackhole'
    args:
      rcode: 0
      ipv4: '127.0.0.1'
      ipv6: '::1'
```
但是用dig测试返回不正常
```shell
❯ dig @192.168.100.1 -t aaaa stackapps.com -p6553
;; Got bad packet: extra input data
72 bytes
d7 c9 81 00 00 01 00 01 00 00 00 00 09 73 74 61          .............sta
63 6b 61 70 70 73 03 63 6f 6d 00 00 1c 00 01 09          ckapps.com......
73 74 61 63 6b 61 70 70 73 03 63 6f 6d 00 00 01          stackapps.com...
00 01 00 00 0e 10 00 10 00 00 00 00 00 00 00 00          ................
00 00 00 00 00 00 00 01                                  ........
```
