### DISCUSSION TITLE
帮忙看下 local 走国内, remote 走代理的分流配置是否有问题、是否有优化之处

### DISCUSSION THREAD

**Discussion by m2acgi** [IrineSistiana/mosdns#211] [Q&A]
请问这样的分流配置是否有问题、是否有优化的地方？@IrineSistiana 大佬，帮忙看下，谢谢！

```yaml
log:
  level: debug
  file: ""
plugin:
  - tag: my_server
    type: server
    args:
      entry:
        - my_cache
        - my_sequence
      server:
        - addr: '[::]:53'
          protocol: udp
        - addr: '[::]:53'
          protocol: tcp
  - tag: 'my_cache'
    type: 'cache'
    args:
      size: 1024
  - tag: my_sequence
    type: sequence
    args:
      exec:
        - if:
            - query_domain_is_local
            - '!_query_is_common'
          exec:
            - forward_dns_to_local
            - _end
        - forward_dns_to_remote
  - tag: query_domain_is_local
    type: query_matcher
    args:
      domain:
        - 'ext:./geosite.dat:cn'
  - tag: forward_dns_to_local
    type: forward
    args:
      upstream:
        - addr: '114.114.114.114'
  - tag: 'forward_dns_to_remote'
    type: 'fast_forward'
    args:
      upstream:
       - addr: 'tcp://8.8.8.8'
         socks5: '192.168.0.2:1080'
      timeout: 5
```
