### DISCUSSION TITLE
有没有可能自动获取DHCP派发下来的DNS地址

### DISCUSSION THREAD

**Discussion by laggardkernel** [IrineSistiana/mosdns#213] [Ideas]
目前对于 `.lan` 域名，需要转发给路由器下发的DNS，以支持解析到局域网内其他设备。有没有可能自定识别出上游DHCP下发的DNS地址？现在我只能写死这种地址，根据不同网络还要去更改它。

目前我知道 NetworkManager 会将DHCP DNS信息存盘
>  The original DNS servers can be found in /run/NetworkManager/no-stub-resolv.conf. 

Clash 好像也实现了这种功能 https://github.com/Dreamacro/clash/pull/1509

提供部分相关配置说明一下我要做什么

```yaml
  - tag: chinadns_entry
    type: sequence
    args:
      exec:
        - match_hosts
        - _default_cache
        - _single_flight
        ...
        - if:
          - match_lan_domain
          exec:
            - forward_dhcp
            - _end
          ...

  - tag: 'forward_dhcp'
    type: fast_forward
    args:
      upstream:
        - addr: udp://192.168.2.1:53
      timeout: 3
  - tag: match_lan_domain
    type: query_matcher
    args:
      logical_and: true
      domain:
        - 'domain:lan'
        # - 'regexp:.+\.lan\.?$'
      qtype: [1, 28]
      qclass: [1]
```

**Comment by IrineSistiana** [comment]
有可能。看 clash 的 commit 它是做了一个 dhcp 客户端然后去拉服务端的数据。工作量有点大.....

我有个懒人的想法:  让 mosdns 运行后去运行一个 bash 脚本去获取 dns  服务器地址。

**Comment by IrineSistiana** [comment]
功能有了。现在配置文件里可以加 `${{ cmd }}` 语法。里面的 `cmd` 会被执行，然后自身会被 `cmd` 的输出替换。就跟 bash 的 `$( cmd )` 一样。

所以可以自己写一个脚本 get_dhcp_dns.sh ，获取 IP，然后配置写成 

```yaml
tag: 'forward_dhcp'
    type: fast_forward
    args:
      upstream:
        - addr: ${{ ./get_dhcp_dns.sh }}
      timeout: 3
```
