### DISCUSSION TITLE
怎么对geosite中广告域名做部分白名单，而不影响其他广告域名的屏蔽

### DISCUSSION THREAD

**Discussion by j4Uq** [IrineSistiana/mosdns#234] [Ideas]
事情起因为小爱音箱无法提供服务，排查后发现geosite.dat:category-ads-all中的`resolver.msg.xiaomi.net`导致的，于是需要对其作白名单处理，也就是域名加到本地域名列表，并且把屏蔽的处理顺序放到本地域名之后，但是调整后，虽然小爱音箱恢复了，其他很多域名也因为同时处于geosite.dat:cn和geosite.dat:category-ads-all中，而无法屏蔽
```
log:
  level: info
  file: ""

plugin:
  - tag: main_server
    type: server
    args:
      entry:
        - main_sequence   # 逻辑
      server:       # 服务器监听地址与协议。
        - addr: '[::]:53'
          protocol: udp
        - addr: '[::]:53'
          protocol: tcp

  ################# 可执行插件 ################

  # 包含分流的逻辑的插件
  - tag: main_sequence
    type: sequence
    args:
      exec:
        - if:
            - query_is_blacklist_domain  # 已知的广告域名
          exec:
            - _block_with_nxdomain
            - _return

        - if:
            - query_is_local_domain   # 已知的本地域名
            - '!_query_is_common'
          exec:
            - mem_cache
            - _single_flight
            - forward_local
            - TTL
            - _return

        - if:
            - query_is_gfwlist_domain  # 已知的gfw屏蔽域名
          exec:
            - _prefer_ipv4
            - _single_flight
            - forward_remote_vps  # 用远程VPS服务器获取的结果
            - TTL_1
            - _return

        - if:
            - query_is_non_local_domain  # 已知的非本地域名
          exec:
            - mem_cache
            - _prefer_ipv4
            - _single_flight
            - forward_remote  # 用远程服务器
            - TTL
            - _return

        # 剩下的未知域名用 IP 分流。详细分流原理请参考 `fallback` 的工作流程。
        - primary:
            - mem_cache
            - _single_flight
            - forward_local
            - TTL
            - if:
                - '!response_has_local_ip'
              exec:
                - _drop_response
          secondary:
            - _prefer_ipv4
            - _single_flight
            - forward_remote
            - TTL
          fast_fallback: 200  # 这里建议设置成 local 服务器正常延时的 2~5 倍。
                              # 这个延时保证了 local 延时偶尔变高时，其结果不会被 remote 抢答。
                              # 如果 local 超过这个延时还没响应，可以假设 local 出现了问题。
                              # 这时用就采用 remote 的应答。
          always_standby: true
      
  # 缓存
  - tag: 'mem_cache'
    type: 'cache'
    args:
      size: 40960
      lazy_cache_ttl: 259200
      lazy_cache_reply_ttl: 30
      
  - tag: TTL
    type: 'ttl'
    args:
      minimal_ttl: 300
      maximum_ttl: 3600

  - tag: TTL_1
    type: 'ttl'
    args: 
      minimal_ttl: 1
      maximum_ttl: 1

  # 转发请求至本地服务器的插件
  - tag: forward_local
    type: fast_forward
    args:
      upstream:
        - addr: 2400:3200::1
        - addr: 240C::6666
        - addr: 218.85.152.99
        - addr: 114.114.114.114

  - tag: forward_remote
    type: fast_forward
    args:
      upstream:
        - addr: tls://8.8.4.4
          idle_timeout: 60
        - addr: tls://8.8.8.8
          trusted: true 
          idle_timeout: 60
        - addr: https://i.233py.com/dns-query
          trusted: true 
          idle_timeout: 60

  - tag: forward_remote_vps
    type: fast_forward
    args:
      upstream:
        - addr: 127.0.0.1:54

  ################ 匹配器插件 #################

  # 匹配本地域名的插件
  - tag: query_is_local_domain
    type: query_matcher
    args:
      domain:
        - 'ext:./locallist.txt'
        - 'ext:./geosite.dat:cn'
        - 'ext:./geosite.dat:category-games@cn'
        - 'ext:./geosite.dat:apple-cn'
        - 'ext:./geosite.dat:google-cn'
        - 'ext:./geosite.dat:azure@cn'
        - 'ext:./geosite.dat:microsoft@cn'

  # 匹配非本地域名的插件
  - tag: query_is_non_local_domain
    type: query_matcher
    args:
      domain:
        - 'ext:./geosite.dat:geolocation-!cn'

  - tag: query_is_blacklist_domain
    type: query_matcher
    args:
      domain:
        - 'ext:./blacklist.txt'
        - 'ext:./geosite.dat:category-ads-all'
        - 'ext:./geosite.dat:win-spy'
  
  - tag: query_is_gfwlist_domain
    type: query_matcher
    args:
      domain:
        - 'ext:./proxylist.txt'
        - 'ext:./geosite.dat:gfw'
        - 'ext:./geosite.dat:greatfire'
        
  # 匹配本地 IP 的插件
  - tag: response_has_local_ip
    type: response_matcher
    args:
      ip:
        - 'ext:./cn.dat:cn'

```
