### DISCUSSION TITLE
DOT/DOH服务器本身的域名是怎么解析的？

### DISCUSSION THREAD

**Discussion by CarterCL** [IrineSistiana/mosdns#242] [Q&A]
一直有这个疑问，adguard home有bootstrap dns可以解析，mosdns的fast_forward是怎么解析doh/dot本身的dns的？
贴下个人配置，顺便问问有没有优化的地方

```
log:
  level: error
  file: "./dns.log"
library: []
plugin:
  - tag: server
    type: server
    args:
      entry:
        - mem_cache
        - main_sequence
      server:
        - addr: 127.0.0.1:53
          protocol: udp
        - addr: 127.0.0.1:53
          protocol: tcp
        - addr: '[::1]:53'
          protocol: udp
        - addr: '[::1]:53'
          protocol: tcp
  - tag: main_sequence
    type: sequence
    args:
      exec:
        - if:
            - query_is_local_domain
            - '!_query_is_common'
          exec:
            - forward_local
            - _end

        - if:
            - query_is_non_local_domain
          exec:
            - _prefer_ipv4
            - forward_remote
            - _end
        - primary:
            - forward_local
            - if:
                - 'response_has_local_ip'
              exec:
                - _drop_response
          secondary:
            - _prefer_ipv4
            - forward_remote
          fast_fallback: 200
          always_standby: true
  - tag: mem_cache
    type: cache
    args:
      size: 1024
  - tag: forward_local
    type: fast_forward
    args:
      upstream:
        - addr: 'tls://dns.alidns.com'
          dial_addr: '223.5.5.5:853'
          idle_timeout: 30
          max_conns: 4
          trusted: true
        - addr: 'https://doh.pub/dns-query'
          dial_addr: '162.14.21.178:443'
          max_conns: 4
          trusted: true
  - tag: forward_remote
    type: fast_forward
    args:
      upstream:
        - addr: 'tls://i.passcloud.xyz'
          dial_addr: '101.33.125.235:5432'
          idle_timeout: 30
          max_conns: 4
          trusted: true
        - addr: 'https://public.dns.iij.jp/dns-query'
          dial_addr: '103.2.57.6:443'
          idle_timeout: 30
          max_conns: 4
          trusted: true
  - tag: query_is_local_domain
    type: query_matcher
    args:
      domain:
        - 'ext:./geosite.dat:cn'

  - tag: query_is_non_local_domain
    type: query_matcher
    args:
      domain:
        - 'ext:./geosite.dat:geolocation-!cn'

  - tag: response_has_local_ip
    type: response_matcher
    args:
      ip:
        - 'ext:./geoip-only-cn-private.dat:cn'
```
