### DISCUSSION TITLE
iOS 屏蔽 type65 请求解决偶发性打不开部分网站

### DISCUSSION THREAD

**Discussion by hplee0120** [IrineSistiana/mosdns#294] [Ideas]
在openwrt上使用mosdns配合梯子
发现在开启IPV6的环境中使用- _prefer_ipv4参数但是IOS15客户端仍然偶发性打不开某些网站，比如V2EX，如果不开启ipv6时一切正常。而在windows上测试似乎没有该问题，所以怀疑是否跟ios设备的dns请求逻辑有关？暂时怀疑的是这个，不确定是不是有没有关系，多刷新几次网页可以正常打开，https://github.com/pymumu/smartdns/issues/616

**Comment by hplee0120** [comment]
搜关键词又找到一个类似情况的，这个例子跟我遇到的情况更加相似
https://www.bv2ex.com/t/797235
暂时放弃ipv6了

**Comment by IrineSistiana** [comment]
或者你可以把 type 65 给屏蔽掉。

**Comment by hplee0120** [comment]
> 或者你可以把 type 65 给屏蔽掉。

请问下具体的配置和参数应该怎么写，wiki似乎没有找到相关的参数

**Comment by IrineSistiana** [comment]
看样子那个 type65 是 qtype 65

看 wiki： query_matcher, blackhole。

用 if 组合。

**Comment by w22gb8** [comment]
我把aaaa和type65都屏蔽了：
```
  - tag: 'query_is_type65_aaaa' #type65和aaaa查询
    type: 'query_matcher'
    args:
      qtype: [28, 65] 
      logical_and: false     
```
