### DISCUSSION TITLE
请教下大佬门，服务器搭建完成后不能根据地理位置进行附近解析

### DISCUSSION THREAD

**Discussion by kankankankankankan** [IrineSistiana/mosdns#306] [Q&A]
如果要让mosdns解析地理位置的服务器，该如何配制？
感谢
```
  - tag: "ecs-cn"
    type: "ecs"
    args:
      auto: true
      force_overwrite: false # 强制覆盖
```
配制下来还是一样不能匹配到附近的服务器
