### DISCUSSION TITLE
如何实现故障转移

### DISCUSSION THREAD

**Discussion by 0xffffharry** [IrineSistiana/mosdns#312] [Q&A] [answered]
假设 8.8.8.8 作为境外 DNS 设置，但是要走代理才能用。如果节点出现故障使得代理失效，那 8.8.8.8 也会失效无法使用。则任何使用 8.8.8.8 这个 DNS 服务器的域名都无法解析。因此想要实现故障转移

配置如下
```
       - if:
            - blacklist_domain
          exec:
            - _prefer_ipv4
            - dns_world
            - if:
                - '!_response_rcode_success'
              exec:
                - dns_china
            - _return
```

DNS 设置
```
- tag: 'dns_china'
    type: fast_forward
    args:
      upstream:
        - addr: 'https://223.5.5.5/dns-query'
        - addr: 'https://223.6.6.6/dns-query'
        - addr: 'tls://1.12.12.12'
        - addr: 'tls://120.53.53.53'
      timeout: 2

- tag: 'dns_world'
    type: forward
    args:
      upstream:
        - addr: 'tls://8.8.8.8'
      timeout: 3
```

理论上没什么问题，但实际上并不能做到上述功能，请问是哪里出问题

**Comment by IrineSistiana** [comment]
> 理论上没什么问题

理论上大问题。_response_rcode_success 不是这样用的。

用 fallback。在 【执行序列】- 【高级操作-并发】 里。

**Reply by 0xffffharry** [reply]
大佬可以贴个配置吗

**Comment by j4Uq** [comment]
```
        # 剩下的未知域名用 IP 分流。详细分流原理请参考 `fallback` 的工作流程。
        - primary:
            - _single_flight
            - forward_local
            - TTL
            - if:
                - response_is_cf_ip
              exec:
                - cf_prefer
                - _return
            - if:
                - '!response_is_local_ip'
              exec:
                - _drop_response
          secondary:
            - _single_flight
            - forward_remote
            - TTL
            - if:
                - response_is_cf_ip
              exec:
                - cf_prefer
                - _return
          fast_fallback: 400  # 这里建议设置成 local 服务器正常延时的 2~5 倍。
                              # 这个延时保证了 local 延时偶尔变高时，其结果不会被 remote 抢答。
                              # 如果 local 超过这个延时还没响应，可以假设 local 出现了问题。
                              # 这时用就采用 remote 的应答。
          always_standby: true
      
```

**Reply by 0xffffharry** [reply]
感谢，已经解决

**Comment by 0xffffharry** [comment, marked as answer]
直接使用执行序列 primary 即可
```
- primary:
    - dns_world
  secondary:
    - dns_world_bak
  fast_fallback: 400
```
