### DISCUSSION TITLE
能否增加根据IP指定上游DNS的功能[Feature request]

### DISCUSSION THREAD

**Discussion by pmkol** [IrineSistiana/mosdns#378] [Q&A]
**根据污染IP指定上游**

发现有一些特殊的域名，只有使用国内DNS才能解析，但这些DNS的服务器在境外，所以通过中国IP来分流的方式无法满足需求

而单纯使用gfwlist名单，名单中的域名指向上游DNS的方式，当个别被污染的域名不在名单时，又无法完美解决污染，目前想到的方式有两种，不知道作者能否加入其中一种：

第一种，根据指定IP选择上游，即污染的IP使用指定上游查询，类似chinaip这种方案，只是多一个自定的IP段
第二种，当域名解析返回 Server failed时，使用指定DNS再次查询

感谢作者: )

**Comment by IrineSistiana** [comment]
> 第一种，根据指定IP选择上游，即污染的IP使用指定上游查询，类似chinaip这种方案，只是多一个自定的IP段

```yaml
- forward_local
- if: bad_ip #response_matcher
  exec: forward_remote
- ...
```
> 第二种，当域名解析返回 Server failed时，使用指定DNS再次查询

用 sequence 的 fallback。
