### DISCUSSION TITLE
关于 v4 版本 没有 继承 v3 版本 的 include 多文件的 配置能力的疑问

### DISCUSSION THREAD

**Discussion by kuyagic** [IrineSistiana/mosdns#386] [Ideas]
因为我v3的时候分了 很多个文件 分别指定每个插件的逻辑。这样修改和同步维护也很方便。
升级到v4 我的配置入口直接报错了

我的入口配置 类似如下的结构
```
log:
# 日志级别。可选 `debug` `info` `warn` `error`。默认 `info`。
#  level: 'debug'
  level: 'info'
  file: '/opt/mosdns.log'
include:
  - './conf.d/ecs.yaml'
  - './conf.d/blackhole.yaml'
  - './conf.d/hosts.yaml'
  - './conf.d/ptr.yaml'
  - './conf.d/matcher.request.yaml'
  - './conf.d/matcher.response.yaml'
  - './conf.d/forward.yaml'
  - './conf.d/sequence.yaml'
  - './conf.d/server.zmbox.yaml'
  - './conf.d/server.local.yaml'
```

希望 v4 能够以一个更加灵活的方式来 实现多配置文件分割的需求
