### DISCUSSION TITLE
fast_forward中多个upstream逻辑

### DISCUSSION THREAD

**Discussion by zhaibin18** [IrineSistiana/mosdns#409] [Q&A]
```
  - tag: forward_local
    type: fast_forward
    args:
      upstream:
        - addr: 123.123.123.123
        - addr: 202.106.46.151
        - addr: 223.5.5.5
```
如上配置，请问三个upstream是并发同时发送请求，还是按只取其中一个发送dns请求？
