### DISCUSSION TITLE
如何屏蔽反向解析

### DISCUSSION THREAD

**Discussion by liang-hiwin** [IrineSistiana/mosdns#411] [Q&A]
屏蔽类似 in-addr.arpa这种反向解析

**Comment by kuyagic** [comment]
盲猜可以把 请求是 PTR 的 都干掉就可以了

**Comment by liang-hiwin** [comment]
怎么写呢？没找到案例

**Comment by sbwml** [comment]
阻止 PTR 请求大致操作：

```yaml
plugins:
  - tag: query_is_ptr_record  # 创建 PTR tag
    type: query_matcher
    args:
      qtype: [12]  # PTR 解析 type id 为 12

  - tag: main_sequence
    type: "sequence"
    args:
      exec:
        - if: query_is_ptr_record  # 如果是 PTR 请求
          exec:
            - _new_nxdomain_response  # 则丢弃
            - _return

servers:
  - exec: main_sequence
    listeners:
      - protocol: udp
        addr: ":5353"
      - protocol: tcp
        addr: ":5353"
```

然而在真实应用场景下是极其不推荐屏蔽 PTR 的，可以参考这个方法（来自 IrineSistiana/mosdns [discussions](https://github.com/IrineSistiana/mosdns/discussions/39#discussioncomment-286339)）

将 local ptr 屏蔽掉，且 ptr 请求由本地dns处理，使用了四五个小时，mosdns 日志暂未出现类似 ```in-addr.arpa```、```xxxx.ip6.arpa``` 的错误日志

https://github.com/sbwml/luci-app-mosdns/commit/459a87d6efd053f7d6eb6edb90faf33cdbe86463
