### DISCUSSION TITLE
v4版本配置完成后，mosdns能正常运行也无报错，但就是不生效，请问我贴出来的哪里存在问题呢？！

### DISCUSSION THREAD

**Discussion by zxlhhyccc** [IrineSistiana/mosdns#422] [Q&A]
``````
log:
  level: error
  file: ''

data_providers:
  - tag: geosite
    file: "/usr/share/v2ray/geosite.dat"
    auto_reload: true
  - tag: geoip
    file: "/usr/share/v2ray/geoip.dat"
    auto_reload: true

plugins:
  # 缓存
  - tag: lazy_cache
    type: cache
    args:
      size: 200000
      lazy_cache_ttl: 259200

  # 修改应答 ttl
  - tag: 'modify_ttl'
    type: 'ttl'
    args:
      minimal_ttl: 300
      maximum_ttl: 3600

  # ipset 写入应答 IP 到系统 ipset
  - tag: 'blacklist'
    type: ipset
    args:
      set_name4: 'blacklist'
      set_name6: ''
      mask4: 24
      mask6: 32

  # 转发至本地服务器的插件
  - tag: forward_local
    type: fast_forward
    args:
      upstream:
        - addr:   119.29.29.29
        - addr:   101.226.4.6
        - addr:   223.5.5.5

  # 转发至远程服务器的插件
  - tag: forward_remote
    type: fast_forward
    args:
      upstream:
        - addr:   tcp://1.1.1.1
        - addr:   tcp://198.153.194.1
        - addr:   tcp://199.85.127.10

  # 匹配本地域名的插件
  - tag: query_is_local_domain
    type: query_matcher
    args:
      domain:
        - 'provider:geosite:cn'

  # 匹配非本地域名的插件
  - tag: query_is_non_local_domain
    type: query_matcher
    args:
      domain:
        - 'provider:geosite:geolocation-!cn'

  # 匹配本地 IP 的插件
  - tag: response_has_local_ip
    type: response_matcher
    args:
      ip:
        - 'provider:geoip:cn'

  # 匹配广告域名的插件
  - tag: query_is_ad_domain
    type: query_matcher
    args:
      domain:
        - 'provider:geosite:category-ads-all'

  # 主要的运行逻辑插件
  # sequence 插件中调用的插件 tag 必须在 sequence 前定义，
  # 否则 sequence 找不到对应插件。
  - tag: main_sequence
    type: sequence
    args:
      exec:
        # 缓存
        - lazy_cache

        # 屏蔽广告域名
        - if: query_is_ad_domain
          exec:
            - _new_nxdomain_response
            - _return

        # 已知的本地域名用本地服务器解析
        - if: query_is_local_domain
          exec:
            - forward_local
            - modify_ttl
            - _return

        # 已知的非本地域名用远程服务器解析
        - if: query_is_non_local_domain
          exec:
            - _prefer_ipv4
            - forward_remote
            - blacklist
            - modify_ttl
            - _return

          # 剩下的未知域名用 IP 分流。
          # 这里借助了 `fallback` 工作机制。分流原理请参考 `fallback`
          # 的工作流程。
          # primary 从本地服务器获取应答，丢弃非本地 IP 的结果。
        - primary:
            - forward_local
            - if: "(! response_has_local_ip) && [_response_valid_answer]"
              exec:
                - _drop_response
          # secondary 从远程服务器获取应答。
          secondary:
            - _prefer_ipv4
            - forward_remote
            - blacklist
            - modify_ttl
          # 这里建议设置成 local 服务器正常延时的 2~5 倍。
          # 这个延时保证了 local 延时偶尔变高时，其结果不会被 remote 抢答。
          # 如果 local 超过这个延时还没响应，可以假设 local 出现了问题。
          # 这时用就采用 remote 的应答。单位: 毫秒。
          fast_fallback: 200

servers:
  - exec: main_sequence
    listeners:
      - protocol: udp
        addr: :5335
      - protocol: tcp
        addr: :5335
`````````

**Comment by zxlhhyccc** [comment]
另外，比如通过ipset add blacklist 1.1.1.1增加到ipset集合，同时通过：ipset test xxxx 1.1.1.1能查询到此IP在blacklist里，也符合插件规范。。。烦请各位大佬解惑啊，谢谢！

**Comment by asnon** [comment]
同样的问题。。不知道哪里错了。。可以启动，但是没日志，也上不了网

**Reply by zxlhhyccc** [reply]
> 同样的问题。。不知道哪里错了。。可以启动，但是没日志，也上不了网

我暂时解决了。。。。

**Reply by asnon** [reply]
请问怎么解决的哇？

**Reply by zxlhhyccc** [reply]
> 请问怎么解决的哇？

我是这样子的配置，你试试：
````
log:
  level: error
  file: '/tmp/mosdns.log'

data_providers:
  - tag: geosite
    file: "/usr/share/v2ray/geosite.dat"
    auto_reload: true
  - tag: geoip
    file: "/usr/share/v2ray/geoip.dat"
    auto_reload: true

plugins:
  # 缓存
  - tag: lazy_cache
    type: cache
    args:
      size: 200000
      lazy_cache_ttl: 259200
      lazy_cache_reply_ttl: 30
      cache_everything: false

  # 修改应答 ttl
  - tag: 'modify_ttl'
    type: 'ttl'
    args:
      minimal_ttl: 300
      maximum_ttl: 3600

  # ipset 写入应答 IP 到系统 ipset
  - tag: remote_ipset
    type: 'ipset'
    args:
      set_name4: 'blacklist'   # 如果非空，存放 ipv4 地址到这个表。这个表属性 family 需为 `inet`。
      set_name6: ''   # 如果非空，存放 ipv6 地址到这个表。这个表属性 family 需为 `inet6`。
      mask4: 24       # 写入 ipv4 地址时使用的掩码。默认: 24。
      mask6: 32       # 写入 ipv6 地址时使用的掩码。默认: 32。

  # 转发至本地服务器的插件
  - tag: forward_local
    type: fast_forward
    args:
      upstream:
        - addr:   119.29.29.29
        - addr:   101.226.4.6
        - addr:   223.5.5.5
          trusted: true # 是否是可信服务器

  # 转发至远程服务器的插件
  - tag: forward_remote
    type: fast_forward
    args:
      upstream:
        - addr:   tcp://1.1.1.1
        - addr:   tcp://198.153.194.1
        - addr:   tcp://199.85.127.10
          trusted: true # 是否是可信服务器

  # 匹配本地域名的插件
  - tag: query_is_local_domain
    type: query_matcher
    args:
      domain:
        - 'provider:geosite:cn'
        - 'provider:geosite:apple-cn'
        - 'provider:geosite:google-cn'

  # 匹配非本地域名的插件
  - tag: query_is_non_local_domain
    type: query_matcher
    args:
      domain:
        - 'provider:geosite:geolocation-!cn'

  # 匹配本地 IP 的插件
  - tag: response_has_local_ip
    type: response_matcher
    args:
      ip:
        - 'provider:geoip:cn'
      cname:
        - 'provider:geosite:cn'

  # 匹配广告域名的插件
  - tag: query_is_ad_domain
    type: query_matcher
    args:
      domain:
        - 'provider:geosite:category-ads-all'

  # 主要的运行逻辑插件
  # sequence 插件中调用的插件 tag 必须在 sequence 前定义，
  # 否则 sequence 找不到对应插件。
  - tag: main_sequence
    type: sequence
    args:
      exec:
        # 缓存
        - _misc_optm
        - lazy_cache
        - _no_ecs

        # 屏蔽广告域名
        - if: query_is_ad_domain
          exec:
            - _new_nxdomain_response
            - _return

        # 已知的本地域名用本地服务器解析
        - if: query_is_local_domain
          exec:
            - forward_local
            - modify_ttl
            - if: response_has_local_ip
              exec:
                - _return

        # 已知的非本地域名用远程服务器解析,优先 IPv4
        - if: query_is_non_local_domain
          exec:
            - _prefer_ipv4
            - forward_remote
            - modify_ttl
            - remote_ipset
            - if: "! response_has_local_ip"
              exec:
                - _return

          # 剩下的未知域名用 IP 分流。
          # 这里借助了 `fallback` 工作机制。分流原理请参考 `fallback`
          # 的工作流程。
          # primary 从本地服务器获取应答，丢弃非本地 IP 的结果。
        - primary:
            - forward_local
            - if: "(! response_has_local_ip) && [_response_valid_answer]"
              exec:
                - _drop_response
          # secondary 从远程服务器获取应答,优先 IPv4。
          secondary:
            - _prefer_ipv4
            - forward_remote
            - modify_ttl
          # 这里建议设置成 local 服务器正常延时的 2~5 倍。
          # 这个延时保证了 local 延时偶尔变高时，其结果不会被 remote 抢答。
          # 如果 local 超过这个延时还没响应，可以假设 local 出现了问题。
          # 这时用就采用 remote 的应答。单位: 毫秒。
          fast_fallback: 500
          always_standby: true

servers:
  - exec: main_sequence
    listeners:
      - protocol: udp
        addr: :5335
      - protocol: tcp
        addr: :5335
      # - protocol: udp
      #   addr: "[::1]:5335"
      # - protocol: tcp
      #   addr: "[::1]:5335"
``````
