### DISCUSSION TITLE
请问metrics里的err统计规则是什么？

### DISCUSSION THREAD

**Discussion by CarterCL** [IrineSistiana/mosdns#424] [Q&A] [answered]
版本：4.1.4
运行环境：Windows 11 x64

运行了一天，发现metrics里err非常多，请问这是为什么？配置在最底下
``` JSON
{
  "plugins": {
    "_default_cache": {
      "hit": 0,
      "lazy_hit": 0,
      "query": 0,
      "size": 0
    },
    "cache": {
      "hit": 325,
      "lazy_hit": 0,
      "query": 4889,
      "size": 58
    },
    "forward_local": {
      "0": {
        "err": 1921,
        "latency": {
          "avg": 19,
          "max": 631,
          "min": 0,
          "p25": 4,
          "p50": 6,
          "p75": 8.75
        },
        "query": 2169
      },
      "1": {
        "err": 1414,
        "latency": {
          "avg": 98,
          "max": 3374,
          "min": 0,
          "p25": 19,
          "p50": 26,
          "p75": 44
        },
        "query": 2169
      }
    },
    "forward_remote": {
      "0": {
        "err": 1158,
        "latency": {
          "avg": 232,
          "max": 2489,
          "min": 46,
          "p25": 75,
          "p50": 152,
          "p75": 263.75
        },
        "query": 2213
      },
      "1": {
        "err": 2207,
        "latency": {
          "avg": 276,
          "max": 509,
          "min": 126,
          "p25": 130,
          "p50": 168,
          "p75": 476.5
        },
        "query": 2213
      }
    }
  },
  "servers": {}
}
```

``` YAML
log:
  level: error
  file: "dns.log"

data_providers:
  - tag: geosite
    file: ./geosite.dat
    auto_reload: true
  - tag: geoip
    file: ./geoip-only-cn-private.dat
    auto_reload: true

plugins:
  # 缓存
  - tag: cache
    type: cache
    args:
      size: 1024

  # 转发至本地服务器的插件
  - tag: forward_local
    type: fast_forward
    args:
      upstream:
        - addr: 'tls://dot.pub'
          dial_addr: '120.53.53.53:853'
          enable_pipeline: false
          max_conns: 2
          trusted: true
        - addr: 'tls://b.iqiq.io'
          dial_addr: '101.42.236.152:853'
          enable_pipeline: false
          max_conns: 2
          trusted: true

  # 转发至远程服务器的插件
  - tag: forward_remote
    type: fast_forward
    args:
      upstream:
        - addr: 'https://public.dns.iij.jp/dns-query'
          dial_addr: '103.2.57.5:443'
          max_conns: 2
          trusted: true
        - addr: 'https://dns-unfiltered.adguard.com/dns-query'
          dial_addr: '94.140.14.141:443'
          max_conns: 2
          trusted: true

  # 匹配本地域名的插件
  - tag: query_is_local_domain
    type: query_matcher
    args:
      domain:
        - 'provider:geosite:cn'

  # 匹配非本地域名的插件
  - tag: query_is_non_local_domain
    type: query_matcher
    args:
      domain:
        - 'provider:geosite:geolocation-!cn'

  # 匹配广告域名的插件
  - tag: query_is_ad_domain
    type: query_matcher
    args:
      domain:
        - 'provider:geosite:category-ads-all'

  # 匹配本地 IP 的插件
  - tag: response_has_local_ip
    type: response_matcher
    args:
      ip:
        - 'provider:geoip:cn'

  - tag: main_sequence
    type: sequence
    args:
      exec:
        - _misc_optm
        - cache

        - if: query_is_ad_domain
          exec:
            - _new_nxdomain_response
            - _return

        - if: query_is_local_domain
          exec:
            - forward_local
            - _return

        - if: query_is_non_local_domain
          exec:
            - _prefer_ipv4
            - forward_remote
            - _return
            - 
        - primary:
            - forward_local
            - if: "(! response_has_local_ip) && [_response_valid_answer]"
              exec:
                - _drop_response
          secondary:
            - _prefer_ipv4
            - forward_remote
          fast_fallback: 1000

servers:
  - exec: main_sequence
    listeners:
      - protocol: udp
        addr: 127.0.0.1:53
      - protocol: udp
        addr: '[::1]:53'
api:
  http: "127.0.0.1:58080"
```
