### DISCUSSION TITLE
开多个server怎么写，server的exec运行多条tag怎么写

### DISCUSSION THREAD

**Discussion by lbhzy** [IrineSistiana/mosdns#435] [Q&A]
openwrt下，开两个server一个给ssrplus用，一个做dnsmasq上游用。server只需要运行两个插件，必须要用sequence吗
```
servers:
  - exec:
    - lazy_cache
    - forward_local
      listeners:
        - protocol:         udp
          addr:             127.0.0.1:6666
  - exec:
    - lazy_cache
    - forward_remote
      listeners:
        - protocol:         udp
          addr:             127.0.0.1:5335
```
这样写报错，就是想实现这个意思要怎么写

**Comment by sbwml** [comment]
有没有一种可能，plugins 内包含多个 sequence，servers 运行多个 sequence

```yaml
plugins:
  - tag: "sequence_1"
    type: "sequence"
    args:
      exec: ...

  - tag: "sequence_2"
    type: "sequence"
    args:
      exec: ...

servers:
  - exec: sequence_1
    listeners:
      - protocol: udp
        addr: "127.0.0.1:6666"
  - exec: sequence_2
    listeners:
      - protocol: udp
        addr: "127.0.0.1:5335"
```
