### DISCUSSION TITLE
常规 fallback和快速 fallback是否可以同时不启用

### DISCUSSION THREAD

**Discussion by hplee0120** [IrineSistiana/mosdns#462] [Q&A]
我的预期是除了已知域名 未知域名只保留主次序列。主序列无应答或者返回大陆ip才交给次序列的国内服务器解析。
我的配置 。已知的本地域名交给国内服务器。剩余的域名ipv4优先发给国外服务器。如果没有获得应答或者返回的是大陆ip就丢弃。然后由国内服务器解析
 - if: query_is_local_domain
          exec:
            - forward_local
            - _return
        - primary:
            - _prefer_ipv4
            - forward_remote
            - if: response_has_local_ip
              exec:
                - _drop_response
          secondary:
            - forward_local

**Comment by BozhanL** [comment]
我不太理解为什么不用 快速 fallback. 这是我在用的配置文件, 看看是否合适.
```yaml
  - tag: main_sequence
    type: sequence
    args:
      exec:
        - if: "query_is_local_domain"   # 已知的本地域名
          exec:
            - local_sequence           # 用本地服务器
            - _return
        - if: "query_is_non_local_domain"  # 已知的非本地域名
          exec:
            - _prefer_ipv4
            - remote_sequence            # 用远程服务器
            - _return

        # 剩下的未知域名用 IP 分流。详细分流原理请参考 `fallback` 的工作流程。
        - primary:
            - _prefer_ipv4
            - remote_sequence # 用远程服务器
            - if: "! response_has_local_ip" # 返回结果 不包含本地IP 就返回
              exec:
                - _return
              else_exec:
                - _drop_response # 丢弃应答
          secondary:
            - local_sequence           # 用本地服务器
            - _return
          fast_fallback: 800   # 这里建议设置成 local 服务器正常延时的 2~5 倍。
                              # 这个延时保证了 local 延时偶尔变高时，其结果不会被 remote 抢答。
                              # 如果 local 超过这个延时还没响应，可以假设 local 出现了问题。
                              # 这时用就采用 remote 的应答。
          always_standby: false
```
