### DISCUSSION TITLE
如何只返回非大陆IP

### DISCUSSION THREAD

**Discussion by 4thanks** [IrineSistiana/mosdns#481] [Q&A]
以下哪种配置是比较合理呢？能否实现只返回非大陆IP

1. `_drop_response`丢掉返回的应答IP？这里是不是本次解析也一并丢弃，给下一个sequence解析？

```yaml
  - tag: ""
    type: "sequence"
    args:
      exec:
        - forward_google
        - if: (response_has_local_ip)
        - exec:
            - _drop_response
```

2. `_return`返回再次解析？

```yaml
  - tag: ""
    type: "sequence"
    args:
      exec:
        - forward_google
        - if: (! response_has_local_ip)
        - exec:
            - _return
```

3. `if & else`双重条件，这种方式大概可能返回IP是被和谐，重复解析直到有效IP？

```yaml
  - tag: ""
    type: "sequence"
    args:
      exec:
        - forward_google
        - if: (response_has_local_ip)
        - exec:
            - _drop_response
        - else_exec:
            - _return
```

4. 如果是fallback多组dns应该怎么配置？

```yaml
- tag: ""
  type: "sequence"
  args:
    exec:
      - primary:            
          - "ecs_1"
          - "forward_1"
        secondary:          
          - "ecs_2"
          - "forward_2"   
        fast_fallback: 200  
        always_standby: true
```
