### DISCUSSION TITLE
反向流水线该怎么理解？

### DISCUSSION THREAD

**Discussion by 0xffffharry** [IrineSistiana/mosdns#559] [Q&A]
比如有下面逻辑：
```
  - tag: main
    type: sequence
    args:
      exec:
        - cache_redis

        - if: domain_cn
          exec:
            - _prefer_ipv4
            - server_cn
            - ipset_direct
            - _return

        - if: domain_gfw
          exec:
            - server_world
            - ipset_proxy
            - _return
```

假如查询 google.com ，那么就会先到达 cache_redis 检查发现没有缓存，然后匹配 domain_gfw 后发送到 server_world，获得解析后写入 ipset_proxy ，然后会怎么走？是往上走到 cache_redis 缓存结果？
