### DISCUSSION TITLE
现在的exec不支持一次性执行好几条指令了？

### DISCUSSION THREAD

**Discussion by wydy** [IrineSistiana/mosdns#586] [General]
以前可以写成
```
exec: 
  - 1
  - 2
  - 3
```
但到了v5版本这种写法似乎不行了？导致match后的exec只能执行一条，甚至做不到执行完动作后顺便accept/return

还有个问题，最新的正式版v5似乎就算log设置为debug也不会打印debug信息

**Comment by yubanmeiqin9048** [comment]
是的

**Comment by laggardkernel** [comment]
内置 debug 不能追踪匹配情况，真的非常不友好。不能 exec 多次，没有逻辑 or。……

**Reply by IrineSistiana** [reply]
> 不能 exec 多次，没有逻辑 or

还有 else

可以用 mark 曲线救国。
```yaml
- tag: main
  type: sequence
  args:
  
    # 匹配成功后打标
    # 打相同标签即可实现"逻辑或"
    - matches:
      - "match_A"
      exec: mark 123456789
    - matches:
      - "match_B"
      exec: mark 123456789

    # 连续执行
    - matches: mark 123456789
      exec: do_something_1
    - matches: mark 123456789
      exec: do_something_2
    # ...
    # 连续执行 else
    - matches: "!mark 123456789"
      exec: else_do_something_1
    - matches: "!mark 123456789"
      exec: else_do_something_2
```
