### DISCUSSION TITLE
请教下这个配置是什么地方出了问题，运行一直报错

### DISCUSSION THREAD

**Discussion by Hades-001** [IrineSistiana/mosdns#587] [Q&A]
```
log:
  level: info
  file: "./mosdns.log"

plugins:
  - tag: "main"
    type: "sequence"
    args:
      - matches:
          - qname $ads_domain
        exec: reject 3
      - exec: $custom_hosts
      - matches: has_resp
        exec: accept
      - exec: $custom_cache
      - matches: has_resp
        exec: accept
      - matches:
          - qname $local_domain
        exec: $forward_local
      - matches: has_wanted_resp
        exec: accept
      - matches:
          - qname $non_local_domain
        exec: $forward_remote
      - matches: has_wanted_resp
        exec: accept
      - exec: $custom_fallback

  - tag: "custom_fallback"
    type: "fallback"
    args:
      primary:
        - exec: $forward_local
        - matches:
            - "!resp_ip $local_ip"
            - "!has_wanted_resp"
          exec: drop_resp
      secondary:
        - exec: prefer_ipv4
        - exec: $forward_remote
      threshold: 500
      always_standby: true

  - tag: "custom_cache"
    type: "cache"
    args:
      size: 40960
      lazy_cache_ttl: 86400
      dump_file: "./cache.dump"
      dump_interval: 600

  - tag: "custom_hosts"
    type: "hosts"
    args:
      files:
        - "./hosts"

  - tag: "forward_local"
    type: "forward"
    args:
      concurrent: 1
      upstreams:
        - tag: "alidns"
          addr: "tls://223.5.5.5"
          idle_timeout: 10
          enable_pipeline: false
          enable_http3: false
          max_conns: 2
          insecure_skip_verify: false
        - tag: "dnspod"
          addr: "https://doh.pub/dns-query"
          dial_addr: "1.12.12.12"
          idle_timeout: 30
          enable_pipeline: false
          enable_http3: false
          max_conns: 2
          insecure_skip_verify: false
  - tag: "forward_remote"
    type: "forward"
    args:
      concurrent: 3
      upstreams:
        - tag: "google_dot"
          addr: "tls://dns.google"
          dial_addr: "8.8.8.8"
          idle_timeout: 10
          enable_pipeline: true
          enable_http3: true
          max_conns: 2
          insecure_skip_verify: false
        - tag: "cloudflare_dot"
          addr: "tls://1.1.1.1"
          idle_timeout: 10
          enable_pipeline: true
          enable_http3: true
          max_conns: 2
          insecure_skip_verify: false
        - tag: "opendns"
          addr: "tcp://208.67.222.222:5353"
          idle_timeout: 10
          enable_pipeline: true
          enable_http3: true
          max_conns: 2
          insecure_skip_verify: false

  - tag: "ads_domain"
    type: "domain_set"
    args:
      files:
        - "./oisd_dbl_full.txt"
  - tag: "local_domain"
    type: "domain_set"
    args:
      files:
        - "./direct-list.txt"
  - tag: "non_local_domain"
    type: "domain_set"
    args:
      files:
        - "./proxy-list.txt"
  - tag: "local_ip"
    type: "ip_set"
    args:
      files:
        - "./china_ip_list.txt"

  - type: "udp_server"
    args:
      entry: main
      listen: 0.0.0.0:53
  - type: "tcp_server"
    args:
      entry: main
      listen: 0.0.0.0:53
```

报错的日志

```
2023-01-15T20:20:08.856+0800    INFO    main config loaded      {"file": "config.yaml"}
Error: failed to init plugin #0 main, failed to init plugin: failed to init rule #0, failed to init matcher #0, failed to init matcher, cannot find domain set ads_domain
2023-01-15T20:20:08.864+0800    FATAL   failed to init plugin #0 main, failed to init plugin: failed to init rule #0, failed to init matcher #0, failed to init matcher, cannot find domain set ads_domain
```

**Comment by ghost** [comment]
.

**Reply by Hades-001** [reply]
放到最后 fallback 报错了，fallback 这个组件要怎么用啊，wiki 没看太明白。

```
2023-01-16T00:42:44.292+0800    INFO    main config loaded      {"file": "config.yaml"}
Error: failed to init plugin #0 custom_fallback, unable to decode plugin args: 2 error(s) decoding:

* 'primary' expected type 'string', got unconvertible type '[]interface {}', value: '[map[exec:$forward_local] map[exec:drop_resp matches:[!resp_ip $local_ip !has_wanted_ans]]]'
* 'secondary' expected type 'string', got unconvertible type '[]interface {}', value: '[map[exec:prefer_ipv4] map[exec:$forward_remote]]'
2023-01-16T00:42:44.308+0800    FATAL   failed to init plugin #0 custom_fallback, unable to decode plugin args: 2 error(s) decoding:

* 'primary' expected type 'string', got unconvertible type '[]interface {}', value: '[map[exec:$forward_local] map[exec:drop_resp matches:[!resp_ip $local_ip !has_wanted_ans]]]'
* 'secondary' expected type 'string', got unconvertible type '[]interface {}', value: '[map[exec:prefer_ipv4] map[exec:$forward_remote]]'
```

现在的配置文件

```
log:
  level: info
  file: "./mosdns.log"

plugins:
  - tag: "custom_cache"
    type: "cache"
    args:
      size: 40960
      lazy_cache_ttl: 86400
      dump_file: "./cache.dump"
      dump_interval: 600

  - tag: "custom_hosts"
    type: "hosts"
    args:
      files:
        - "./hosts"

  - tag: "forward_local"
    type: "forward"
    args:
      concurrent: 1
      upstreams:
        - tag: "alidns"
          addr: "tls://223.5.5.5"
          idle_timeout: 10
          enable_pipeline: false
          enable_http3: false
          max_conns: 2
          insecure_skip_verify: false
        - tag: "dnspod"
          addr: "https://doh.pub/dns-query"
          dial_addr: "1.12.12.12"
          idle_timeout: 30
          enable_pipeline: false
          enable_http3: false
          max_conns: 2
          insecure_skip_verify: false
  - tag: "forward_remote"
    type: "forward"
    args:
      concurrent: 3
      upstreams:
        - tag: "google_dot"
          addr: "tls://dns.google"
          dial_addr: "8.8.8.8"
          idle_timeout: 10
          enable_pipeline: true
          enable_http3: true
          max_conns: 2
          insecure_skip_verify: false
        - tag: "cloudflare_dot"
          addr: "tls://1.1.1.1"
          idle_timeout: 10
          enable_pipeline: true
          enable_http3: true
          max_conns: 2
          insecure_skip_verify: false
        - tag: "opendns"
          addr: "tcp://208.67.222.222:5353"
          idle_timeout: 10
          enable_pipeline: true
          enable_http3: true
          max_conns: 2
          insecure_skip_verify: false

  - tag: "ads_domain"
    type: "domain_set"
    args:
      files:
        - "./oisd_dbl_full.txt"
  - tag: "local_domain"
    type: "domain_set"
    args:
      files:
        - "./direct-list.txt"
  - tag: "non_local_domain"
    type: "domain_set"
    args:
      files:
        - "./proxy-list.txt"
  - tag: "local_ip"
    type: "ip_set"
    args:
      files:
        - "./china_ip_list.txt"

  - tag: "custom_fallback"
    type: "fallback"
    args:
      primary:
        - exec: $forward_local
        - matches:
            - "!resp_ip $local_ip"
            - "!has_wanted_ans"
          exec: drop_resp
      secondary:
        - exec: prefer_ipv4
        - exec: $forward_remote
      threshold: 500
      always_standby: true
  
  - tag: "main"
    type: "sequence"
    args:
      - matches:
          - qname $ads_domain
        exec: reject 3
      - exec: $custom_hosts
      - matches: has_resp
        exec: accept
      - exec: $custom_cache
      - matches: has_resp
        exec: accept
      - matches:
          - qname $local_domain
        exec: $forward_local
      - matches: has_wanted_ans
        exec: accept
      - matches:
          - qname $non_local_domain
        exec: $forward_remote
      - matches: has_wanted_ans
        exec: accept
      - exec: $custom_fallback
  
  - type: "udp_server"
    args:
      entry: main
      listen: 0.0.0.0:53
  - type: "tcp_server"
    args:
      entry: main
      listen: 0.0.0.0:53
```

**Reply by Hades-001** [reply]
改成这样可以运行了

```
log:
  level: info
  file: "./mosdns.log"

plugins:
  - tag: "custom_cache"
    type: "cache"
    args:
      size: 40960
      lazy_cache_ttl: 86400
      dump_file: "./cache.dump"
      dump_interval: 600

  - tag: "custom_hosts"
    type: "hosts"
    args:
      files:
        - "./hosts"

  - tag: "forward_local"
    type: "forward"
    args:
      concurrent: 1
      upstreams:
        - tag: "alidns"
          addr: "tls://223.5.5.5"
          idle_timeout: 10
          enable_pipeline: false
          enable_http3: false
          max_conns: 2
          insecure_skip_verify: false
        - tag: "dnspod"
          addr: "https://doh.pub/dns-query"
          dial_addr: "1.12.12.12"
          idle_timeout: 30
          enable_pipeline: false
          enable_http3: false
          max_conns: 2
          insecure_skip_verify: false
  - tag: "forward_remote"
    type: "forward"
    args:
      concurrent: 3
      upstreams:
        - tag: "google_dot"
          addr: "tls://dns.google"
          dial_addr: "8.8.8.8"
          idle_timeout: 10
          enable_pipeline: true
          enable_http3: true
          max_conns: 2
          insecure_skip_verify: false
        - tag: "cloudflare_dot"
          addr: "tls://1.1.1.1"
          idle_timeout: 10
          enable_pipeline: true
          enable_http3: true
          max_conns: 2
          insecure_skip_verify: false
        - tag: "opendns"
          addr: "tcp://208.67.222.222:5353"
          idle_timeout: 10
          enable_pipeline: true
          enable_http3: true
          max_conns: 2
          insecure_skip_verify: false

  - tag: "ads_domain"
    type: "domain_set"
    args:
      files:
        - "./oisd_dbl_full.txt"
  - tag: "local_domain"
    type: "domain_set"
    args:
      files:
        - "./direct-list.txt"
  - tag: "non_local_domain"
    type: "domain_set"
    args:
      files:
        - "./proxy-list.txt"
  - tag: "local_ip"
    type: "ip_set"
    args:
      files:
        - "./china_ip_list.txt"

  - tag: "local"
    type: "sequence"
    args:
      - exec: $forward_local
      - matches:
          - "!resp_ip $local_ip"
          - "!has_wanted_ans"
        exec: drop_resp
  - tag: "remote"
    type: "sequence"
    args:
      - exec: prefer_ipv4
      - exec: $forward_remote

  - tag: "custom_fallback"
    type: "fallback"
    args:
      primary: local
      secondary: remote
      threshold: 500
      always_standby: true
  
  - tag: "main"
    type: "sequence"
    args:
      - matches:
          - qname $ads_domain
        exec: reject 3
      - exec: $custom_hosts
      - matches: has_resp
        exec: accept
      - exec: $custom_cache
      - matches: has_resp
        exec: accept
      - matches:
          - qname $local_domain
        exec: $forward_local
      - matches: has_wanted_ans
        exec: accept
      - matches:
          - qname $non_local_domain
        exec: $forward_remote
      - matches: has_wanted_ans
        exec: accept
      - exec: $custom_fallback
  
  - type: "udp_server"
    args:
      entry: main
      listen: 0.0.0.0:53
  - type: "tcp_server"
    args:
      entry: main
      listen: 0.0.0.0:53
```
