### DISCUSSION TITLE
match后，我要执行2个exec，怎么写呢？

### DISCUSSION THREAD

**Discussion by PHCSJC** [IrineSistiana/mosdns#601] [Q&A] [answered]
就比如下面的，先写入ipset，再accept，这个应该怎么写呢？下面这个是错误的配置，启动会报错
```yaml
      - matches: qname &/etc/mosdns/gfw-list.txt
        exec: $forward_remote
      - matches: has_resp
        exec: ipset gfwlist,inet,24
        exec: accept 
```

**Comment by 4thanks** [comment]
https://github.com/IrineSistiana/mosdns/issues/599#issuecomment-1411750463
和 v4 不一样。v5 需要手动终止。后面加
```yaml
- matches: has_resp
  exec: accept
```

**Reply by PHCSJC** [reply]
> [#599 (comment)](https://github.com/IrineSistiana/mosdns/issues/599#issuecomment-1411750463) 和 v4 不一样。v5 需要手动终止。后面加
> 
> ```yaml
> - matches: has_resp
>   exec: accept
> ```

帅哥，你没明白我的意思，我是要在match后，先执行ipset，再执行终止，这个怎么写呢？

**Comment by wangmice** [comment]
写成这样行不：
```
- matches: qname &/etc/mosdns/gfw-list.txt
        exec: $forward_remote
      - matches: has_resp
        exec: 
		 - ipset gfwlist,inet,24
		 - accept 
```

**Comment by urlesistiana** [comment, marked as answer]
一个 rule = 零个或多个 match + **一个** exec 。不支持写两个 exec。

> 我要执行2/多个exec，怎么写呢？

写在另一个 sequence

```yaml

      - matches: qname &/etc/mosdns/gfw-list.txt
        exec: goto gfw-list

# ...
# 另一个 sequence 叫 gfw-list
        exec: ipset gfwlist,inet,24
        exec: accept 
```

**Reply by wangmice** [reply]
这样似乎导致配置文件过于复杂，也不直观。如果一个exec能执行多个操作就好了，wiki里好像有这种写法的。
exec:
    - 
    -

**Reply by PHCSJC** [reply]
可以了，感谢！你那最后那2个exec少了个 -

```yaml
  - tag: gfw-list
    type: sequence
    args:
      - exec: ipset gfwlist,inet,24
      - exec: accept
```
