### DISCUSSION TITLE
matches的域名如果没解析成功就不会继续往下走了

### DISCUSSION THREAD

**Discussion by PHCSJC** [IrineSistiana/mosdns#603] [Q&A] [answered]
重现步骤：
修改1个不存在的本地DNS，比如1.2.3.4
解析dig baidu.com 127.0.0.1 -p 5353，解析不出结果
我理解正常的逻辑应该是如果本地DNS解析不出结果，会继续到fallback，然后由secondary来解析出来结果，而实际上并不是
如果把我标注上面的那段去掉，就可以由secondary成功解析

所以问题是，为什么会在我标注的那里停了，不继续往下走了？

```yaml
# /etc/mosdns/config.yaml
log:
  level: debug

plugins:
  # 缓存
  - tag: cache
    type: cache
    args:
      size: 10240
      lazy_cache_ttl: 86400

  # 转发至本地服务器
  - tag: forward_local
    type: forward
    args:
      upstreams:
        - addr: udp://1.2.3.4

  # 转发至远程服务器
  - tag: forward_remote
    type: forward
    args:
      upstreams:
        - addr: tcp://8.8.8.8

  # fallback 用本地服务器 sequence
  # 返回不包含本地 ip 则 reject
  - tag: local_ip_sequence
    type: sequence
    args:
      - exec: $forward_local
      - matches: resp_ip &/etc/mosdns/CN-ip-cidr.txt
        exec: accept
      - exec: reject

  # fallback 用远程服务器 sequence
  - tag: remote_sequence
    type: sequence
    args:
      - exec: $forward_remote
      - exec: accept

  # fallback 用远程服务器 sequence
  - tag: "fallback"
    type: "fallback"
    args:
      primary: local_ip_sequence
      secondary: remote_sequence
      threshold: 500
      always_standby: true


  # 主要的运行逻辑插件
  # sequence 插件中调用的插件 tag 必须在 sequence 前定义，
  # 否则 sequence 找不到对应插件。
  - tag: main_sequence
    type: sequence
    args:
      - matches: qname &/etc/mosdns/reject-list.txt
        exec: reject

      - exec: $cache
      - matches: has_resp
        exec: accept

      - matches: qname &/etc/mosdns/direct-list.txt
        exec: $forward_local
      - matches: has_resp
        exec: accept
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<到这里就结束了，不继续往下走了

      - matches: qname &/etc/mosdns/gfw-list.txt
        exec: $forward_remote
      - matches: has_resp
        exec: accept

      - exec: $fallback



  # 启动 udp 服务器。
  - tag: udp_server
    type: udp_server
    args:
      entry: main_sequence
      listen: :5353
```
