### DISCUSSION TITLE
分享个v5国内国外域名分流的配置

### DISCUSSION THREAD

**Discussion by PHCSJC** [IrineSistiana/mosdns#605] [Ideas]
首先感谢大佬的付出，从v3就开始用，真的非常不错，感谢！

这个配置可以实现：
1.国内域名（已知和未知）用国内DNS解析，直连
2.国外域名（已经和未知）用国外DNS解析，走代理访问（ipset方式）
未知域名的处理方式：先用国内和国外DNS并行解析出ip，再用ip判断，如果是国内ip则直连，如果是国外ip则走代理

```yaml
log:
  level: info

plugins:
  # 缓存
  - tag: cache
    type: cache
    args:
      size: 10240
      lazy_cache_ttl: 86400

  # 重定向域名
  - tag: redirect
    type: redirect
    args:
      rules:
        - www.cnbeta.com www.cnbeta.com.cdn.cloudflare.net

  # 转发至国内DNS, 并发查询
  - tag: forward_local
    type: forward
    args:
      concurrent: 2
      upstreams:
        - addr: udp://119.29.29.29
        - addr: udp://223.5.5.5

  # 转发至国外DNS, 并发查询
  - tag: forward_remote
    type: forward
    args:
      concurrent: 2
      upstreams:
        - addr: tcp://8.8.8.8
        - addr: tcp://1.1.1.1

  # 自定义hosts
  - tag: hosts
    type: hosts
    args:
      files:
        - "/etc/mosdns/hosts"

  # china ip和自己的vps ip、国内dns ip、内网ip，避免这些ip被加到ipset
  - tag: local_ip
    type: ip_set
    args:
      files:
        - /etc/mosdns/china_ip_list.txt
        - /etc/mosdns/myvpsip.txt

  # fallback的primary服务器, 返回国内ip则accept, 返回非国内ip则drop
  - tag: local_sequence
    type: sequence
    args:
      - exec: $forward_local
      - matches: resp_ip $local_ip
        exec: accept
      - exec: drop_resp

  # fallback的secondary服务器, 返回非国内ip则添加至ipset, 返回国内ip只接受不会添加ipset
  - tag: remote_sequence
    type: sequence
    args:
      - exec: $forward_remote
      - matches: "!resp_ip $local_ip"
        exec: ipset gfwlist,inet,32
      - exec: accept

  # fallback sequence
  - tag: fallback
    type: fallback
    args:
      primary: local_sequence
      secondary: remote_sequence
      threshold: 500
      always_standby: true

  # gfwlist解析出的ip添加至ipset，添加前先判断是否为国内ip或内网ip
  - tag: gfw-list
    type: sequence
    args:
      - exec: ttl 300-3600
      - matches: "!resp_ip $local_ip"
        exec: ipset gfwlist,inet,24
      - exec: accept

  # 主运行序列
  - tag: main_sequence
    type: sequence
    args:
      - exec: $hosts
      - matches: has_resp
        exec: accept

      # 屏蔽PTR和DNSSEC，解决ios系统的一些问题
      - matches: qtype 12 65
        exec: reject 0

      # 屏蔽广告
      - matches: qname &/etc/mosdns/reject-list.txt &/etc/mosdns/my-reject-list.txt
        exec: black_hole 127.0.0.1

      - exec: prefer_ipv4

      - exec: $redirect

      # 动态域名跳过缓存
      - matches: "!qname 00006801.com"
        exec: $cache
      - matches: has_resp
        exec: accept

      # 国内域名
      - matches: qname &/etc/mosdns/direct-list.txt
        exec: $forward_local
      - matches: has_resp
        exec: accept

      # 国外域名
      - matches: qname &/etc/mosdns/proxy-list.txt
        exec: $forward_remote
      - matches: has_resp
        exec: goto gfw-list

      # 其他未知域名
      - exec: $fallback


  # 启动监听服务
  - tag: udp_server
    type: udp_server
    args:
      entry: main_sequence
      listen: :53

  - tag: tcp_server
    type: tcp_server
    args:
      entry: main_sequence
      listen: :53
```

**Comment by PHCSJC** [comment]
一些解释：
1.myvpsip.txt包含所有内网ip段、自己的vps地址、国内的dns，避免这些ip被添加至ipset
2.goto gfw-list是因为要执行多个exec，所以放到一个单独的序列中
3.gfw-list序列中添加了ip判断，是因为之前出现过某个gfw域名解析出的ip竟然是127.0.0.1这种奇葩事件
4.此配置已最优化访问所有网站，不过有2个缺点，缺点1是：有些直接通过ip访问（国外ip）的网站不会走代理，如果常用可以手动添加至ipset来解决，缺点2是：不能防DNS泄漏，可以把所有未知域名只交给国外DNS解析，避免一定的泄漏，但也不能完全避免，比如正常app故意内置了探测域名，且解析出的ip也在国外
5.文件来源
域名和ip均来自：https://github.com/Loyalsoldier/v2ray-rules-dat
china_ip_list：https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/cn.txt
广告域名：https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/reject-list.txt
直连域名：https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/direct-list.txt
代理域名：https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/proxy-list.txt

**Reply by nil-ca** [reply]
> 一些解释： 1.myvpsip.txt包含所有内网ip段和自己的vps地址，避免这些ip被添加至ipset 2.goto gfw-list是因为要执行多个exec，所以放到一个单独的序列中 3.gfw-list序列中添加了ip判断，是因为之前出现过某个gfw域名解析出的ip竟然是127.0.0.1这种奇葩事件 4.此配置已最优化访问所有网站，唯一的缺点是：有些直接通过ip访问（国外ip）的网站不会走代理，如果常用可以手动添加至ipset来解决 5.域名和ip来自：https://github.com/Loyalsoldier/v2ray-rules-dat

IP好像可以用https://github.com/Loyalsoldier/geoip/tree/release/text 
Loyalsoldier大佬好像每次更新都会把新的txt文件传到release 有这个应该可以配合!感叹号做取反吧

**Reply by PHCSJC** [reply]
看了是一样的，可以取反的，感谢！

**Comment by Swiftfrog** [comment]
这是V5的配置吗？看起来好像比V4翻到简洁了。

不过逻辑似乎都没变。

**Comment by yyysuo** [comment]
您好，请问加入ipset有什么好处呢，我看您加入的ipset的名字是gfwlist，是和ssrp配合的吗？我用套娃把dns方案独立出来了，用ipset list gfwlist命令看并没有条目，也没有影响我科学上网。

**Comment by jayolim** [comment]
个人感觉很漂亮，谢谢分享

**Comment by yyysuo** [comment]
关于IPSET，最近学习了一下ssrp和passwall关于ipset的部分，发现都向op的防火墙添加了match-set相关的规则，我觉得可以利用blacklist和whitelist，这2个ipset在ssrp和passwall中都被使用了，gfwlist这个ipset反而没有被添加到防火墙规则当中，楼主是自己添加了iptables规则吗？

**Reply by PHCSJC** [reply]
我用的软路由，直接debian10做网关，ipset和iptables都是自己配置的，所以配置起来很自由

**Comment by w22gb8** [comment]
继续坚守v3

**Comment by zqp561022** [comment]
感谢分享~

**Comment by xiaoyigg** [comment]
不知道咋个用，直接复制配置文件到自定义配置里就可以了嘛？

**Comment by GD2021** [comment]
![image](https://user-images.githubusercontent.com/81171294/225803639-28ae1e3c-5587-4a01-adaf-db930284e71a.png)

![image](https://user-images.githubusercontent.com/81171294/225803517-56a6eef8-d4ac-4658-9a23-8ed0c0f9a837.png)
log:
  level: info

plugins:
  # 缓存
  - tag: cache
    type: cache
    args:
      size: 10240
      lazy_cache_ttl: 86400

  # 重定向域名
  - tag: redirect
    type: redirect
    args:
      rules:
        - www.cnbeta.com www.cnbeta.com.cdn.cloudflare.net

  # 转发至国内DNS，并发查询
  - tag: forward_local
    type: forward
    args:
      upstreams:
      concurrent: 2
        - addr: udp://119.29.29.29
        - addr: udp://223.5.5.5

  # 转发至国外DNS，并发查询
  - tag: forward_remote
    type: forward
    args:
      upstreams:
      concurrent: 2
        - addr: tcp://8.8.8.8
        - addr: tcp://1.1.1.1

  # 自定义hosts
  - tag: hosts
    type: hosts
    args:
      files:
        - "/etc/mosdns/hosts"

  # china ip和自己的vps ip
  - tag: local_ip
    type: ip_set
    args:
      files:
        - /etc/mosdns/rule/china_ip_list.txt
        - /etc/mosdns/rule/myvpsip.txt

  # fallback的primary服务器,返回非国内ip则drop_resp
  - tag: local_sequence
    type: sequence
    args:
      - exec: $forward_local
      - matches: "!resp_ip $local_ip"
        exec: accept
      - exec: drop_resp

  # fallback的secondary服务器,返回非国内ip则添加至ipset,返回国内ip只接受不会添加ipset
  - tag: remote_sequence
    type: sequence
    args:
      - exec: $forward_remote
      - matches: "!resp_ip $local_ip"
        exec: ipset gfwlist,inet,24
      - exec: accept

  # fallback sequence
  - tag: fallback
    type: fallback
    args:
      primary: local_sequence
      secondary: remote_sequence
      threshold: 500
      always_standby: true

  # gfwlist解析出的ip添加至ipset，添加前先判断是否为国内ip或内网ip
  - tag: gfw-list
    type: sequence
    args:
      - exec: ttl 300-3600
      - matches: "!resp_ip $local_ip"
        exec: ipset gfwlist,inet,24
      - exec: accept

  # 主运行序列
  - tag: main_sequence
    type: sequence
    args:
      - exec: $hosts
      - matches: has_resp
        exec: accept
      
      - matches: qtype 65
        exec: reject 3

      - matches: qname &/etc/mosdns/rule/reject-list.txt &/etc/mosdns/my-reject-list.txt
        exec: reject

      - exec: prefer_ipv4

      - exec: $redirect

      # 动态域名跳过缓存
      - matches: "!qname 00006801.com"
        exec: $cache
      - matches: has_resp
        exec: accept

      - matches: qname &/etc/mosdns/rule/direct-list.txt
        exec: $forward_local
      - matches: has_resp
        exec: accept

      - matches: qname &//etc/mosdns/rule/proxy-list.txt
        exec: $forward_remote
      - matches: has_resp
        exec: goto gfw-list

      - exec: $fallback


  # 启动监听服务
  - tag: udp_server
    type: udp_server
    args:
      entry: main_sequence
      listen: :53

  - tag: tcp_server
    type: tcp_server
    args:
      entry: main_sequence
      listen: :53

我下载了需要的配置文件，并且修改了配置的路径，为何运行不起来呢

**Reply by GD2021** [reply]
我是在N1旁路由上使用的

**Reply by tlze** [reply]
找个搞技术的帮你一把先，就你上面的问题，很难有人能帮到你。

**Reply by GD2021** [reply]
我是装的luci版5.1.1

**Reply by ziyeqf** [reply]
挖个坟, 可以用一下命令手动运行mosdns来查看报错信息 , 其中`{config_file}`是你配置文件的路径
```
mosdns start -c {config_file}
```

**Comment by AlphaAnother** [comment]
> 首先感谢大佬的付出，从v3就开始用，真的非常不错，感谢！
> 
> 这个配置可以实现： 1.国内域名（已知和未知）用国内DNS解析，直连 2.国外域名（已经和未知）用国外DNS解析，走代理访问（ipset方式）
> 
> ```yaml
> log:
>   level: info
> 
> plugins:
>   # 缓存
>   - tag: cache
>     type: cache
>     args:
>       size: 10240
>       lazy_cache_ttl: 86400
> 
>   # 重定向域名
>   - tag: redirect
>     type: redirect
>     args:
>       rules:
>         - www.cnbeta.com www.cnbeta.com.cdn.cloudflare.net
> 
>   # 转发至国内DNS，并发查询
>   - tag: forward_local
>     type: forward
>     args:
>       upstreams:
>       concurrent: 2
>         - addr: udp://119.29.29.29
>         - addr: udp://223.5.5.5
> 
>   # 转发至国外DNS，并发查询
>   - tag: forward_remote
>     type: forward
>     args:
>       upstreams:
>       concurrent: 2
>         - addr: tcp://8.8.8.8
>         - addr: tcp://1.1.1.1
> 
>   # 自定义hosts
>   - tag: hosts
>     type: hosts
>     args:
>       files:
>         - "/etc/mosdns/hosts"
> 
>   # china ip和自己的vps ip
>   - tag: local_ip
>     type: ip_set
>     args:
>       files:
>         - /etc/mosdns/china_ip_list.txt
>         - /etc/mosdns/myvpsip.txt
> 
>   # fallback的primary服务器,返回非国内ip则drop_resp
>   - tag: local_sequence
>     type: sequence
>     args:
>       - exec: $forward_local
>       - matches: "!resp_ip $local_ip"
>         exec: accept
>       - exec: drop_resp
> 
>   # fallback的secondary服务器,返回非国内ip则添加至ipset,返回国内ip只接受不会添加ipset
>   - tag: remote_sequence
>     type: sequence
>     args:
>       - exec: $forward_remote
>       - matches: "!resp_ip $local_ip"
>         exec: ipset gfwlist,inet,24
>       - exec: accept
> 
>   # fallback sequence
>   - tag: fallback
>     type: fallback
>     args:
>       primary: local_sequence
>       secondary: remote_sequence
>       threshold: 500
>       always_standby: true
> 
>   # gfwlist解析出的ip添加至ipset，添加前先判断是否为国内ip或内网ip
>   - tag: gfw-list
>     type: sequence
>     args:
>       - exec: ttl 300-3600
>       - matches: "!resp_ip $local_ip"
>         exec: ipset gfwlist,inet,24
>       - exec: accept
> 
>   # 主运行序列
>   - tag: main_sequence
>     type: sequence
>     args:
>       - exec: $hosts
>       - matches: has_resp
>         exec: accept
>       
>       - matches: qtype 65
>         exec: reject 3
> 
>       - matches: qname &/etc/mosdns/reject-list.txt &/etc/mosdns/my-reject-list.txt
>         exec: reject
> 
>       - exec: prefer_ipv4
> 
>       - exec: $redirect
> 
>       # 动态域名跳过缓存
>       - matches: "!qname 00006801.com"
>         exec: $cache
>       - matches: has_resp
>         exec: accept
> 
>       - matches: qname &/etc/mosdns/direct-list.txt
>         exec: $forward_local
>       - matches: has_resp
>         exec: accept
> 
>       - matches: qname &/etc/mosdns/proxy-list.txt
>         exec: $forward_remote
>       - matches: has_resp
>         exec: goto gfw-list
> 
>       - exec: $fallback
> 
> 
>   # 启动监听服务
>   - tag: udp_server
>     type: udp_server
>     args:
>       entry: main_sequence
>       listen: :53
> 
>   - tag: tcp_server
>     type: tcp_server
>     args:
>       entry: main_sequence
>       listen: :53
> ```

local_sequence这段的执行是不是搞反了？和注释的逻辑不一样吧？

**Reply by bovbo** [reply]
顺手复制粘贴不能起动  用内置运行有时间再研究修改下

**Reply by CyEilo** [reply]
同感

```
  # fallback的primary服务器,返回非国内ip则drop_resp
  - tag: local_sequence
    type: sequence
    args:
      - exec: $forward_local
      - matches: "!resp_ip $local_ip"
        exec: accept
      - exec: drop_resp

  # fallback的secondary服务器,返回非国内ip则添加至ipset,返回国内ip只接受不会添加ipset
  - tag: remote_sequence
    type: sequence
    args:
      - exec: $forward_remote
      - matches: "!resp_ip $local_ip"
        exec: ipset gfwlist,inet,24
      - exec: accept
```

按照注释的理解 第一段最后两行似乎写反了?
应该是?

```
  # fallback的primary服务器,返回非国内ip则drop_resp
  - tag: local_sequence
    type: sequence
    args:
      - exec: $forward_local
      - matches: "!resp_ip $local_ip"
        exec: drop_resp
      - exec: accept
```


不是很确定, 或者是注释写错了?希望有大佬解惑
