### DISCUSSION TITLE
问一下matches 怎么实现 “或”呢？

### DISCUSSION THREAD

**Discussion by wangmice** [IrineSistiana/mosdns#608] [Q&A]
多个条件是and的关系，如果要实现或的关系怎么处理？
比如 if A and B or C 后执行一条规则D。
如果分成两个matches写：
```
- matches:
   - A
   - B
   exec: D
 - matches: C
    exec: D
```
还是达不到上述的效果，如果两个matches都匹配的话，D要执行两次了。

**Comment by wwng2333** [comment]
可以考虑用 mosdns v4 ，支持`||` 和 `&&`。

**Comment by BuBuXSY** [comment]
我写的时候 也突然发现 V4的与或不能用了 只能只能硬着头皮让他们重复一遍又一遍这样子走

**Comment by 4thanks** [comment]
可以试试`goto`或`jump`配合`return`。
```yaml
# if A and B序列
...
 - matches:
    - A
    - B
    exec: D
 - exec: goto c-tag

# or C序列
 ...
 - matches: C
    exec: D
 - exec: return
```
