### DISCUSSION TITLE
分享个基于mosdns v5，OpenWRT接管dnsmasq解析的配置

### DISCUSSION THREAD

**Discussion by wwng2333** [IrineSistiana/mosdns#614] [Ideas]
```yaml
log:
  level: info
  file: "/tmp/mosdns.log"

plugins:
  - tag: forward_alidns 
    type: forward
    args:
      upstreams:
        - addr: https://dns.alidns.com/dns-query
          bootstrap: 223.5.5.5
  - tag: main
    type: sequence
    args:
      - matches:
        - "!qname domain:.lan"
        exec: $forward_alidns
      - matches: has_resp
        exec: accept 
      - exec: forward 192.168.123.1:531
  - type: udp_server
    args:
      entry: main
      listen: 0.0.0.0:53
```
如题，将dnsmasq端口设置成531，非本地解析发给阿里DoH，本地解析发给dnsmasq，测试一切正常。
