### DISCUSSION TITLE
分享个V5的配置

### DISCUSSION THREAD

**Discussion by yubanmeiqin9048** [IrineSistiana/mosdns#624] [Ideas]
```yaml
log:
  level: info
  production: true

plugins: 
  - tag: "direct_domain"
    type: domain_set
    args:
      files:
        - "./accelerated-domains.china.txt"

  - tag: "direct_ip"
    type: ip_set
    args:
      files:
        - "./CN-ip-cidr.txt"

  - tag: "hosts"
    type: hosts
    args:
      files:                       
        - "./hosts.txt"             

  - tag: "cache"
    type: cache
    args:
      size: 65536
      lazy_cache_ttl: 86400
      dump_file: ./cache.dump

  - tag: "remote_forward"
    type: forward
    args:
      concurrent: 2
      upstreams: 
        - addr: "https://8.8.4.4/dns-query"
          socks5: "127.0.0.1:1080"
          idle_timeout: 86400
        - addr: "https://1.0.0.1/dns-query"
          socks5: "127.0.0.1:1080"
          idle_timeout: 86400

  - tag: "local_forward"
    type: forward
    args:
      concurrent: 2
      upstreams: 
        - addr: "https://223.5.5.5/dns-query"
          idle_timeout: 86400
        - addr: "https://120.53.53.53/dns-query"
          idle_timeout: 86400

  - tag: "ttl_sequence"
    type: sequence
    args:
      - exec: ttl 600-3600
      - exec: accept

  - tag: "local_sequence"
    type: sequence
    args:
      - exec: query_summary local_forward
      - exec: $local_forward
      - exec: goto ttl_sequence

  - tag: "remote_sequence"
    type: sequence
    args:
      - exec: query_summary remote_forward
      - exec: $remote_forward
      - matches: "resp_ip $direct_ip"
        exec: goto local_sequence
      - exec: goto ttl_sequence

  - tag: "final"
    type: fallback
    args:
      primary: remote_sequence
      secondary: local_sequence
      threshold: 500
      always_standby: true

  - tag: "main_sequence"
    type: sequence
    args:
      - exec: prefer_ipv4
      - exec: $hosts
      - exec: $cache
      - matches: has_resp
        exec: accept
      - matches: "qname $direct_domain"
        exec: goto local_sequence
      - exec: $final


  - tag: udp_server
    type: udp_server
    args:
      entry: main_sequence
      listen: :53
```
