### DISCUSSION TITLE
[分享]本以为sleep插件没什么卵用就是个demo插件，结果我发现它的妙用

### DISCUSSION THREAD

**Discussion by mkanako** [IrineSistiana/mosdns#63] [Ideas]
因为日志出现大量的几个apple.com域名报错
```
2021-02-04T14:45:44.042+0800	warn	fast_forward_remote	utils/utils.go:325	upstream failed	{"query": "time-macos.apple.com. 1 1 12455 41", "from": "tls://dns.google", "error": "dial tcp 8.8.8.8:853: connect: network is down"}
```
单独测试又没啥问题，匪夷所思，很恼人

观察了一段时间似乎明白了，这些错误都发生在电脑睡眠后刚刚被唤醒的时候，网络还没连接好
就琢磨着怎么解决，想到在缓存上动手，顺便优化下缓存提高缓存效率，于是就有了这个帖子https://github.com/IrineSistiana/mosdns/discussions/62

然后我又灵光一闪，错误发生在网络还没连接好的情况，那就延迟一下等连好了，再请求就噢了

sleep插件闪亮登场，日志再也没错误了🥳

**Comment by IrineSistiana** [comment]
sleep 是 parallel 微调延时差用的。

现有机制你是怎么 重连时触发 sleep 的?🤔

**Reply by mkanako** [reply]
你可能还没理解好，不存在你说的这回事

问题：电脑刚刚被唤醒，不知道哪个进程就会请求time-macos.apple.com，但这时候我估计是因为网络还不通，所以日志就出现报错

解决很简单
```
if:
    - match_apple_domain
  exec:
    - sleep1000
    - fast_forward_local
  goto: _end
```
