### DISCUSSION TITLE
请问是我对accept的理解有问题吗？

### DISCUSSION THREAD

**Discussion by 2cydg** [IrineSistiana/mosdns#637] [Q&A] [answered]
版本号：V5.1.1
首先说我想实现的效果：
1. 国内域名和我指定的直连域名(有部分国外域名)准确解析，直接使用fallback流程；
2. 其他域名转发给clash的dns，返回fake-ip。

关键配置如下
```yaml
    # 转发到clash
    - tag: forward_fake_ip
      type: forward
      args:
        concurrent: 1
        upstreams:
          - tag: forward_clash
            addr: "127.0.0.1:55553"

    # 国内域名转发流程
    - tag: local_sequence
      type: sequence
      args:
        - exec: $forward_local
        - matches: resp_ip $local_ip
          exec: accept
        - exec: reject

    # 国外域名转发流程
    - tag: remote_sequence
      type: sequence
      args:
        - exec: $forward_remote
        - exec: accept

    # fallback流程
    - tag: fallback_sequence
      type: fallback
      args:
        primary: local_sequence
        secondary: remote_sequence
        threshold: 500
        always_standby: true

    # direct流程
    - tag: direct_sequence
      type: sequence
      args:
        - exec: $cache
        - matches: has_resp
          exec: accept

        - exec: $fallback_sequence
        - exec: accept
    # 主流程
    - tag: main_sequence
      type: sequence
      args:
        - matches: qtype 65
          exec: reject 3

        - exec: prefer_ipv4

        - matches: qname $direct_domain
          exec: $direct_sequence

        - matches: qname $proxy_domain
          exec: $forward_fake_ip
        - exec: accept

```

问题是，direct_sequence中最后执行了accept，fallback插件的两个流程中也分别有accept，但是main_sequence中似乎并没有停止执行后续规则，还是转发到了clash
这就导致我执行 nslookup cn.bing.com，返回的是fake-ip

mosdns的wiki里对accept是这样描述的
``` text
停止后续规则执行。如果本 sequence 存在上级 sequence，所有上级的 sequence 也不再继续执行后续规则。
```

我理解的是只要执行了accept，内层和外层的sequence都不再继续执行了，请问是我理解的不对吗？
如果要实现我上边说的效果，应该如何配置？

**Comment by urlesistiana** [comment, marked as answer]
你的理解没问题。fallback 的 bug #633

编译 HEAD 试试？

**Reply by 2cydg** [reply]
好的，谢谢！  
我升级到最新版本试试

**Reply by 2cydg** [reply]
最新版本V5.1.2依旧是同样的问题，我在main_sequence的exec: $direct_sequence下边加了- matches: has_resp exec: accept，流程才结束 

```yaml
    # 主流程
    - tag: main_sequence
      type: sequence
      args:
        - matches: qtype 65
          exec: reject 3

        - exec: prefer_ipv4

        - matches: qname $direct_domain
          exec: $direct_sequence
        - matches: has_resp
          exec: accept

        - matches: qname $proxy_domain
          exec: $forward_fake_ip
        - exec: accept
```

**Reply by urlesistiana** [reply]
你需要自己编译 main 分支的 HEAD。#633 在 v5.1.2 之后。v5.1.2 没修。

**Reply by 2cydg** [reply]
OK，了解了，谢谢！

**Reply by 2cydg** [reply]
我又做了个实验，既然fallback插件有问题，我就不用了，直接用sequence模拟fallback流程
配置如下：
``` yaml
    # 国内域名转发流程
    - tag: local_sequence
      type: sequence
      args:
        - exec: $forward_local
        - matches: resp_ip $local_ip
          exec: accept
        - exec: reject

    # 国外域名转发流程
    - tag: remote_sequence
      type: sequence
      args:
        - exec: $forward_remote
        - exec: accept

    # fallback流程(使用sequence模拟)
    - tag: fallback_sequence
      type: sequence
      args:
        - exec: $local_sequence
        - matches: has_resp
          exec: accept

        - exec: $remote_sequence
        - exec: accept

    # direct流程
    - tag: direct_sequence
      type: sequence
      args:
        - exec: $cache
        - matches: has_resp
          exec: accept

        - exec: $fallback_sequence
        - exec: accept
    # 主流程
    - tag: main_sequence
      type: sequence
      args:
        - matches: qtype 65
          exec: reject 3

        - exec: prefer_ipv4

        - matches: qname $direct_domain
          exec: $direct_sequence

        - matches: qname $proxy_domain
          exec: $forward_fake_ip
        - exec: accept
```
但是问题依旧，nslookup cn.bing.com还是返回了fake-ip
direct_domain里有cn.bing.com
proxy_domain里有bing.com
所以流程还是没有结束，匹配到了proxy_domain里了😂
