### DISCUSSION TITLE
关于 cache 插件使用问题有问

### DISCUSSION THREAD

**Discussion by sbwml** [IrineSistiana/mosdns#652] [Q&A]
```yaml
...
  - tag: lazy_cache
    type: cache
    args:
      size: 20000
      lazy_cache_ttl: 86400
      dump_file: /etc/mosdns/cache.dump
      dump_interval: 600
...
  - tag: main_sequence
    type: sequence
    args:
      - exec: $hosts
      - exec: jump has_resp_sequence
      - matches:
        - "!qname $ddnslist"
        - "!qname $blocklist"
        - "!qname $adlist"
        - "!qname $sp_low"
        exec: $lazy_cache
      - exec: $redirect
      - exec: jump has_resp_sequence
      - exec: $query_is_ddns_domain
...
```

当我以这种方式去运行 cache 插件，设置的 `dump_interval` 将无法生效。即使超过设定时间后，它依然没有将缓存写到硬盘。
但当我停止 mosdns 进程后，它有成功写入缓存到硬盘。

-----------

```yaml
  - tag: main_sequence
    type: sequence
    args:
      - exec: $lazy_cache
```

如果我没有做任何匹配条件，直接运行 cache 插件，那么它自动 dump cache 到磁盘是工作正常的。

如果我要使用独立的 [cache](https://irine-sistiana.gitbook.io/mosdns-wiki/mosdns-v5/ru-he-pei-zhi-mosdns/ke-zhi-hang-cha-jian#cache) 插件，**应该如何正确地排除某些域名列表？**
