### DISCUSSION TITLE
black_hole 是否计划支持使用 tag 或者外部文件

### DISCUSSION THREAD

**Discussion by gqbre** [IrineSistiana/mosdns#668] [Q&A]
```
  # Cloudflare CDN 优选 IP
  - tag: cloudflare_best_ip
    type: ip_set
    args:
      ips:
        - 1.1.1.1

  # fallback 用远程服务器 sequence
  - tag: remote_sequence
    type: sequence
    args:
      - exec: $forward_remote
      # CloudFlare劫持到优选IP
      - matches:
          - resp_ip $cloudflare_ip
        exec: black_hole $cloudflare_best_ip
      - exec: accept
```

上面这样的配置跑不起来，使用 `black_hole 1.1.1.1` 就可以，此处希望是个动态值，或者有什么方案可以实现
