### DISCUSSION TITLE
请大家帮忙针对以下配置给点意见

### DISCUSSION THREAD

**Discussion by PullGuy** [IrineSistiana/mosdns#669] [General]
我想实现的效果：
1. 用ipv6解析ddns域名且不缓存其解析结果；
2. 在ddns域名解析设置prefer_ipv6以后，不影响其他域名的解析；
3. 如果direct和gfw都没有匹配到域名，则能够根据解析得到的IP分流：IP为国外的，送到代理去，IP为国内的则直连。

最后，我有一点疑问：根据解析得到的IP分流，是带域名的转发还是直接转发解析得到的IP？我希望能带域名转发，因为直接转发IP，后面的代理没办法处理。
如有其他改进意见，也请不吝赐教！
配置代码如下：
```yaml
log:
  level: info

plugins:
  # 缓存
  - tag: cache
    type: cache
    args:
      size: 10240
      lazy_cache_ttl: 86400
      dump_file: ./cache.dump
      dump_interval: 600

  # 转发至国内DNS，并发查询
  - tag: local
    type: forward
    args:
      concurrent: 3
      upstreams:
        - tag: ali_doh
          addr: "https://dns.alidns.com/dns-query"
          bootstrap: "211.138.180.2"
          enable_pipeline: true
          max_conns: 10
        - tag: tencent_doh
          addr: "https://doh.pub/dns-query"
          bootstrap: "211.138.180.2"
          enable_pipeline: true
          max_conns: 10
        - tag: cisco_doh
          addr: "https://doh.opendns.com/dns-query"
          bootstrap: "211.138.180.2"
          enable_pipeline: true
          max_conns: 10

  # 转发至代理
  - tag: clash
    type: forward
    args:
      upstreams:
        - addr: 127.0.0.1:1053

  # 主运行序列
  - tag: main_sequence
    type: sequence
    args:
      # 去广告
      - matches:
          - qname &./anti-ad-domains.txt
        exec: reject

      # 动态域名跳过缓存
      - matches: 
        - "!qname &./uncache.txt"
        exec: $cache
      - matches: 
        - has_resp
        exec: accept      

      # 命中direct.txt的域名本地解析
      - matches:
        - qname &./direct.txt
        exec: $local
      - matches:
        - has_resp
        exec: accept

      # 命中gfw.txt的域名直接转发到代理dns
      - matches: 
        - qname &./gfw.txt
        exec: $clash
      - matches: 
        - has_resp
        exec: accept

      # ddns域名设置ttl
      - matches: 
        - "qname &./uncache.txt"
        exec: ttl 60
        exec: prefer_ipv6
      - matches: 
        - has_resp
        exec: accept

      # 其他的请求就查询本地dns
      - exec: $local
      - matches: 
        - "!resp_ip &./all_cn_ip.txt"
        exec: $clash
      - matches: 
        - has_resp
        exec: accept

  # 启动监听服务
  - tag: udp_server
    type: udp_server
    args:
      entry: main_sequence
      listen: :53

  - tag: tcp_server
    type: tcp_server
    args:
      entry: main_sequence
      listen: :53
```
