### DISCUSSION TITLE
Windows 时常显示无internet访问权限

### DISCUSSION THREAD

**Discussion by Pixelw** [IrineSistiana/mosdns#673] [Q&A]
<img width="301" alt="image" src="https://user-images.githubusercontent.com/27913491/235837851-ec2f02a0-1d1d-4452-9bb4-c6a613951b61.png">
我给家里的openwrt配置了mosdns(用那个luci app 配置的基础上改的, dnsmasq转发), 时常Windows下面会出现无internet的情况, 但是上网一切正常.
配置如下:

```yaml
  
  log:
    level: info
    file: "/tmp/mosdns.log"
  
  # carl modded 23-4-12
  
  api:
    http: "0.0.0.0:9091"
  
  include: []
  
  plugins:
    - tag: geosite_cn
      type: domain_set
      args:
        files:
          - "/var/mosdns/geosite_cn.txt"
  
    - tag: geoip_cn
      type: ip_set
      args:
        files:
          - "/var/mosdns/geoip_cn.txt"
  
    - tag: geosite_no_cn
      type: domain_set
      args:
        files:
          - "/var/mosdns/geosite_geolocation-!cn.txt"
  
    - tag: whitelist
      type: domain_set
      args:
        files:
          - "/etc/mosdns/rule/whitelist.txt"
  
    - tag: blocklist
      type: domain_set
      args:
        files:
          - "/etc/mosdns/rule/blocklist.txt"
  
    - tag: greylist
      type: domain_set
      args:
        files:
          - "/etc/mosdns/rule/greylist.txt"
  
    - tag: ddnslist
      type: domain_set
      args:
        files:
          - "/etc/mosdns/rule/ddnslist.txt"
  
    - tag: hosts
      type: hosts
      args:
        files:
          - "/etc/mosdns/rule/hosts.txt"
  
    - tag: redirect
      type: redirect
      args:
        files:
          - "/etc/mosdns/rule/redirect.txt"
  
    - tag: local_ptr
      type: domain_set
      args:
        files:
          - "/etc/mosdns/rule/local-ptr.txt"
  
    - tag: sp_low
      type: domain_set
      args:
        files:
          - "/usr/share/mosdns/sp_low.tdata"
  
    - tag: lazy_cache
      type: cache
      args:
        size: 20000
        lazy_cache_ttl: 86400
        dump_file: /etc/mosdns/cache.dump
        dump_interval: 3600
  
    - tag: forward_local
      type: forward
      args:
        concurrent: 2
        upstreams:
          - addr: https://223.5.5.5/dns-query
            enable_pipeline: true
            max_conns: 2
            insecure_skip_verify: false
            idle_timeout: 30
  
          - addr: tls://1.12.12.12
            enable_pipeline: true
            max_conns: 2
            insecure_skip_verify: false
            idle_timeout: 30
  
          - addr: https://223.6.6.6/dns-query
            enable_pipeline: true
            max_conns: 2
            insecure_skip_verify: false
            idle_timeout: 30
  
          - addr: tls://120.53.53.53
            enable_pipeline: true
            max_conns: 2
            insecure_skip_verify: false
            idle_timeout: 30
  
    - tag: forward_remote
      type: forward
      args:
        concurrent: 2
        upstreams:
          - addr: https://208.67.220.220/dns-query
            enable_pipeline: true
            max_conns: 2
            insecure_skip_verify: false
            idle_timeout: 30
          - addr: https://208.67.222.222/dns-query
            enable_pipeline: true
            max_conns: 2
            insecure_skip_verify: false
            idle_timeout: 30
          - addr: https://doh.apad.pro/dns-query
            bootstrap: 114.114.114.114
            enable_pipeline: true
            max_conns: 2
            insecure_skip_verify: false
            idle_timeout: 30
            enable_http3: false
  
    - tag: unsafe_local
      type: forward
      args: 
        upstreams: 
          - addr: 114.114.114.114
          - addr: 223.5.5.5
          - addr: 223.6.6.6
  
    - tag: modify_ttl
      type: sequence
      args:
        - exec: ttl 0-0
  
    - tag: modify_ddns_ttl
      type: sequence
      args:
        - exec: ttl 5-5
  
    - tag: local_sequence
      type: sequence
      args:
        - exec: $forward_local
  
    - tag: remote_sequence
      type: sequence
      args:
        - exec: prefer_ipv4
        - exec: $forward_remote
  
    - tag: has_resp_sequence
      type: sequence
      args:
        - matches: qname $ddnslist
          exec: $modify_ddns_ttl
        - matches: "!qname $ddnslist"
          exec: $modify_ttl
        - matches: has_resp
          exec: accept
  
    - tag: query_is_local_ip
      type: sequence
      args:
        - exec: $local_sequence
        - matches: "!resp_ip $geoip_cn"
          exec: drop_resp
  
    - tag: query_is_remote
      type: sequence
      args:
        - exec: $remote_sequence
  
    - tag: fallback
      type: fallback
      args:
        primary: query_is_local_ip
        secondary: unsafe_local
        threshold: 500
        always_standby: false
  
    - tag: query_is_ddns_domain
      type: sequence
      args:
        - matches: qname $ddnslist
          exec: $local_sequence
  
    - tag: query_is_local_domain
      type: sequence
      args:
        - matches: qname $geosite_cn
          exec: $local_sequence
  
    - tag: query_is_no_local_domain
      type: sequence
      args:
        - matches: qname $geosite_no_cn
          exec: $remote_sequence
  
    - tag: query_is_whitelist_domain
      type: sequence
      args:
        - matches: qname $whitelist
          exec: $local_sequence
  
    - tag: query_is_greylist_domain
      type: sequence
      args:
        - matches: qname $greylist
          exec: $remote_sequence
  
    - tag: query_is_reject_domain
      type: sequence
      args:
        - matches: qname $blocklist
          exec: reject 3
        - matches: qname $sp_low
          exec: reject 3
        - matches:
          - qtype 12
          - qname $local_ptr
          exec: reject 3
        - matches: qtype 65
          exec: reject 3
  
    - tag: main_sequence
      type: sequence
      args:
        - exec: $hosts
        - exec: jump has_resp_sequence
        - matches:
          - "!qname $ddnslist"
          - "!qname $blocklist"
          - "!qname $sp_low"
          - "!qname $local_ptr"
          exec: $lazy_cache
        - exec: $redirect
        - exec: jump has_resp_sequence
        - exec: $query_is_ddns_domain
        - exec: jump has_resp_sequence
        - exec: $query_is_whitelist_domain
        - exec: jump has_resp_sequence
        - exec: $query_is_reject_domain
        - exec: jump has_resp_sequence
        - exec: $query_is_greylist_domain
        - exec: jump has_resp_sequence
        - exec: $query_is_local_domain
        - exec: jump has_resp_sequence
        - exec: $query_is_no_local_domain
        - exec: jump has_resp_sequence
        - exec: $fallback
  
    - tag: udp_server
      type: udp_server
      args:
        entry: main_sequence
        listen: ":5335"
  
    - tag: tcp_server
      type: tcp_server
      args:
        entry: main_sequence
        listen: ":5335"
```
