### DISCUSSION TITLE
自定义qname，没有按照预期使用upstream

### DISCUSSION THREAD

**Discussion by luweijun1992** [IrineSistiana/mosdns#676] [General]
问题一：
下面为配置文件，指定www.duckdns.org走本地DNS进行解析，但是实际测试，走了远端DNS进行解析的。
请问是哪里有问题？

---
问题二：
以下按照我的理解是，先到forward_local进行解析，然后使用返回的IP跟./rules/CN-ip-cidr.txt进行取反匹配，如果不在这个范围内的就将这个解析记录丢弃，那如果返回的解析记录IP跟./rules/CN-ip-cidr.txt 匹配了，那是执行什么动作？
```
  - tag: cn_ip
    type: sequence
    args:
      - exec: $forward_local
      - matches: "!resp_ip &./rules/CN-ip-cidr.txt"
        exec: drop_resp
```
---
问题三：
另外帮忙看下配置文件是否有错误的地方，还请指出。谢谢。

---
以下为配置文件：
Custom-local.txt
```
full:www.duckdns.org
```

config.yaml
```
## -- Log Config -- ##
log:
  level: info # ["debug", "info", "warn", and "error"], default is set to "info"

## -- API Config -- ##
api:
  http: "0.0.0.0:18080"

## -- Plugins Config -- ##
plugins:
  ## --- Cache --- ##
  - tag: cache
    type: cache
    args:
      size: 10240
      lazy_cache_ttl: 86400

  ## --- TTL --- ##
  - tag: ttl
    type: sequence
    args:
      - exec: ttl 600-3600

  ## --- Upstream Servers --- ##
  - tag: forward_local
    type: forward
    args:
      concurrent: 2
      upstreams:
        - addr: udp://223.5.5.5
        - addr: https://dns.alidns.com/dns-query
          bootstrap: 223.5.5.5
        - addr: udp://119.29.29.29
        - addr: https://1.12.12.12/dns-query
          bootstrap: 119.29.29.29
  - tag: forward_remote
    type: forward
    args:
      # concurrent: 2
      upstreams:
        # - addr: udp://8.8.8.8
        - addr: udp://172.31.0.253

  ## --- Local Sequence --- ##
  - tag: local_seq
    type: sequence
    args:
      - exec: $forward_local
      # - exec: goto ttl_seq

  ## --- Remote Sequence --- ##
  - tag: remote_seq
    type: sequence
    args:
      - exec: $forward_remote
      # - exec: goto ttl_seq

  ## --- CN-IP Sequence --- ##
  # if response does NOT has CN IP, drop it
  - tag: cn_ip
    type: sequence
    args:
      - exec: $forward_local
      - matches: "!resp_ip &./rules/CN-ip-cidr.txt"
        exec: drop_resp
      # - exec: goto ttl_seq

  ## --- Fallback --- ##
  # (ip split) if response has CN ip, accept it; otherwise, drop --> forward it to remote upstream servers
  - tag: fallback_ip
    type: fallback
    args:
      primary: cn_ip # empty response
      secondary: remote_seq
      threshold: 500 # no response timeout, default value is 500ms
      always_standby: true

  ## --- Main Sequence --- ##
  - tag: main_sequence
    type: sequence
    args:
      - exec: query_summary entry
      # - exec: metrics_controller metrics # prometheus & grafana usage
      - exec: prefer_ipv4 # prefer ipv4 for remote

      # - matches: qtype 12
      #   exec: reject 3
      # - matches: qtype 65
      #   exec: reject 3

      - matches:
          # - qname &./domain/category-ads-all.txt # ads
          - qname &./rules/reject-list.txt
        exec: reject

      - exec: $cache # enable cache
      - matches: has_resp
        exec: accept # end if reponse found in cache

      - matches:
          - qname &./rules/direct-list.txt # cn domains
          - qname &./rules/apple-cn.txt
          - qname &./rules/google-cn.txt
          - qname &./rules/Custom-local.txt # Custom
        exec: goto local_seq

      - matches:
          - qname &./rules/proxy-list.txt
          - qname &./rules/gfw.txt
          - qname &./rules/Custom-remote.txt # Custom
        exec: goto remote_seq

      - exec: $fallback_ip # use ip to split the rest domains

  ## --- Server Configuration --- ##
  - tag: udp_server
    type: udp_server
    args:
      entry: main_sequence
      listen: 0.0.0.0:53

  - tag: tcp_server
    type: tcp_server
    args:
      entry: main_sequence
      listen: 0.0.0.0:53
```

**Comment by luweijun1992** [comment]
请问有人可以帮忙解答下吗，谢谢。
@IrineSistiana

**Comment by luweijun1992** [comment]
有人指导下吗？

**Comment by nil-ca** [comment]
问题三 matches 这么多条件是AND的关系 要同时匹配4个条件合适才会到exec里，你要访问的网站能同时在这4个里面吗。

问题二 等于IP的话应该就直接结束了吧，看了下www.duckdns.org没有国内的IP，前面的matches 条件应该匹配不了，所以进入了fallback，但是fallback-cn_ip返回国外的IP，然后被丢弃了，进到了remote_seq里面。

可以看一下luci-app-mosdns的来改
https://github.com/sbwml/luci-app-mosdns/blob/v5/luci-app-mosdns/root/usr/share/mosdns/default.yaml

**Reply by luweijun1992** [reply]
> 问题三 matches 这么多条件是AND的关系 要同时匹配4个条件合适才会到exec里，你要访问的网站能同时在这4个里面吗。
> 
> 问题二 等于IP的话应该就直接结束了吧，goto好像也不会返回上级sequence执行。

您好，感谢回答。我先看看研究下

**Comment by luweijun1992** [comment]
> 问题三 matches 这么多条件是AND的关系 要同时匹配4个条件合适才会到exec里，你要访问的网站能同时在这4个里面吗。
> 
> 问题二 等于IP的话应该就直接结束了吧，看了下www.duckdns.org没有国内的IP，前面的matches 条件应该匹配不了，所以进入了fallback，但是fallback-cn_ip返回国外的IP，然后被丢弃了，进到了remote_seq里面。
> 
> 可以看一下luci-app-mosdns的来改 https://github.com/sbwml/luci-app-mosdns/blob/v5/luci-app-mosdns/root/usr/share/mosdns/default.yaml

您好，我看了luci-app-mosdns配置。
如果有多个matches，是AND关系，那这个不是也要在4个文件都存在才会被匹配吗？
```
      - matches:
        - "!qname $ddnslist"
        - "!qname $blocklist"
        - "!qname $adlist"
        - "!qname $local_ptr"
```
```
  - tag: main_sequence
    type: sequence
    args:
      - exec: $hosts
      - exec: jump has_resp_sequence
      - matches:
        - "!qname $ddnslist"
        - "!qname $blocklist"
        - "!qname $adlist"
        - "!qname $local_ptr"
        exec: $lazy_cache
      - exec: $redirect
      - exec: jump has_resp_sequence
      - exec: $query_is_ddns_domain
      - exec: jump has_resp_sequence
      - exec: $query_is_whitelist_domain
      - exec: jump has_resp_sequence
      - exec: $query_is_reject_domain
      - exec: jump has_resp_sequence
      - exec: $query_is_greylist_domain
      - exec: jump has_resp_sequence
      - exec: $query_is_local_domain
      - exec: jump has_resp_sequence
      - exec: $query_is_no_local_domain
      - exec: jump has_resp_sequence
      - exec: $fallback
```

**Reply by nil-ca** [reply]
不过他用的是取反，只要不匹配上面的四个条件就行，不匹配比匹配容易，因为你需要匹配的话得四个文本里面都有这个域名。

**Reply by luweijun1992** [reply]
> 不过他用的是取反，只要不匹配上面的四个条件就行，不匹配比匹配容易，因为你需要匹配的话得四个文本里面都有这个域名。

明白了，v5版本配置默认是and关系，那or的关系应该如何写？

**Reply by nil-ca** [reply]
or在V4版本有，V5没有了，只能一条一条加了。

**Reply by Sereinfy** [reply]
准备两个txt
只有一个里面有百度
nslookup.exe baidu.com ok
2个里面有百度
输出Query refused
```
      - matches:
          - qname &/etc/mosdns/rule/baidu1.txt # 黑名单，可添加去广告列表
          - qname &/etc/mosdns/rule/baidu2.txt # 黑名单，可添加去广告列表  
        exec: reject 5
        # 确认是and关系
```
        
 第二种
        
```
      - matches:
          - qname &/etc/mosdns/rule/baidu1.txt &/etc/mosdns/rule/baidu2.txt # 只有一个里面有百度
        exec: reject 5
        输出Query refused
        # 确认是 or 关系
```
目前531版本， @luweijun1992

**Comment by luweijun1992** [comment]
那我的配置是不是修改为如下：
当前：
```
      - matches:
          - qname &./rules/direct-list.txt # cn domains
          - qname &./rules/apple-cn.txt
          - qname &./rules/google-cn.txt
          - qname &./rules/Custom-local.txt # Custom
        exec: goto local_seq
```
修改：
```
      - matches:
          - qname &./rules/direct-list.txt # cn domains
        exec: goto local_seq
      - matches:
          - qname &./rules/apple-cn.txt
        exec: goto local_seq
      - matches:
          - qname &./rules/google-cn.txt
        exec: goto local_seq
      - matches:
          - qname &./rules/Custom-local.txt # Custom
        exec: goto local_seq
```

**Reply by nil-ca** [reply]
对，因为这四个文本需要匹配的域名只在一个文本里面。所以分开判断就好了，嫌太长就再建一个sequence

**Reply by luweijun1992** [reply]
> 对，因为这四个文本需要匹配的域名只在一个文本里面。所以分开判断就好了，嫌太长就再建一个sequence

请问我现在配置修改为如下，是否有问题呢，且有没有不合理的地方？请指导下。

另外在最后main_sequence的地方用jump和goto 两个到底有啥区别，应用场景又是怎么样的。

mosdns如何看某个解析流程到底都经过了哪些处理，这样好判断自己的配置是否满足自己需求。

```
## -- Log Config -- ##
log:
  level: info # ["debug", "info", "warn", and "error"], default is set to "info"

## -- API Config -- ##
api:
  http: "0.0.0.0:18080"

## -- Plugins Config -- ##
plugins:
  ## --- Cache --- ##
  - tag: cache
    type: cache
    args:
      size: 10240
      lazy_cache_ttl: 86400

  ## --- TTL --- ##
  - tag: ttl
    type: sequence
    args:
      - exec: ttl 600-3600

  ## --- has_resp accept --- ##
  - tag: has_resp_sequence
    type: sequence
    args:
      - matches: has_resp
        exec: accept

  ## --- Upstream Servers --- ##
  - tag: forward_local
    type: forward
    args:
      upstreams:
        - addr: udp://adguardhome
          bootstrap: 169.254.0.54
  - tag: forward_remote
    type: forward
    args:
      upstreams:
        - addr: udp://172.31.0.253

  ## --- Local Sequence --- ##
  - tag: local_sequence
    type: sequence
    args:
      - exec: metrics_collector local_sequence
      - exec: $forward_local
      # - exec: goto ttl_seq

  ## --- Remote Sequence --- ##
  - tag: remote_sequence
    type: sequence
    args:
      - exec: metrics_collector remote_sequence
      - exec: $forward_remote
      # - exec: goto ttl_seq

  ## --- CN-IP Sequence --- ##
  # if response does NOT has CN IP, drop it
  - tag: cn_ip
    type: sequence
    args:
      - exec: $local_sequence
      - matches: "!resp_ip &./rules/CN-ip-cidr.txt"
        exec: drop_resp
      # - exec: goto ttl_seq

  ## --- Fallback --- ##
  # (ip split) if response has CN ip, accept it; otherwise, drop --> forward it to remote upstream servers
  - tag: fallback_ip
    type: fallback
    args:
      primary: cn_ip # empty response
      secondary: remote_sequence
      threshold: 500 # no response timeout, default value is 500ms
      always_standby: true

  ## --- Main Sequence --- ##
  - tag: main_sequence
    type: sequence
    args:
      - exec: query_summary entry
      - exec: metrics_collector metrics # prometheus & grafana usage
      - exec: prefer_ipv4 # prefer ipv4 for remote

      # - matches: qtype 12
      #   exec: reject 3
      # - matches: qtype 65
      #   exec: reject 3

      # - exec: $cache # enable cache
      # - matches: has_resp
      #   exec: accept # end if reponse found in cache

      - matches: qname &./rules/Custom-local.txt # Custom-local
        exec: $local_sequence
      - exec: jump has_resp_sequence
      - matches: qname &./rules/Custom-remote.txt # Custom-remote
        exec: $remote_sequence
      - exec: jump has_resp_sequence
      - matches: qname &./rules/reject-list.txt
        exec: reject
      - matches: qname &./rules/direct-list.txt # cn domains
        exec: $local_sequence
      - exec: jump has_resp_sequence
      - matches: qname &./rules/apple-cn.txt
        exec: $local_sequence
      - exec: jump has_resp_sequence
      - matches: qname &./rules/google-cn.txt
        exec: $local_sequence
      - exec: jump has_resp_sequence
      - matches: qname &./rules/proxy-list.txt
        exec: $remote_sequence
      - exec: jump has_resp_sequence
      - matches: qname &./rules/gfw.txt
        exec: $remote_sequence
      - exec: jump has_resp_sequence

      - exec: $fallback_ip # use ip to split the rest domains

  ## --- Server Configuration --- ##
  - tag: udp_server
    type: udp_server
    args:
      entry: main_sequence
      listen: 0.0.0.0:53

  - tag: tcp_server
    type: tcp_server
    args:
      entry: main_sequence
      listen: 0.0.0.0:53
```
