### DISCUSSION TITLE
请示这个matches: client_ip进入子sequence后为什么不能返回继续了？

### DISCUSSION THREAD

**Discussion by PHCSJC** [IrineSistiana/mosdns#678] [Q&A]
匹配client_ip是102后进入102-sequence，再匹配如果域名是666.com则hole，其他域名则return回继续执行，但实际102客户端无法解析任何域名，请问这是哪里的问题呢？

``` 
 - tag: 102-sequence
    type: sequence
    args:
      - matches: qname 666.com
        exec: black_hole 0.0.0.0
      - exec: return

  - tag: main_sequence
    type: sequence
    args:
      - matches: client_ip 192.168.1.102
        exec: goto 102-sequence
.
.
.
```
