### DISCUSSION TITLE
有个疑问请教下各位，没有按预期执行

### DISCUSSION THREAD

**Discussion by LisonFan** [IrineSistiana/mosdns#687] [Q&A]
mosdns 版本
```
/ # mosdns version
v5.1.3
```
我的配置
```
log:
  level: debug
  production: true
  file: "./logs/mosdns.log"

plugins:
  - tag: "fallback_forward_dns"
    type: "forward"
    args:
      concurrent: 3
      upstreams:
        - tag: "google_8888_doh"
          addr: "https://dns.google/dns-query"
          dial_addr: "8.8.8.8"
          socks5: "10.10.10.2:7890"
          idle_timeout: 30
          enable_pipeline: false
          enable_http3: false
          max_conns: 2
          insecure_skip_verify: false
        - tag: "google_8844_doh"
          addr: "https://dns.google/dns-query"
          dial_addr: "8.8.4.4"
          socks5: "10.10.10.2:7890"
          idle_timeout: 30
          enable_pipeline: false
          enable_http3: false
          max_conns: 2
          insecure_skip_verify: false

        - tag: "cloudflare_1111_doh"
          addr: "https://cloudflare-dns.com/dns-query"
          dial_addr: "1.1.1.1"
          socks5: "10.10.10.2:7890"
          idle_timeout: 30
          enable_pipeline: false
          enable_http3: false
          max_conns: 2
          insecure_skip_verify: false
        - tag: "cloudflare_1001_doh"
          addr: "https://cloudflare-dns.com/dns-query"
          dial_addr: "1.0.0.1"
          socks5: "10.10.10.2:7890"
          idle_timeout: 30
          enable_pipeline: false
          enable_http3: false
          max_conns: 2
          insecure_skip_verify: false

  - tag: "default_forward_dns"
    type: "forward"
    args:
      concurrent: 3
      upstreams:
        - tag: "dnspod_master_doh"
          addr: "https://doh.pub/dns-query"
          dial_addr: "1.12.12.12"
          idle_timeout: 30
          enable_pipeline: false
          enable_http3: false
          max_conns: 2
          insecure_skip_verify: false
        - tag: "dnspod_slave_doh"
          addr: "https://doh.pub/dns-query"
          dial_addr: "120.53.53.53"
          idle_timeout: 30
          enable_pipeline: false
          enable_http3: false
          max_conns: 2
          insecure_skip_verify: false

        - tag: "alidns_master_doh"
          addr: "https://dns.alidns.com/dns-query"
          dial_addr: "223.5.5.5"
          idle_timeout: 30
          enable_pipeline: false
          enable_http3: false
          max_conns: 2
          insecure_skip_verify: false
        - tag: "alidns_slave_doh"
          addr: "https://dns.alidns.com/dns-query"
          dial_addr: "223.6.6.6"
          idle_timeout: 30
          enable_pipeline: false
          enable_http3: false
          max_conns: 2
          insecure_skip_verify: false

  - tag: "china_ip_list"
    type: "ip_set"
    args:
      files:
        - "./rules/china-ip.list"

  - tag: "main_sequence"
    type: "sequence"
    args:
      - exec: $default_forward_dns
      - matches: resp_ip $china_ip_list
        exec: accept

      - exec: $fallback_forward_dns

  - tag: "udp_server"
    type: "udp_server"
    args:
      entry: main_sequence
      listen: :5353
```

[./rules/china-ip.list](https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/cn.txt)

按照我的理解，命中了`default_forward_dns`就不会执行`fallback_forward_dns`了，但是情况并没有按照我的理解发展
这是其中一段日志
```
{"level":"info","ts":1685611484.704614,"logger":"main_sequence.r0","msg":"\"default forward dns\"","query":";; opcode: QUERY, status: NOERROR, id: 40317\n;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1\n\n;; OPT PSEUDOSECTION:\n; EDNS: version 0; flags:; udp: 4096\n\n;; QUESTION SECTION:\n;www.json.cn.\tIN\t AAAA\n"}
{"level":"info","ts":1685611484.7049072,"logger":"main_sequence.r0","msg":"\"default forward dns\"","query":";; opcode: QUERY, status: NOERROR, id: 10810\n;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1\n\n;; OPT PSEUDOSECTION:\n; EDNS: version 0; flags:; udp: 4096\n\n;; QUESTION SECTION:\n;www.json.cn.\tIN\t A\n"}
{"level":"info","ts":1685611484.7251458,"logger":"main_sequence.r3","msg":"\"fallback forward dns\"","query":";; opcode: QUERY, status: NOERROR, id: 40317\n;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1\n\n;; OPT PSEUDOSECTION:\n; EDNS: version 0; flags:; udp: 4096\n\n;; QUESTION SECTION:\n;www.json.cn.\tIN\t AAAA\n"}
{"level":"info","ts":1685611484.7252243,"logger":"main_sequence.r3","msg":"\"fallback forward dns\"","response":";; opcode: QUERY, status: NOERROR, id: 40317\n;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 1, ADDITIONAL: 1\n\n;; OPT PSEUDOSECTION:\n; EDNS: version 0; flags:; udp: 4096\n\n;; QUESTION SECTION:\n;www.json.cn.\tIN\t AAAA\n\n;; ANSWER SECTION:\nwww.json.cn.\t1\tIN\tCNAME\twww.json.cn.cname.yunjiasu-cdn.net.\n\n;; AUTHORITY SECTION:\nyunjiasu-cdn.net.\t1\tIN\tSOA\tns1.yjs-cdn.com. dns.yjs-cdn.com. 1470920182 1800 900 604800 300\n"}
````
解析`www.json.cn`的时候，`fallback_forward_dns`还执行了
这是为啥呢？
