### DISCUSSION TITLE
分享自用的 V5 的配置，带有 IP 优选

### DISCUSSION THREAD

**Discussion by Journalist-HK** [IrineSistiana/mosdns#697] [Ideas]
仓库地址：https://github.com/Journalist-HK/mosdns-config

基本都有注释，等有空再完善一下。这个 V5 版本有一个不太友好的地方，`match` 后面的 `exec` 只有一条，如果要运行两条命令，得新建一个 sequence。

```yaml
  - match:
      - qname google.com
    exec: prefer_ipv4
  - exec: $forward
```
这样写会出问题，希望 `exec` 能支持嵌套。
