### DISCUSSION TITLE
请问怎么使用特定的dns解析netflix呢？

### DISCUSSION THREAD

**Discussion by h40st3r** [IrineSistiana/mosdns#710] [Q&A]
想看netflix的非自制剧，需要特定的一台dns服务器来解析netflix.com，请问在v5里可以设置吗？

**Comment by sieveLau** [comment]
用qname就可以了呀，比如你想用8.8.8.8解析netflix.com：

```yaml
plugins:
 - tag: "main_sequence"
   type: "sequence"
   args:
        - matches: qname netflix.com
          exec: forward 8.8.8.8
```
