### DISCUSSION TITLE
`if` 和 `if_and` 在配置文件中可以联用么？

### DISCUSSION THREAD

**Discussion by IceCodeNew** [IrineSistiana/mosdns#72] [Q&A] [answered]
如题，举例来说有下面一个配置：
```
        - forward_ali_and_tx
        - if:
            - response_has_local_cdn
            - response_has_local_ip
          if_and:
            - _response_rcode_success
          goto: _end
```

假设这里阿里和腾讯服务器维护一个黑名单，对上面的域名不污染，只是返回 NX_DOMAIN 错误（这里假设只是为了契合实际请求的 DNS 服务器情况，毕竟举例的配置不是真实使用的配置）。
我希望实现的效果是无视这个上游服务器返回的 RCODE 不为0 的响应，然后仅当响应内容为国内的域名/IP 时，结束整个处理流程。
所以我期待的匹配逻辑是 `(local_cdn || local_ip) && rcode_success`，但实在不知道怎么才能确认 mosdns 实际是不是按照这个逻辑处理的，就来问问。

**Comment by IceCodeNew** [comment]
这里的需要我认真考虑过，原本是打算直接用 `trusted: false` 实现的。
但是仔细读 Wiki，发现介绍说的是：“trusted 可信服务器，用于过滤 Rcode != 0 的应答。**仅配置了多个服务器时生效。**”
我的猜测是：在配置了多个服务器时，至少需要设置一台服务器为可信服务器，不能全部设为不可信服务器。
所以才没办法选择现在的思路解决。

**Comment by IrineSistiana** [comment, marked as answer]
如果你仔细看 if 那块的注释.....
（`if` || `if_and`）

**Reply by IceCodeNew** [reply]
想了好久都没有想到替代的办法，不知道可否考虑在执行序列里也引入 `logical_and: true` 这个选项

**Reply by IrineSistiana** [reply]
逻辑与可以用
```
if case1 
exec 
   if case2
   exec
```
 嵌套实现。

**Reply by IceCodeNew** [reply]
```
if case1 
exec
    if case2
```
这里的 exec 可以为空么……

**Reply by IrineSistiana** [reply]
if里的exec 也是个执行序列，里面可以接着放 if，可以接着 exec。可以无限嵌套。
```
if:
  - case1 
exec:
    - if:
      - case2
      exec:
      - dosomething
```
~~老年人手机敲符号不易~~
