### DISCUSSION TITLE
分享下升级 V5 后简单的分流配置

### DISCUSSION THREAD

**Discussion by 5uy4n9** [IrineSistiana/mosdns#724] [Show and tell]
大致流程：
1. 先查缓存，有结束，没有继续
2. 域名是国内域名就走国内 DNS 查询，不是就继续
3. 走国外 DNS 查询，IP 是国内段就重新用国内 DNS 查询

国内外 DNS 都只设了一个，国外用的自建的 DoH 地址我就隐藏了，可以改成你自己的或者走代理的公共 DNS，其他有需要可以自己添加
根据注释的链接定期更新国内域名列表和国内 IP 段就行
开了本地的 DoH server，不需要的可以注释掉

``` yaml
log:                                                                                                                                                                                                                                                                                                                             
  level: info
  production: true
  file: "/var/log/mosdns.log"

api:
  http: "127.0.0.1:5353"

plugins:
# https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/direct-list.txt
    - tag: cn_domainList
      type: "domain_set"
      args:
        files:
          - "./direct-list.txt"

# https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/cn.txt
    - tag: cn_ipList
      type: "ip_set"
      args:
        files:
          - "./cn.txt"

    - tag: free_DNS
      type: "forward"
      args:
        upstreams:
            - tag: selfhost_doh
              addr: "https://****************/dns-query"
              dial_addr: "*********"
              enable_http3: true
              insecure_skip_verify: false

    - tag: cn_DNS
      type: "forward"
      args:
        upstreams:
          - tag: dnspod_doh
            addr: "tls://dot.pub"
            dial_addr: "1.12.12.12"
            enable_pipeline: true
            insecure_skip_verify: false
    
   - tag: local_cache
      type: "cache"
      args:
        size: 10240
        lazy_cache_ttl: 18000
        dump_file: "./cache.dump"
        dump_interval: 600

# resolve process
    - tag: cache_resolve
      type: "sequence"
      args:
        - exec: $local_cache
#        - matches:
#            - has_resp
#          exec: query_summary cache
        - matches:
            - has_resp
          exec: accept

    - tag: cn_resolve
      type: "sequence"
      args:
        - exec: $cn_DNS
        - exec: query_summary cn_DNS

    - tag: resolve_process
      type: "sequence"
      args:
        - exec: prefer_ipv4

        - exec: jump cache_resolve

        - matches:
          - "qname $cn_domainList"
          exec: goto cn_resolve

        - exec: $free_DNS
        - exec: query_summary free_DNS

        - matches:
          - "resp_ip $cn_ipList"
          exec: goto cn_resolve

# server
    - tag: udp_server
      type: "udp_server"
      args:
        entry: resolve_process
        listen: "127.0.0.1:53"

    - tag: doh_server
      type: "http_server"
      args:
        entries:
          - path: "/dns-query"
            exec: resolve_process
        src_ip_header: "X-Forwarded-For"
        cert: ""
        key: ""
        idle_timeout: 10
        listen: "127.0.0.1:553"
```
