### DISCUSSION TITLE
v5 是否能支持 ASN 之类的 dat 数据用以分流

### DISCUSSION THREAD

**Discussion by QuentinHsu** [IrineSistiana/mosdns#729] [General]
形如链接所示的数据源，https://github.com/Loyalsoldier/geoip
一个 ASN 数据源，（貌似）就搞定了 IP 和 域名了

不过，不知道这个在底层是否会像正则匹配那样造成更多资源消耗😂，主要是在 iOS 代理软件上有用到该类数据。）

我在 #393 中发现配置中有，但感觉是早期版本的配置，因为没有 `type` 

```yml
- tag: geoip-asn
   file: /etc/mosdns/geoip-asn.dat
   auto_reload: true
```
