### DISCUSSION TITLE
如何在流程里获取源IP

### DISCUSSION THREAD

**Discussion by BingMeng** [IrineSistiana/mosdns#736] [General]
例如 sequence 里，想实现
if source_ip = x.x.x.x 
exec: exec_something

**Comment by sbwml** [comment]
yaml:
```yaml
- tag: ""
  type: "sequence"
  args:
    - matches: "client_ip 192.168.1.1"
      exec: exec_something
```

json:
```json
[
    {
        "tag": "",
        "type": "sequence",
        "args": [
            {
                "matches": "client_ip 192.168.1.1",
                "exec": "exec_something"
            }
        ]
    }
]
```
