### DISCUSSION TITLE
关于 cache/hosts 插件和 sequence 插件的匹配器 has_wanted_ans

### DISCUSSION THREAD

**Discussion by cherinyy** [IrineSistiana/mosdns#755] [Q&A]
mosdns v5.2.1 配置参考：

```
...
plugins:

  - tag: cache
    type: cache
    args:
      size: 8192
      dump_file: ./cache.dump

  - tag: main
    type: sequence
    args:
      - exec: $cache
      - matches:
          - has_wanted_ans
        exec: accept
...
```

~~我这么设置，似乎 cache 插件不会生效，它只能配合 has_resp 匹配器使用吗？~~

正常生效，问题出现在别处。
