### DISCUSSION TITLE
域名转跳功能

### DISCUSSION THREAD

**Discussion by monochrome-yeh** [IrineSistiana/mosdns#760] [Q&A]
想请问先进们，请问插件有可以实现如
xboxlive.com
硬改成请求
xboxlive.cn

这样的功能吗？

**Comment by cherinyy** [comment]
这个需求应该不会有人去实现，因为首先这不属于传统 DNS 软件的职能，它应该属于防火墙（拦截连接）。

然后如果需要实现这个功能，首先 DNS 应该返回一个由你所控制的 IP 地址，而在那个地址上需要有个同端口的 HTTP(S) 服务器，然后这个 HTTP(S) 服务器再返回 HTTP 302 状态及目标地址到客户端。

而这里面最大的问题就在于，如果是 HTTPS 链接，则需要一个可信的数字证书。你自然不可能拥有“xboxlive.com”合法的数字证书，你只能自签名，然后在客户端中手动信任。整个流程下来，如果要在多端实现自动化流程，无疑是非常繁琐的工作，没有人会这么做。

因此通常这类操作都是有专门的，在本地运行的软件负责（比如防火墙）。
而你的这个仅仅是简单的跳转需求，又太过于小众，我不确定市面上是否真的有这一类软件。

我所知道的，最符合你需求的软件，应该是羽翼城的 [steamcommunity 302](https://www.dogfight360.com/blog/686/)。

**Comment by qingtian110** [comment]
“域名转跳功能”   访问 xboxlive.com 自动跳转到 xboxlive.cn ，这种可以使用 mosdns 自带插件 `arbitrary` 自定义应答 CNAME 记录值到 xboxlive.cn，但是只适合需要跳转的域名不多的情况下使用，因为维护不便捷。


只是举例：

```yaml
...
  - tag: "cname"
    type: "arbitrary"
    args:
      rules:
        - xboxlive.com. 5m0s CNAME xboxlive.cn.
...
  - tag: query_is_xboxlive
    type: sequence
    args:
      - matches: qname xboxlive.com
        exec: $cname
...
```

当然，你可以将这一切做成数据库形式实现批量管理，至于怎么玩，靠自己的感觉，反正你这个需求 `arbitrary` 插件完全可以实现到跳转。
