### DISCUSSION TITLE
Sequence 插件内建操作 `ecs` 和 `ecs_handler` 插件的差异

### DISCUSSION THREAD

**Discussion by cherinyy** [IrineSistiana/mosdns#762] [Q&A]
我的理解是：

```
plugins:
  - tag: ecs_handler
    type: ecs_handler
    args:
      send: true

  - tag: main
    type: sequence
    args:
      - exec: $ecs_handler
      - exec: forward 8.8.8.8
```

---

```
plugins:
  - tag: main
    type: sequence
    args:
      - exec: ecs
      - exec: forward 8.8.8.8
```

这两者应该是等效的，然而 Google Public DNS 却拒绝了前者的 DNS 请求 ( https://github.com/IrineSistiana/mosdns/issues/621 )。

是我的理解有误吗，还是说存在 BUG？我是在 [ImmortalWrt](https://github.com/immortalwrt/immortalwrt) 上运行 mosdns 的。

执行 `dig o-o.myaddr.google.com TXT` 时遇到了该问题。
