### DISCUSSION TITLE
借助Fallback能否实现既查询缓存又不会让上游查询结果写入缓存？

### DISCUSSION THREAD

**Discussion by Sakyoriii** [IrineSistiana/mosdns#767] [Q&A]
我当前的网络中mosdns的海外上游是clash的fake ip（有编写静态路由不会出现问题），所以不希望缓存查询结果，但又希望在向上游发起查询之前先在缓存中匹配是否又结果。

根据wiki中对fallback的描述： 

> fallback 是多线程。primary 和 secondary 是独立的线程，它们收到的请求是 fallback 收到的请求的镜像。任何一方对请求做出修改不会影响对方，也不会影响 fallback 所在的。

是否可以理解为在primary中使用exec:$cache并不会导致secondary中的结果被缓存？
根据这个结论我写了一下fallback：
```
  - tag: fallback_cache
    type: sequence
    args: 
      - exec: $mem_cache
      
  - tag: fallback_query
    type: fallback
    args:
      primary: fallback_local # 大陆上游查询
      secondary: fallback_remote # 海外上游查询（clash Fake ip）
      threshold: 500 
      always_standby: true 

  - tag: fallback_task
    type: fallback
    args:
      primary: fallback_cache #cache中查询
      secondary: fallback_query # 向上游查询
      threshold: 500 
      always_standby: true
```
暂时只经过短时间使用测试并没有出现问题，
请问这样能否实现预期，有没有我没注意到的问题？
