### DISCUSSION TITLE
分享一个纯域名分流的v5配置

### DISCUSSION THREAD

**Discussion by junx964** [IrineSistiana/mosdns#789] [Ideas]
config.yaml
```
log:
    level: info
    production: false
    file: "/path/to/mosdns.log"

plugins:
  # 缓存
  - tag: cache
    type: cache
    args:
      size: 10240
      lazy_cache_ttl: 86400

  # 重定向域名
  - tag: redirect
    type: redirect
    args:
      rules:
        - cloudflare.top www.cloudflare.top

  # 自定义hosts
  - tag: hosts
    type: hosts
    args:
      files:
        - "/path/to/hosts"    # 此hosts和/etc/hosts不通，这里有说明：https://irine-sistiana.gitbook.io/mosdns-wiki/mosdns-v5/ru-he-pei-zhi-mosdns/ke-zhi-hang-cha-jian#hosts

  # 转发至国内DNS，并发查询
  - tag: forward_local
    type: forward
    args:
      concurrent: 3
      upstreams:
        # DNS 派
        - addr: "udp://101.226.4.6"
        - addr: "udp://218.30.118.6"
        - addr: "udp://123.125.81.6"
        - addr: "udp://140.207.198.6"

  # 转发至国外DNS，并发查询
  - tag: forward_remote
    type: forward
    args:
      concurrent: 2
      upstreams:
        - tag: google_tls
          addr: "tls://8.8.8.8"
          dial_addr: "8.8.8.8"
          bootstrap: "8.8.8.8"
          bootstrap_version: 4
          socks5: "127.0.0.1:1081"    # socks5代理， 有其他代理方式或者不需要代理，请删除此行
          idle_timeout: 30
          enable_pipeline: true
          enable_http3: true
          insecure_skip_verify: false
        - tag: cloudflare_tls
          addr: "tls://1.1.1.1"
          dial_addr: "1.1.1.1"
          bootstrap: "1.1.1.1"
          bootstrap_version: 4
          socks5: "127.0.0.1:1081"    # socks5代理， 有其他代理方式或者不需要代理，请删除此行
          idle_timeout: 30
          enable_pipeline: true
          enable_http3: true
          insecure_skip_verify: false

  # primary fallback
  - tag: primary_fallback
    type: forward
    args:
      concurrent: 2
      upstreams:
        - tag: dns.sb_tls
          addr: "tls://185.222.222.222"
          dial_addr: "185.222.222.222"
          bootstrap: "185.222.222.222"
          bootstrap_version: 4
          socks5: "127.0.0.1:1081"    # socks5代理， 有其他代理方式或者不需要代理，请删除此行
          idle_timeout: 30
          enable_pipeline: true
          enable_http3: true
          insecure_skip_verify: false
        - tag: ibm_quad9_tls
          addr: "tls://dns10.quad9.net"
          dial_addr: "2620:fe::fe:10"
          bootstrap: "2620:fe::fe:10"
          bootstrap_version: 4
          socks5: "127.0.0.1:1081"    # socks5代理， 有其他代理方式或者不需要代理，请删除此行
          idle_timeout: 30
          enable_pipeline: true
          enable_http3: true
          insecure_skip_verify: false

  # secondary fallback
  - tag: secondary_fallback
    type: forward
    args:
      concurrent: 3
      upstreams:
        # 阿里公共DNS
        - addr: "udp://223.5.5.5"
        - addr: "udp://2400:3200::1"
        # 腾讯公共DNS(DNSPod)
        - addr: "udp://119.29.29.29"
        - addr: "udp://2402:4e00::"
        # 百度公共DNS
        - addr: "udp://180.76.76.76"
        - addr: "udp://2400:da00::6666"

  # primary fallback sequence
  - tag: primary_fallback_sequence
    type: sequence
    args:
      - exec: $primary_fallback
      - matches: has_resp
        exec: accept

  # secondary fallback sequence
  - tag: secondary_fallback_sequence
    type: sequence
    args:
      - exec: $secondary_fallback
      - matches: has_resp
        exec: accept

  # fallback sequence， 99%用不到， 上边指定的上游server太多了
  - tag: fallback
    type: fallback
    args:
      primary: primary_fallback_sequence
      secondary: secondary_fallback_sequence
      threshold: 500
      always_standby: true

  # main
  - tag: main_sequence
    type: sequence
    args:
      - exec: $hosts
      - matches: has_resp
        exec: accept
      
      - matches: qtype 65
        exec: reject 3

      # https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/reject-list.txt
      - matches: qname &/path/to/reject-list.txt    # 请指向广告域名列表文件
        exec: reject

      # 没有ipv6需要完全禁用ipv6解析的，官方解释：https://irine-sistiana.gitbook.io/mosdns-wiki/mosdns-v5/ru-he-pei-zhi-mosdns/sequence-cha-jian#prefer_ipv4-6
      # - exec: prefer_ipv4

      - exec: $redirect

      # https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/direct-list.txt
      # https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/apple-cn.txt
      # https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/google-cn.txt
      - matches: qname &/path/to/direct-list.txt &/path/to/apple-cn.txt &/path/to/google-cn.txt    # 请指向直连解析的列表
        exec: $forward_local
      - matches: has_resp
        exec: accept

      # 只要不是直连的都会进入代理， 进入国外dns服务器
      - exec: $forward_remote
      - matches: has_resp
        exec: accept

      - exec: $fallback

  # 启动监听服务
  - tag: udp_server
    type: udp_server
    args:
      entry: main_sequence
      listen: :53

  - tag: tcp_server
    type: tcp_server
    args:
      entry: main_sequence
      listen: :53
```
