### DISCUSSION TITLE
嵌套sequence行为不统一

### DISCUSSION THREAD

**Discussion by brainiac19** [IrineSistiana/mosdns#791] [Q&A]
这个配置不会reject

```
- tag: reject_sequence
    type: sequence
    args:
      - exec: reject

- tag: main_sequence
    type: sequence
    args:
      - exec: jump reject_sequence
```

这个配置正常reject
```
- tag: main_sequence
    type: sequence
    args:
      - exec: reject
```

把reject换成accept，就没这个情况？
