### DISCUSSION TITLE
prefer_ipv4/v6 作用位置是否应该后移

### DISCUSSION THREAD

**Discussion by ljcbaby** [IrineSistiana/mosdns#795] [Ideas]
```zone
sub.a.com.    600    IN      CNAME   sub.b.com.
sub.b.com.    600    IN      A        46.17.42.153
sub.b.com.    600    IN      AAAA    2a00:b700::8:e2
```

对于以上的区域文件，使用如下配置文件（关键片段）运行mosdns，其中 `domain:b.com`存在`duallist`中。

```yaml
  - tag: local_sequence
    type: sequence
    args:
      - exec: $cache
      - exec: jump has_resp_sequence
      - matches: "!qname $duallist"
        exec:  prefer_ipv4
      - exec: $forward_local
```

此时`sub.b.com`已经能够解析双栈，但是`sub.a.com`仍然会被 prefer_ipv4 影响，无法解析双栈。
