### DISCUSSION TITLE
wiki 示例配置改进

### DISCUSSION THREAD

**Discussion by qinghon** [IrineSistiana/mosdns#806] [Ideas]
目前的wiki 示例配置只有两个，两个配置之间差距较大，缺乏一些关键提示，比如变量，顺序规则
在越过了这两个配置后在后续定制时，`sequence` 部分配置示例不完整，需要来回查看配置，难度曲线不平缓

建议修改 `多功能转发器` 部分配置为：

```yaml

log:
  level: info

plugins:
  - tag: forward_google # 先定义一个转发器
    type: forward
    args:
      upstreams:
      - addr: https://8.8.8.8/dns-query
        socks5: "127.0.0.1:7890" # 使用socks5 代理

  - tag: main
    type: sequence
    args:
    - matches:             # 如果
      - qname &./oisd_dbl_basic.txt # 如果请求的域名在广告列表内。
      exec: reject 3       # 执行 直接返回 NXDOMAIN(3) 屏蔽。
    - exec: cache 1024     # 然后。查找 cache。
    - matches:             # 如果
      - has_resp         # 有应答了(上一步 cache 找到应答)
      exec: accept         # 结束。

    # 上一步没有找到缓存，就会到这一步，使用转发器转发至 Google 获取应答。
    - exec: $forward_google
    # sequence 结束(被 reject，accept，或者运行到末尾)后就会返回调用者。在这个配置文件中
    # 调用者是下面的服务器。服务器就会返回应答至客户端。


  # 启动 udp 和 tcp 服务器。
  - type: udp_server
    args:
      entry: main # 收到的请求会执行上面的逻辑
      listen: 127.0.0.1:5533
  - type: tcp_server
    args:
      entry: main
      listen: 127.0.0.1:5533

```

没找到wiki 仓库，只好发在这里了
