### DISCUSSION TITLE
domain_set插件同时定义exps和files，是取交集还是取并集？

### DISCUSSION THREAD

**Discussion by Benjamin1919** [IrineSistiana/mosdns#811] [Q&A]
示例：
```
  - tag: DIRECT
    type: domain_set
    args:
      exps:
        - "gspe1-ssl.ls.apple.com"
      files:
        - "/usr/local/mosdns/geosite_apple@cn.txt"
        - "/usr/local/mosdns/geosite_microsoft@cn.txt"
```
       
请问最终的域名是上述几个条件的交集还是并集？
