### DISCUSSION TITLE
分享一个openwrt x86 fakeip网关/分流的全套方案，带ipt/nft规则，带mosdns全套配置，sing-box支持订阅，带ios回家配置，自用很久了。

### DISCUSSION THREAD

**Discussion by yyysuo** [IrineSistiana/mosdns#837] [Show and tell]
解压不了的，请用7zip

最新全套：https://drive.google.com/drive/folders/1ldD2XqIrREPgr_CKMSgvYomXgwknpApi?usp=sharing
一些进阶的用法

[mosdns-ph-20251104全新单独部署版本.zip](https://github.com/user-attachments/files/23322095/mosdns-ph-20251104.zip)

1：ipt/nft只劫持fakeip段，没有ipset变大缓慢的问题。
2：bt/pt的ip连接天然直连。
3：对未知域名有自行判断分流的能力。

需要的东西全在附件中，自取。

旧教程：[x86 openwrt配置sing-box透明代理 nft ipt fakeip网关模式 20250401.zip](https://github.com/user-attachments/files/19543941/x86.openwrt.sing-box.nft.ipt.fakeip.20250401.zip)

**Comment by uioprr** [comment]
来自D版带着爱

**Comment by llity** [comment]
谢谢分享，用着可以，我主要用mosdns分流国外转发给 sing-box，我把forward_fakeip的IP修改了。还有下面代码主要作用是什么，我用的docker安装mosdns，是否不需要下面的处理，谢谢


```
####################对外服务端口定义部分############
#解析节点域名的服务器
  - tag: sbnode_udp
    type: udp_server
    args:
      entry: sequence_sbnode
      listen: ":7777"

  - tag: sbnode_tcp
    type: tcp_server
    args:
      entry: sequence_sbnode
      listen: ":7777"

#sing-box使用的服务器
  - tag: sb_udp
    type: udp_server
    args:
      entry: sequence_sb
      listen: ":8888"

  - tag: sb_tcp
    type: tcp_server
    args:
      entry: sequence_sb
      listen: ":8888"
```

**Comment by yyysuo** [comment]
> 谢谢分享，用着可以，我主要用mosdns分流国外转发给 sing-box，我把forward_fakeip的IP修改了。还有下面代码主要作用是什么，我用的docker安装mosdns，是否不需要下面的处理，谢谢
> 
> 
> 
> 
> 
> ```
> 
> ####################对外服务端口定义部分############
> 
> #解析节点域名的服务器
> 
>   - tag: sbnode_udp
> 
>     type: udp_server
> 
>     args:
> 
>       entry: sequence_sbnode
> 
>       listen: ":7777"
> 
> 
> 
>   - tag: sbnode_tcp
> 
>     type: tcp_server
> 
>     args:
> 
>       entry: sequence_sbnode
> 
>       listen: ":7777"
> 
> 
> 
> #sing-box使用的服务器
> 
>   - tag: sb_udp
> 
>     type: udp_server
> 
>     args:
> 
>       entry: sequence_sb
> 
>       listen: ":8888"
> 
> 
> 
>   - tag: sb_tcp
> 
>     type: tcp_server
> 
>     args:
> 
>       entry: sequence_sb
> 
>       listen: ":8888"
> 
> ```

是的 不需要 如果用我发的sb配置 就需要了 。

**Reply by llity** [reply]
发现一个问题，请教怎么修改配置文件，解决对列表外的国外域名无法返回正确的DNS查询结果的问题。谢谢
（1）比如下面我用的docker是否 socks5: "127.0.0.1:7890" 应该删除。
```
  # 转发到Google DNS的设置
  - tag: forward_google
    type: forward
    args:
      concurrent: 1
      upstreams:
        - addr: "https://8.8.8.8/dns-query"
          socks5: "127.0.0.1:7890"  # 使用本地socks5代理
```
（2）- exec: drop_resp 删除后才能正常返回一些列表外的域名DNS查询。
```
  # 列表外域名的处理逻辑
  - tag: sequence_not_in_list
    type: sequence
    args:
      # - exec: drop_resp  # 丢弃不必要的IP响应
      - exec: $sequence_google
```

访问 appstorrent.ru 部分错误信息，172.16.1.2是adguard home服务的IP，为路由器DNS。

```
forward_google	upstream error	{"uqid": 8089, "qname": "appstorrent.ru.", "qclass": 1, "qtype": 1, "upstream": "https://8.8.8.8/dns-query", "error": "http request failed: socks connect tcp 127.0.0.1:7891->8.8.8.8:443: dial tcp 127.0.0.1:7891: connect: connection refused"}

2024-09-07T07:30:26.696Z	WARN	udp_main	entry err	{"query": {"uqid": 224, "client": "::ffff:172.16.1.2", "qname": "appstorrent.ru.", "qtype": 1, "qclass": 1, "elapsed": "5.000129404s"}, "error": "context deadline exceeded"}
```
