### DISCUSSION TITLE
一个"domain_set"插件下，可以同时挂载两个txt文件吗？一个自动更新，一个是我手动添加的避免被更新覆盖。

### DISCUSSION THREAD

**Discussion by yeezylife** [IrineSistiana/mosdns#839] [Q&A]
```
  - tag: "direct_domain"
    type: domain_set
    args:
      files:
        - "./direct-list.txt"
        - "./direct-list-custom.txt"
```

我在配置文件里这样写的，但是direct-list-custom.txt里添加的域名，还是没有走直连，这是没成功读取两个文件吗
