### DISCUSSION TITLE
请教 doh ecs 问题

### DISCUSSION THREAD

**Discussion by dansean** [IrineSistiana/mosdns#840] [Q&A]
我看wiki配置了个简单的转发器，想添加ecs` 的支持：请求中有ecs 就根据请求的ecs地址，没有则按 X-Forwarded-For 的直至请求。
但是配完发现没什么变化。
以下是我的配置：

```
log:
  level: debug
plugins:
  - tag: dns_primary
    type: forward
    args:
      concurrent: 2
      upstreams:
        - addr: "https://cloudflare-dns.com/dns-query"
          dial_addr: "1.1.1.1"
          enable_http3: true
        - addr: "https://dns.google/dns-query"
          dial_addr: "8.8.8.8"
          enable_http3: true
  - tag: dns_secondary
    type: forward
    args:
      concurrent: 2
      upstreams:
        - addr: "tls://one.one.one.one"
          dial_addr: "1.0.0.1"
          enable_pipeline: true
        - addr: "tls://dns.google"
          dial_addr: "8.8.4.4"
          enable_pipeline: true
  - tag: ecs_add
    type: ecs_handler
    args:
      forward: true
      preset: ""  
      send: true 
      mask4: 24
      mask6: 48 
  - tag: dns_query
    type: fallback
    args:
      primary: dns_primary
      secondary: dns_secondary
      threshold: 200
      always_standby: true
  - tag: has_reports
    type: sequence
    args:
      - matches: has_resp
        exec: accept
  - tag: man_sequence
    type: sequence
    args:
      - exec: $ecs_add
      - exec: $dns_query
      - exec: jump has_reports
      - exec: return
  - tag: doh_server
    type: http_server
    args:
      entries:
        - path: /dns-query
          exec: man_sequence
      src_ip_header: "X-Forwarded-For"
      listen: :8053
      idle_timeout: 10
```

有没有大佬指正下，如何将src_ip_header 传递给 ecs_handler 的 send ?
