### DISCUSSION TITLE
分享mosdns V5 FakeIP 分流方案

### DISCUSSION THREAD

**Discussion by chenbin3625** [IrineSistiana/mosdns#844] [Ideas]
打包产物：
[dns.zip](https://github.com/user-attachments/files/17106443/dns.zip)

核心思路：
Mosdns：负责 DNS 分流查询，国内转发ISP+阿里 国外通过sock5代理转发cf+google（国内国外均有2*2组dns并行查询）
AdGuard Home(ADG)：负责 DNS 去广告+控制面板（不需要可以去除，仅使用mosdns也可以）
可用来代替paopaodns分流 配合paopaogateway或者singbox等fakeip网关实现分流科学上网

DNS泄漏：
"所谓的DNS泄露国内节点，只是在IP分流时，查询了国内DNS引起，仅在理论上有安全问题。当然这个DoH使用境外服务器进行IP分流，完美解决泄漏问题 [[DNS分流与泄露分析 31](https://apad.pro/dns-leak/)] 

DNS检测：
境内检测：[https://nstool.netease.com 123](https://nstool.netease.com/)
境外检测：[DNS Leak Test - BrowserLeaks 99](https://browserleaks.com/dns)
[DNS泄露检测](https://ipleak.net/)
这个可以查询DNS泄露情况 理想状态打开都是实际代理区域的DNS

效果：
adg配置去广告和去pcdn黑名单
adg不开启缓存（fakeip需要TTL尽量短），如有需要在mosdns的localdns中设置
0缓存实现dns查询10s，所有网站秒开
![image](https://github.com/user-attachments/assets/0095ac22-72ad-478a-9aab-da65c25977ef)

![image](https://github.com/user-attachments/assets/3e8df003-2a99-4526-92bc-eeec8f85f2d6)

配置文件
下载分流所需文件
使用以下脚本，修改变量 v2dat_dir 为你的保存路径 (保存为 .sh 文件后, 记得 chmod +x xxx.sh 赋权)：

```

#!/bin/sh

set -e  # Exit if any command fails

TMPDIR=$(mktemp -d)
trap 'rm -rf "$TMPDIR"' EXIT  # Ensure temporary directory is removed on script exit

v2dat_dir=<自定义路径>/mosdns

geodat_update() {
    curl --connect-timeout 5 -m 60 -kfSL -o "$TMPDIR/geoip.dat" "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/geoip-only-cn-private.dat"
    
    curl --connect-timeout 5 -m 60 -kfSL -o "$TMPDIR/geosite.dat" "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat"

    \cp -a "$TMPDIR"/geoip.dat "$TMPDIR"/geosite.dat $v2dat_dir
}

# Unpack and process the data
v2dat_dump() {
    mkdir -p "$v2dat_dir/rules/"

    curl -fSL -o "$v2dat_dir/v2dat" "https://raw.githubusercontent.com/xukecheng/scripts/main/v2dat"
    chmod +x "$v2dat_dir/v2dat"

    rm -f "$v2dat_dir/rules/geo"*.txt
    "$v2dat_dir/v2dat" unpack geoip -o "$v2dat_dir/rules/" -f cn "$v2dat_dir/geoip.dat"
    "$v2dat_dir/v2dat" unpack geosite -o "$v2dat_dir/rules/" -f apple -f cn -f 'geolocation-!cn' "$v2dat_dir/geosite.dat"

    rm -rf "$v2dat_dir/v2dat"
}

update_local_ptr() {
    curl --connect-timeout 5 -m 60 -kfSL -o "$v2dat_dir/rules/local-ptr.txt" "https://raw.githubusercontent.com/sbwml/luci-app-mosdns/v5/luci-app-mosdns/root/etc/mosdns/rule/local-ptr.txt"
}

geodat_update
v2dat_dump
update_local_ptr

touch $v2dat_dir/rules/force-nocn.txt
touch $v2dat_dir/rules/force-cn.txt
# force-cn 是强制本地解析域名，force-nocn 是强制非本地解析域名

echo "localhost 127.0.0.1" >> $v2dat_dir/rules/hosts.txt
```

说明（hosts可以自定义域名解析，force-cn.txt为强制转发国内dns，force-nocn.txt为强制转发国外DNS，请自行修改，格式为mosdns标准格式）

```
chmod +x xxx.sh
./xxx.sh

# 检查文件
tree -f <变量 v2dat_dir 定义的路径>

<变量 v2dat_dir 定义的路径>
├── <变量 v2dat_dir 定义的路径>/geoip.dat
├── <变量 v2dat_dir 定义的路径>/geosite.dat
└── <变量 v2dat_dir 定义的路径>/rules
    ├── <变量 v2dat_dir 定义的路径>/rules/force-cn.txt
    ├── <变量 v2dat_dir 定义的路径>/rules/force-nocn.txt
    ├── <变量 v2dat_dir 定义的路径>/rules/geoip_cn.txt
    ├── <变量 v2dat_dir 定义的路径>/rules/geosite_apple.txt
    ├── <变量 v2dat_dir 定义的路径>/rules/geosite_cn.txt
    ├── <变量 v2dat_dir 定义的路径>/rules/geosite_geolocation-!cn.txt
    ├── <变量 v2dat_dir 定义的路径>/rules/hosts.txt
    └── <变量 v2dat_dir 定义的路径>/rules/local-ptr.txt
```
DNS 配置文件 dns.yaml  请自行修改ISP的DNS和socks5代理地址 用来转发查询国外域名
```
plugins:
  - tag: google
    type: forward
    args:
      concurrent: 2
      upstreams:
        - addr: "tls://8.8.8.8:853"
          enable_pipeline: false
          socks5: "10.10.11.253:1080"
          
        - addr: "tls://8.8.4.4:853"
          enable_pipeline: false
          socks5: "10.10.11.253:1080"

  - tag: cloudflare
    type: forward
    args:
      concurrent: 2
      upstreams:
        - addr: "tls://1.1.1.1:853"
          enable_pipeline: true
          socks5: "10.10.11.253:1080"

        - addr: "tls://1.0.0.1:853"
          enable_pipeline: true
          socks5: "10.10.11.253:1080"

  - tag: ali
    type: forward
    args:
      concurrent: 2
      upstreams:
        - addr: "udp://223.5.5.5:53"
        - addr: "udp://223.6.6.6:53"

#ISP提供的DNS，请自行修改
  - tag: local
    type: forward
    args:
      concurrent: 2
      upstreams:
        - addr: "udp://221.12.1.227:53"
        - addr: "udp://221.12.33.227:53"

#上游fakeip代理网关
  - tag: proxy
    type: forward
    args:
      concurrent: 1
      upstreams:
        - addr: "udp://10.10.11.253:53"


  # server 失败
  - tag: reject_2
    type: sequence
    args:
      - exec: reject 2

  # 拒绝响应
  - tag: reject_3
    type: sequence
    args:
      - exec: reject 3

  # 不支持的操作
  - tag: reject_5
    type: sequence
    args:
      - exec: reject 5
```

config.yaml 
```
log:
  level: warn
  file: "/etc/mosdns/mosdns.log"

api:
  http: "0.0.0.0:80"

include: ['/etc/mosdns/dns.yaml']

plugins:

  # 国内域名
  - tag: geosite_cn
    type: domain_set
    args:
      files:
        - "/etc/mosdns/rules/geosite_cn.txt"
        - "/etc/mosdns/rules/geosite_apple.txt"
        - "/etc/mosdns/rules/force-cn.txt"

  # 国内 IP
  - tag: geoip_cn
    type: ip_set
    args:
      files:
        - "/etc/mosdns/rules/geoip_cn.txt"

  # 国外域名
  - tag: geosite_no_cn
    type: domain_set
    args:
      files:
        - "/etc/mosdns/rules/geosite_geolocation-!cn.txt"
        - "/etc/mosdns/rules/force-nocn.txt"

  - tag: hosts
    type: hosts
    args:
      files:
        - "/etc/mosdns/rules/hosts.txt"

  - tag: local_ptr
    type: domain_set
    args:
      files:
        - "/etc/mosdns/rules/local-ptr.txt"


  - tag: forward_local
    type: fallback
    args:
      primary: local # 主dns
      secondary: ali # 备用dns
      threshold: 50
      always_standby: true

  - tag: forward_remote
    type: fallback
    args:
      primary: cloudflare # 主dns
      secondary: google # 备用dns
      threshold: 100
      always_standby: true

  - tag: forward_proxy
    type: fallback
    args:
      primary: proxy # 主dns
      secondary: proxy # 备用dns
      threshold: 100
      always_standby: true

  # ECS
  - tag: ecs_cn
    type: "ecs_handler"
    args:
      forward: true # 是否转发来自下游的 ecs
      preset: "" # 发送预设 ecs 
      send: true # 是否发送 ecs
      mask4: 24 # ipv4 掩码。默认 24 | 12
      mask6: 48 # ipv6 掩码。默认 48 | 32

  - tag: no_ecs
    type: "ecs_handler"
    args:
      forward: false # 是否转发来自下游的 ecs
      preset: "" # 发送预设 ecs
      send: false # 是否发送 ecs
      mask4: 24
      mask6: 48 

  ################ 核心序列 #################

  # 国外解析
  - tag: forward_remote_upstream
    type: sequence
    args:
      - exec: $no_ecs
      - exec: prefer_ipv4
      - exec: query_summary forward_remote
      - exec: $forward_proxy

  # 响应操作
  - tag: has_resp_sequence
    type: sequence
    args:
      - matches: has_resp
        exec: accept

  # 查询国内域名
  # 返回非国内IP则 drop_resp
  - tag: query_is_non_local_ip
    type: sequence
    args:
      - exec: $ecs_cn
      - exec: prefer_ipv4
      - exec: $forward_local
      - matches: "!resp_ip $geoip_cn"
        exec: drop_resp

  # fallback: 失败时回滚
  - tag: fallback
    type: fallback
    args:
      primary: forward_remote_upstream
      secondary: forward_remote_upstream
      threshold: 100
      always_standby: true

  # ################ 条件判断序列 #################
  
  # 匹配本地域名
  - tag: query_is_local_domain
    type: sequence
    args:
      - exec: $ecs_cn
      - exec: prefer_ipv4
      - matches: qname $geosite_cn
        exec: $forward_local
      - exec: query_summary forward_local

 # 匹配国外域名
  - tag: query_is_no_local_domain
    type: sequence
    args:
      - matches: qname $geosite_no_cn
        exec: $forward_remote_upstream

 # 匹配阻断域名
  - tag: query_is_reject_domain
    type: sequence
    args:
      - matches:
        - qtype 12
        - qname $local_ptr
        exec: reject 3
      - matches: qtype 65
        exec: reject 3
    
  # 主序列
  - tag: main_sequence
    type: sequence
    args:
      - exec: prefer_ipv4
      - exec: $hosts
      - exec: jump has_resp_sequence
      - exec: forward_edns0opt 8
      - exec: $query_is_reject_domain
      - exec: jump has_resp_sequence
      - exec: $query_is_local_domain
      - exec: jump has_resp_sequence
      - exec: $query_is_no_local_domain
      - exec: jump has_resp_sequence
      - exec: $fallback
      - exec: jump has_resp_sequence

  ################ 服务器 #################

  - tag: udp_server
    type: udp_server
    args:
      entry: main_sequence
      listen: ":53"
```
