### DISCUSSION TITLE
查询不存在的域名时，日志里显示的消息却是服务器无响应

### DISCUSSION THREAD

**Discussion by IceCodeNew** [IrineSistiana/mosdns#85] [General]
如题，我无意中在 nslookup 里把 `exit` 敲成 `exiy` 时发现的这个现象：
```
2021-02-26T00:47:46.932+0800	warn	my_server	server/server_handler.go:88	entry returned an err	{"query": "exiy. 1 1 4 21", "error": "main_sequence: forward_nextdns: no response"}
```

感觉这个逻辑很不合理，但不确定我有没有哪里分析出错，所以贴上上面的 debug 日志邀请开发者看看。

**Comment by IceCodeNew** [comment]
完整的队列配置如下：
```
- tag: main_sequence
  type: sequence
  args:
    exec:
      - cloak_hosts

      - if:
          - query_is_ad_domain
          - query_is_local_ptr
        exec:
          - _block_with_nxdomain
        goto: _end

      - if_and:
          - query_is_non_local_domain
          - _qtype_AAAA
        exec:
          - _block_with_empty_response
        goto: _end

      - _default_cache
      - set_ecs

      - if:
          - query_is_non_local_domain
        exec:
          - forward_nextdns
        goto: _end

      - if:
          - query_is_local_domain
        exec:
          - with_fallback_cn_dns_serv
          - if:
              - response_has_bogus_ip
            exec:
              - _block_with_nxdomain
        goto: _end

      - if:
          - _qtype_AAAA
        exec:
          - forward_tuna_moe
          - if:
              - "!response_has_local_ipv6"
            exec:
              - _block_with_empty_response
        goto: _end

      - forward_tuna_moe
      - if:
          - response_has_local_cdn
          - response_has_local_ip
        goto: _end

      - forward_nextdns        # 兜底
```

**Comment by IrineSistiana** [comment]
-已删

**Reply by IceCodeNew** [reply]
> 你是不是配置了多个服务器，但都是 trusted: false(或者没配置)。

确实是这样：
```
- tag: forward_nextdns
  type: forward
  args:
    upstream:
      - addr: https://dns.nextdns.io/**********/XXXXXXXXXX
        ip_addr:
        - 45.90.28.666
        - 45.90.30.666
        - 2a07:a8c0::gg:gggg
        - 2a07:a8c1::gg:gggg
      - addr: tls://XXXXXXXXXX-**********.dns.nextdns.io
        ip_addr:
        - 45.90.28.666
        - 45.90.30.666
        - 2a07:a8c0::gg:gggg
        - 2a07:a8c1::gg:gggg
    deduplicate: true
    insecure_skip_verify: false
    timeout: 10
```
