### DISCUSSION TITLE
所有主机名、域名都查询不到结果

### DISCUSSION THREAD

**Discussion by xbot** [IrineSistiana/mosdns#872] [General]
配置文件内容如下：

```yaml
plugins:
  # 内网域名集合
  - tag: internal_domains
    type: domain_set
    args:
      exps:
        - "router"
        - "sidecar"

  # 家庭 DNS
  - tag: forward_home
    type: forward
    args:
      upstreams:
        - addr: "10.0.0.3"

  # 办公室 DNS
  - tag: forward_office
    type: forward
    args:
      upstreams:
        - addr: "192.168.10.107"

  # 公网 DNS 并发查询
  - tag: forward_public
    type: forward
    args:
      concurrent: true
      upstreams:
        - addr: "223.5.5.5"
        - addr: "223.6.6.6"
        - addr: "119.29.29.29"
        - addr: "114.114.114.114"

  - tag: main_sequence
    type: sequence
    args:
      # 内网主机
      - matches: qname $internal_domains
        exec: $forward_home
      - matches: has_resp
        exec: accept
      # 在家时
      - matches: client_ip 10.0.0.0/24
        exec: $forward_home
      - matches: has_resp
        exec: accept
      # 在办公室
      - matches: client_ip 192.168.10.0/24
        exec: $forward_office
      - matches: has_resp
        exec: accept
      # 缺省
      - exec: $forward_public
      - matches: has_resp
        exec: accept

  # - tag: cache
  #   type: cache
  #   args:
  #     size: 4096
  #     lazy_cache_ttl: 0

  - tag: "udp_server_1"
    type: "udp_server"
    args:
      entry: main_sequence
      listen: "127.0.0.1:53"

  - tag: "tcp_server_1"
    type: "tcp_server"
    args:
      entry: main_sequence
      listen: "127.0.0.1:53"
```
