### ISSUE TITLE
[BUG] 蜜汁无法运行

### ISSUE THREAD

**Issue by leon911000** [IrineSistiana/mosdns#108]
**出现了什么问题**

描述一下问题的表现。可以直接附上截图或log。建议配置`logger`插件使用`debug`级别获取更详细的调试log。

使用wiki中的本地/远程域名分流外加广告域名屏蔽配置例并下载 geoip.dat 和 geosite.dat 文件到 mosdns 的目录后，尝试管理员身份运行service_control.bat，1安装显示成功，3启动也显示成功，但实际mosdns.exe并未成功运行，5重启显示“2021-03-29T17:37:21.210+0800    fatal   mosdns/main.go:208      restart mosdns: The service has not been started.”～尝试系统服务里启动mosdns服务，提示错误1067，进程意外终止～文件夹内也无log文件出现

**如何重现**

描述一下如何重现该问题。请尽可能的包含：

mosdns 的版本号(`mosdns -v`)：1.6.0～1.7.0

使用的启动参数或启动方式：

操作系统和平台：win10 ltsc

进行了什么操作导致了问题的出现：

使用的配置文件：

```
log:
  level: info
  file: './log.log'

plugin:

  ################# 服务插件 ################

  - tag: main_server      # 启动服务器
    type: server
    args:
      entry:
        - _default_cache  # 缓存
        - main_sequence
      server:
        - protocol: udp
          addr: 127.0.0.1:53
        - protocol: tcp
          addr: 127.0.0.1:53
        - protocol: udp
          addr: '[::1]:53'
        - protocol: tcp
          addr: '[::1]:53'

  ################# 可执行插件 ################

  - tag: main_sequence
    type: sequence
    args:
      exec:
        - if:
            - query_is_ad_domain    # 已知的广告域名
          exec:
            - _block_with_nxdomain  # 屏蔽
            - _end

        - if:
            - query_is_local_domain   # 已知的本地域名
            - '!_query_is_common'     # 和不常见的请求类型
          exec:
            - forward_local           # 用本地服务器
            - _end

        - if:
            - query_is_non_local_domain  # 已知的非本地域名
          exec:
            - forward_remote             # 用远程服务器
            - _end

        # 剩下的未知域名用 IP 分流。以下是"顺序 IP 分流"的逻辑。很稳定，不易出错。
        # <高级> 如果想用"并发 IP 分流"逻辑，从下文的 <并发 IP 分流示例> 里选择一个方案，
        # 然后将下面几行替换掉。
        - forward_local               # 先请求转发至本地服务器
        - if:
            - response_has_local_ip   # 如果(本地)应答包含本地 IP
          exec:
            - _end                    # 就直接采用结果
        - forward_remote              # 否则去请求远程服务器的结果

  - tag: forward_local                # 转发至本地服务器的插件
    type: forward
    args:
      upstream:
        - addr: https://223.5.5.5/dns-query

  - tag: forward_remote               # 转发至远程服务器的插件
    type: forward
    args:
      upstream:
        - addr: https://1.0.0.1/dns-query

  ################ 匹配器插件 #################

  - tag: query_is_local_domain         # 匹配本地域名的插件
    type: query_matcher
    args:
      domain:
        - 'ext:./geosite.dat:cn'

  - tag: query_is_non_local_domain    # 匹配非本地域名的插件
    type: query_matcher
    args:
      domain:
        - 'ext:./geosite.dat:geolocation-!cn'

  - tag: query_is_ad_domain           # 匹配广告域名的插件
    type: query_matcher
    args:
      domain:
        - 'ext:./geosite.dat:category-ads-all'

  - tag: response_has_local_ip        # 匹配本地 IP 的插件
    type: response_matcher
    args:
      ip:
        - 'ext:./geoip.dat:cn' 

```
