### ISSUE TITLE
[BUG] 作为 DoH 服务器不能正常工作 

### ISSUE THREAD

**Issue by rampageX** [IrineSistiana/mosdns#120]
**出现了什么问题**

作为 DoH 服务器的时候不能工作，其他所有同样配置情况下，监听为 DoT 以及普通 TCP/UDP 服务器都能工作。

使用 DoH 客户端查询，开启 debug 模式，会卡在这然后超时，mosdns 那边也开启了 debug 模式但是没有任何信息输出。
```txt
...
== Info: ALPN, offering h2
== Info: ALPN, offering http/1.1
== Info: ALPN, server did not agree to a protocol
...
---

而正常的 DoH 服务器比如 dns.sb，日志为：

```txt
...
== Info: ALPN, offering h2
== Info: ALPN, offering http/1.1
== Info: ALPN, server accepted to use h2
...
```

**如何重现**

描述一下如何重现该问题。请尽可能的包含：

mosdns 的版本号(`mosdns -v`)： v1.8.0-0-gca72cf7，之前没用过这个功能所以以前行不行不知道。

使用的启动参数或启动方式： sudo /usr/local/sbin/mosdns -c /home/ubuntu/cfg/mosdns.yaml

操作系统和平台：Ubuntu 18.04 TLS

进行了什么操作导致了问题的出现：

使用的配置文件：

监听端口 443 不行，为了避免被侦测改为 4433 情况一样。

```yaml

  - tag: doh_server
    type: server
    args:
      max_concurrent_queries: 0
      entry: main_parallel
      server:
        - protocol: 'doh'
          addr: '[::]:4433'
          timeout: 5
          idle_timeout: 30
          cert: '/home/ubuntu/.acme.sh/3344567.xyz/fullchain.cer'
          key: '/home/ubuntu/.acme.sh/3344567.xyz/3344567.xyz.key'
          url_path: '/dns-query'
          get_user_ip_from_header: 'X-Forwarded-For'

````

**Comment by IrineSistiana** [comment]
> 使用 DoH 客户端查询，开启 debug 模式，会卡在这然后超时，mosdns 那边也开启了 debug 模式但是没有任何信息输出。

这个客户端叫什么？我尝试复现一下。

**Comment by IrineSistiana** [comment]
```
# curl -H 'accept: application/dns-message' 'https://192.168.1.190:4443/dns-query?dns=q80BAAABAAAAAAAAA3d3dwdleGFtcGxlA2NvbQAAAQAB' -k -v
*   Trying 192.168.1.190:4443...
* TCP_NODELAY set
* Connected to 192.168.1.190 (192.168.1.190) port 4443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN, server accepted to use h2
...
```

我本地用 curl 没问题。

> mosdns 那边也开启了 debug 模式但是没有任何信息输出。

这就很奇怪。你在服务器用 curl 上试试？

**Comment by rampageX** [comment]
VPS 1, 国内主机：

```bash
curl -H 'accept: application/dns-message' 'https://172.17.0.3:443/dns-query?dns=q80BAAABAAAAAAAAA3d3dwdleGFtcGxlA2NvbQAAAQAB' -k -v
*   Trying 172.17.0.3...
* TCP_NODELAY set
* Connected to 172.17.0.3 (172.17.0.3) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Unknown (8):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Client hello (1):
* TLSv1.3 (OUT), TLS Unknown, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=761026.xyz
*  start date: Apr 11 15:47:02 2021 GMT
*  expire date: Jul 10 15:47:02 2021 GMT
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
> GET /dns-query?dns=q80BAAABAAAAAAAAA3d3dwdleGFtcGxlA2NvbQAAAQAB HTTP/1.1
> Host: 172.17.0.3
> User-Agent: curl/7.58.0
> accept: application/dns-message
>
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS Unknown, Unknown (21):
* TLSv1.3 (IN), TLS alert, Client hello (1):
* Empty reply from server
* Connection #0 to host 172.17.0.3 left intact
curl: (52) Empty reply from server
```

VPS 2, 香港主机：

```bash
curl -H 'accept: application/dns-message' 'https://172.17.19.192:4433/dns-query?dns=q80BAAABAAAAAAAAA3d3dwdleGFtcGxlA2NvbQAAAQAB' -k -v
*   Trying 172.17.19.192...
* TCP_NODELAY set
* Connected to 172.17.19.192 (172.17.19.192) port 4433 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=quakemachinex.com
*  start date: Apr  3 15:22:39 2021 GMT
*  expire date: Jul  2 15:22:39 2021 GMT
*  issuer: C=US; O=(STAGING) Let's Encrypt; CN=(STAGING) Artificial Apricot R3
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
> GET /dns-query?dns=q80BAAABAAAAAAAAA3d3dwdleGFtcGxlA2NvbQAAAQAB HTTP/1.1
> Host: 172.17.19.192:4433
> User-Agent: curl/7.52.1
> accept: application/dns-message
>
* TLSv1.2 (IN), TLS alert, Client hello (1):
* Curl_http_done: called premature == 0
* Empty reply from server
* Connection #0 to host 172.17.19.192 left intact
curl: (52) Empty reply from server
```

**Comment by rampageX** [comment]
完整配置：

```yaml
log:
   level: debug           # 日志级别。可选 `debug` `info` `warn` `error`。默认 `info`。
   # file: "/var/log/mosdns.log"    # 记录日志到文件。
   # level: debug
   file: ""

plugin:
  ## 启动 sequence 服务器 DoT
  - tag: dot_server
    type: server
    args:
      max_concurrent_queries: 0
      entry: main_sequence
      server:
        - protocol: 'dot'          # 服务器协议。可以是 `udp`, `tcp`, `dot/tls`, `doh/https`, `http`。必需。
          addr: '0.0.0.0:853'     # 服务器监听地址。必需。
          timeout: 5               # 请求处理超时时间。单位: 秒。默认: 5。
          idle_timeout: 30         # 空连接超时时间。单位: 秒。默认: 10。适用于除了 `udp` 以外的协议。
          cert: '/home/ubuntu/.acme.sh/3344567.xyz/fullchain.cer' # 证书文件。适用于 `dot`, `doh`。必需。
          key: '/home/ubuntu/.acme.sh/3344567.xyz/3344567.xyz.key'  # 证书密钥文件。适用于 `dot`, `doh`。必需。
          url_path: '/dns-query'   # url 路径。适用于 `doh`, `http`。如果为空，则任意路径的请求都能被处理。
          get_user_ip_from_header: 'X-Forwarded-For' # 适用于 `doh`, `http`。尝试从 HTTP 头获取用户 IP。

  ## 启动 parallel 服务器 DoH
  - tag: doh_server
    type: server
    args:
      max_concurrent_queries: 0
      entry: main_parallel
      server:
        - protocol: 'doh'
          addr: '[::]:443'
          timeout: 5
          idle_timeout: 30
          cert: '/home/ubuntu/.acme.sh/3344567.xyz/fullchain.cer'
          key: '/home/ubuntu/.acme.sh/3344567.xyz/3344567.xyz.key'
          url_path: '/dns-query'
          get_user_ip_from_header: 'X-Forwarded-For'

  ## 启动 parallel 服务器
  - tag: parallel_server
    type: server
    args:
      max_concurrent_queries: 0
      entry: main_parallel
      server:
        - protocol: udp
          addr: 0.0.0.0:5353
        - protocol: tcp
          addr: 0.0.0.0:5353


  ## 可执行插件-顺序
  - tag: main_sequence
    type: sequence
    args:
      exec:
        - _default_cache          # 缓存
        - if:
            - match_local_domain      # 处理已知的本地域名
            - "!_query_is_common"  # 和不常见的请求类型
          exec:
            - ecs_local
            - forward_local
            - _end

        - if:
            - match_non_local_domain  # 处理已知的非本地域名
          exec:
            - ecs_remote
            - forward_remote
            - _end

        - sequence_bypass_local       # 分流未知域名。有两种方案：顺序或并行。这是顺序执行。

  ## 可执行插件-并发
  - tag: main_parallel
    type: sequence
    args:
      exec:
        - _default_cache          # 缓存
        - if:
            - match_local_domain      # 处理已知的本地域名
            - "!_query_is_common"  # 和不常见的请求类型
          exec:
            - ecs_local
            - fast_forward_local
            - _end

        - if:
            - match_non_local_domain  # 处理已知的非本地域名
          exec:
            - ecs_remote
            - fast_forward_remote
            - _end

        - parallel_bypass_local       # 分流未知域名。有两种方案：顺序或并行。这是并发执行。

  ## 两种分流逻辑
  - tag: sequence_bypass_local        # 顺序执行的分流逻辑
    type: sequence
    args:
      exec:
        - forward_local               # 先请求转发至本地服务器
        - if:
            - match_local_ip          # 如果应答包含本地 IP
          goto: _end                  # 就直接采用结果
        - forward_remote              # 否则用远程服务器的结果

  - tag: parallel_bypass_local        # 并发执行的分流的逻辑
    type: parallel
    args:
      parallel:
        - - fast_forward_local             # 并发请求本地和远程服务器
          - if:
              - "!match_local_ip"       # 本地服务器返回的非本地 IP 的应答会被丢弃
            exec:
              - _drop_response
        - - fast_forward_remote

  ## 匹配器插件
  # - tag: match_qtype_HTTPS # 匹配 HTTPS 请求
  #   type: query_matcher
  #   args:
  #     type: [65]

  - tag: match_local_domain # 匹配请求域名是否是本地域名
    type: query_matcher
    args:
      domain:
        - ext:/home/ubuntu/cfg/geosite.dat:cn

  - tag: match_non_local_domain # 匹配请求域名是否是境外域名
    type: query_matcher
    args:
      domain:
        - ext:/home/ubuntu/cfg/geosite.dat:geolocation-!cn

  - tag: match_local_ip # 匹配应答的 IP 是否是本地 IP
    type: response_matcher
    args:
      ip:
        - ext:/home/ubuntu/cfg/geoip.dat:cn

  ## ECS
  - tag: ecs_local
    type: ecs
    args:
      auto: true
      force_overwrite: false
      mask4: 24
      mask6: 32
      ipv4: ""
      ipv6: ""

  - tag: ecs_remote
    type: ecs
    args:
      auto: false
      force_overwrite: false
      mask4: 24
      mask6: 32
      ipv4: "202.67.222.0"
      ipv6: ""

  ## 功能性插件
  - tag: forward_local # 转发至本地服务器
    type: forward
    args:
      upstream:
        # - addr: https://doh.360.cn/dns-query
        # - addr: https://i.233py.com/dns-query
        # - addr: tls://dns.alidns.com
          # trusted: true
        # - addr: tls://dns.pub
        - addr: 223.5.5.5
          trusted: true
        - addr: 119.29.29.29
          trusted: true
      deduplicate: false           # 是否请求去重。
      insecure_skip_verify: false  # 禁用 TLS 身份验证。
      fastest_ip: false            # 最快 IP 模式。
      timeout: 6                  # 超时时间，单位: 秒。
      # 用于解析上游服务器域名的 bootstrap 服务器地址。可配置多个。必须没有域名。可以为空，会使用系统设置。
      bootstrap:
        - 9.9.9.9:9953
        - 208.67.220.220:443

  - tag: forward_remote # 转发至远程服务器
    type: forward
    args:
      upstream:
        # - addr: https://dns11.quad9.net/dns-query
          # trusted: true
        # - addr: https://dns.twnic.tw/dns-query
          # trusted: true
        # - addr: tls://dns.google
          # trusted: true
        # - addr: tls://dns.sb
          # trusted: true
        - addr: 9.9.9.11:9953
          trusted: true
        - addr: 101.6.6.6:5353
          trusted: true
      deduplicate: false
      insecure_skip_verify: false
      fastest_ip: false
      timeout: 6
      bootstrap:
        - 9.9.9.9:9953
        - 208.67.220.220:443

  - tag: fast_forward_local
    type: fast_forward
    args:
      deduplicate: false    # 是否请求去重。
      ca: [ ]             # 用于 TLS 验证的 CA 证书。适用于 `dot`，`doh` 协议。为空默认使用系统证书。
      timeout: 5          # 请求超时时间。单位: 秒。默认 5。
      upstream:             # 上游服务器。至少要配置一个。可配置多个，会并发请求全部服务器。
        - addr: 'tls://dns.alidns.com'  # 服务器地址。必需。
          dial_addr: 223.5.5.5:853  # 指定服务器网络地址。格式 `host:port`，端口不可省略。
          trusted: false     # 是否是可信服务器。仅配置了多个服务器时生效。
                            # true: 该服务器返回的 Rcode != 0 的应答会被接受。
                            # false: 该服务器返回的 Rcode != 0 会被丢弃。
          socks5: ""  # socks5 服务器地址。格式 `host:port`。`:port` 不可省略。
                      # 不支持用户名密码认证。适用于 `tcp`, `dot`, `doh` 协议。
          max_conns: 1                      # 最大连接数。目前仅适用于 `doh` 协议。默认: 1。
          idle_timeout: 10    # 空连接超时时间。单位: 秒。
                              # 如果为 0，则禁用连接重用(对于 `udp` 协议是禁用套接字重用)。适用于全部协议。
          insecure_skip_verify: false # 是否禁用 TLS 验证。适用于 `dot`，`doh` 协议。

        - addr: 'tls://dns.pub'
          dial_addr: 162.14.21.56:853
          trusted: false
          socks5: ""
          max_conns: 1
          idle_timeout: 10
          insecure_skip_verify: false

  - tag: fast_forward_remote
    type: fast_forward
    args:
      deduplicate: false
      ca: [ ]
      timeout: 5
      upstream:
        - addr: '9.9.9.11:9953'
          dial_addr: 9.9.9.11:9953
          trusted: true
          socks5: ""
          max_conns: 1
          idle_timeout: 30
          insecure_skip_verify: false

        - addr: '208.67.222.222:443'
          dial_addr: 208.67.222.222:443
          trusted: true
          socks5: ""
          max_conns: 1
          idle_timeout: 30
          insecure_skip_verify: false

```

本地查询时，mosdns 在 debug 模式并无输出：

```
2021-04-18T03:28:57.836+0800	info	mosdns/main.go:174	mosdns ver: v1.8.0-0-gca72cf7
2021-04-18T03:28:57.836+0800	info	mosdns/main.go:175	arch: amd64, os: linux, go: go1.16.3
2021-04-18T03:28:57.837+0800	info	coremain/run.go:65	loading config	{"file": "/home/ubuntu/cfg/mosdns.yaml"}
2021-04-18T03:28:57.838+0800	info	coremain/run.go:116	loading plugin	{"tag": "dot_server"}
2021-04-18T03:28:57.839+0800	info	coremain/run.go:116	loading plugin	{"tag": "doh_server"}
2021-04-18T03:28:57.840+0800	info	coremain/run.go:116	loading plugin	{"tag": "parallel_server"}
2021-04-18T03:28:57.840+0800	info	coremain/run.go:116	loading plugin	{"tag": "main_sequence"}
2021-04-18T03:28:57.841+0800	info	coremain/run.go:116	loading plugin	{"tag": "main_parallel"}
2021-04-18T03:28:57.841+0800	info	coremain/run.go:116	loading plugin	{"tag": "sequence_bypass_local"}
2021-04-18T03:28:57.841+0800	info	coremain/run.go:116	loading plugin	{"tag": "parallel_bypass_local"}
2021-04-18T03:28:57.841+0800	info	coremain/run.go:116	loading plugin	{"tag": "match_local_domain"}
2021-04-18T03:28:57.979+0800	info	match_local_domain	query_matcher/query_matcher.go:94	domain matcher loaded	{"length": 71029}
2021-04-18T03:28:57.979+0800	info	coremain/run.go:116	loading plugin	{"tag": "match_non_local_domain"}
2021-04-18T03:28:57.992+0800	info	match_non_local_domain	query_matcher/query_matcher.go:94	domain matcher loaded	{"length": 29709}
2021-04-18T03:28:57.993+0800	info	coremain/run.go:116	loading plugin	{"tag": "match_local_ip"}
2021-04-18T03:28:58.144+0800	info	match_local_ip	response_matcher/response_matcher.go:92	ip matcher loaded	{"length": 8546}
2021-04-18T03:28:58.144+0800	info	coremain/run.go:116	loading plugin	{"tag": "ecs_local"}
2021-04-18T03:28:58.144+0800	info	coremain/run.go:116	loading plugin	{"tag": "ecs_remote"}
2021-04-18T03:28:58.145+0800	info	coremain/run.go:116	loading plugin	{"tag": "forward_local"}
2021-04-18T03:28:58.145+0800	info	coremain/run.go:116	loading plugin	{"tag": "forward_remote"}
2021-04-18T03:28:58.145+0800	info	coremain/run.go:116	loading plugin	{"tag": "fast_forward_local"}
2021-04-18T03:28:58.146+0800	info	coremain/run.go:116	loading plugin	{"tag": "fast_forward_remote"}
2021-04-18T03:28:58.146+0800	info	coremain/run.go:42	all plugins are successfully loaded
```
