### ISSUE TITLE
nxdomain后面有end，还会继续执行后面的序列？

### ISSUE THREAD

**Issue by muziling** [IrineSistiana/mosdns#125]
pingfore.qq.com 这个域名是正常可解析的，但日志里有报错，也许是属于广告域名，被nxdomain，但nxdomain后面有配了end了，正常也不应该继续往后执行

```
Wed Apr 21 08:59:21 2021 daemon.err mosdns[705]: 2021-04-21T00:59:21.852Z	warn	main_server	dns_handler/server_handler.go:88	entry returned an err	{"query": "pingfore.qq.com.lan. IN A 53194 1655", "error": "main_sequence: forward_local: no response"}
```

我的配置：
```
log:
  level: warn
  file: ''

plugin:

  ################# 服务插件 ################

  - tag: main_server      # 启动服务器
    type: server
    args:
      entry:
        - _default_cache  # 缓存
        - query_hosts
        - main_sequence
        - ttl_set
      server:
        - protocol: udp
          addr: 0.0.0.0:53
        - protocol: tcp
          addr: 0.0.0.0:53

  ################# 可执行插件 ################

  - tag: main_sequence
    type: sequence
    args:
      exec:
        - if:
            - query_is_pollute_domain    # 已知的域名不能解析为国内IP
          exec:
            - forward_remote  # 屏蔽
            - _end

        - if:
            - query_is_ad_domain    # 已知的广告域名
          exec:
            - _block_with_nxdomain  # 屏蔽
            - _end

        # 剩下的未知域名用 IP 分流。以下是"顺序 IP 分流"的逻辑。很稳定，不易出错。
        # <高级> 如果想用"并发 IP 分流"逻辑，从下文的 <并发 IP 分流示例> 里选择一个方案，
        # 然后将下面几行替换掉。
        - forward_local               # 先请求转发至本地服务器
        - if:
            - response_has_local_ip   # 如果(本地)应答包含本地 IP
          exec:
            - _end                    # 就直接采用结果
        - forward_remote              # 否则去请求远程服务器的结果

  - tag: forward_local                # 转发至本地服务器的插件
    type: forward
    args:
      upstream: #可配置多个。至少要配置一个。会并发请求全部服务器。
        - addr: 218.85.157.99
        - addr: 218.85.152.99

  - tag: forward_remote               # 转发至远程服务器的插件
    type: forward
    args:
      upstream:
        - addr: 127.0.0.1:9053

  ################ 匹配器插件 #################

  - tag: ttl_set
    type: ttl
    args:
      minimal_ttl: 300  # 最小TTL。如果非零，小于这个数的应答的TTL会被修改成这个值。
      maximum_ttl: 3600 # 最大TTL。如果非零，大于这个数的应答的TTL会被修改成这个值。

  - tag: query_hosts           # 匹配hosts的插件
    type: hosts
    args:
      hosts:
        - test.xyz 10.146.138.20

  - tag: query_is_ad_domain           # 匹配广告域名的插件
    type: query_matcher
    args:
      domain:
        - 'ext:./geosite.dat:category-ads-all'

  - tag: query_is_pollute_domain           # 匹配域名不能解析为国内IP的插件
    type: query_matcher
    args:
      domain:
        - googleapis.cn
        - gstatic.com

  - tag: response_has_local_ip        # 匹配本地 IP 的插件
    type: response_matcher
    args:
      ip:
        - 'ext:./geoip.dat:cn'
```
