### ISSUE TITLE
[BUG] ecs 是否可以排除特定地址作为子网，如 127.0.0.1/xx

### ISSUE THREAD

**Issue by laggardkernel** [IrineSistiana/mosdns#14]
**出现了什么问题**

通过本地 `dig` 测试发现，`127.0.0.1/24` 子网被设置为 EDNS client subnet，导致域名解析失败。

```
dig @127.0.0.1 -p 53001 i2.hdslb.com
❯ dig @127.0.0.1 -p 53001 i2.hdslb.com

; <<>> DiG 9.16.9 <<>> @127.0.0.1 -p 53001 i2.hdslb.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 3882
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; CLIENT-SUBNET: 127.0.0.0/24/24
;; QUESTION SECTION:
;i2.hdslb.com.                  IN      A

;; ANSWER SECTION:
i2.hdslb.com.           452     IN      CNAME   img.hdslb.com.
img.hdslb.com.          152     IN      CNAME   i0.hdslb.com.cdn20.com.

;; Query time: 14 msec
;; SERVER: 127.0.0.1#53001(127.0.0.1)
;; WHEN: Wed Dec 16 16:22:41 CST 2020
;; MSG SIZE  rcvd: 223

;; Query time: 14 msec
;; SERVER: 127.0.0.1#53001(127.0.0.1)
;; WHEN: Wed Dec 16 16:22:41 CST 2020
;; MSG SIZE  rcvd: 223

```

是不是可以在插件 ecs 排除部分地址？

---

**如何重现**

描述一下如何重现该问题。请尽可能的包含：

mosdns 的版本号(`mosdns -v`)：v0.16.0-0-gbe90c3f

使用的启动参数或启动方式：

操作系统和平台：masOS

进行了什么操作导致了问题的出现：

使用的配置文件：

```yaml
plugin:
  - tag: my_logger
    type: logger
    args:
      file: ""
      level: info
      # level: debug

  - tag: domestic_server
    type: plain_server
    args:
      entry: domestic_sequence
      listen:
        - udp://127.0.0.1:53001
        - tcp://127.0.0.1:53001

  - tag: domestic_sequence
    type: sequence
    args:
      exec:
        # - add_ecs  # may wrongly add 127.0.0.1/24
        # - _no_ecs
        - forward_dnspod
      next: ""

  - tag: forward_dnspod
    type: forward
    args:
      bootstrap:
        - tls://223.5.5.5
      deduplicate: false
      insecure_skip_verify: false
      timeout: 2
      upstream:
        - addr: tls://dns.pub

  - tag: add_ecs
    type: ecs
    args:
      auto: true # 是否自动将客户端地址作为 ECS 附加到请求。如果为 true，则预设地址不会被使用。
      force_overwrite: false  # 如果请求已有 ECS，是否覆盖。
      mask4: 24               # 用于 ipv4 地址的掩码。
      mask6: 32               # 用于 ipv6 地址的掩码。
      # ipv4: "1.2.3.4"         # 预设的 ipv4 地址。如果非空，会附加在 A 请求中。
      # ipv6: "2001:dd8:1a::"   # 预设的 ipv6 地址。如果非空，会附加在 AAAA 请求中。

include: []
````
