### ISSUE TITLE
[Feature request] 对 `v2fly/domain-list-community` 项目中 `@attr` 的支持

### ISSUE THREAD

**Issue by IceCodeNew** [IrineSistiana/mosdns#15]
**希望添加的功能**

我没有确认到目前是否已经实现了这个功能，所以如果已经实现了，请轻拍（
目前 Wiki 配置里的以下部分用到了 https://github.com/v2fly/domain-list-community 项目的 `geolocation-!cn` 数据，这部分数据里其实包含了不少接入点在国内的域名，曾经就给 shadowsocks 用户造成过困扰。（Refer: https://github.com/shadowsocks/shadowsocks-windows/issues/2971）
```
  - tag: match_non_local_domain   # 匹配非本地域名
    type: domain_matcher
    args:
      check_cname: false
      check_question: true
      domain:
        - "./geosite.dat:geolocation-!cn"
```

个人认为这块相当有必要进行修改，尚不知道作者打算如何处理这种在引用 `geosite.dat` 文件中数据时 **排除** 某个 attr 的需要。
