### ISSUE TITLE
[BUG]同时使用ipv4和ipv6监听端口后，程序报错无法启动

### ISSUE THREAD

**Issue by bigfoxtail** [IrineSistiana/mosdns#151]
我在配置文件中同时配置了ipv4  0.0.0.0和ipv6  [::]的53端口监听
启动程序会发生报错，无法正常启动。
但是只监听0.0.0.0程序运行正常，以下是netstat输出，貌似端口显示成ipv6的格式？
这种情况属于正常现象吗？还是我哪里的配置或者环境有问题？

运行环境：Unraid自带的docker ，网络模式：Bridge
docker端口映射情况：
172.17.0.2:53/TCP 192.168.1.11:5454
172.17.0.2:53/UDP 192.168.1.11:5454

```txt
/ # netstat -lnp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 :::53                   :::*                    LISTEN      1/mosdns
udp        0      0 :::53                   :::*                                1/mosdns
Active UNIX domain sockets (only servers)
Proto RefCnt Flags       Type       State         I-Node PID/Program name    Path
/ # 
```

日志
```txt
2021-08-17T16:39:37.380Z	fatal	handler/error.go:50	plugin fatal err	{"from": "main_server", "msg": "server exited with err: listen udp 0.0.0.0:53: bind: address already in use"}
```

关键点配置
```yaml
  # 启动服务器的插件
  - tag: main_server
    type: server
    args:
      entry:
        - _default_cache  # 缓存
        - main_sequence   # 分流逻辑
      server:
        - protocol: udp
          addr: 0.0.0.0:53
        - protocol: tcp
          addr: 0.0.0.0:53
        - protocol: udp
          addr: '[::]:53'
        - protocol: tcp
          addr: '[::]:53'

````
