### ISSUE TITLE
[BUG]作为DOH服务端的时候请求报错400

### ISSUE THREAD

**Issue by linusxiong** [IrineSistiana/mosdns#162]
**出现了什么问题**
使用HTTP或者DOH服务时，使用DOH均报错400，且debug模式下日志中未检测到有dns请求，使用udp，dot，tcp均正常，使用caddy反向代理http同样报错400，但是使用http模式本地curl正常返回200，doh没试，但是应该是一样正常的，唯独远程请求时报错400

```
root@debian:~# curl -H 'accept: application/dns-message' 'http://127.0.0.1:60199/dns-query?dns=q80BAAABAAAAAAAAA3d3dwdleGFtcGxlA2NvbQAAAQAB' -k -v
* Expire in 0 ms for 6 (transfer 0x564bfedbdfb0)
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x564bfedbdfb0)
* Connected to 127.0.0.1 (127.0.0.1) port 60199 (#0)
> GET /dns-query?dns=q80BAAABAAAAAAAAA3d3dwdleGFtcGxlA2NvbQAAAQAB HTTP/1.1
> Host: 127.0.0.1:60199
> User-Agent: curl/7.64.0
> accept: application/dns-message
> 
< HTTP/1.1 200 OK
< Content-Type: application/dns-message
< Date: Sun, 12 Sep 2021 18:01:10 GMT
< Content-Length: 75
< 
Warning: Binary output can mess up your terminal. Use "--output -" to tell 
Warning: curl to output it to your terminal anyway, or consider "--output 
Warning: <FILE>" to save to a file.
* Failed writing body (0 != 75)
* Closing connection 0
```

**如何重现**

描述一下如何重现该问题。请尽可能的包含：

mosdns 的版本号(`mosdns -v`)：1.8.6

使用的启动参数或启动方式：systemctl启动

操作系统和平台：debian 10 x64

使用的配置文件：

```yaml
log:
  level: info
  file: "./log.log"
plugin:
  - tag: inbound_server
    type: server
    args:
      entry:
        - ecs
        - cache
        - main_sequence
      server:
        - protocol: doh
          addr: :60190
          timeout: 5
          idle_timeout: 30
          cert: '/root/.acme.sh/脱敏/fullchain.cer'
          key: '/root/.acme.sh/脱敏.key'
          url_path: '/dns-query'
          get_user_ip_from_header: 'X-Forwarded-For'
        - protocol: udp
          addr: :60150
        - protocol: tcp
          addr: :60151
        - protocol: dot
          addr: :60195
          timeout: 5
          idle_timeout: 30
          cert: '/root/.acme.sh/脱敏/fullchain.cer'
          key: '/root/.acme.sh/脱敏.key'
  - tag: main_sequence
    type: sequence
    args:
      exec:
        - if:
            - query_is_local_domain   # 已知的cn域名
            - '!_query_is_common'     # 和不常见的请求类型
          exec:
            - forward_dnspod           # 用dnspod服务器
            - _end

        - if:
            - query_is_non_local_domain  # 已知的非cn域名
          exec:
            - forward_google             # 用google服务器
            - _end

        - forward_dnspod               # 先请求转发至本地服务器
        - if:
            - response_has_local_ip   # 如果应答包含cn IP
          exec:
            - _end                    # 就直接采用结果
        - forward_google             # 否则去请求google服务器的结果
# 匹配本地域名的插件
  - tag: query_is_local_domain
    type: query_matcher
    args:
      domain:
        - 'ext:./geosite.dat:cn'

  # 匹配非本地域名的插件
  - tag: query_is_non_local_domain
    type: query_matcher
    args:
      domain:
        - 'ext:./geosite.dat:geolocation-!cn'

  # 匹配广告域名的插件
  # - tag: query_is_ad_domain
  #   type: query_matcher
  #   args:
  #     domain:
  #       - 'ext:./geosite.dat:category-ads-all'

  # 匹配本地 IP 的插件
  - tag: response_has_local_ip
    type: response_matcher
    args:
      ip:
        - 'ext:./geoip.dat:cn'
  # 添加ECS的插件
  - tag: ecs
    type: ecs
    args:
      auto: true
      force_overwrite: false
  # 缓存插件
  - tag: cache
    type: cache
    argus: 
      size: 10000
      cleaner_interval: 180
  # 转发插件
  - tag: forward_google
    type: fast_forward
    args:
      upstream:
        - addr: 1.1.1.1
          trusted: true 
      deduplicate: true
  - tag: forward_dnspod
    type: fast_forward
    args:
      upstream:
        - addr: 119.29.29.29
          trusted: true 
      deduplicate: true

````
