### ISSUE TITLE
cache 插件存在 bug

### ISSUE THREAD

**Issue by IceCodeNew** [IrineSistiana/mosdns#18]
在针对最新版本推出的功能进行对应配置以后，我遇到了可以正常启动程序，但是在接收到 DNS 请求后程序无法顺利处理并退出的问题。
以下是报错信息：
```
time="2020-12-24T15:29:13+08:00" level=info msg="mosdns ver: v0.18.0-0-g5ca1a5e"
time="2020-12-24T15:29:13+08:00" level=info msg="arch: amd64, os: windows, go: go1.15.6"
time="2020-12-24T15:29:13+08:00" level=info msg="loading config file: config.yaml"
time="2020-12-24T15:29:13+08:00" level=info msg="loading plugin my_logger"
time="2020-12-24T15:29:13+08:00" level=warning msg="[{ts.eset.com. 1 1}], id: 10135, t: 0 ms, from: udp://[::1]:60445: entry route_ingress returned with err: plugin route_ingress reported an err: plugin exec_preprocessing_route reported an err: plugin exec_preprocessing_route reported an err: plugin tag match_ad_domain not defined" plugin=my_plain_server
time="2020-12-24T15:29:13+08:00" level=warning msg="[{ts.eset.com. 28 1}], id: 63752, t: 0 ms, from: udp://[::1]:56027: entry route_ingress returned with err: plugin route_ingress reported an err: plugin exec_preprocessing_route reported an err: plugin exec_preprocessing_route reported an err: plugin tag match_ad_domain not defined" plugin=my_plain_server
time="2020-12-24T15:29:13+08:00" level=warning msg="[{ts.eset.com. 1 1}], id: 10135, t: 0 ms, from: udp://127.0.0.1:60445: entry route_ingress returned with err: plugin route_ingress reported an err: plugin exec_preprocessing_route reported an err: plugin exec_preprocessing_route reported an err: plugin tag match_ad_domain not defined" plugin=my_plain_server
time="2020-12-24T15:29:13+08:00" level=warning msg="[{ts.eset.com. 28 1}], id: 63752, t: 0 ms, from: udp://127.0.0.1:56027: entry route_ingress returned with err: plugin route_ingress reported an err: plugin exec_preprocessing_route reported an err: plugin exec_preprocessing_route reported an err: plugin tag match_ad_domain not defined" plugin=my_plain_server
panic: runtime error: index out of range [0] with length 0

goroutine 39 [running]:
github.com/IrineSistiana/mosdns/dispatcher/plugin/pipeline/cache.getMinimalTTL(0xc000162360, 0xd216c0)
        github.com/IrineSistiana/mosdns/dispatcher/plugin/pipeline/cache/cache.go:157 +0x1c5
github.com/IrineSistiana/mosdns/dispatcher/plugin/pipeline/cache.(*cachePipeLine).Connect(0xc0001660a0, 0xd216c0, 0xc001008000, 0xc000038040, 0xc000038480, 0x2, 0x2)
        github.com/IrineSistiana/mosdns/dispatcher/plugin/pipeline/cache/plugin.go:89 +0xeb
github.com/IrineSistiana/mosdns/dispatcher/handler.(*PipeContext).ExecNextPlugin(0xc000038480, 0xd216c0, 0xc001008000, 0xc000038040, 0xc0002cf630, 0x1)
        github.com/IrineSistiana/mosdns/dispatcher/handler/pipeline_plugin.go:56 +0x5ed
github.com/IrineSistiana/mosdns/dispatcher/plugin/router/pipeline.(*pipelineRouter).Do(0xc000005d20, 0xd216c0, 0xc001008000, 0xc000038040, 0xc000005d20, 0x0, 0x0, 0x0)
        github.com/IrineSistiana/mosdns/dispatcher/plugin/router/pipeline/pipeline.go:76 +0xf3
github.com/IrineSistiana/mosdns/dispatcher/handler.Walk(0xd216c0, 0xc001008000, 0xc000038040, 0xc00002a6c0, 0xd, 0xc001008000, 0xd21640)
        github.com/IrineSistiana/mosdns/dispatcher/handler/router_plugin.go:54 +0x1e9
github.com/IrineSistiana/mosdns/dispatcher/handler.(*DefaultServerHandler).ServeDNS(0xc0000057a0, 0xd216c0, 0xc001008000, 0xc000038040, 0xd11300, 0xc00374e080)
        github.com/IrineSistiana/mosdns/dispatcher/handler/server.go:45 +0x7a
github.com/IrineSistiana/mosdns/dispatcher/plugin/plain_server.(*singleServer).serveUDP.func1(0xd21640, 0xc000300080, 0xd11020, 0xc0000057a0, 0xc000038040, 0xc00374e080)
        github.com/IrineSistiana/mosdns/dispatcher/plugin/plain_server/udp.go:83 +0xbc
created by github.com/IrineSistiana/mosdns/dispatcher/plugin/plain_server.(*singleServer).serveUDP
        github.com/IrineSistiana/mosdns/dispatcher/plugin/plain_server/udp.go:80 +0x258
```

配置文件的结构如下：
```
route_ingress (sequence)  ---【执行 exec_preprocessing_route (sequence)】--->  sequence 执行完成，进入下一条路由
---> route_pipeline_main (pipeline) 

pipeline 内容如下：
  - _default_cache
  - set_ecs (function plugin)
  - bypass_local (sequence)
  - default_route (sequence)
```

我在配置时推断了很久的地方在于：如何在 pipeline 路由中添加类似 sequence 路由里的条件判断。
如果希望缓存请求应答，那么看起来有必要将处理请求的全部环节都放在 pipeline 路由中。但是同时我希望做到对国内域名和国外域名分别请求，Wiki 里没有见到支持 if 这样的语法，所以我就尝试着把 sequence 路由放在 pipeline 路由里执行了。

完整的配置文件如下，希望能帮忙指点哪里有问题。

---

```yaml
plugin:
  - tag: my_logger
    type: logger
    args:
      file: "./mosdns.log"
      level: warn
  - tag: my_plain_server
    type: plain_server
    args:
      entry: route_ingress
      listen:
        - udp://127.0.0.1:53
        - tcp://127.0.0.1:53
        - udp://[::1]:53
        - tcp://[::1]:53

  ################ 路由插件 #################

  - tag: exec_preprocessing_route
    type: sequence
    args:
      exec:
        - if:
            - match_hosts
          goto: _end
        - if:
            - match_ad_domain
          exec:
            - _block_with_nxdomain
          goto: _end
      next: ""

  - tag: route_ingress
    type: sequence
    args:
      exec:
        - exec_preprocessing_route
      next: "route_pipeline_main"

  - tag: route_pipeline_main        # 分流路由
    type: pipeline
    args:
      pipe: 
        - _default_cache            # 可以是 pipeline 插件，
        - set_ecs                   # 功能插件
        - bypass_local              # 路由插件
        - default_route
      next: "" # 下一个路由插件。

  - tag: bypass_local
    type: sequence
    args:
      exec:
        - if:
            - match_local_domain
          exec:
            - fallback_local
          goto: _end

      next: ""

  - tag: default_route
    type: sequence
    args:
      exec:
        - forward_cf
      next: ""

  ################ 匹配器插件 #################

  - tag: match_hosts
    type: hosts
    args:
      hosts: # hosts 文件。可配置多个。至少要配置一个。
        - ./mosdns-hosts.txt

  - tag: match_ad_domain   # 匹配广告域名
    type: domain_matcher
    args:
      check_cname: true
      check_question: true
      domain:
        - "./geosite.dat:category-ads-all"

  - tag: match_local_domain   # 匹配本地域名
    type: domain_matcher
    args:
      check_cname: true
      check_question: true
      domain:
        - "./geosite.dat:cn"

  - tag: match_non_local_domain   # 匹配非本地域名
    type: domain_matcher
    args:
      check_cname: true
      check_question: true
      domain:
        - "./geosite.dat:geolocation-!cn"

  ################# 功能性插件 ################

  - tag: set_ecs
    type: ecs
    args:
      auto: false # 是否自动将客户端地址作为 ECS 附加到请求。如果为 true，则预设地址不会被使用。
      force_overwrite: false  # 如果请求已有 ECS，是否覆盖。
      mask4: 24               # 用于 ipv4 地址的掩码。
      mask6: 32               # 用于 ipv6 地址的掩码。
      ipv4: "223.6.6.6:53"   # 预设的 ipv4 地址。如果非空，会附加在 A 请求中。
      ipv6: "2001:da8:223:5555:5555:5555:5555:5555"  # 预设的 ipv6 地址。如果非空，会附加在 AAAA 请求中。

  - tag: fallback_local
    type: fallback
    args:
      primary:            # 主要运行序列。可以是功能插件，路由插件。
        - set_ecs
        - forward_tuna_moe
      secondary:          # 次要运行序列。同上。
        - _no_ecs
        - fallback_with_plain_request
      stat_length: 10     # 统计长度。默认 10。
      threshold: 5        # 触发阈值。不可大于统计长度。默认 5。

  - tag: fallback_with_plain_request
    type: fast_forward
    args:
      upstream: # 上游服务器地址。至少要配置一个。如果配置了多个上游服务器，会同时请求，然后取最快返回的应答。
        - udp://223.5.5.5:53
        - udp://223.6.6.6:53

  - tag: forward_tuna_moe
    type: forward
    args:
      upstream:
        - addr: https://101.6.6.6:8443/resolve
      deduplicate: true
      insecure_skip_verify: false
      timeout: 10

  - tag: forward_cf # 转发至远程服务器
    type: forward
    args:
      upstream: # 上游服务器。可配置多个。至少要配置一个。
        - addr: https://1.0.0.1/dns-query
      deduplicate: true # 是否请求去重。
      insecure_skip_verify: false # 禁用 TLS 身份验证。
      timeout: 10 # 超时时间，单位: 秒。

```
