### ISSUE TITLE
blackhole IP 屏蔽 dig 测试不正常

### ISSUE THREAD

**Issue by IrineSistiana** [IrineSistiana/mosdns#182]
不用dnsmasq的话openwrt有一大票基于dnsmasq-full的插件用不了了呐，一些ip分流、广告过滤什么的。
我另外试了用替换ip的方式屏蔽aaaa
```yaml
- if_and:
    - '!query_is_local_domain'
    - _qtype_AAAA
  exec:
    - blockaaaa
    - _end

  - tag: 'blockaaaa'
    type: 'blackhole'
    args:
      rcode: 0
      ipv4: '127.0.0.1'
      ipv6: '::1'
```
但是用dig测试返回不正常
```shell
❯ dig @192.168.100.1 -t aaaa stackapps.com -p6553
;; Got bad packet: extra input data
72 bytes
d7 c9 81 00 00 01 00 01 00 00 00 00 09 73 74 61          .............sta
63 6b 61 70 70 73 03 63 6f 6d 00 00 1c 00 01 09          ckapps.com......
73 74 61 63 6b 61 70 70 73 03 63 6f 6d 00 00 01          stackapps.com...
00 01 00 00 0e 10 00 10 00 00 00 00 00 00 00 00          ................
00 00 00 00 00 00 00 01                                  ........
```

_Originally posted by @klever1988 in https://github.com/IrineSistiana/mosdns/discussions/181#discussioncomment-1452798_
