### ISSUE TITLE
[BUG] 命令行运行时日志中存在颜色代码

### ISSUE THREAD

**Issue by laggardkernel** [IrineSistiana/mosdns#19]
**出现了什么问题**

log 写入时保留了颜色代码，或者叫做 escape sequence。

```txt
[36mINFO[0m[0000] loading plugin chinadns_server               
```

想要输出的格式，没有颜色代码

```
time="2020-12-27T00:49:50+08:00" level=info msg="loading plugin chinadns_server"
time="2020-12-27T00:49:50+08:00" level=info msg="udp server started at 127.0.0.1:53000" plugin=chinadns_server
```

前者是通过在终端命令行启动，后者是通过配置 macOS launch daemon 启动。猜测输出内容会根据是否为交互终端而输出颜色代码，而不是根据输出对象是否为文本。

---

**如何重现**

mosdns 的版本号(`mosdns -v`)：v0.20.0-0-g41c6960

使用的启动参数或启动方式：`mosdns -c config.yaml`

操作系统和平台：macOS

使用的配置文件：

```yaml
plugin:
  - tag: my_logger
    type: logger
    args:
      file: "/usr/local/var/log/mosdns/mosdns.log"
      # file: ""
      level: info
      # level: debug
...
````
