### ISSUE TITLE
希望可以提供国内外分流DNS的配置模板或者教程，wiki看了之后不是很明白怎么配置

### ISSUE THREAD

**Issue by CCNano** [IrineSistiana/mosdns#2]
希望可以提供国内外分流DNS的配置模板或者教程，wiki看了之后不是很明白怎么配置

**Comment by Auska** [comment]
这是我使用的示例，就是简单按照黑名单区分
```
log:
    level: ""
    file: ""
server:
    bind:
        - udp://0.0.0.0:6053
    max_udp_size: 1472
entry:
    - "chn"
plugin:
    - tag: "china"
      type: forward
      args:
        deduplicate: false
        insecure_skip_verify: false
        next: ""
        timeout: 10
        upstream:
            - addr: 1.2.4.8:53
              ip_addr:
                - 1.2.4.8
            - addr: 114.114.114.114:53
              ip_addr:
                - 114.114.114.114
    - tag: "gfw"
      type: forward
      args:
        deduplicate: false
        insecure_skip_verify: false
        next: ""
        timeout: 10
        upstream:
            - addr: tls://8.8.8.8
              ip_addr:
                - 8.8.8.8
            - addr: tls://1.1.1.1
              ip_addr:
                - 1.1.1.1
    - tag: "chn"
      type: redirect_domain
      args:
        check_cname: false
        check_question: true
        domain:
            - "./chn_domain.list"
        next: "gfw"
        redirect: "china"
```
