### ISSUE TITLE
[Feature request] 自动获取 DNS 服务器地址

### ISSUE THREAD

**Issue by IrineSistiana** [IrineSistiana/mosdns#215]
目前的想法是 mosdns 会运行一个外部脚本，比如 linux 上是 sh。脚本返回 DNS 地址，比如读 `/etc/resolve.conf` 然后抠字符串。然后 mosdns 用返回的字符串作为地址。

---
目前对于 `.lan` 域名，需要转发给路由器下发的DNS，以支持解析到局域网内其他设备。有没有可能自定识别出上游DHCP下发的DNS地址？现在我只能写死这种地址，根据不同网络还要去更改它。

目前我知道 NetworkManager 会将DHCP DNS信息存盘
>  The original DNS servers can be found in /run/NetworkManager/no-stub-resolv.conf. 

Clash 好像也实现了这种功能 https://github.com/Dreamacro/clash/pull/1509

提供部分相关配置说明一下我要做什么

```yaml
  - tag: chinadns_entry
    type: sequence
    args:
      exec:
        - match_hosts
        - _default_cache
        - _single_flight
        ...
        - if:
          - match_lan_domain
          exec:
            - forward_dhcp
            - _end
          ...

  - tag: 'forward_dhcp'
    type: fast_forward
    args:
      upstream:
        - addr: udp://192.168.2.1:53
      timeout: 3
  - tag: match_lan_domain
    type: query_matcher
    args:
      logical_and: true
      domain:
        - 'domain:lan'
        # - 'regexp:.+\.lan\.?$'
      qtype: [1, 28]
      qclass: [1]
```

_Originally posted by @laggardkernel in https://github.com/IrineSistiana/mosdns/discussions/213_
