### ISSUE TITLE
[Feature request]load_balance衍生的一些问题

### ISSUE THREAD

**Issue by linusxiong** [IrineSistiana/mosdns#219]
load_balance实现了轮询访问上游的功能，但是可能同样造成了性能下降，与提升mosdns性能的初衷不符。
例如将原本的转发器拆分成多个，以及可能导致**idle_time失效**。

- 能否在使用load_balance的时候，第一个请求直接handle下所有的转发器，保持一致的idle_time？
- 这样无需在每一次请求都重新打开一个tcp请求，增加tcp连接复用的有效性。
- 并且这里的idle时间可以覆盖掉在转发器中设置的时间。

这是我的对于load_balance的一些微小的建议，感谢开发者的付出！

**Comment by IrineSistiana** [comment]
我觉得吧

- load_balance 只有在几乎一点流量都没有（几秒一个请求）的情况下才会导致 idletimeout 失效。
- 如果几乎一点流量都没有的话，为什么要 load_balance 呢.....

还有个问题。idle_timeout 这个参数虽然 mosdns 可以调大，但实际的 idle_timeout 还取决与服务器的设定。所以没有办法保持一致的 idle_timeout。即使 mosdns 刷新本地的 idle_timeout，如果 mosdns 不发送任何请求，服务器那边的 idle_timeout 不会重置，连接还是会失效。

**Comment by IrineSistiana** [comment]
我感觉除非触发上游限流，否则 load_balance 没啥必要。

**Comment by linusxiong** [comment]
> 我觉得吧
> 
> * load_balance 只有在几乎一点流量都没有（几秒一个请求）的情况下才会导致 idletimeout 失效。
> * 如果几乎一点流量都没有的话，为什么要 load_balance 呢.....
> 
> 还有个问题。idle_timeout 这个参数虽然 mosdns 可以调大，但实际的 idle_timeout 还取决与服务器的设定。所以没有办法保持一致的 idle_timeout。即使 mosdns 刷新本地的 idle_timeout，如果 mosdns 不发送任何请求，服务器那边的 idle_timeout 不会重置，连接还是会失效。

load_balance不是会轮流使用转发器嘛，转发完成收到了结果，其实并不会关闭这个tcp是吗？
我的理解是发送一个dns请求之后mosdns又换了一个转发器去发送请求，然后会关闭上一个tcp的请求，其实是两个都是会保持keepalive的吗？

**Comment by linusxiong** [comment]
> 我感觉除非触发上游限流，否则 load_balance 没啥必要。

确实是触发了限流，日志里很多context canceled，在15个小时里有33万个这样的报错

**Comment by IrineSistiana** [comment]
> load_balance不是会轮流使用转发器嘛，转发完成收到了结果，其实并不会关闭这个tcp是吗？
我的理解是发送一个dns请求之后mosdns又换了一个转发器去发送请求，然后会关闭上一个tcp的请求，其实是两个都是会保持keepalive的吗？

如果是你是用的 fast_forward 转发器。对。

> 确实是触发了限流，日志里很多context canceled，在15个小时里有33万个这样的报错

context canceled = 在规定时间内(你server 设的 timeout)没受到应答。不一定是触发限流了。一般大企的服务器限制都在1000+qps。不容易摸到上限。

**Comment by IrineSistiana** [comment]
忙猜你用了 udp 的上游?

**Comment by linusxiong** [comment]
> > load_balance不是会轮流使用转发器嘛，转发完成收到了结果，其实并不会关闭这个tcp是吗？
> > 我的理解是发送一个dns请求之后mosdns又换了一个转发器去发送请求，然后会关闭上一个tcp的请求，其实是两个都是会保持keepalive的吗？
> 
> 如果是你是用的 fast_forward 转发器。对。
> 
> > 确实是触发了限流，日志里很多context canceled，在15个小时里有33万个这样的报错
> 
> context canceled = 在规定时间内(你server 设的 timeout)没受到应答。不一定是触发限流了。一般大企的服务器限制都在1000+qps。不容易摸到上限。

实际上使用dnsperf进行压测的真实qps腾讯是在300左右，阿里是在500左右，谷歌在800左右，这是udp的数据

**Comment by linusxiong** [comment]
> 忙猜你用了 udp 的上游?

不是，全是tls

**Comment by IrineSistiana** [comment]
那确实可能是限流了。

**Comment by linusxiong** [comment]
> > 忙猜你用了 udp 的上游?
> 
> 不是，全是tls

同环境不同配置文件的环境下，开启load_balance比不使用的情况压测性能低了3倍

**Comment by linusxiong** [comment]
```
  - tag: if_sequence
    type: sequence
    args:
      exec:
        - if:
            - query_is_local_domain
          exec:
            - load_banlance_domestic
            - _end

        - if:
            - query_is_non_local_domain  # 已知的非cn域名
          exec:
            - load_banlance_oversea             # 用google服务器
            - _end

        - load_banlance_domestic               # 先请求转发至本地服务器
        - if:
            - response_has_local_ip   # 如果应答包含cn IP
          exec:
            - _end                    # 就直接采用结果
        - load_banlance_oversea             # 否则去请求google服务器的结果

  - tag: load_banlance_domestic
    type: sequence
    args:
      exec:
        - load_balance:
            - - 'forward_domestic_0'
              - 'change_ttl'
            - - 'forward_domestic_1'
              - 'change_ttl'
            - - 'forward_domestic_2'
              - 'change_ttl'

  - tag: load_banlance_oversea
    type: sequence
    args:
      exec:
        - load_balance:
            - - 'forward_oversea_0'
              - 'change_ttl'
            - - 'forward_oversea_1'
              - 'change_ttl'
            - - 'forward_oversea_2'
              - 'change_ttl'
            - - 'forward_oversea_3'
              - 'change_ttl'
# 匹配本地域名的插件
  - tag: query_is_local_domain
    type: query_matcher
    args:
      domain:
        - 'ext:./geosite.dat:cn'
        - 'ext:./geosite.dat:apple@cn'
  # 匹配非本地域名的插件
  - tag: query_is_non_local_domain
    type: query_matcher
    args:
      domain:
        - 'ext:./geosite.dat:geolocation-!cn'

  # 匹配本地 IP 的插件
  - tag: response_has_local_ip
    type: response_matcher
    args:
      ip:
        - 'ext:./geoip.dat:cn'

  # 添加ECS的插件
  - tag: ecs
    type: ecs
    args:
      auto: true
  # 设置bufsize
  - tag: 'set_bufsize'
    type: 'bufsize'
    args:
      size: 1232
  # 缓存插件
  - tag: cache
    type: cache
    argus: 
      size: 100000
      lazy_cache_ttl: 86400
      lazy_cache_reply_ttl: 100
  # 修改TTL插件
  - tag: 'change_ttl'
    type: 'ttl'
    args:
      minimal_ttl: 600  # 最小TTL。如果非零，小于这个数的应答的TTL会被修改成这个值。
      maximum_ttl: 3600 # 最大TTL。如果非零，大于这个数的应答的TTL会被修改成这个值。
  # 转发插件
  # 国外转发，拆分为了负载均衡
  - tag: forward_oversea_0
    type: fast_forward
    args:
      upstream:
       - addr: 'tls://one.one.one.one'
         dial_addr: '1.0.0.1:853'
         trusted: true
         idle_timeout: 120
         max_conns: 1000
         insecure_skip_verify: true
      timeout: 10
  - tag: forward_oversea_1
    type: fast_forward
    args:
      upstream:
       - addr: 'tls://one.one.one.one'
         dial_addr: '1.1.1.1:853'
         trusted: true
         idle_timeout: 120
         max_conns: 1000
         insecure_skip_verify: true
      timeout: 10
  - tag: forward_oversea_2
    type: fast_forward
    args:
      upstream:
       - addr: 'tls://dns.google'
         dial_addr: '8.8.8.8:853'
         trusted: true
         idle_timeout: 120
         max_conns: 1000
         insecure_skip_verify: true
      timeout: 10
  - tag: forward_oversea_3
    type: fast_forward
    args:
      upstream:
       - addr: 'tls://dns.google'
         dial_addr: '8.8.4.4:853'
         trusted: true
         idle_timeout: 120
         max_conns: 1000
         insecure_skip_verify: true
      timeout: 10


# 国内转发，拆分为了负载均衡
  - tag: forward_domestic_0
    type: fast_forward
    args:
      upstream:
        - addr: 'tls://dot.pub'
          dial_addr: '1.12.34.56:853'
          trusted: true
          idle_timeout: 120
          max_conns: 1000
          insecure_skip_verify: true
      timeout: 10
  - tag: forward_domestic_1
    type: fast_forward
    args:
      upstream:
        - addr: 'tls://dot.pub'
          dial_addr: '162.14.21.56:853'
          trusted: true
          idle_timeout: 120
          max_conns: 1000
          insecure_skip_verify: true
      timeout: 10
  - tag: forward_domestic_2
    type: fast_forward
    args:
      upstream: 
        - addr: 'tls://dot.pub'
          dial_addr: '162.14.21.178:853'
          trusted: true
          idle_timeout: 120
          max_conns: 1000
          insecure_skip_verify: true
      timeout: 10
```
