### ISSUE TITLE
[配置] 初次使用,测试显示超时

### ISSUE THREAD

**Issue by xfoxtbat** [IrineSistiana/mosdns#225]
**出现了什么问题**

简要描述一下问题的表现，以及执行了什么操作导致了问题的出现：

 % dig @192.168.50.112 baidu.com

; <<>> DiG 9.10.6 <<>> @192.168.50.112 baidu.com
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached

想测试dns是否可用 显示超时

看程序正常开启了

mosdns 的 log 记录:

2021-12-29T11:07:55.042+0800    info    v2/main.go:222  mosdns ver: v2.2.2-0-g492ec7f
2021-12-29T11:07:55.042+0800    info    v2/main.go:223  arch: amd64, os: linux, go: go1.17.5
2021-12-29T11:07:55.042+0800    info    coremain/run.go:67      loading config  {"file": "/etc/mosdns/config.yaml"}
2021-12-29T11:07:55.043+0800    info    coremain/run.go:104     loading plugin  {"tag": "main_server"}
2021-12-29T11:07:55.043+0800    info    coremain/run.go:104     loading plugin  {"tag": "main_sequence"}
2021-12-29T11:07:55.043+0800    info    coremain/run.go:104     loading plugin  {"tag": "mem_cache"}
2021-12-29T11:07:55.043+0800    info    coremain/run.go:104     loading plugin  {"tag": "modify_ttl"}
2021-12-29T11:07:55.043+0800    info    coremain/run.go:104     loading plugin  {"tag": "forward_local"}
2021-12-29T11:07:55.043+0800    info    coremain/run.go:104     loading plugin  {"tag": "forward_remote"}
2021-12-29T11:07:55.043+0800    info    coremain/run.go:104     loading plugin  {"tag": "query_is_local_domain"}
2021-12-29T11:07:55.104+0800    info    query_is_local_domain   query_matcher/query_matcher.go:94       domain matcher loaded   {"length": 69341}
2021-12-29T11:07:55.104+0800    info    coremain/run.go:104     loading plugin  {"tag": "query_is_non_local_domain"}
2021-12-29T11:07:55.113+0800    info    query_is_non_local_domain       query_matcher/query_matcher.go:94       domain matcher loaded   {"length": 35547}
2021-12-29T11:07:55.113+0800    info    coremain/run.go:104     loading plugin  {"tag": "response_has_local_ip"}
2021-12-29T11:07:55.209+0800    info    response_has_local_ip   response_matcher/response_matcher.go:92 ip matcher loaded       {"length": 11562}
2021-12-29T11:07:55.209+0800    info    coremain/run.go:42      all plugins are successfully loaded

```

---

**环境**

描述一下问题出现的环境，便于复现以更快定位问题。必须包含：

mosdns 的版本号(`mosdns -v`)：v2.2.2-0

操作系统和平台：debab

使用的配置文件：Debian

<!-- 将配置文件复制到下面的框里 -->
log:
  level: info
  file: ''

plugin:

  ################# 服务插件 ################

  # 启动服务器的插件
  - tag: main_server
    type: server
    args:
      entry:
        - mem_cache       # 启用缓存
        - main_sequence   # 运行主执行序列
        - modify_ttl      # 修改 ttl
      server:
        - protocol: udp
          addr: 127.0.0.1:53
        - protocol: tcp
          addr: 127.0.0.1:53
        - protocol: udp
          addr: '[::1]:53'
        - protocol: tcp
          addr: '[::1]:53'
  
  ################# 可执行插件 ################

  # 包含分流的逻辑的插件
  - tag: main_sequence
    type: sequence
    args:
      exec:
        - if:
            - query_is_local_domain   # 已知的本地域名
            - '!_query_is_common'     # 和不常见的请求类型
          exec:
            - forward_local           # 用本地服务器
            - _end

        - if:
            - query_is_non_local_domain  # 已知的非本地域名
          exec:
            - _prefer_ipv4               # 优先 IPv4
            - forward_remote             # 用远程服务器
            - _end

        # 剩下的未知域名用 IP 分流。详细分流原理请参考 `fallback` 的工作流程。
        - primary:
            - forward_local
            - if:
                - '!response_has_local_ip'
              exec:
                - _drop_response
          secondary:
            - _prefer_ipv4
            - forward_remote
          fast_fallback: 200  # 这里建议设置成 local 服务器正常延时的 2~5 倍。
                              # 这个延时保证了 local 延时偶尔变高时，其结果不会被 remote 抢答。
                              # 如果 local 超过这个延时还没响应，可以假设 local 出现了问题。
                              # 这时用就采用 remote 的应答。单位: 毫秒。
          always_standby: true

  # 缓存
  - tag: 'mem_cache'
    type: 'cache'
    args:
      size: 1024

  # 修改应答 ttl
  - tag: 'modify_ttl'
    type: 'ttl'
    args:
      minimal_ttl: 300 
      maximum_ttl: 3600

  # 转发请求至本地服务器的插件
  - tag: forward_local
    type: forward
    args:
      upstream:
        - addr: 119.29.29.29
        - addr: 223.5.5.5
        - addr: 114.114.114.114
        - addr: 202.106.0.20
        - addr: https://dh-dns.global-idc.net/dns-query


  # 转发请求至远程服务器的插件
  - tag: forward_remote
    type: forward
    args:
      upstream:
        - addr: https://1.1.1.1/dns-query
        - addr: 8.8.8.8
        - addr: 1.1.1.1
        - addr: https://dns.google/dns-query
        - addr: https://dns11.quad9.net/dns-query

  ################ 匹配器插件 #################

  # 匹配本地域名的插件
  - tag: query_is_local_domain
    type: query_matcher
    args:
      domain:
        - 'ext:/etc/mosdns/geosite.dat:cn'

  # 匹配非本地域名的插件
  - tag: query_is_non_local_domain
    type: query_matcher
    args:
      domain:
        - 'ext:/etc/mosdns/geosite.dat:geolocation-!cn'

  # 匹配本地 IP 的插件
  - tag: response_has_local_ip
    type: response_matcher
    args:
      ip:
        - 'ext:/etc/mosdns/geoip.dat:cn'
````
