### ISSUE TITLE
[BUG] v0.21.0 的缓存问题

### ISSUE THREAD

**Issue by rampageX** [IrineSistiana/mosdns#23]
**出现了什么问题**

使用 wiki 的示例配置，多次查询发现缓存似乎并未生效？调试信息里面也看不上到缓存命中直接返回的相关信息。

```txt
time="2020-12-30T11:58:53+08:00" level=debug msg="[{twitter.com. 1 1}], id: 13798, t: 0 ms, from: udp://127.0.0.1:31243: exec context plugin _default_cache" func="github.com/IrineSistiana/mosdns/dispatcher/handler.(*PipeContext).ExecNextPlugin" file="github.com/IrineSistiana/mosdns/dispatcher/handler/context_plugin.go:54" plugin=pipeline
time="2020-12-30T11:58:53+08:00" level=debug msg="[{twitter.com. 1 1}], id: 13798, t: 0 ms, from: udp://127.0.0.1:31243: exec executable plugin main_sequence" func="github.com/IrineSistiana/mosdns/dispatcher/handler.(*PipeContext).ExecNextPlugin" file="github.com/IrineSistiana/mosdns/dispatcher/handler/context_plugin.go:57" plugin=pipeline
time="2020-12-30T11:58:53+08:00" level=debug msg="[{twitter.com. 1 1}], id: 13798, t: 0 ms, from: udp://127.0.0.1:31243: exec matcher plugin match_ad_domain, returned: false" func="github.com/IrineSistiana/mosdns/dispatcher/handler.(*ifBlock).ExecCmd" file="github.com/IrineSistiana/mosdns/dispatcher/handler/executable_plugin.go:108" plugin=main_sequence
time="2020-12-30T11:58:53+08:00" level=debug msg="[{twitter.com. 1 1}], id: 13798, t: 1 ms, from: udp://127.0.0.1:31243: exec matcher plugin match_local_domain, returned: false" func="github.com/IrineSistiana/mosdns/dispatcher/handler.(*ifBlock).ExecCmd" file="github.com/IrineSistiana/mosdns/dispatcher/handler/executable_plugin.go:108" plugin=main_sequence
time="2020-12-30T11:58:53+08:00" level=debug msg="[{twitter.com. 1 1}], id: 13798, t: 1 ms, from: udp://127.0.0.1:31243: exec matcher plugin _query_type_is_unusual, returned: false" func="github.com/IrineSistiana/mosdns/dispatcher/handler.(*ifBlock).ExecCmd" file="github.com/IrineSistiana/mosdns/dispatcher/handler/executable_plugin.go:108" plugin=main_sequence
time="2020-12-30T11:58:53+08:00" level=debug msg="[{twitter.com. 1 1}], id: 13798, t: 1 ms, from: udp://127.0.0.1:31243: exec matcher plugin match_non_local_domain, returned: true" func="github.com/IrineSistiana/mosdns/dispatcher/handler.(*ifBlock).ExecCmd" file="github.com/IrineSistiana/mosdns/dispatcher/handler/executable_plugin.go:108" plugin=main_sequence
time="2020-12-30T11:58:53+08:00" level=debug msg="[{twitter.com. 1 1}], id: 13798, t: 1 ms, from: udp://127.0.0.1:31243: exec plugin forward_remote" func=github.com/IrineSistiana/mosdns/dispatcher/handler.executablePluginTag.ExecCmd file="github.com/IrineSistiana/mosdns/dispatcher/handler/executable_plugin.go:72" plugin=main_sequence
time="2020-12-30T11:58:53+08:00" level=debug msg="[{twitter.com. 1 1}], id: 13798, t: 169 ms, from: udp://127.0.0.1:31243: goto plugin _end" func="github.com/IrineSistiana/mosdns/dispatcher/handler.(*ExecutableCmdSequence).Exec" file="github.com/IrineSistiana/mosdns/dispatcher/handler/executable_plugin.go:204" plugin=main_sequence
time="2020-12-30T11:58:57+08:00" level=debug msg="[{twitter.com. 1 1}], id: 25131, t: 0 ms, from: udp://127.0.0.1:28551: exec context plugin _default_cache" func="github.com/IrineSistiana/mosdns/dispatcher/handler.(*PipeContext).ExecNextPlugin" file="github.com/IrineSistiana/mosdns/dispatcher/handler/context_plugin.go:54" plugin=pipeline
time="2020-12-30T11:58:57+08:00" level=debug msg="[{twitter.com. 1 1}], id: 25131, t: 0 ms, from: udp://127.0.0.1:28551: exec executable plugin main_sequence" func="github.com/IrineSistiana/mosdns/dispatcher/handler.(*PipeContext).ExecNextPlugin" file="github.com/IrineSistiana/mosdns/dispatcher/handler/context_plugin.go:57" plugin=pipeline
time="2020-12-30T11:58:57+08:00" level=debug msg="[{twitter.com. 1 1}], id: 25131, t: 0 ms, from: udp://127.0.0.1:28551: exec matcher plugin match_ad_domain, returned: false" func="github.com/IrineSistiana/mosdns/dispatcher/handler.(*ifBlock).ExecCmd" file="github.com/IrineSistiana/mosdns/dispatcher/handler/executable_plugin.go:108" plugin=main_sequence
time="2020-12-30T11:58:57+08:00" level=debug msg="[{twitter.com. 1 1}], id: 25131, t: 0 ms, from: udp://127.0.0.1:28551: exec matcher plugin match_local_domain, returned: false" func="github.com/IrineSistiana/mosdns/dispatcher/handler.(*ifBlock).ExecCmd" file="github.com/IrineSistiana/mosdns/dispatcher/handler/executable_plugin.go:108" plugin=main_sequence
time="2020-12-30T11:58:57+08:00" level=debug msg="[{twitter.com. 1 1}], id: 25131, t: 1 ms, from: udp://127.0.0.1:28551: exec matcher plugin _query_type_is_unusual, returned: false" func="github.com/IrineSistiana/mosdns/dispatcher/handler.(*ifBlock).ExecCmd" file="github.com/IrineSistiana/mosdns/dispatcher/handler/executable_plugin.go:108" plugin=main_sequence
time="2020-12-30T11:58:57+08:00" level=debug msg="[{twitter.com. 1 1}], id: 25131, t: 1 ms, from: udp://127.0.0.1:28551: exec matcher plugin match_non_local_domain, returned: true" func="github.com/IrineSistiana/mosdns/dispatcher/handler.(*ifBlock).ExecCmd" file="github.com/IrineSistiana/mosdns/dispatcher/handler/executable_plugin.go:108" plugin=main_sequence
time="2020-12-30T11:58:57+08:00" level=debug msg="[{twitter.com. 1 1}], id: 25131, t: 1 ms, from: udp://127.0.0.1:28551: exec plugin forward_remote" func=github.com/IrineSistiana/mosdns/dispatcher/handler.executablePluginTag.ExecCmd file="github.com/IrineSistiana/mosdns/dispatcher/handler/executable_plugin.go:72" plugin=main_sequence
time="2020-12-30T11:58:57+08:00" level=debug msg="[{twitter.com. 1 1}], id: 25131, t: 169 ms, from: udp://127.0.0.1:28551: goto plugin _end" func="github.com/IrineSistiana/mosdns/dispatcher/handler.(*ExecutableCmdSequence).Exec" file="github.com/IrineSistiana/mosdns/dispatcher/handler/executable_plugin.go:204" plugin=main_sequence
```
dig 查询时间，第二次和第一次时间一样为 168ms：（如果更换为国内常见域名，第一次查询时间会很短，比如 12ms，但是之后的查询保持为 10几ms，而不是缓存生效时通常的个位数甚至 0ms）

```
root@N1-U20:~# digg -p 66 twitter.com

; <<>> DiG 9.16.1-Ubuntu <<>> -p 66 twitter.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 13798
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;twitter.com.			IN	A

;; ANSWER SECTION:
twitter.com.		192	IN	A	104.244.42.1 [美国 Twitter公司]

;; Query time: 168 msec
;; SERVER: 127.0.0.1 [本机地址]#66(127.0.0.1 [本机地址])
;; WHEN: Wed Dec 30 11:58:53 CST 2020
;; MSG SIZE  rcvd: 67

root@N1-U20:~# digg -p 66 twitter.com

; <<>> DiG 9.16.1-Ubuntu <<>> -p 66 twitter.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 25131
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;twitter.com.			IN	A

;; ANSWER SECTION:
twitter.com.		189	IN	A	104.244.42.1 [美国 Twitter公司]

;; Query time: 168 msec
;; SERVER: 127.0.0.1 [本机地址]#66(127.0.0.1 [本机地址])
;; WHEN: Wed Dec 30 11:58:57 CST 2020
;; MSG SIZE  rcvd: 67
```

---

**如何重现**

描述一下如何重现该问题。请尽可能的包含：

mosdns 的版本号(`mosdns -v`)： v0.21.0-0-gcce303d

使用的启动参数或启动方式：mosdns -c /root/cfg/mosdns_s.yaml

操作系统和平台： Linux N1-U20 5.9.0-arm-64 #20.10 SMP PREEMPT Wed Oct 14 12:04:42 MSK 2020 aarch64 aarch64 aarch64 GNU/Linux

进行了什么操作导致了问题的出现：

使用的配置文件：

```yaml
plugin:
  - tag: log        # 日志
    type: logger 
    args:
      no_color: true
      level: debug

  - tag: main_server    # 启动服务器
    type: server
    args:
      entry: pipeline
      max_concurrent_queries: 0
      server:
        - protocol: udp
          addr: 0.0.0.0:66
        - protocol: tcp
          addr: 0.0.0.0:66

  ################# 可执行插件 ################

  - tag: pipeline
    type: pipeline
    args:
      pipe:
        - _default_cache          # 缓存
        - main_sequence           # 处理请求的主要执行序列

  - tag: main_sequence
    type: sequence
    args:
      exec:
        - if:
            - match_ad_domain       # 处理已知的广告域名
          exec:
            - _block_with_nxdomain  # 屏蔽
          goto: _end

        - if:
            - match_local_domain      # 处理已知的本地域名
            - _query_type_is_unusual  # 和不常见的请求类型
          exec:
            - forward_local
          goto: _end

        - if:
            - match_non_local_domain  # 处理已知的非本地域名
          exec:
            - forward_remote
          goto: _end

        - sequence_bypass_local       # 分流未知域名。有两种方案：顺序或并行。这是顺序执行。
      # - parallel_bypass_local       # 如果想用类似 ChinaDNS 的并发分流逻辑。用这个。

  - tag: sequence_bypass_local        # 顺序执行的分流逻辑
    type: sequence
    args:
      exec:
        - forward_local               # 先请求转发至本地服务器
        - if:
            - match_local_ip          # 如果应答包含本地 IP
          goto: _end                  # 就直接采用结果
        - forward_remote              # 否则用远程服务器的结果

  - tag: parallel_bypass_local        # 并发执行的分流的逻辑
    type: parallel
    args:
      exec:
        - - forward_local             # 并发请求本地和远程服务器
          - if:
              - !match_local_ip       # 本地服务器返回的非本地 IP 的应答会被丢弃
            exec:
              - _drop_response
        - - forward_remote

  - tag: forward_local # 转发至本地服务器的插件
    type: forward
    args:
      upstream:
        - addr: https://223.5.5.5/dns-query

  - tag: forward_remote # 转发至远程服务器的插件
    type: forward
    args:
      upstream:
        - addr: https://1.1.1.1/dns-query

  ################ 匹配器插件 #################

  - tag: match_local_domain   # 匹配本地域名的插件
    type: domain_matcher
    args:
      check_cname: false
      check_question: true
      domain:
        - "/root/cfg/geosite.dat:cn"

  - tag: match_non_local_domain   # 匹配非本地域名的插件
    type: domain_matcher
    args:
      check_cname: false
      check_question: true
      domain:
        - "/root/cfg/geosite.dat:geolocation-!cn"

  - tag: match_local_ip       # 匹配本地 IP的插件
    type: ip_matcher
    args:
      match_client: false
      match_response: true
      ip:
        - "/root/cfg/geoip.dat:cn"

  - tag: match_ad_domain   # 匹配广告域名的插件
    type: domain_matcher
    args:
      check_cname: false
      check_question: true
      domain:
        - "/root/cfg/geosite.dat:category-ads-all"

include: [ ]
````
