### ISSUE TITLE
[BUG]日志中大量出现udp read err	{"error": "dns: overflow unpacking opt"}

### ISSUE THREAD

**Issue by loarland** [IrineSistiana/mosdns#231]
**出现了什么问题**

日志中大量出现下面这种报错信息是什么原因？
我是在openwrt的dns转发中填写10.10.10.3#6153来调用mosdns的

mosdns 的 log 记录:

2021-12-30T06:22:15.587Z	warn	server	server/udp.go:69	udp read err	{"error": "dns: overflow unpacking opt"}
2021-12-30T06:22:15.793Z	warn	server	server/udp.go:69	udp read err	{"error": "dns: overflow unpacking opt"}
2021-12-30T06:22:16.001Z	warn	server	server/udp.go:69	udp read err	{"error": "dns: overflow unpacking opt"}
2021-12-30T06:22:16.208Z	warn	server	server/udp.go:69	udp read err	{"error": "dns: overflow unpacking opt"}
2021-12-30T06:22:16.415Z	warn	server	server/udp.go:69	udp read err	{"error": "dns: overflow unpacking opt"}
2021-12-30T06:22:16.622Z	warn	server	server/udp.go:69	udp read err	{"error": "dns: overflow unpacking opt"}
2021-12-30T06:22:16.829Z	warn	server	server/udp.go:69	udp read err	{"error": "dns: overflow unpacking opt"}
2021-12-30T06:22:17.036Z	warn	server	server/udp.go:69	udp read err	{"error": "dns: overflow unpacking opt"}
2021-12-30T06:22:17.243Z	warn	server	server/udp.go:69	udp read err	{"error": "dns: overflow unpacking opt"}
2021-12-30T06:22:17.449Z	warn	server	server/udp.go:69	udp read err	{"error": "dns: overflow unpacking opt"}
2021-12-30T06:22:17.655Z	warn	server	server/udp.go:69	udp read err	{"error": "dns: overflow unpacking opt"}
2021-12-30T06:22:17.862Z	warn	server	server/udp.go:69	udp read err	{"error": "dns: overflow unpacking opt"}
2021-12-30T06:22:18.070Z	warn	server	server/udp.go:69	udp read err	{"error": "dns: overflow unpacking opt"}
2021-12-30T06:22:18.277Z	warn	server	server/udp.go:69	udp read err	{"error": "dns: overflow unpacking opt"}
2021-12-30T06:22:18.485Z	warn	server	server/udp.go:69	udp read err	{"error": "dns: overflow unpacking opt"}
2021-12-30T06:22:18.628Z	warn	server	server/udp.go:69	udp read err	{"error": "dns: overflow unpacking opt"}
2021-12-30T06:22:18.628Z	warn	server	server/udp.go:69	udp read err	{"error": "dns: overflow unpacking opt"}
2021-12-30T06:22:18.628Z	warn	server	server/udp.go:69	udp read err	{"error": "dns: overflow unpacking opt"}
2021-12-30T06:22:18.628Z	warn	server	server/udp.go:69	udp read err	{"error": "dns: overflow unpacking opt"}
2021-12-30T06:22:18.628Z	warn	server	server/udp.go:69	udp read err	{"error": "dns: overflow unpacking opt"}
2021-12-30T06:22:28.777Z	warn	server	server/udp.go:69	udp read err	{"error": "dns: overflow unpacking opt"}
2021-12-30T06:22:28.983Z	warn	server	server/udp.go:69	udp read err	{"error": "dns: overflow unpacking opt"}
2021-12-30T06:22:29.190Z	warn	server	server/udp.go:69	udp read err	{"error": "dns: overflow unpacking opt"}
2021-12-30T06:22:29.398Z	warn	server	server/udp.go:69	udp read err	{"error": "dns: overflow unpacking opt"}
2021-12-30T06:22:29.605Z	warn	server	server/udp.go:69	udp read err	{"error": "dns: overflow unpacking opt"}
2021-12-30T06:22:29.812Z	warn	server	server/udp.go:69	udp read err	{"error": "dns: overflow unpacking opt"}
2021-12-30T06:22:30.019Z	warn	server	server/udp.go:69	udp read err	{"error": "dns: overflow unpacking opt"}
**环境**

描述一下问题出现的环境，便于复现以更快定位问题。必须包含：

mosdns 的版本号(`mosdns -v`)：2.2.2

操作系统和平台：ubuntu 20.04

使用的配置文件：

````
log:
  level: debug
  file: "/moddns.log"

plugin:
  - tag: server
    type: server
    args:
      entry:
        - mem_cache
        - forward_cn
        - modify_ttl
      server:
        - addr: :6153
          protocol: udp
        # - addr: :6153
        #   protocol: tcp

  - tag: forward_cn
    type: forward
    args:
      upstream:
        - addr: '114.114.114.114'
        - addr: '223.5.5.5'
        - addr: '61.139.2.69'
        - addr: 'https://doh.pub/dns-query'
          ip_addr:
            - '119.29.29.29'
          trusted: true
        - addr: 'https://dns.google/dns-query' # 必需。服务器地址。
          ip_addr:  # 当服务器地址为域名时，手动指定服务器的 IP 地址。可以配置多个。
                # 如果配置了，则不会使用 bootstrap 服务器。
            - '8.8.8.8'
            # - '2001:4860:4860::8888'
          trusted: true # 是否是可信服务器。mosdns 的移植功能，说明详见 `fast_forward` 插件。
        - addr: 'https://1.1.1.1/dns-query'
          ip_addr:
            - '1.1.1.1'
            # - '2606:4700:4700::1111'
          trusted: true
      bootstrap:
        - 'tls://1.1.1.1'
        - 'https://223.5.5.5/dns-query'
      timeout: 5          # 请求超时时间，单位: 秒。
      fastest_ip: false   # 最快 IP 模式。测试所有解析到的 IP 的延时，然后仅返回延时最低的。
                      # (注意: 测试需要时间，启用这个功能会导致 DNS 响应时间变长，可能很长。)
      insecure_skip_verify: false  # 禁用 TLS 身份验证。

  - tag: 'mem_cache'
    type: 'cache'
    args:
      size: 8192

  - tag: 'modify_ttl'
    type: 'ttl'
    args:
      minimal_ttl: 300
      maximum_ttl: 3600
````
