### ISSUE TITLE
[BUG] linux平台不支持原本的hosts文件

### ISSUE THREAD

**Issue by aa51513** [IrineSistiana/mosdns#237]
**出现了什么问题**
配置文件里type: 'hosts'直接引用/etc/hosts文件，无法启动

简要描述一下问题的表现，以及执行了什么操作导致了问题的出现：

我想让mosdns直接用我本地hosts文件里面的记录，找不到再去调用dns服务器查询
配置了type: 'hosts'直接引用/etc/hosts文件，启动报错

mosdns 的 log 记录:

```txt
load plugin  query_hosts: failed to init plugin [query_hosts], failed to load entry ext:/etc/hosts: line 1: invalid ip addr localhost"}
```

---

**环境**

描述一下问题出现的环境，便于复现以更快定位问题。必须包含：

mosdns 的版本号(`mosdns -v`)：
v2.2.2

操作系统和平台：Linux x86_64

使用的配置文件：

```yaml
plugin:
  - tag: 'query_hosts'
    type: 'hosts'
    args:
      hosts:
        - 'ext:/etc/hosts'
````
