### ISSUE TITLE
[BUG] 3.0.0隔一段时间就崩溃

### ISSUE THREAD

**Issue by christaikobo** [IrineSistiana/mosdns#240]
正常使用，每隔一段时间就崩溃，5-15分钟不等
原设置在2.0.0一切正常

mosdns 的 log 记录:

```
Thu Jan  6 18:51:26 2022 daemon.err mosdns[10966]: panic: runtime error: index out of range [0] with length 0
Thu Jan  6 18:51:26 2022 daemon.err mosdns[10966]:
Thu Jan  6 18:51:26 2022 daemon.err mosdns[10966]: goroutine 2324 [running]:
Thu Jan  6 18:51:26 2022 daemon.err mosdns[10966]: github.com/AdguardTeam/dnsproxy/fastip.(*FastestAddr).ExchangeFastest(0xc00014ccf0, 0xc000103ef0, {0xc00012b500, 0xbf0420, 0xd8a998})
Thu Jan  6 18:51:26 2022 daemon.err mosdns[10966]: 	github.com/AdguardTeam/dnsproxy@v0.40.3/fastip/fastest.go:69 +0x1bc
Thu Jan  6 18:51:26 2022 daemon.err mosdns[10966]: github.com/IrineSistiana/mosdns/v3/dispatcher/plugin/executable/forward.(*forwardPlugin).exec(0xc0001c8bd0, {0xd85398, 0xc00237abc0}, 0xc000030690)
Thu Jan  6 18:51:26 2022 daemon.err mosdns[10966]: 	github.com/IrineSistiana/mosdns/v3/dispatcher/plugin/executable/forward/forward.go:162 +0x78
Thu Jan  6 18:51:26 2022 daemon.err mosdns[10966]: github.com/IrineSistiana/mosdns/v3/dispatcher/plugin/executable/forward.(*forwardPlugin).Exec(0x12bdda0, {0xd85398, 0xc00237abc0}, 0xc0004dfc98, {0x0, 0x0})
Thu Jan  6 18:51:26 2022 daemon.err mosdns[10966]: 	github.com/IrineSistiana/mosdns/v3/dispatcher/plugin/executable/forward/forward.go:150 +0x32
Thu Jan  6 18:51:26 2022 daemon.err mosdns[10966]: github.com/IrineSistiana/mosdns/v3/dispatcher/handler.(*PluginWrapper).exec(0xc0001c8cc0, {0xd85398, 0xc00237abc0}, 0xc000117b80, {0x0, 0x0})
Thu Jan  6 18:51:26 2022 daemon.err mosdns[10966]: 	github.com/IrineSistiana/mosdns/v3/dispatcher/handler/plugin_wrapper.go:93 +0x97
Thu Jan  6 18:51:26 2022 daemon.err mosdns[10966]: github.com/IrineSistiana/mosdns/v3/dispatcher/handler.(*PluginWrapper).Exec(0xc0001c8cc0, {0xd85398, 0xc00237abc0}, 0xc000030690, {0x0, 0x0})
Thu Jan  6 18:51:26 2022 daemon.err mosdns[10966]: 	github.com/IrineSistiana/mosdns/v3/dispatcher/handler/plugin_wrapper.go:77 +0x285
Thu Jan  6 18:51:26 2022 daemon.err mosdns[10966]: github.com/IrineSistiana/mosdns/v3/dispatcher/pkg/executable_seq.RefExecPluginNode.Exec({0xc0000b2468, 0x15}, {0xd85398, 0xc00237abc0}, 0x1, {0x0, 0x0})
Thu Jan  6 18:51:26 2022 daemon.err mosdns[10966]: 	github.com/IrineSistiana/mosdns/v3/dispatcher/pkg/executable_seq/executable_cmd_sequence.go:42 +0x6f
Thu Jan  6 18:51:26 2022 daemon.err mosdns[10966]: github.com/IrineSistiana/mosdns/v3/dispatcher/handler.ExecChainNode({0xd85398, 0xc00237abc0}, 0xc0002217a0, {0xd8aa18, 0xc0001c8960})
Thu Jan  6 18:51:26 2022 daemon.err mosdns[10966]: 	github.com/IrineSistiana/mosdns/v3/dispatcher/handler/utils.go:28 +0x7b
Thu Jan  6 18:51:26 2022 daemon.err mosdns[10966]: github.com/IrineSistiana/mosdns/v3/dispatcher/pkg/executable_seq.(*FallbackNode).doPrimary(0xc0000b9f00, {0xd85398, 0xc00237abc0}, 0xc000030690)
Thu Jan  6 18:51:26 2022 daemon.err mosdns[10966]: 	github.com/IrineSistiana/mosdns/v3/dispatcher/pkg/executable_seq/fallback.go:172 +0x45
Thu Jan  6 18:51:26 2022 daemon.err mosdns[10966]: github.com/IrineSistiana/mosdns/v3/dispatcher/pkg/executable_seq.(*FallbackNode).doFastFallback.func1()
Thu Jan  6 18:51:26 2022 daemon.err mosdns[10966]: 	github.com/IrineSistiana/mosdns/v3/dispatcher/pkg/executable_seq/fallback.go:196 +0x45
Thu Jan  6 18:51:26 2022 daemon.err mosdns[10966]: created by github.com/IrineSistiana/mosdns/v3/dispatcher/pkg/executable_seq.(*FallbackNode).doFastFallback
Thu Jan  6 18:51:26 2022 daemon.err mosdns[10966]: 	github.com/IrineSistiana/mosdns/v3/dispatcher/pkg/executable_seq/fallback.go:195 +0x1d1


```

---

**环境**

mosdns 的版本号(`mosdns -v`)：3.0.0

操作系统和平台：openwrt amd64

**Comment by IrineSistiana** [comment]
这个日志不全。只有后半部分。应该前面还有。

**Comment by christaikobo** [comment]
markdown不熟悉，把第一行吃掉了...
其实就差了一行
已经补充进去了

**Comment by IrineSistiana** [comment]
定位了。是 adhome 的bug。

**Comment by IrineSistiana** [comment]
adhome fastip 的 bug，mosdns 不好修。建议先别开 fastip 。

**Comment by christaikobo** [comment]
> adhome fastip 的 bug，mosdns 不好修。建议先别开 fastip 。

收到，多谢

**Comment by IrineSistiana** [comment]
FYI, 这个 bug 跟新版本没关系，估计从 mosdns 一开始就存在了。

这个 bug 的起因也很奇怪。是因为你的 mosdns 收到了一个奇怪的没有任何意义的空白的请求。(只有数据头，没有任何请求信息的请求)。

**Comment by christaikobo** [comment]
> FYI, 这个 bug 跟新版本没关系，估计从 mosdns 一开始就存在了。
> 
> 这个 bug 的起因也很奇怪。是因为你的 mosdns 收到了一个奇怪的没有任何意义的空白的请求。(只有数据头，没有任何请求信息的请求)。


我退回2.0试试...
以前是真的没有过

**Comment by IrineSistiana** [comment]
> ~adhome fastip 的 bug，mosdns 不好修。~

曲线救国 √

**Comment by christaikobo** [comment]
我想说可能有什么隐藏的原因触发了这个问题
因为我退回2.0之后，完全没出现任何问题

**Comment by IrineSistiana** [comment]
配置贴一下？

**Comment by IrineSistiana** [comment]
以及用的是 v2 的哪一版？v2.0.0？

**Comment by christaikobo** [comment]
同样配置2.0.0 和2.1.2都用过一段时间
```
    ################################# 日志设定
  log:
    level: info
    file: ""

  plugin:

    ################################# 可执行插件
    - tag: default
      type: sequence
      args:
        exec:
          # 屏蔽广告和特定域名
          - if:
              - match_ad_domain               # 匹配已知的屏蔽域名
            exec:
              - _block_with_nxdomain        # 屏蔽
              - _end                                    # 结束

          - _single_flight                           # 去重

          - if:
              - match_foreign_domain       # 匹配国外域名
            exec:
              - forward_remote                  # 转发至远程服务器
              - _end

          - forward_local                          # 转发至本地服务器，获取应答

          - if:
              - match_cn_domain               # 匹配中国域名
              - match_cn_ip                        # 匹配中国IP
            exec:
              - _end

          # 剩余请求(既不是已知的域名，也没有返回中国IP)
          - forward_remote                      # 转发至远程服务器，获取应答(之前的应答会被复写)
     
          - _end


    - tag: forward_local
      type: sequence
      args:
        exec:
          - primary:                     # 主要执行序列。
              - forward_local_primary
            secondary:                  # 次要执行序列。
              - forward_local_secondary
            stat_length: 10            # 统计长度。默认 10。
            threshold: 5                 # fallback 触发阈值。不可大于统计长度。默认 5。
            fast_fallback: 200        # 快速 fallback 触发阈值。单位: 毫秒。默认: 0，禁用快速 fallback。
                                              # 参考建议: 设为 `primary` 正常延时的 3-5 倍。
            always_standby: false # secondary 始终待命。仅用于快速 fallback。

    - tag: forward_remote
      type: sequence
      args:
        exec:    
          - primary:                      # 主要执行序列。
              - forward_remote_primary
            secondary:                  # 次要执行序列。
              - forward_remote_secondary
            stat_length: 10            # 统计长度。默认 10。
            threshold: 5                 # fallback 触发阈值。不可大于统计长度。默认 5。
            fast_fallback: 900        # 快速 fallback 触发阈值。单位: 毫秒。默认: 0，禁用快速 fallback。
                                              # 参考建议: 设为 `primary` 正常延时的 3-5 倍。
            always_standby: true  # secondary 始终待命。仅用于快速 fallback。

    - tag: forward_local_primary          # 转发至本地服务器
      type: forward
      args:
        upstream:
          - addr: https://223.5.5.5/dns-query
            ip_addr: 
               - 223.5.5.5
          - addr: https://doh.pub/dns-query
        bootstrap:
          - "https://223.5.5.5/dns-query"
        timeout: 10                                # 超时时间，单位: 秒。
        insecure_skip_verify: false        # 禁用 TLS 身份验证。
        fastest_ip: true                          # 最快 IP 模式。
        
    - tag: forward_local_secondary      # 转发至本地备用服务器
      type: forward
      args:
        upstream:
          - addr: https://doh.360.cn/dns-query
        bootstrap:
          - "https://223.5.5.5/dns-query"
        timeout: 10                                # 超时时间，单位: 秒。
        insecure_skip_verify: false        # 禁用 TLS 身份验证。
        fastest_ip: true                          # 最快 IP 模式。

    - tag: forward_remote_primary      # 转发至远程服务器
      type: forward
      args:
        upstream:
          - addr: https://1.0.0.1/dns-query
            ip_addr: 
               - 1.0.0.1
            trusted: true
          - addr: https://8.8.8.8/dns-query
            ip_addr: 
               - 8.8.8.8
            trusted: true
        timeout: 10                                # 超时时间，单位: 秒。
        insecure_skip_verify: false        # 禁用 TLS 身份验证。
        fastest_ip: true                          # 最快 IP 模式。
        
    - tag: forward_remote_secondary # 转发至远程备用服务器
      type: forward
      args:
        upstream:
          - addr: https://private.canadianshield.cira.ca/dns-query
            ip_addr: 
               - 149.112.121.10
            trusted: true
        timeout: 10                                # 超时时间，单位: 秒。
        insecure_skip_verify: false        # 禁用 TLS 身份验证。
        fastest_ip: true                          # 最快 IP 模式。


    ############################### 匹配器插件
    - tag: match_cn_domain                            # 匹配请求域名是否是中国域名
      type: query_matcher
      args:
        domain:
          - ext:./geosite.dat:cn

    - tag: match_foreign_domain                    # 匹配请求域名是否是国外域名
      type: query_matcher
      args:
        domain:
          - ext:./geosite.dat:geolocation-!cn

    - tag: match_ad_domain                            # 匹配请求域名是否是geosite广告域名
      type: query_matcher
      args:
        domain:
          - ext:./geosite.dat:category-ads-all

    - tag: match_cn_ip                                       # 匹配应答的 IP 是否是中国IP
      type: response_matcher
      args:
        ip:
          - ext:./chn.list


    ################################# 启动服务器
    - tag: main_server
      type: server
      args:
        entry: default                                           # 入口路由插件。该服务器收到的请求将会送至这里处理。
        max_concurrent_queries: 0
        server:
           - protocol: udp
             addr: 127.0.0.1:*
           - protocol: tcp
             addr: 127.0.0.1:*
           - protocol: udp
             addr: "[::1]:*
           - protocol: tcp
             addr: "[::1]:*"
```
