### ISSUE TITLE
[BUG] 0.22 fast_forward 问题

### ISSUE THREAD

**Issue by rampageX** [IrineSistiana/mosdns#25]
**出现了什么问题**

parallel 模式配合 fast_forward 上游，如用 `dig` 或者 `kdig` 测试，在任意域名`第二次`查询时报错超时： `;; Warning: ID mismatch:`。
用 `nslookup` 无问题！
不用 fast_forward 做上游无问题！

mosdns 日志：
```txt
time="2020-12-31T21:38:55+08:00" level=debug msg="cpool cleaner 0x40002c9800 exited" func="github.com/IrineSistiana/mosdns/dispatcher/plugin/executable/fast_forward/cpool.(*Pool).startCleaner" file="github.com/IrineSistiana/mosdns/dispatcher/plugin/executable/fast_forward/cpool/pool.go:149" addr="8.8.8.8:853" plugin=fast_forward_remote protocol=tcp
time="2020-12-31T21:39:05+08:00" level=debug msg="[{wsj.com. 1 1}], id: 13237, t: 0 ms, from: udp://192.168.2.8:62659: exec context plugin _default_cache" func="github.com/IrineSistiana/mosdns/dispatcher/handler.(*PipeContext).ExecNextPlugin" file="github.com/IrineSistiana/mosdns/dispatcher/handler/context_plugin.go:54" plugin=pipeline_parallel
time="2020-12-31T21:39:05+08:00" level=debug msg="[{wsj.com. 1 1}], id: 13237, t: 0 ms, from: udp://192.168.2.8:62659: exec executable plugin main_parallel" func="github.com/IrineSistiana/mosdns/dispatcher/handler.(*PipeContext).ExecNextPlugin" file="github.com/IrineSistiana/mosdns/dispatcher/handler/context_plugin.go:57" plugin=pipeline_parallel
time="2020-12-31T21:39:05+08:00" level=debug msg="[{wsj.com. 1 1}], id: 13237, t: 1 ms, from: udp://192.168.2.8:62659: exec matcher plugin match_local_domain, returned: false" func=github.com/IrineSistiana/mosdns/dispatcher/handler.ifConditionfile="github.com/IrineSistiana/mosdns/dispatcher/handler/executable_plugin.go:153" plugin=main_parallel
time="2020-12-31T21:39:05+08:00" level=debug msg="[{wsj.com. 1 1}], id: 13237, t: 1 ms, from: udp://192.168.2.8:62659: exec matcher plugin match_non_local_domain, returned: true" func=github.com/IrineSistiana/mosdns/dispatcher/handler.ifCondition file="github.com/IrineSistiana/mosdns/dispatcher/handler/executable_plugin.go:153" plugin=main_parallel
time="2020-12-31T21:39:05+08:00" level=debug msg="[{wsj.com. 1 1}], id: 13237, t: 2 ms, from: udp://192.168.2.8:62659: exec plugin ecs_remote" func=github.com/IrineSistiana/mosdns/dispatcher/handler.executablePluginTag.ExecCmd file="github.com/IrineSistiana/mosdns/dispatcher/handler/executable_plugin.go:72" plugin=main_parallel
time="2020-12-31T21:39:05+08:00" level=debug msg="[{wsj.com. 1 1}], id: 13237, t: 2 ms, from: udp://192.168.2.8:62659: exec plugin fast_forward_remote" func=github.com/IrineSistiana/mosdns/dispatcher/handler.executablePluginTag.ExecCmd file="github.com/IrineSistiana/mosdns/dispatcher/handler/executable_plugin.go:72" plugin=main_parallel
time="2020-12-31T21:39:05+08:00" level=debug msg="[{wsj.com. 1 1}], id: 13237, t: 199 ms, from: udp://192.168.2.8:62659: goto plugin _end" func="github.com/IrineSistiana/mosdns/dispatcher/handler.(*ExecutableCmdSequence).Exec" file="github.com/IrineSistiana/mosdns/dispatcher/handler/executable_plugin.go:237" plugin=main_parallel
time="2020-12-31T21:39:05+08:00" level=debug msg="cpool cleaner 0x40002c9800 started" func="github.com/IrineSistiana/mosdns/dispatcher/plugin/executable/fast_forward/cpool.(*Pool).startCleaner" file="github.com/IrineSistiana/mosdns/dispatcher/plugin/executable/fast_forward/cpool/pool.go:136" addr="8.8.8.8:853" plugin=fast_forward_remote protocol=tcp
time="2020-12-31T21:39:06+08:00" level=debug msg="cpool cleaner 0x40002c9740 started" func="github.com/IrineSistiana/mosdns/dispatcher/plugin/executable/fast_forward/cpool.(*Pool).startCleaner" file="github.com/IrineSistiana/mosdns/dispatcher/plugin/executable/fast_forward/cpool/pool.go:136" addr="9.9.9.11:853" plugin=fast_forward_remote protocol=tcp
time="2020-12-31T21:39:09+08:00" level=debug msg="HeapObjects: 30225 NumGC: 14 PauseTotalNs: 2824826, NumGoroutine: 13" func=github.com/IrineSistiana/mosdns/dispatcher/plugin/logger.configLogger.func1 file="github.com/IrineSistiana/mosdns/dispatcher/plugin/logger/logger.go:117"
time="2020-12-31T21:39:10+08:00" level=debug msg="[{wsj.com. 1 1}], id: 13237, t: 0 ms, from: udp://192.168.2.8:62659: exec context plugin _default_cache" func="github.com/IrineSistiana/mosdns/dispatcher/handler.(*PipeContext).ExecNextPlugin" file="github.com/IrineSistiana/mosdns/dispatcher/handler/context_plugin.go:54" plugin=pipeline_parallel
time="2020-12-31T21:39:10+08:00" level=debug msg="[{wsj.com. 1 1}], id: 13237, t: 0 ms, from: udp://192.168.2.8:62659: exec executable plugin main_parallel" func="github.com/IrineSistiana/mosdns/dispatcher/handler.(*PipeContext).ExecNextPlugin" file="github.com/IrineSistiana/mosdns/dispatcher/handler/context_plugin.go:57" plugin=pipeline_parallel
time="2020-12-31T21:39:10+08:00" level=debug msg="[{wsj.com. 1 1}], id: 13237, t: 1 ms, from: udp://192.168.2.8:62659: exec matcher plugin match_local_domain, returned: false" func=github.com/IrineSistiana/mosdns/dispatcher/handler.ifConditionfile="github.com/IrineSistiana/mosdns/dispatcher/handler/executable_plugin.go:153" plugin=main_parallel
time="2020-12-31T21:39:10+08:00" level=debug msg="[{wsj.com. 1 1}], id: 13237, t: 1 ms, from: udp://192.168.2.8:62659: exec matcher plugin match_non_local_domain, returned: true" func=github.com/IrineSistiana/mosdns/dispatcher/handler.ifCondition file="github.com/IrineSistiana/mosdns/dispatcher/handler/executable_plugin.go:153" plugin=main_parallel
time="2020-12-31T21:39:10+08:00" level=debug msg="[{wsj.com. 1 1}], id: 13237, t: 2 ms, from: udp://192.168.2.8:62659: exec plugin ecs_remote" func=github.com/IrineSistiana/mosdns/dispatcher/handler.executablePluginTag.ExecCmd file="github.com/IrineSistiana/mosdns/dispatcher/handler/executable_plugin.go:72" plugin=main_parallel
time="2020-12-31T21:39:10+08:00" level=debug msg="[{wsj.com. 1 1}], id: 13237, t: 2 ms, from: udp://192.168.2.8:62659: exec plugin fast_forward_remote" func=github.com/IrineSistiana/mosdns/dispatcher/handler.executablePluginTag.ExecCmd file="github.com/IrineSistiana/mosdns/dispatcher/handler/executable_plugin.go:72" plugin=main_parallel
time="2020-12-31T21:39:10+08:00" level=debug msg="[{wsj.com. 1 1}], id: 13237, t: 3 ms, from: udp://192.168.2.8:62659: goto plugin _end" func="github.com/IrineSistiana/mosdns/dispatcher/handler.(*ExecutableCmdSequence).Exec" file="github.com/IrineSistiana/mosdns/dispatcher/handler/executable_plugin.go:237" plugin=main_parallel
time="2020-12-31T21:39:15+08:00" level=debug msg="[{wsj.com. 1 1}], id: 13237, t: 0 ms, from: udp://192.168.2.8:62659: exec context plugin _default_cache" func="github.com/IrineSistiana/mosdns/dispatcher/handler.(*PipeContext).ExecNextPlugin" file="github.com/IrineSistiana/mosdns/dispatcher/handler/context_plugin.go:54" plugin=pipeline_parallel
time="2020-12-31T21:39:15+08:00" level=debug msg="[{wsj.com. 1 1}], id: 13237, t: 0 ms, from: udp://192.168.2.8:62659: exec executable plugin main_parallel" func="github.com/IrineSistiana/mosdns/dispatcher/handler.(*PipeContext).ExecNextPlugin" file="github.com/IrineSistiana/mosdns/dispatcher/handler/context_plugin.go:57" plugin=pipeline_parallel
time="2020-12-31T21:39:15+08:00" level=debug msg="[{wsj.com. 1 1}], id: 13237, t: 1 ms, from: udp://192.168.2.8:62659: exec matcher plugin match_local_domain, returned: false" func=github.com/IrineSistiana/mosdns/dispatcher/handler.ifConditionfile="github.com/IrineSistiana/mosdns/dispatcher/handler/executable_plugin.go:153" plugin=main_parallel
time="2020-12-31T21:39:15+08:00" level=debug msg="[{wsj.com. 1 1}], id: 13237, t: 1 ms, from: udp://192.168.2.8:62659: exec matcher plugin match_non_local_domain, returned: true" func=github.com/IrineSistiana/mosdns/dispatcher/handler.ifCondition file="github.com/IrineSistiana/mosdns/dispatcher/handler/executable_plugin.go:153" plugin=main_parallel
time="2020-12-31T21:39:15+08:00" level=debug msg="[{wsj.com. 1 1}], id: 13237, t: 2 ms, from: udp://192.168.2.8:62659: exec plugin ecs_remote" func=github.com/IrineSistiana/mosdns/dispatcher/handler.executablePluginTag.ExecCmd file="github.com/IrineSistiana/mosdns/dispatcher/handler/executable_plugin.go:72" plugin=main_parallel
time="2020-12-31T21:39:15+08:00" level=debug msg="[{wsj.com. 1 1}], id: 13237, t: 2 ms, from: udp://192.168.2.8:62659: exec plugin fast_forward_remote" func=github.com/IrineSistiana/mosdns/dispatcher/handler.executablePluginTag.ExecCmd file="github.com/IrineSistiana/mosdns/dispatcher/handler/executable_plugin.go:72" plugin=main_parallel
time="2020-12-31T21:39:15+08:00" level=debug msg="[{wsj.com. 1 1}], id: 13237, t: 4 ms, from: udp://192.168.2.8:62659: goto plugin _end" func="github.com/IrineSistiana/mosdns/dispatcher/handler.(*ExecutableCmdSequence).Exec" file="github.com/IrineSistiana/mosdns/dispatcher/handler/executable_plugin.go:237" plugin=main_parallel

```
同时查询窗口：
```
dig @192.168.2.20 -p 66 wsj.com +nocookie
;; Warning: ID mismatch: expected ID 13237, got 43271
;; Warning: ID mismatch: expected ID 13237, got 43271
;; Warning: ID mismatch: expected ID 13237, got 3305

; <<>> DiG 9.17.6 <<>> @192.168.2.20 -p 66 wsj.com +nocookie
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached
```

---

**如何重现**

描述一下如何重现该问题。请尽可能的包含：

mosdns 的版本号(`mosdns -v`)： v0.22.0-0-g5fdab3e

使用的启动参数或启动方式：mosdns -c mosdns.yaml

操作系统和平台：Linux N1-U20 5.9.0-arm-64 #20.10 SMP PREEMPT Wed Oct 14 12:04:42 MSK 2020 aarch64 aarch64 aarch64 GNU/Linux

进行了什么操作导致了问题的出现：

使用的配置文件：(由于想测试所有功能所以配置写的比较复杂>_<)

```yaml
plugin:
  ## 日志
  - tag: logger
    type: logger
    args:
      no_color: true
      # file: "/var/log/mosdns.log"
      # level: info
      file: ""
      level: debug

  ## 启动 sequence 服务器
  - tag: sequence_server
    type: server
    args:
      max_concurrent_queries: 0
      entry: pipeline_sequence
      server:
        - protocol: udp
          addr: 0.0.0.0:64
        - protocol: tcp
          addr: 0.0.0.0:64

  ## 启动 parallel 服务器
  - tag: parallel_server
    type: server
    args:
      max_concurrent_queries: 0
      entry: pipeline_parallel
      server:
        - protocol: udp
          addr: 0.0.0.0:66
        - protocol: tcp
          addr: 0.0.0.0:66

  ## 可执行插件-顺序
  - tag: pipeline_sequence
    type: pipeline
    args:
      pipe:
        - _default_cache          # 缓存
        - main_sequence           # 处理请求

  - tag: main_sequence
    type: sequence
    args:
      exec:
        - if:
            - match_local_domain      # 处理已知的本地域名
            - !_query_is_common  # 和不常见的请求类型
          exec:
            - ecs_local
            - forward_local
          goto: _end

        - if:
            - match_non_local_domain  # 处理已知的非本地域名
          exec:
            - ecs_remote
            - forward_remote
          goto: _end

        - sequence_bypass_local       # 分流未知域名。有两种方案：顺序或并行。这是顺序执行。

  ## 可执行插件-并发
  - tag: pipeline_parallel
    type: pipeline
    args:
      pipe:
        - _default_cache          # 缓存
        - main_parallel           # 处理请求

  - tag: main_parallel
    type: sequence
    args:
      exec:
        - if:
            - match_local_domain      # 处理已知的本地域名
            - !_query_is_common  # 和不常见的请求类型
          exec:
            - ecs_local
            - fast_forward_local
          goto: _end

        - if:
            - match_non_local_domain  # 处理已知的非本地域名
          exec:
            - ecs_remote
            - fast_forward_remote
          goto: _end

        - parallel_bypass_local       # 分流未知域名。有两种方案：顺序或并行。这是并发执行。

  ## 两种分流逻辑
  - tag: sequence_bypass_local        # 顺序执行的分流逻辑
    type: sequence
    args:
      exec:
        - forward_local               # 先请求转发至本地服务器
        - if:
            - match_local_ip          # 如果应答包含本地 IP
          goto: _end                  # 就直接采用结果
        - forward_remote              # 否则用远程服务器的结果

  - tag: parallel_bypass_local        # 并发执行的分流的逻辑
    type: parallel
    args:
      exec:
        - - fast_forward_local             # 并发请求本地和远程服务器
          - if:
              - !match_local_ip       # 本地服务器返回的非本地 IP 的应答会被丢弃
            exec:
              - _drop_response
        - - fast_forward_remote

  ## 匹配器插件
  # - tag: match_qtype_HTTPS # 匹配 HTTPS 请求
  #   type: query_matcher
  #   args:
  #     type: [65]

  - tag: match_local_domain # 匹配请求域名是否是本地域名
    type: query_matcher
    args:
      domain:
        - "/root/cfg/geosite.dat:cn"

  - tag: match_non_local_domain # 匹配请求域名是否是境外域名
    type: query_matcher
    args:
      domain:
        - "/root/cfg/geosite.dat:geolocation-!cn"

  - tag: match_local_ip # 匹配应答的 IP 是否是本地 IP
    type: response_matcher
    args:
      ip:
        - "/root/cfg/geoip.dat:cn"

  ## ECS
  - tag: ecs_local
    type: ecs
    args:
      auto: false # 是否根据客户端地址自动附加 ECS。如果为 true，则预设地址不会被使用。
      force_overwrite: false  # 如果请求已有 ECS，是否覆盖。
      mask4: 24               # 用于 ipv4 地址的掩码。
      mask6: 32               # 用于 ipv6 地址的掩码。
      ipv4: "120.230.137.0"         # 预设的 ipv4 地址。如果非空，会附加在 A 请求中。
      ipv6: ""   # 预设的 ipv6 地址。如果非空，会附加在 AAAA 请求中。

  - tag: ecs_remote
    type: ecs
    args:
      auto: false
      force_overwrite: false
      mask4: 24
      mask6: 32
      ipv4: "202.67.222.0"
      ipv6: ""

  ## 功能性插件
  - tag: forward_local # 转发至本地服务器
    type: forward
    args:
      upstream:
        - addr: 211.136.192.6:53
        - addr: 120.196.165.24:53
        - addr: https://doh.360.cn/dns-query
        - addr: https://i.233py.com/dns-query
        - addr: tls://dns.alidns.com
        - addr: tls://dns.pub
      deduplicate: false           # 是否请求去重。
      insecure_skip_verify: false  # 禁用 TLS 身份验证。
      timeout: 6                  # 超时时间，单位: 秒。
      # 用于解析上游服务器域名的 bootstrap 服务器地址。可配置多个。必须没有域名。可以为空，会使用系统设置。
      bootstrap:
        - 9.9.9.9:9953
        - 208.67.220.220:443

  - tag: forward_remote # 转发至远程服务器
    type: forward
    args:
      upstream:
        - addr: https://dns11.quad9.net/dns-query
        - addr: https://dns.twnic.tw/dns-query
        - addr: tls://dns.google
        - addr: tls://dns.sb
      deduplicate: false
      insecure_skip_verify: false
      timeout: 6
      bootstrap:
        - 9.9.9.9:9953
        - 208.67.220.220:443

  - tag: fast_forward_local
    type: fast_forward
    args:
      deduplicate: false    # 是否请求去重。
      upstream:             # 上游服务器。至少要配置一个。可配置多个，会并发请求全部服务器。
        - protocol: dot     # 服务器协议。可以是 `udp`, `tcp`, `dot`, `doh`。为空默认 `udp`。
          addr: 223.5.5.5:853  # 服务器地址。不可为空。格式 `host:port`。`:port` 可省略。
          trusted: false     # 是否是可信服务器。仅配置了多个服务器时生效。
                            # true: 该服务器返回的 Rcode != 0 的应答会被接受。
                            # false: 该服务器返回的 Rcode != 0 会被丢弃。
          socks5: ""  # socks5 服务器地址。格式 `host:port`。`:port` 不可省略。
                      # 不支持用户名密码认证。适用于 `tcp`, `dot`, `doh` 协议。
          server_name: dns.alidns.com           # 服务器(证书)名。适用于 `dot` 协议。不可为空。
          url: https://dns.alidns.com/dns-query # 服务器 URL。适用于 `doh` 协议。不可为空。
          timeout: 5          # 应答超时时间。单位: 秒。默认 5。适用于全部协议。
          idle_timeout: 10    # 空连接超时时间。单位: 秒。
                              # 如果为 0，则禁用连接重用(对于 `udp` 协议是禁用套接字重用)。适用于全部协议。
          insecure_skip_verify: false # 是否禁用 TLS 验证。适用于 `dot`，`doh` 协议。
          ca: [ ]             # 用于 TLS 验证的 CA 证书。适用于 `dot`，`doh` 协议。为空默认使用系统证书。

        - protocol: dot
          addr: 162.14.21.56:853
          trusted: false
          socks5: ""
          server_name: dns.pub
          url: https://dns.pub/dns-query
          timeout: 5
          idle_timeout: 10
          insecure_skip_verify: false
          ca: [ ]

  - tag: fast_forward_remote
    type: fast_forward
    args:
      deduplicate: false    # 是否请求去重。
      upstream:             # 上游服务器。至少要配置一个。可配置多个，会并发请求全部服务器。
        - protocol: dot     # 服务器协议。可以是 `udp`, `tcp`, `dot`, `doh`。为空默认 `udp`。
          addr: 9.9.9.11:853  # 服务器地址。不可为空。格式 `host:port`。`:port` 可省略。
          trusted: true     # 是否是可信服务器。仅配置了多个服务器时生效。
                            # true: 该服务器返回的 Rcode != 0 的应答会被接受。
                            # false: 该服务器返回的 Rcode != 0 会被丢弃。
          socks5: ""  # socks5 服务器地址。格式 `host:port`。`:port` 不可省略。
                      # 不支持用户名密码认证。适用于 `tcp`, `dot`, `doh` 协议。
          server_name: dns11.quad9.net           # 服务器(证书)名。适用于 `dot` 协议。不可为空。
          url: https://dns11.quad9.net/dns-query # 服务器 URL。适用于 `doh` 协议。不可为空。
          timeout: 5          # 应答超时时间。单位: 秒。默认 5。适用于全部协议。
          idle_timeout: 10    # 空连接超时时间。单位: 秒。
                              # 如果为 0，则禁用连接重用(对于 `udp` 协议是禁用套接字重用)。适用于全部协议。
          insecure_skip_verify: false # 是否禁用 TLS 验证。适用于 `dot`，`doh` 协议。
          ca: [ ]             # 用于 TLS 验证的 CA 证书。适用于 `dot`，`doh` 协议。为空默认使用系统证书。

        - protocol: dot
          addr: 8.8.8.8:853
          trusted: true
          socks5: "127.0.0.1:7575"
          server_name: dns.google
          url: https://dns.google/dns-query
          timeout: 5
          idle_timeout: 10
          insecure_skip_verify: false
          ca: [ ]
          
````
