### ISSUE TITLE
[BUG]使用3.0版本ecs无法正常工作

### ISSUE THREAD

**Issue by linusxiong** [IrineSistiana/mosdns#265]
**出现了什么问题**

简要描述一下问题的表现，以及执行了什么操作导致了问题的出现：
当mosdns配置到远程服务器的时候，开启ecs日志里会疯狂弹context doesn't have a client ip，并且请求日志中的地址全变成了127.0.0.1，应该是没有正确获取到用户来源ip的原因，换回了2.2.1版本则没有这个问题，
例如这样一条错误日志中
```
"query": "hd.mmstat.com. IN A 13385 5499 183.169.38.4:1473", "error": "_single_flight: ecs: cache: if_sequence: forward_domestic: context canceled"
```
获取到了来源ip和端口，但是3.0版本则为127.0.0.1，配置文件仅仅为_return和timeout的改动
mosdns 的 log 记录:

```txt
context doesn't have a client ip
```

---

**环境**
mosdns 的版本号(`mosdns -v`)：3.0.0

操作系统和平台：debian

ecs部分配置
```
  # 添加ECS的插件
  - tag: ecs
    type: ecs
    args:
      auto: true
```
