### ISSUE TITLE
[BUG] nslookup Parse error

### ISSUE THREAD

**Issue by muziling** [IrineSistiana/mosdns#271]
**出现了什么问题**

简要描述一下问题的表现，以及执行了什么操作导致了问题的出现：

mosdns 的 log 记录:

```txt
root@OpenWrt:/etc/init.d# nslookup www.qq.com
Server:		127.0.0.1
Address:	127.0.0.1#53

*** Can't find www.qq.com: Parse error
*** Can't find www.qq.com: Parse error
root@OpenWrt:/etc/init.d# nslookup www.baidu.com
Server:		127.0.0.1
Address:	127.0.0.1#53

Name:      www.baidu.com
www.baidu.com	canonical name = www.a.shifen.com
Name:      www.a.shifen.com
Address 1: 14.215.177.38
Address 2: 14.215.177.39
www.baidu.com	canonical name = www.a.shifen.com
root@OpenWrt:/etc/init.d# nslookup www.jd.com
Server:		127.0.0.1
Address:	127.0.0.1#53

*** Can't find www.jd.com: Parse error
Name:      www.jd.com
www.jd.com	canonical name = www.jd.com.gslb.qianxun.com
Name:      www.jd.com.gslb.qianxun.com
www.jd.com.gslb.qianxun.com	canonical name = www.jdcdn.com
Name:      www.jdcdn.com
www.jdcdn.com	canonical name = img20.360buyimg.com.s.galileo.jcloud-cdn.com
Name:      img20.360buyimg.com.s.galileo.jcloud-cdn.com
img20.360buyimg.com.s.galileo.jcloud-cdn.com	canonical name = img2x-sched.jcloud-cdn.com

```
回退到旧版 mosdns ver: v2.1.1-0-g546b56f 后正常

---

**环境**

描述一下问题出现的环境，便于复现以更快定位问题。必须包含：

mosdns 的版本号(`mosdns -v`)：0ec6593

操作系统和平台：

使用的配置文件：

```yaml
log:
  level:                   error
  file:                    '/tmp/mosdns.log'

plugin:
  - tag:                   main_server
    type:                  server
    args:
      entry:
        - _no_ecs
        - lazy_cache
        - query_hosts
        - main_sequence
      server:
        - protocol:        udp
          addr:            '0.0.0.0:53'
        - protocol:        tcp
          addr:            '0.0.0.0:53'

  - tag:                   main_sequence
    type:                  sequence
    args:
      exec:
        - if:
            - query_is_ad_domain
          exec:
            - _block_with_nxdomain
            - _end
        - if:
            - query_is_pollute_domain    # 已知的域名不能解析为国内IP
          exec:
            - forward_remote  # 屏蔽
            - _end
        - if:
            - query_is_local_domain
            - '!_query_is_common'
          exec:
            - forward_local
            - _end
        - if:
            - query_is_non_local_domain
          exec:
            - if:
                - _qtype_AAAA
              exec:
                - _block_with_empty_response
                - _end
            - forward_remote
            - _end
        - primary:
            - forward_local
            - if:
                - '!response_has_local_ip'
              exec:
                - _drop_response
          secondary:
            - if:
                - _qtype_AAAA
              exec:
                - _block_with_empty_response
                - _end
            - forward_remote
          fast_fallback:   150
          always_standby:  true

  - tag:                   forward_local
    type:                  fast_forward
    args:
      upstream:
        - addr:            218.85.157.99
        - addr:            218.85.152.99

  - tag:                   forward_remote
    type:                  fast_forward
    args:
      upstream:
        - addr:            'tls://8.8.4.4'
          idle_timeout:    180
          max_conns:       100
        - addr:            'tls://101.101.101.101'
          idle_timeout:    180
          max_conns:       100
        - addr:            '127.0.0.1:9053'

  - tag: query_hosts
    type: hosts
    args:
      hosts:
        - 'domain:arpa 127.0.0.1 ::1'

  - tag:                   lazy_cache
    type:                  cache
    args:
      size:                512000
      lazy_cache_ttl:      31536000

  - tag:                   query_is_local_domain
    type:                  query_matcher
    args:
      domain:
        - 'ext:./geosite.dat:cn'

  - tag:                   query_is_non_local_domain
    type:                  query_matcher
    args:
      domain:
        - 'ext:./geosite.dat:geolocation-!cn'

  - tag:                   query_is_ad_domain
    type:                  query_matcher
    args:
      domain:
        - 'ext:./geosite.dat:category-ads-all'

  - tag:                   response_has_local_ip
    type:                  response_matcher
    args:
      ip:
        - 'ext:./geoip.dat:cn'

  - tag: query_is_pollute_domain           # 匹配域名不能解析为国内IP的插件
    type: query_matcher
    args:
      domain:
        - googleapis.cn
        - gstatic.com

````
