### ISSUE TITLE
[BUG]这个输出处理没问题吗？

### ISSUE THREAD

**Issue by daiaji** [IrineSistiana/mosdns#289]
```yaml
log:
  level:                   error
  file:                    ''

plugin:
  - tag:                   main_server
    type:                  server
    args:
      entry:
        - _no_ecs
        - lazy_cache
        - _single_flight
        - main_sequence
      server:
        - protocol:        udp
          addr:            '0.0.0.0:5553'
        - protocol:        tcp
          addr:            '0.0.0.0:5553'

  - tag:                   main_sequence
    type:                  sequence
    args:
      exec:
        - if:
            - query_is_ad_domain
          exec:
            - _block_with_nxdomain
            - _end
        - if:
            - my_domain
          exec:
            - my_remote
            - _end
        - if:
            - query_is_local_domain
            - '!_query_is_common'
          exec:
            - forward_local
            - _end
        - if:
            - query_is_non_local_domain
          exec:
            - forward_remote
            - _end
        - primary:
            - forward_local
            - if:
                - '!response_has_local_ip'
              exec:
                - _drop_response
          secondary:
            - forward_remote
          fast_fallback:   150
          always_standby:  true

  - tag:                   forward_local
    type:                  fast_forward
    args:
      upstream:
        - addr:            ${{ ./dns.sh 0 }}
        - addr:            ${{ ./dns.sh 1 }}
        - addr:            223.5.5.5
        - addr:            223.6.6.6
        - addr:            114.114.114.119
        - addr:            114.114.115.119
        - addr:            119.29.29.29

  - tag:                   forward_remote
    type:                  fast_forward
    args:
      upstream:
        - addr:            'tls://8.8.4.4'                                                                                                                                                                                      
          idle_timeout:    10                                                                                                                                                                                                   
        - addr:            'tls://9.9.9.9'
          idle_timeout:    10
        - addr:            'tls://101.101.101.101'                                                                                                                                                                                      
          idle_timeout:    10
        - addr:            'tls://[2606:4700:4700::1111]'                                                                                                                                                                                      
          idle_timeout:    10                                                                                                                                                                                                   
        - addr:            'tls://[2606:4700:4700::1001]'
          idle_timeout:    10
        - addr:            'tls://[2620:fe::fe]'                                                                                                                                                                                      
          idle_timeout:    10                                                                                                                                                                                                   
        - addr:            'tls://[2620:fe::9]'
          idle_timeout:    10
        - addr:            'tls://[2620:fe::11]'                                                                                                                                                                                   
          idle_timeout:    10
        - addr:            'tls://[2620:fe::fe:11]'                                                                                                                                                                                   
          idle_timeout:    10
        - addr:            'tls://1.1.1.1'                                                                                                                                                                                      
          idle_timeout:    10                                                                                                                                                                                                   
        - addr:            'tls://1.0.0.1'
          idle_timeout:    10
        - addr:            'https://101.101.101.101/dns-query'
          idle_timeout:    10
        - addr:            'https://9.9.9.9/dns-query'
          idle_timeout:    10
        - addr:            'https://[2606:4700:4700::1111]/dns-query'
          idle_timeout:    10
        - addr:            'https://[2606:4700:4700::1001]/dns-query'
          idle_timeout:    10
        - addr:            'https://[2001:de4::101]/dns-query'
          idle_timeout:    10
        - addr:            'https://[2620:fe::fe]/dns-query'
          idle_timeout:    10
        - addr:            'https://[2620:fe::9]/dns-query'
          idle_timeout:    10
        - addr:            'https://[2620:fe::11]/dns-query'
          idle_timeout:    10
        - addr:            'https://[2620:fe::fe:11]/dns-query'
          idle_timeout:    10
        - addr:            'https://1.1.1.1/dns-query'
          idle_timeout:    10
        - addr:            'https://1.0.0.1/dns-query'
          idle_timeout:    10
        - addr:            'https://doh.dns.sb/dns-query'
          idle_timeout:    10
        - addr:            'https://doh.sb/dns-query'
          idle_timeout:    10
        - addr:            'https://jp-nrt.doh.sb/dns-query'
          idle_timeout:    10
        - addr:            'https://public.dns.iij.jp/dns-query '
          idle_timeout:    10
          
  - tag:                   my_remote
    type:                  fast_forward
    args:
      upstream:
        - addr:            'tls://9.9.9.9'
          idle_timeout:    10
        - addr:            'tls://149.112.112.112'
          idle_timeout:    10
        - addr:            'https://9.9.9.9/dns-query'
          idle_timeout:    10
        - addr:            'https://149.112.112.112/dns-query'
          idle_timeout:    10
          
  - tag:                   lazy_cache
    type:                  cache
    args:
      size:                512000
      lazy_cache_ttl:      259200

  - tag:                   query_is_local_domain
    type:                  query_matcher
    args:
      domain:
        - 'ext:./geosite.dat:cn'

  - tag:                   query_is_non_local_domain
    type:                  query_matcher
    args:
      domain:
        - 'ext:./geosite.dat:geolocation-!cn'

  - tag:                   response_has_local_ip
    type:                  response_matcher
    args:
      ip:
        - 'ext:./geoip.dat:cn'

  - tag: query_is_ad_domain
    type: query_matcher
    args:
      domain:
        - 'ext:./serverlist.txt'
        
  - tag: my_domain
    type: query_matcher
    args:
      domain:
        - 'eroiaji.xyz'
```
```
root@OpenWrt:/tmp/mosdns# mosdns -dir /etc/mosdns -c cus_config.yaml 1>./log 2>./err
^Croot@OpenWrt:/tmp/mosdns# ls
err  log
root@OpenWrt:/tmp/mosdns# cat err 
2022-02-12T11:18:13.158Z        info    v3/main.go:157  current working directory: /etc/mosdns
2022-02-12T11:18:13.158Z        info    v3/main.go:223  mosdns ver: 20f7604
2022-02-12T11:18:13.158Z        info    v3/main.go:224  arch: amd64, os: linux, go: go1.17.6
2022-02-12T11:18:13.158Z        info    coremain/run.go:67      loading config  {"file": "cus_config.yaml"}
2022-02-12T11:18:13.158Z        info    coremain/cmd.go:15      executing config cmd    {"cmd": "./dns.sh 0"}
2022-02-12T11:18:13.163Z        info    coremain/cmd.go:21      successfully executed cmd       {"cmd": "./dns.sh 0", "stdout": "59.51.78.210"}
2022-02-12T11:18:13.163Z        info    coremain/cmd.go:15      executing config cmd    {"cmd": "./dns.sh 1"}
2022-02-12T11:18:13.167Z        info    coremain/cmd.go:21      successfully executed cmd       {"cmd": "./dns.sh 1", "stdout": "222.246.129.80"}
root@OpenWrt:/tmp/mosdns# cat log 
root@OpenWrt:/tmp/mosdns# 
```
输出的东西应该只是普通输出吧。
但内容却被输出到了stderr
