### ISSUE TITLE
[BUG] 配置 mosdns 对指定范围的双栈域名立即屏蔽 AAAA 解析请求，但并未得到期待的结果

### ISSUE THREAD

**Issue by IceCodeNew** [IrineSistiana/mosdns#29]
**出现了什么问题**

配置 mosdns 对指定范围的双栈域名立即屏蔽 AAAA 解析请求，但并未得到期待的结果。
具体来说，因为代理服务器可能不支持 IPv6 环境，但是本地访问一些学术资料时却可能需要用到 IPv6，所以希望配置 mosdns 只对指定范围的域名屏蔽 AAAA 解析请求。

**mosdns 的版本号(`mosdns -v`)：**
`v0.22.1-0-g8c1d997`

**使用的启动参数或启动方式：**
使用发行时压缩包内包含的 winsw XML 配置将 mosdns 安装为系统服务并启动。

**进行了什么操作导致了问题的出现**：
`dig +nocookie www.facebook.com @127.0.0.1 AAAA`
// 因为 facebook 的首页域名肯定会被 non_local_domain 匹配上，所以预期的结果是不返回结果。但实际上返回了正确的 IPv6 地址。

**使用的配置文件（为方便阅读，仅提供节选的配置）：**

```yaml
  ################ Executable Plugin (Route) #################

  - tag: main_pipeline           # 分流路由
    type: pipeline
    args:
      pipe:
        - cloak_hosts            # 可以是 pipeline 插件，
        - _default_cache
        - set_ecs                # 功能插件
        - main_sequence          # 路由插件

  - tag: main_sequence
    type: sequence
    args:
      exec:
        - if:
            - query_is_ad_domain
          exec:
            - _block_with_nxdomain
          goto: _end

        - if:
            - query_is_non_local_domain
          exec:
            - forward_nextdns
            - if:
                - match_aaaa
              exec:
                - _drop_response
          goto: _end

        - if:
            - query_is_local_domain
          exec:
            - with_fallback_cn_dns_serv
            - if:
                - response_has_bogus_ip
              exec:
                - _drop_response
          goto: _end

        - forward_nextdns        # 兜底

  ################ Matcher Plugin #################

  - tag: query_is_local_domain        # 匹配本地域名的插件
    type: query_matcher
    args:
      domain:                         # 匹配请求域名的域名表
        - "./geosite.dat:cn"
        - "./geosite.dat:category-scholar-!cn"
        - "./dnsmasq-china-list.txt"

  - tag: query_is_non_local_domain    # 匹配非本地域名的插件
    type: query_matcher
    args:
      domain:
        - "./geosite.dat:geolocation-!cn"
        - "./geosite.dat:google-scholar"

  - tag: query_is_ad_domain           # 匹配广告域名的插件
    type: query_matcher
    args:
      domain:
        - "./geosite.dat:category-ads-all"

  - tag: match_aaaa
    type: query_matcher
    args:
      qtype: [28]

  - tag: response_has_bogus_ip
    type: response_matcher
    args:
      ip:
        - "./bogus-nxdomain.china.ip.txt"

````

**Comment by IceCodeNew** [comment]
光是这个问题的话我还能通过升级到 v0.23.0 版本解决，但是就像上面配置文件展示的那样，sequence 路由插件里存在下面这样两个匹配条件：
其中前一个可以改写成 `if,if_and,exec,goto` 的形式。但是第二个因为需要先尝试解析一次，才能匹配第二个匹配条件（`if(response_has_bogus_ip)`），因此只能写成 `if,exec,if,exec,go` 的形式。
这是我为什么要提出这个 issue 的主要原因，因为从结果来看我目前的这个写法根本不起效果。

```yaml
        - if:
            - query_is_non_local_domain
          exec:
            - forward_nextdns
            - if:
                - match_aaaa
              exec:
                - _drop_response
          goto: _end
```
和
```yaml
        - if:
            - query_is_local_domain
          exec:
            - with_fallback_cn_dns_serv
            - if:
                - response_has_bogus_ip
              exec:
                - _drop_response
          goto: _end
```
