### ISSUE TITLE
[BUG] log文件有可执行权限

### ISSUE THREAD

**Issue by crysislinux** [IrineSistiana/mosdns#308]
**出现了什么问题**

生成的log文件具有可执行权限，不影响功能，不过log是不应该有这个权限的

```
-rwxr-xr-x    1 root     root        2.6M Mar  7 03:21 mosdns
```

---

**环境**

描述一下问题出现的环境，便于复现以更快定位问题。必须包含：

mosdns 的版本号(`mosdns -v`)：v3.4.0-0-gcdcedbe

操作系统和平台：Linux OpenWrt 5.4.154 #0 SMP Sun Oct 24 09:01:35 2021 x86_64 GNU/Linux

使用的配置文件：

```yaml
log:
  level: info
  file: "/var/log/mosdns"
````
