### ISSUE TITLE
[BUG] forward 的 bootstrap 无法使用纯 IPv6 的 DoH

### ISSUE THREAD

**Issue by wrxvl8oy** [IrineSistiana/mosdns#315]
**出现了什么问题**

我之前使用的是 2.0 的 mosdns ，应该是最后一个版本（v2.2.2），前几天看到支持 DNS over HTTP3 就升级了 v3.4.0 。
然后发现 forward 的 bootstrap 无法使用纯 IPv6 的 DoH 。
2.0 的版本正常。刚刚的 3.5.0 也不行。不知道从 3.0 的哪个版本出现的。

mosdns 的 log 记录:

```txt
2022-03-12T21:30:18.072+0800	fatal	coremain/run.go:38	failed to load config	{"error": "failed to init plugin forward_local: failed to init upsteam: creating https bootstrapper: Resolver https://[2400:3200::1]/dns-query is not eligible to be a bootstrap DNS server"}
```

---

**环境**

mosdns 的版本号(`mosdns -v`)：v3.5.0

操作系统和平台：Windows 10

使用的配置文件：

```yaml
# 转发请求至本地服务器的插件
  - tag: forward_local
    type: forward
    args:
      upstream:
        - addr: https://dns.alidns.com/dns-query
        - addr: https://doh.pub/dns-query
      bootstrap:
        - https://223.5.5.5/dns-query
        - https://[2400:3200::1]/dns-query
````

另外请问，如果开启了 enable_http3 ，用了 Cloudflare 的 DoH ，并且能正常使用，是否就代表已经使用 DNS over HTTP3 了？日志中好像看不出来。
还有 Wiki 中 [fast_forward](https://github.com/IrineSistiana/mosdns/wiki/Plugin#fast_forward) 有个 typo :
> 已知 Cloudflare https://cloudflare-dns.com/dns-query 和 **Google https://google.dns/dns-query** 现已支持 HTTP3。可做参考。
