### ISSUE TITLE
建议在wiki里增加多线路分流的示例

### ISSUE THREAD

**Issue by douglas-lee** [IrineSistiana/mosdns#321]
比如，同时有日本，美国，香港，本地，该如何配置分流，建议在wiki里示例说明，因为这种需求，目前还是有很多的，现在完全自己摸索着写，有些人会写错。

**Comment by IrineSistiana** [comment]
没有这方面的使用经验，所以不知道怎么写合适。

欢迎分享配置模板和教程。我会把它们放在 wiki，或链接到这里。

**Comment by douglas-lee** [comment]
> 没有这方面的使用经验，所以不知道怎么写合适。
> 
> 欢迎分享配置模板和教程。我会把它们放在 wiki，或链接到这里。

先说明一下我的使用场景：

在网关路由器上用iptables+ipset+clash实现多条线路分流，分别有香港，日本，奈飞专用，美国4条线路，然后用mosdns实现dns分流解析，mosdns配置文件如下：

```
log:
  level: error
  file: /var/log/mosdns.log

plugin:
  - tag: server
    type: server
    args:
      entry:
        - _default_cache 
        - main_sequence
      server:
        - protocol: udp
          addr: 127.0.0.1:5353

  - tag: main_sequence
    type: sequence
    args:
      exec:
        - if:
            - _qtype_AAAA
          exec:
            - _block_with_empty_response
            - _return
        
        - if:
            - '!_query_is_common'
          exec:
            - forward_chn
            - add_ipset_chn
            - _return

        - if:
            - match_nf_domain
          exec:
            - forward_nf
            - add_ipset_nf
            - _return

        - if:
            - match_us_domain
          exec:
            - forward_us
            - add_ipset_us
            - _return

        - if:
            - match_jp_domain
          exec:
            - forward_jp
            - add_ipset_jp
            - _return

        - forward_chn

        - if:
            - match_chn_domain
            - match_chn_ip
          exec:
            - add_ipset_chn
            - _return

        - forward_hk

  - tag: match_chn_domain
    type: query_matcher
    args:
      domain:
        - 'ext:/etc/geosite.dat:cn'
        - 'ext:/etc/geosite.dat:apple-cn'
        - 'ext:/etc/geosite.dat:google-cn'
        - 'ext:/etc/geosite.dat:icloud'
        - 'ext:/etc/otherlist.txt'

  - tag: match_jp_domain
    type: query_matcher
    args:
      domain:
        - 'ext:/etc/jplist.txt'

  - tag: match_nf_domain
    type: query_matcher
    args:
      domain:
        - 'ext:/etc/geosite.dat:netflix'

  - tag: match_us_domain
    type: query_matcher
    args:
      domain:
        - 'ext:/etc/geosite.dat:tiktok'
        - 'ext:/etc/uslist.txt'

  - tag: match_chn_ip
    type: response_matcher
    args:
      ip:
        - 'ext:/etc/geoip.dat:cn'

  - tag: forward_chn
    type: fast_forward
    args:
      upstream:
        - addr: 'https://223.5.5.5/dns-query'

  - tag: forward_hk
    type: fast_forward
    args:
      upstream:
        - addr: 'https://cloudflare-dns.com/dns-query'
          socks5: '127.0.0.1:1080'

  - tag: forward_jp
    type: fast_forward
    args:
      upstream:
        - addr: 'https://cloudflare-dns.com/dns-query'
          socks5: '127.0.0.1:1081'

  - tag: forward_nf
    type: fast_forward
    args:
      upstream:
        - addr: 'https://cloudflare-dns.com/dns-query'
          socks5: '127.0.0.1:1082'
  
  - tag: forward_us
    type: fast_forward
    args:
      upstream:
        - addr: 'https://cloudflare-dns.com/dns-query'
          socks5: '127.0.0.1:1083'

  - tag: add_ipset_chn
    type: ipset
    args:
      mask4: 32
      mask6: 0
      set_name4: 'chnroute'
      set_name6: ''

  - tag: add_ipset_jp
    type: ipset
    args:
      mask4: 32
      mask6: 0
      set_name4: 'jproute'
      set_name6: ''

  - tag: add_ipset_nf
    type: ipset
    args:
      mask4: 32
      mask6: 0
      set_name4: 'nfroute'
      set_name6: ''

  - tag: add_ipset_us
    type: ipset
    args:
      mask4: 32
      mask6: 0
      set_name4: 'usroute'
      set_name6: ''
```

目前使用没啥问题，当然，大家也可以一起帮忙看看配置文件是否还有优化空间？
