### ISSUE TITLE
[Feature request]允许结果中IPv6地址为空的新插件

### ISSUE THREAD

**Issue by PussAzuki** [IrineSistiana/mosdns#343]
如题，这功能针对使用 parallel 查询某些奇怪的域名时，用国内DNS查询仅能查到国内IPv4地址，但国外DNS查到它同时拥有IPv4和IPv6地址。例子：`bigota.d.miui.com` `hugeota.d.miui.com`。

如果有更好的逻辑，欢迎讨论。

**Comment by IrineSistiana** [comment]
没懂......

**Comment by PussAzuki** [comment]
```
        - parallel:
            - - forward_local_dns
              - if:
                  - match_local_ip
                exec:
                  - _return
                else_exec:
                  - _drop_response
            - - forward_remote_dns
              - if:
                  - match_local_ip
                exec:
                  - _drop_response
                else_exec:
                  - _return
```
上面是我认为并发请求的逻辑
下面是例子结果
![image](https://user-images.githubusercontent.com/30948760/167393518-44cd24f3-0321-44fb-a62e-ba723ff5d499.png)
![image](https://user-images.githubusercontent.com/30948760/167393627-82ee471c-3996-443c-9315-561e91cbe4f8.png)

**Comment by IrineSistiana** [comment]
还是没懂....完全没懂....

**Comment by PussAzuki** [comment]
对于每次从上游返回的DNS查询的结果，只有：
1.存在A结果
2.不存在A结果
3.存在AAAA结果
4.不存在AAAA结果
这时是没问题的，但是并发查询多个上游的话，这之后一般要人为添加判断是否符合预期，但预期只有：
1.符合geoip:cn
2.不符合geoip:cn
但实际情况还有个3.空值 ，而得到空值大都当作被污染了来当作2来处理，于是就出现了一个域名的 A结果是国内的，AAAA结果是国外的 而不是 A结果是国内的，没有AAAA结果 这样的一个问题

**Comment by PussAzuki** [comment]
所以怎样尽可能的不误伤 还能偷懒？

```
        - parallel:
            - - forward_local_dns
              - if:
                  - match_local_ip
                exec:
                  - _return
                else_exec:
                  - _drop_response
            - - forward_remote_dns
              - if:
                  - match_local_ip
                exec:
                  - _drop_response
                else_exec:
                  - _return
```

已知这样只能得到判断过了是否geoip:cn的结果，对AAAA空值没有完全正确的判断，所以或许可以加个允许返回AAAA为空的插件

**Comment by IrineSistiana** [comment]
偷懒：remote 的 if 用“非”

**Comment by PussAzuki** [comment]
但那不是把AAAA的空值判断为属于forward_remote_dns的结果了吗，目前是forward_local_dns对AAAA查询返回空值是有效的啊

**Comment by PussAzuki** [comment]
或者说mosdns通过一个插件来 将一个域名的A和AAAA结果绑定成一个项(?反正就当作特殊的“一个”请求)，然后再向上游请求，得到A和AAAA结果后就保存起来，逻辑看起来像 `_prefer_ipv4/6` 但应该没啥潜在影响？

**Comment by IrineSistiana** [comment]
太麻烦。不可靠。像这种个例不如用白名单处理。

**Comment by PussAzuki** [comment]
那出一个代表 空值 且属于response_matcher的预初始化的插件如何？
这样就能实现选中 geoip:cn 和 空值 了，姑且能填补目前逻辑的缺陷（可能不是最优解，因为这个插件默认是在 匹配远程域名 之后的）

**Comment by PussAzuki** [comment]
```
        - if:
            - remote_query
          exec:
            - remote_forward
            - remote_ipset
            - _return
        - parallel:
            - - local_forward
              - if:
                  - local_response
                exec:
                  - _return
                else_exec:
                  - _block_with_empty_response
                  - _return
            - - remote_forward
              - if:
                  - local_response
                exec:
                  - _drop_response
                else_exec:
                  - _return
```
这样姑且能处理问题？但最好还得是加个空值插件(?)

**Comment by PussAzuki** [comment]
```
        - parallel:
            - - local_forward
              - if:
                  - local_response
                exec:
                  - _return
                else_exec:
                  - _drop_response
            - - remote_forward
              - if:
                  - local_response
                exec:
                  - _block_with_empty_response
                else_exec:
                  - _return
```
似乎，解决了问题？
