### ISSUE TITLE
[Bug] redirect插件似乎不能正确工作

### ISSUE THREAD

**Issue by j4Uq** [IrineSistiana/mosdns#393]
### 在提交之前，请确认

- [X] 我已经尝试搜索过 Issue ，但没有找到相关问题。
- [X] 我正在使用最新的 mosdns 版本(或者最新的 commit)，问题依旧存在。
- [X] 我仔细看过 wiki 后仍然无法自行解决该问题。
- [X] 我非常确定这是 mosdns 核心的问题。(如果是通过第三方衍生软件使用 mosdns 核心，不确定问题源头时，请先向衍生软件开发者提交问题。)

### mosdns 版本

v4.0.0-0-g08cefb3

### 操作系统

openwrt

### Bug 描述和复现步骤

![图片](https://user-images.githubusercontent.com/6436073/175922127-912413cc-1e06-4c62-90e5-dec84f11ca35.png)

### 使用的配置文件

```yaml
log:
  level: info
  file: "/tmp/log/mosdns/running.log"

data_providers:
  - tag: geosite
    file: /etc/mosdns/geosite.dat
    auto_reload: true
  - tag: cn
    file: /etc/mosdns/cn.dat
    auto_reload: true
  - tag: geoip-asn
    file: /etc/mosdns/geoip-asn.dat
    auto_reload: true
  - tag: locallist
    file: /etc/mosdns/locallist.txt
    auto_reload: true
  - tag: proxylist
    file: /etc/mosdns/proxylist.txt
    auto_reload: true
  - tag: blacklist
    file: /etc/mosdns/blacklist.txt
    auto_reload: true

plugins:
  # 缓存
  - tag: cache
    type: cache
    args:
      size: 1024

  - tag: TTL
    type: 'ttl'
    args:
      minimal_ttl: 300
      maximum_ttl: 3600

  - tag: TTL_1
    type: 'ttl'
    args: 
      minimal_ttl: 1
      maximum_ttl: 1

  # 转发至本地服务器的插件
  - tag: forward_local
    type: fast_forward
    args:
      upstream:
        - addr: 127.0.0.1:54
          so_mark: 2

  # 转发至远程服务器的插件
  - tag: forward_remote
    type: fast_forward
    args:
      upstream:
        - addr: 127.0.0.1:55
          so_mark: 2

  # 转发至本地+远程服务器的插件
  - tag: forward_all
    type: fast_forward
    args:
      upstream:
        - addr: 127.0.0.1:6053
          so_mark: 2

  # 转发至代理服务器的插件
  - tag: forward_remote_vps
    type: fast_forward
    args:
      upstream:
        - addr: 127.0.0.1:56
          so_mark: 2

  - tag: redirect
    type: redirect
    args:
      rule:
         - speech.platform.bing.com cn.bing.com

  # 匹配本地域名的插件
  - tag: query_is_local_domain
    type: query_matcher
    args:
      domain:
        - 'provider:locallist'
        - 'provider:geosite:cn'
        - 'provider:geosite:category-games@cn'
        - 'provider:geosite:apple-cn'
        - 'provider:geosite:google-cn'
        - 'provider:geosite:tld-cn'
        - 'provider:geosite:azure@cn'
        - 'provider:geosite:microsoft@cn'

  # 匹配非本地域名的插件
  - tag: query_is_non_local_domain
    type: query_matcher
    args:
      domain:
        - 'provider:geosite:geolocation-!cn'

  # 匹配非广告域名的插件
  - tag: query_is_non_ad_domain
    type: query_matcher
    args:
      domain:
        - 'provider:locallist'
        - 'provider:proxylist'

  # 匹配广告域名的插件
  - tag: query_is_ad_domain
    type: query_matcher
    args:
      domain:
        - 'provider:blacklist'
        - 'provider:geosite:category-ads-all'
        - 'provider:geosite:win-spy'

  # 匹配代理域名的插件
  - tag: query_is_gfwlist_domain
    type: query_matcher
    args:
      domain:
        - 'provider:proxylist'
        - 'provider:geosite:gfw'
        - 'provider:geosite:greatfire'

  # 匹配本地 IP 的插件
  - tag: response_has_local_ip
    type: response_matcher
    args:
      ip:
        - 'provider:cn:cn'

  # 匹配Cloudflare IP 的插件
  - tag: response_is_cf_ip
    type: response_matcher
    args:
      ip:
        - 'provider:geoip-asn:cloudflare'

  # 主要的运行逻辑插件
  # sequence 插件中调用的插件 tag 必须在 sequence 前定义，
  # 否则 sequence 找不到对应插件。
  - tag: main_sequence
    type: sequence
    args:
      exec:
        # 缓存
        #- cache
        - redirect

        # 屏蔽广告域名
        - if: query_is_ad_domain && ! query_is_non_ad_domain
          exec:
            - _new_nxdomain_response
            - _return

        # 已知的代理域名用代理服务器获取的结果
        - if: query_is_gfwlist_domain
          exec:
            - _prefer_ipv4
            - forward_remote_vps
            - TTL_1
            - _return

        # 已知的本地域名用本地服务器解析
        - if: query_is_local_domain
          exec:
            - forward_local
            - _return

        # 已知的非本地域名用远程服务器解析
        - if: query_is_non_local_domain
          exec:
            - forward_remote
            - _return

        - forward_all
          # 剩下的未知域名用 IP 分流。
          # 这里借助了 `fallback` 工作机制。分流原理请参考 `fallback`
          # 的工作流程。
          # primary 从本地服务器获取应答，丢弃非本地 IP 的结果。
        #- primary:
        #    - forward_local
        #    - if: "(! response_has_local_ip) && [_response_valid_answer]"
        #      exec:
        #        - _drop_response
          # secondary 从远程服务器获取应答。
          #secondary:
          #  - _prefer_ipv4
          #  - forward_remote
          # 这里建议设置成 local 服务器正常延时的 2~5 倍。
          # 这个延时保证了 local 延时偶尔变高时，其结果不会被 remote 抢答。
          # 如果 local 超过这个延时还没响应，可以假设 local 出现了问题。
          # 这时用就采用 remote 的应答。单位: 毫秒。
          #fast_fallback: 200

servers:
  - exec: main_sequence
    listeners:
      - protocol: udp
        addr: "[::]:53"
```
