### ISSUE TITLE
[Bug] cannot build sequence: invalid cmd at #2: can not find execuable _single_flight

### ISSUE THREAD

**Issue by pmkol** [IrineSistiana/mosdns#396]
### 在提交之前，请确认

- [X] 我已经尝试搜索过 Issue ，但没有找到相关问题。
- [X] 我正在使用最新的 mosdns 版本(或者最新的 commit)，问题依旧存在。
- [X] 我仔细看过 wiki 后仍然无法自行解决该问题。
- [X] 我非常确定这是 mosdns 核心的问题。(如果是通过第三方衍生软件使用 mosdns 核心，不确定问题源头时，请先向衍生软件开发者提交问题。)

### mosdns 版本

4.0

### 操作系统

centos

### Bug 描述和复现步骤

cannot build sequence: invalid cmd at #2: can not find execuable _single_flight
以上为报错内容

        # 已知的本地域名用本地服务器解析
        - if: query_is_local_domain
          exec:
            - ecs_cn
            - _single_flight
            - forward_alidns
            - _return

将 - _single_flight 屏蔽后配置可以正常启动，- _single_flight 是被取消掉了么？

### 使用的配置文件

```yaml
# 已知的本地域名用本地服务器解析
        - if: query_is_local_domain
          exec:
            - ecs_cn
            - _single_flight
            - forward_alidns
            - _return
```
