### ISSUE TITLE
ipset的黑白名单

### ISSUE THREAD

**Issue by cutemanworking** [IrineSistiana/mosdns#40]
有没可能实现local的查询结果写入一个白名单ipset,  remote的查询结果写入一个黑名单ipset，这样用于iptable分流更有意义。
如果黑白域名都写入一个ipset， 我没想到该如何有效利用.

**Comment by IrineSistiana** [comment]
> 有没可能实现local的查询结果写入一个白名单ipset, remote的查询结果写入一个黑名单ipset

mosdns 同类型的插件也可以想配置几个就配置几个，只要 tag 不一样就行。

> 如果黑白域名都写入一个ipset


没有限制只能用一个 `ipset`。你可以配置多个 `ipset` 插件，然后在不同的地方调用。

**Comment by IrineSistiana** [comment]
```yaml
if:
  - query_is_local
exec: 
  - forward_local
  - add_local_ipset
  - _end

- forward_remote
- add_remote_ipset
```

差不多这个意思？
