### ISSUE TITLE
[Bug] DOH浏览器访问错误400

### ISSUE THREAD

**Issue by pmkol** [IrineSistiana/mosdns#405]
### 在提交之前，请确认

- [X] 我已经尝试搜索过 Issue ，但没有找到相关问题。
- [X] 我正在使用最新的 mosdns 版本(或者最新的 commit)，问题依旧存在。
- [X] 我仔细看过 wiki 后仍然无法自行解决该问题。
- [X] 我非常确定这是 mosdns 核心的问题。(如果是通过第三方衍生软件使用 mosdns 核心，不确定问题源头时，请先向衍生软件开发者提交问题。)

### mosdns 版本

4.1

### 操作系统

centos

### Bug 描述和复现步骤

用浏览器访问DOH地址的时候，是错误400，但用dosproxy一类的程序，转成UDP是没任何问题的，这个是BUG，还是刻意做了什么限制？如果想用浏览器测试的话，应该怎么测试？

### 使用的配置文件

```yaml
servers:
  - exec: main_sequence
    timeout: 2
    listeners:
      - protocol: udp
        addr: "0.0.0.0:53"
      - protocol: tcp
        addr: "0.0.0.0:53"
      - protocol: http
        addr: "0.0.0.0:9053"
        url_path: "/dns-query"
        get_user_ip_from_header: "X-Forwarded-For"
```
