### ISSUE TITLE
[Bug] fast_forward开启socks模式后，缓存更新一些域名时报错

### ISSUE THREAD

**Issue by pmkol** [IrineSistiana/mosdns#412]
### 在提交之前，请确认

- [X] 我已经尝试搜索过 Issue ，但没有找到相关问题。
- [X] 我正在使用最新的 mosdns 版本(或者最新的 commit)，问题依旧存在。
- [X] 我仔细看过 wiki 后仍然无法自行解决该问题。
- [x] 我非常确定这是 mosdns 核心的问题。(如果是通过第三方衍生软件使用 mosdns 核心，不确定问题源头时，请先向衍生软件开发者提交问题。)

### mosdns 版本

4.1

### 操作系统

centos

### Bug 描述和复现步骤

2022-06-30T16:24:04.868+0800	warn	executable_seq/utils.go:37	sequence failed	{"query": "hk-port.iqdnsio.co. IN A 0 6723 114.252.*.*", "sequence": 2, "error": "read tcp 127.0.0.1:46964->127.0.0.1:1090: read: connection reset by peer"}
2022-06-30T16:24:04.868+0800	warn	cache/cache.go:217	failed to update lazy cache	{"query": "hk-port.iqdnsio.co. IN A 0 6723 114.252.*.*", "error": "no response"}
2022-06-30T16:30:08.708+0800	warn	cache/cache.go:217	failed to update lazy cache	{"query": "android.clients.google.com. IN A 56975 8113 221.178.*.*", "error": "read tcp 127.0.0.1:48748->127.0.0.1:1090: read: connection reset by peer"}
2022-06-30T16:38:44.740+0800	warn	cache/cache.go:217	failed to update lazy cache	{"query": "in.appcenter.ms. IN A 0 9394 112.96.*.*", "error": "read tcp 127.0.0.1:50460->127.0.0.1:1090: read: connection reset by peer"}

这些域名貌似都是一些在境内无法访问的域名，不知道为什么会报 connection reset by peer ，目前确定我的代理很稳定，没有丢包，代理是通过shadowsocks的客户端建立的

使用curl --socks5 测试发现主要是两种情况：

第一种，可以直接访问的，也会报connection reset by peer，原因未知；
第二种，是域名本身有问题的，应该是一些有解析结果但服务器本身停止服务的，即使在海外服务器上直接curl访问，一样会超时，看样子是用户访问一些没有及时更新的网站时所出现到缓存里的。

基本上现在log日志里只有这类报错，差不多每小时10~20条的样子，又怕将日志等级设置error的话会错过其它信息，不知道应该如何解决这类问题？

sokcs5模式下可以优化一下么？或者有什么好的解决办法。

### 使用的配置文件

```yaml
- tag: forward_remote_socks
    type: fast_forward
    args:
      upstream:
        - addr: "tcp://127.0.0.1:53"
          socks5: "127.0.0.1:1090"
          enable_pipeline: true

注：127.0.0.1是远程服务器，上面也配置了DNS，所以直接通过127.0.0.1:53就能访问到。
```
