### ISSUE TITLE
[Bug] ipset插件无效和query_matcher插件的qtype选项无效

### ISSUE THREAD

**Issue by PussAzuki** [IrineSistiana/mosdns#419]
### 在提交之前，请确认

- [X] 我已经尝试搜索过 Issue ，但没有找到相关问题。
- [X] 我正在使用最新的 mosdns 版本(或者最新的 commit)，问题依旧存在。
- [X] 我仔细看过 wiki 后仍然无法自行解决该问题。
- [X] 我非常确定这是 mosdns 核心的问题。(如果是通过第三方衍生软件使用 mosdns 核心，不确定问题源头时，请先向衍生软件开发者提交问题。)

### mosdns 版本

v4.1.4-0-g533ada5

### 操作系统

openwrt snapshot

### Bug 描述和复现步骤

在之前的3.9.0版本都是正常可用的

升到4.1.4并按照wiki修改了多次配置文件让程序跑得起来之后发现有这些问题

开了debug 没有发现有ipset记录，使用`ipset list warp`也找不到有添加进去的痕迹

之后也发现没有拦截PTR记录(记录类型是12)

### 使用的配置文件

```yaml
log:
  level: debug
  file: ""

data_providers:
  - tag: geosite
    file: "/etc/mosdns/geosite.dat"
    auto_reload: true
  - tag: anti-ad
    file: "/etc/mosdns/domains.txt"
    auto_reload: true
  - tag: china-ipv4
    file: "/etc/mosdns/china.txt"
    auto_reload: true
  - tag: china-ipv6
    file: "/etc/mosdns/china6.txt"
    auto_reload: true

plugins:

  - tag: local_forward
    type: fast_forward
    args:
      upstream:
        - addr: https://223.6.6.6/dns-query
        - addr: https://1.12.12.12/dns-query

  - tag: remote_forward
    type: fast_forward
    args:
      upstream:
        - addr: https://8.8.4.4/dns-query
        - addr: https://1.0.0.1/dns-query

  - tag: remote_ipset
    type: ipset
    args:
      set_name4: "warp"
      set_name6: "warp6"
      mask4: "24"
      mask6: "64"

  - tag: blocked_query
    type: query_matcher
    args:
      qtype: [12]
      domain:
        - "provider:anti-ad"

  - tag: remote_query
    type: query_matcher
    args:
      domain:
        - "provider:geosite:gfw"
        - "provider:geosite:greatfire"
        - 'keyword:starmap'
        - 'keyword:c3pool'
        - 'xiaomi.eu'
        - 'workers.dev'
        - 'services.googleapis.cn'
        - 'jsdelivr.net'

  - tag: local_response
    type: 'response_matcher'
    args:
      ip:
        - "provider:china-ipv4"
        - "provider:china-ipv6"

  - tag: all_work
    type: sequence
    args:
      exec:
        - if: blocked_query
          exec:
            - _new_nxdomain_response
            - _return
        - if: remote_query
          exec:
            - remote_forward
            - remote_ipset
            - _return
        - primary:
            - local_forward
            - if: "(! local_response) &&  [_response_valid_answer]"
              exec:
                - _return
          secondary:
            - remote_forward
          fast_fallback: 500

servers:
  - exec: all_work
    timeout: 5
    listeners:
      - protocol: udp
        addr: ':1053'
      - protocol: tcp
        addr: ':1053'
```

### mosdns 的 log 记录

```txt
Sun Jul  3 03:26:58 2022 daemon.info mosdns[22848]: 2022-07-02T19:26:58.784Z	debug	executable_seq/if_node.go:164	matcher result	{"query": "www.google.com. IN A 43433 68 127.0.0.1", "tag": "blocked_query", "result": false}
Sun Jul  3 03:26:58 2022 daemon.info mosdns[22848]: 2022-07-02T19:26:58.785Z	debug	executable_seq/if_node.go:173	condition matcher result	{"query": "www.google.com. IN A 43433 68 127.0.0.1", "expr": "blocked_query", "result": false}
Sun Jul  3 03:26:58 2022 daemon.info mosdns[22848]: 2022-07-02T19:26:58.787Z	debug	executable_seq/if_node.go:164	matcher result	{"query": "www.google.com. IN A 43433 68 127.0.0.1", "tag": "remote_query", "result": true}
Sun Jul  3 03:26:58 2022 daemon.info mosdns[22848]: 2022-07-02T19:26:58.788Z	debug	executable_seq/if_node.go:173	condition matcher result	{"query": "www.google.com. IN A 43433 68 127.0.0.1", "expr": "remote_query", "result": true}
Sun Jul  3 03:26:59 2022 daemon.info mosdns[22848]: 2022-07-02T19:26:59.358Z	debug	bundled_upstream/bundled_upstream.go:98	response accepted	{"query": "www.google.com. IN A 43433 68 127.0.0.1", "from": "https://1.0.0.1/dns-query"}
Sun Jul  3 03:26:59 2022 daemon.info mosdns[22848]: 2022-07-02T19:26:59.360Z	debug	dns_handler/server_handler.go:88	entry returned	{"query": "www.google.com. IN A 43433 68 127.0.0.1", "status": "responded"}
Sun Jul  3 03:26:59 2022 daemon.info mosdns[22848]: 2022-07-02T19:26:59.366Z	debug	executable_seq/if_node.go:164	matcher result	{"query": "www.google.com. IN AAAA 56300 69 127.0.0.1", "tag": "blocked_query", "result": false}
Sun Jul  3 03:26:59 2022 daemon.info mosdns[22848]: 2022-07-02T19:26:59.367Z	debug	executable_seq/if_node.go:173	condition matcher result	{"query": "www.google.com. IN AAAA 56300 69 127.0.0.1", "expr": "blocked_query", "result": false}
Sun Jul  3 03:26:59 2022 daemon.info mosdns[22848]: 2022-07-02T19:26:59.368Z	debug	executable_seq/if_node.go:164	matcher result	{"query": "www.google.com. IN AAAA 56300 69 127.0.0.1", "tag": "remote_query", "result": true}
Sun Jul  3 03:26:59 2022 daemon.info mosdns[22848]: 2022-07-02T19:26:59.369Z	debug	executable_seq/if_node.go:173	condition matcher result	{"query": "www.google.com. IN AAAA 56300 69 127.0.0.1", "expr": "remote_query", "result": true}
Sun Jul  3 03:26:59 2022 daemon.info mosdns[22848]: 2022-07-02T19:26:59.554Z	debug	bundled_upstream/bundled_upstream.go:98	response accepted	{"query": "www.google.com. IN AAAA 56300 69 127.0.0.1", "from": "https://1.0.0.1/dns-query"}
Sun Jul  3 03:26:59 2022 daemon.info mosdns[22848]: 2022-07-02T19:26:59.555Z	debug	dns_handler/server_handler.go:88	entry returned	{"query": "www.google.com. IN AAAA 56300 69 127.0.0.1", "status": "responded"}


Sun Jul  3 03:19:38 2022 daemon.info mosdns[22753]: 2022-07-02T19:19:38.467Z	debug	executable_seq/if_node.go:164	matcher result	{"query": "227.38.130.61.in-addr.arpa. IN PTR 40902 19 127.0.0.1", "tag": "blocked_query", "result": false}
Sun Jul  3 03:19:38 2022 daemon.info mosdns[22753]: 2022-07-02T19:19:38.473Z	debug	executable_seq/if_node.go:173	condition matcher result	{"query": "227.38.130.61.in-addr.arpa. IN PTR 40902 19 127.0.0.1", "expr": "blocked_query", "result": false}
```
