### ISSUE TITLE
关于forward插件的一些疑问

### ISSUE THREAD

**Issue by clash1step** [IrineSistiana/mosdns#43]
你好，目前我使用的是1.1.0，关于forward，做了一下配置：
```
  - tag: forward_smartdns 
    type: forward
    args:
      upstream:
        - addr: 127.0.0.1:5351
```
上游服务器用的是smartdns来解析国内域名，目的是利用smartdns的并发请求跟测速，来选择国内最有IP。
刚刚看到1.1.1版本更新了fastest_ip选项，看到issue里面说到是一个类似smartdns的测速功能，那么，我是不是可以通过以下配置，达到跟smartdns一样效果呢
```
  - tag: forward_cn
    type: forward
    args:
      upstream:
        - addr: 223.5.5.5
        - addr: 223.6.6.6
        - addr: 114.114.114.114
        - addr: 114.114.115.115
      fastest_ip: ture
```
这样配置的话，当调用到forward_cn的话，upstream里的所有服务器，是同时发起请求呢，还是逐一请求呢？
