### ISSUE TITLE
[Feature request] fast_forward 支持指定出口网卡

### ISSUE THREAD

**Issue by soffchen** [IrineSistiana/mosdns#432]
**fast_forward 支持指定出口网卡**

fast_forward  目前支持指定 socks5 代理出去，希望可以进一步支持指定 interface，走 wireguard 等 tun/tap 设备出去。

例如:

```
tag: ""
type: "fast_forward"
args:
  upstream:
    - addr: "https://dns.google/dns-query"
      interface: "wg0"
```
