### ISSUE TITLE
[Bug] fast-forward 非pipeline模式的TLS内存泄露

### ISSUE THREAD

**Issue by Coolkids** [IrineSistiana/mosdns#434]
### 在提交之前，请确认

- [X] 我已经尝试搜索过 Issue ，但没有找到相关问题。
- [X] 我正在使用最新的 mosdns 版本(或者最新的 commit)，问题依旧存在。
- [X] 我仔细看过 wiki 后仍然无法自行解决该问题。
- [X] 我非常确定这是 mosdns 核心的问题。(如果是通过第三方衍生软件使用 mosdns 核心，不确定问题源头时，请先向衍生软件开发者提交问题。)

### mosdns 版本

v4.1.5

### 操作系统

openwrt

### Bug 描述和复现步骤

内存泄露
<img width="720" alt="image" src="https://user-images.githubusercontent.com/1288503/178211426-92b42ebb-3264-435f-9abb-a1fd0ff73ae7.png">
[heap.txt](https://github.com/IrineSistiana/mosdns/files/9081750/heap.txt)
[goroutine.txt](https://github.com/IrineSistiana/mosdns/files/9081752/goroutine.txt)
[allocs.txt](https://github.com/IrineSistiana/mosdns/files/9081753/allocs.txt)

### 使用的配置文件

```yaml
log:
  level: info
  file: "/tmp/mosdns.txt"

# 数据源设置
data_providers:
  - tag:                   geosite
    file:                  "/usr/share/v2ray/geosite.dat"
    auto_reload:           false

  - tag:                   geoip
    file:                  "/usr/share/v2ray/geoip.dat"
    auto_reload:           false

  - tag:                   adlist
    file:                  "./rule/serverlist.txt"
    auto_reload:           false

  - tag:                   whitelist
    file:                  "./rule/whitelist.txt"
    auto_reload:           false

  - tag:                   hosts
    file:                  "./rule/hosts.txt"
    auto_reload:           false

  - tag:                   blocklist
    file:                  "./rule/blocklist.txt"
    auto_reload:           false

  - tag:                   local_ptr
    file:                  "./rule/local-ptr.txt"
    auto_reload:           false
    
  - tag:                   redirect
    file:                  "./rule/redirect.txt"
    auto_reload:           false

plugins:
  - tag: "360dns"
    type: fast_forward
    args:
      upstream:
        - addr: https://doh.360.cn/dns-query
          dial_addr: '36.99.170.86:443'

  - tag: "aliyun"
    type: fast_forward
    args:
      upstream:
        - addr: https://dns.alidns.com/dns-query
          dial_addr: '223.5.5.5:443'
        - addr: tls://223.6.6.6
          trusted: true
  - tag: "dnspod"
    type: fast_forward
    args:
      upstream:
        - addr: https://doh.pub/dns-query
          dial_addr: '1.12.12.12:443'
        - addr: tls://120.53.53.53
          trusted: true
          
  - tag: "google"
    type: fast_forward
    args:
      upstream:
        - addr: 'https://dns.google/dns-query'
          dial_addr: '8.8.8.8:443'
          socks5: '127.0.0.1:23456'
        - addr: 'tls://8.8.4.4'
          socks5: '127.0.0.1:23456'
          trusted: true
      
  - tag: "cloudflare"
    type: fast_forward
    args:
      upstream:
        - addr: 'tls://1.0.0.1'
          socks5: '127.0.0.1:23456'
        - addr: "https://cloudflare-dns.com/dns-query"
          dial_addr: '1.1.1.1:443'
          socks5: '127.0.0.1:23456'
          trusted: true

  - tag: "opendns"
    type: fast_forward
    args:
      upstream:
        - addr: "https://doh.opendns.com/dns-query"
          dial_addr: '146.112.41.2'
          socks5: '127.0.0.1:23456'
          trusted: true
  - tag: "quad9"
    type: fast_forward
    args:
      upstream:
        - addr: "https://dns10.quad9.net/dns-query" # 服务器地址
          dial_addr: 9.9.9.10
          trusted: true # 是否是可信服务器
        - addr: "https://dns10.quad9.net/dns-query" # 服务器地址
          dial_addr: 149.112.112.10
          trusted: true # 是否是可信服务器
  # doq 备用
  - tag: adguard
    type: fast_forward
    args:
      upstream:
        - addr: "https://dns-unfiltered.adguard.com/dns-query" # 服务器地址
          dial_addr: 94.140.14.140
          trusted: true # 是否是可信服务器
        - addr: "https://dns-unfiltered.adguard.com/dns-query" # 服务器地址
          dial_addr: 94.140.14.141
          trusted: true # 是否是可信服务器
          
  - tag: localdns
    type: fast_forward
    args:
      upstream:
        - addr: "114.114.114.114"

  # local 序列
  - tag: forward_local
    type: sequence
    args:
      exec:
        - primary:
          - parallel: # 并行
              - - "dnspod" # 执行序列 #2。
              - - "aliyun"
              - - "360dns"
          secondary:
            - localdns # 备用本地
          fast_fallback: 400 # 这里建议设置成 primary 服务器正常延时的 2~5 倍 单位: 毫秒。
          always_standby: true

  # remote 序列
  - tag: forward_remote
    type: sequence
    args:
      exec:
        - primary:
            - parallel: # 并行
                - - "google" # 执行序列 #1。
                - - "cloudflare" # 执行序列 #2。
                - - "opendns"
                - - "quad9"
          secondary:
            - adguard # 备用 adguard
          fast_fallback: 600 # 这里建议设置成 primary 服务器正常延时的 2~5 倍 单位: 毫秒。
          always_standby: true

  - tag: "mem_cache"
    type: cache
    args:
      size: 2048
      lazy_cache_ttl: 17200
  # 修改应答 ttl
  - tag: 'modify_ttl'
    type: 'ttl'
    args:
      minimal_ttl: 300
      maximum_ttl: 3600

  - tag: "query_is_qtype65"
    type:  query_matcher
    args:
      qtype: [65]

  - tag: "query_is_local_ptr"
    type: query_matcher
    args:
      qtype: [12]
      domain:
        - "provider:local_ptr"

  - tag: "query_is_hosts_domain"
    type: hosts
    args:
      hosts:
        - "provider:hosts"

  - tag: "query_is_redirect_domain"
    type: redirect
    args:
      rule:
        - "provider:redirect"

  - tag: "query_is_ad_domain"
    type: query_matcher
    args:
      domain:
        - "provider:geosite:category-ads-all"

  - tag: "query_is_whitelist_domain"
    type: query_matcher
    args:
      domain:
        - "provider:whitelist"

  - tag: "query_is_blocklist_domain"
    type: query_matcher
    args:
      domain:
        - "provider:blocklist"

  # 匹配本地域名的插件
  - tag: "query_is_local_domain"
    type: query_matcher
    args:
      domain:
        - "provider:geosite:icloud,apple-cn,cn"

  - tag: "query_is_gfw"
    type: query_matcher
    args:
      domain:
        - "provider:geosite:greatfire,gfw"

  # 匹配本地 IP 的插件
  - tag: "response_has_local_ip"
    type: response_matcher
    args:
      ip:
        - "provider:geoip:cn"

  - tag: main_sequence
    type: sequence
    args:
      exec:
        - _misc_optm
        - mem_cache
        - query_is_hosts_domain
        - query_is_redirect_domain
        - if: query_is_whitelist_domain
          exec:
            - forward_local
            - _return
        - if: query_is_ad_domain || query_is_blocklist_domain || query_is_qtype65 || query_is_local_ptr
          exec:
            - _new_nxdomain_response
            - _return
        - if: query_is_gfw
          exec:
            - forward_remote
            - _return
        # 本地服务器获取应答。
        - forward_local
        - modify_ttl    

  - tag: second_sequence
    type: sequence
    args:
      exec:
        - _misc_optm
        - mem_cache
        - query_is_hosts_domain
        - query_is_redirect_domain
        - if: query_is_whitelist_domain
          exec:
            - forward_remote
            - _return
        - if: query_is_ad_domain || query_is_blocklist_domain || query_is_qtype65 || query_is_local_ptr
          exec:
            - _new_nxdomain_response
            - _return
        # 已知的本地域名
        - if: query_is_local_domain   
          exec:
            # 用本地服务器获取应答
            - forward_local
            - modify_ttl
            - _return
        - _prefer_ipv4
        - forward_remote
        - modify_ttl

# 服务器设置
servers:
  - exec: main_sequence
    listeners:
      - protocol: udp
        addr: "[::1]:5335"
      - protocol: tcp
        addr: "[::1]:5335"
      - protocol: udp
        addr: "127.0.0.1:5335"
      - protocol: tcp
        addr: "127.0.0.1:5335"
  - exec: second_sequence
    listeners:
      - protocol: udp
        addr: "[::1]:5336"
      - protocol: tcp
        addr: "[::1]:5336"
      - protocol: udp
        addr: "127.0.0.1:5336"
      - protocol: tcp
        addr: "127.0.0.1:5336"

# API 入口设置     
api:
  http: "0.0.0.0:3000"
```

**Comment by IrineSistiana** [comment]
@Coolkids 采样数据下载错了。下载时请不要加 `?debug=1` 的后缀。

https://irine-sistiana.gitbook.io/mosdns-wiki/mosdns/debug-nei-cun-yu-xing-neng-wen-ti

**Comment by Coolkids** [comment]
@IrineSistiana  [dump.zip](https://github.com/IrineSistiana/mosdns/files/9082003/dump.zip)

**Comment by Coolkids** [comment]
@IrineSistiana   最新的代码还是内存泄露
<img width="704" alt="image" src="https://user-images.githubusercontent.com/1288503/178410154-58ba3fdf-51c7-4f1c-a74c-d5af4277a5c0.png">

[dump.zip](https://github.com/IrineSistiana/mosdns/files/9089556/dump.zip)

**Comment by IrineSistiana** [comment]
问题应该是在 fastforward 的 tls 的协议里。你可以先避免用 tls 的上游。

update：问题应该在没开启 pipeline 的 tcp/tls 协议里。

**Comment by sbwml** [comment]
> 问题应该是在 fastforward 的 tls 的协议里。你可以先避免用 tls 的上游。

应该和tls没关系，我一直在使用 tls的 fast_forward，但是还遇到过内存泄漏的现象（4.x 任何版本），内存一直在52-56M ，cache 20万条

![IMG_4342(20220712-175727)](https://user-images.githubusercontent.com/16485166/178464564-9b24e251-2eab-43f8-9b1a-600c7ed327a9.PNG)

**Comment by IrineSistiana** [comment]
@sbwml 具体点说，应该是没开启 pipeline 的 tcp/tls 有泄漏。

你开 pipeline 了么？

**Comment by sbwml** [comment]
> @sbwml 具体点说，应该是没开启 pipeline 的 tcp/tls 有泄漏。
> 
> 你开 pipeline 了么？

我不清楚，配置文件我没有去定义 ```enable_pipeline```

**Comment by IrineSistiana** [comment]
@sbwml 那就是没开。

目前还不知道泄漏原因。但有 @Coolkids 的内存pppof能确定是源头是没开启 pipeline 的 tls。tcp 大概率也会，因为和tls用的一套代码。

**Comment by sbwml** [comment]
> @sbwml 那就是没开。
> 
> 目前还不知道泄漏原因。但有 @Coolkids 的内存pppof能确定是源头是没开启 pipeline 的 tls。tcp 大概率也会，因为和tls用的一套代码。

我另一个设备没来得及更新  跑的v4.1.2，forward_local 是`tls://`  ，forward_remote 是`https://` + `tls://`，进程运行了有11天，常驻内存占用55M，看起来没什么问题，可对比上面https://github.com/IrineSistiana/mosdns/issues/434#issuecomment-1181308481 就很迷惑。。。

**Comment by qingtian110** [comment]
> > @sbwml 具体点说，应该是没开启 pipeline 的 tcp/tls 有泄漏。
> > 你开 pipeline 了么？
> 
> 我不清楚，配置文件我没有去定义 `enable_pipeline`

可以给openwrt luci 默认配置加一个 pipeline 的开关选项吗？

看Wiki，好像很有用的样子

enable_pipeline: TCP/DoT 使用 RFC 7766 新的 query pipelining 连接复用模式。
启用后可大幅提高连接利用率，减少建立连接/握手的次数，进而降低延时。
并非所有服务器都支持。必须确定服务器支持后再启用该选项。
Tips: 已知 Google 和 Cloudflare 的 TCP/DoT 都是支持的。知名的公共 DNS 服务商大多数都支持该模式。mosdns 自带一个测试命令可以测试服务器是否支持该模式。

而且luci 预设的公共tls:// dns  用 `mosdns probe pipeline tls://xxxxxx` 测试全部是支持的 server supports RFC7766 query pipelining

**Comment by sbwml** [comment]
> 

。。。能是能，但是。。我不知道怎么叫它，中文翻译怎么喊它

**Comment by sbwml** [comment]
> > > @sbwml 具体点说，应该是没开启 pipeline 的 tcp/tls 有泄漏。
> > > 你开 pipeline 了么？
> > 
> > 
> > 我不清楚，配置文件我没有去定义 `enable_pipeline`
> 
> 可以给openwrt luci 默认配置加一个 pipeline 的开关选项吗？
> 
> 看Wiki，好像很有用的样子
> 
> enable_pipeline: TCP/DoT 使用 RFC 7766 新的 query pipelining 连接复用模式。 启用后可大幅提高连接利用率，减少建立连接/握手的次数，进而降低延时。 并非所有服务器都支持。必须确定服务器支持后再启用该选项。 Tips: 已知 Google 和 Cloudflare 的 TCP/DoT 都是支持的。知名的公共 DNS 服务商大多数都支持该模式。mosdns 自带一个测试命令可以测试服务器是否支持该模式。
> 
> 而且luci 预设的公共tls:// dns 用 `mosdns probe pipeline tls://xxxxxx` 测试全部是支持的 server supports RFC7766 query pipelining

。。。能是能，但是。。我不知道怎么叫它，中文翻译怎么喊它

**Comment by Coolkids** [comment]
> 问题应该是在 fastforward 的 tls 的协议里。你可以先避免用 tls 的上游。
> 
> update：问题应该在没开启 pipeline 的 tcp/tls 协议里。

确实是这个问题 我换成DoH后就正常了

**Comment by j4Uq** [comment]
```
log:
  level: info
  file: ""

data_providers:
  - tag: geosite
    file: ./geosite.dat
    auto_reload: true
  - tag: locallist
    file: ./locallist.txt
    auto_reload: true
  - tag: proxylist
    file: ./proxylist.txt
    auto_reload: true
  - tag: blacklist
    file: ./blacklist.txt
    auto_reload: true

plugins:
  # 修改ttl为1
  - tag: TTL
    type: ttl
    args: 
      minimal_ttl: 1
      maximum_ttl: 1

  # 转发至本地服务器的插件
  - tag: forward_local
    type: fast_forward
    args:
      upstream:
        - addr: 127.0.0.1:54
          so_mark: 2

  # 转发至远程服务器的插件
  - tag: forward_remote
    type: fast_forward
    args:
      upstream:
        - addr: 127.0.0.1:55
          so_mark: 2

  # 转发至本地+远程服务器的插件
  - tag: forward_all
    type: fast_forward
    args:
      upstream:
        - addr: 127.0.0.1:6053
          so_mark: 2

  # 转发至代理服务器的插件
  - tag: forward_remote_vps
    type: fast_forward
    args:
      upstream:
        - addr: 127.0.0.1:56
          so_mark: 2

  # 将指定域名的解析指向另一个域名
  - tag: redirect
    type: redirect
    args:
      rule:
         - speech.platform.bing.com cn.bing.com

  # 匹配本地域名的插件
  - tag: query_is_local_domain
    type: query_matcher
    args:
      domain:
        - 'provider:locallist'
        - 'provider:geosite:cn,category-games@cn,apple-cn,google-cn,tld-cn,azure@cn,microsoft@cn'

  # 匹配非本地域名的插件
  - tag: query_is_non_local_domain
    type: query_matcher
    args:
      domain:
        - 'provider:geosite:geolocation-!cn'

  # 匹配非广告域名的插件
  - tag: query_is_non_ad_domain
    type: query_matcher
    args:
      domain:
        - 'provider:locallist'
        - 'provider:proxylist'

  # 匹配广告域名的插件
  - tag: query_is_ad_domain
    type: query_matcher
    args:
      domain:
        - 'provider:blacklist'
        - 'provider:geosite:category-ads-all,win-spy'

  # 匹配代理域名的插件
  - tag: query_is_gfwlist_domain
    type: query_matcher
    args:
      domain:
        - 'provider:proxylist'
        - 'provider:geosite:gfw,greatfire'

  # 匹配本地 IP 的插件
  #- tag: response_has_local_ip
  #  type: response_matcher
  #  args:
  #    ip:
  #      - 'provider:cn:cn'

  # 主要的运行逻辑插件
  # sequence 插件中调用的插件 tag 必须在 sequence 前定义，
  # 否则 sequence 找不到对应插件。
  - tag: main_sequence
    type: sequence
    args:
      exec:
        - _misc_optm
        - redirect

        # 屏蔽广告域名
        - if: query_is_ad_domain && ! query_is_non_ad_domain
          exec:
            - _new_nxdomain_response
            - _return

        # 已知的本地域名用本地服务器解析
        - if: query_is_local_domain
          exec:
            - forward_local
            - _return

        # 已知的代理域名用代理服务器获取的结果
        - if: query_is_gfwlist_domain
          exec:
            - _prefer_ipv4
            - forward_remote_vps
            - TTL
            - _return

        # 已知的非本地域名用远程服务器解析
        - if: query_is_non_local_domain
          exec:
            - forward_remote
            - _return

        - forward_all

servers:
  - exec: main_sequence
    listeners:
      - protocol: udp
        addr: "[::]:53"

```
我也遇到内存泄漏了，用的最新版，刚刚偶然去openwrt看了下cpu占用发现的，因为没有设置保存日志，系统日志记录只看到全是
`Tue Jul 12 21:48:28 2022 daemon.info mosdns[8502]: 2022-07-12T21:48:24.394+0800	warn	dns_handler/server_handler.go:86	entry returned an err	{"query": "cdn-china.ampproject.org. IN HTTPS 24624 2608349 127.0.0.1", "error": "context deadline exceeded"}
`
因为我上游全是udp，且mosdns只是用来分流，所以似乎和楼上的情况不太一样，日志记录的这个域名指向127.0.0.1：56这个上游，这个上游是xray提供的fakedns，我本地dig这个域名是能正常解析出结果的，说明还没卡死。
看cpu占用的话mosdns占了60%，剩下基本被xray占了，mosdns一直在不断向上游发起解析这个域名，重启mosdns后，世界都安静了
