### ISSUE TITLE
[Feature request] ecs插件支持动态设置或加载ipv4,  解决VPN内网下DNS的CDN问题

### ISSUE THREAD

**Issue by xiaolei0125** [IrineSistiana/mosdns#447]
**希望添加的功能**

在ecs插件中可以支持动态设置或加载ipv4地址
```
type: "ecs"
args:
  auto: false                         # 是否自动将用户请求的来源地址作为 ECS 附加到请求。
  ipv4: 'provider:my_ecs_ip.'         # 预设的 IPv4 地址。会优先附加在 A 请求里。
```
**需求背景：**
- 架设环境：mosdns架设在内网，手机在移动或WIFI网络上使用WireGuard VPN连接到内网，并使用mosdns作为VPN的DNS，用来访问内网的服务，以及分流去广告等。
- 面临问题：手机端访问国内网站使用自身的移动网络, 不走VPN， 但DNS是通过家里宽带网络的mosdns解析，对4G或其他WIFI网络CDN效果不佳。而且手机app通过VPN内网访问mosdns,  mosdns无法获取DNS请求报文携带的公网出口源IP， 无法直接使用ecs插件的auto功能。而且手机是移动的使用的网络环境不同，所以ecs的ipv4是无法固定或预设的。
- 解决办法： 自己编写代码获取VPN下手机的移动网络出口IP,  将出口IP保存到my_ecs_ip.txt文件，然后通过ecs插件的ipv4: 'provider:my_ecs_ip.'  自动加载， 如果ecs ipv4能支持provider的话。

**总结说明：** 
-  mosdns的架构设计非常优秀，目前使用mosdns几乎能满足我所有DNS相关的需求。非常感谢@IrineSistiana 提供这么好的软件！
- 大多数使用VPN的场景下，通过VPN网络访问内网的mosdns,  应该都会面临这种CDN的问题，希望ecs插件能提供相关的支持，谢谢！
