### ISSUE TITLE
[Bug] docker 环境变量TZ是Asia/Shanghai系统时间还是UTC

### ISSUE THREAD

**Issue by edwardostara** [IrineSistiana/mosdns#456]
### 在提交之前，请确认

- [X] 我已经尝试搜索过 Issue ，但没有找到相关问题。
- [X] 我正在使用最新的 mosdns 版本(或者最新的 commit)，问题依旧存在。
- [X] 我仔细看过 wiki 后仍然无法自行解决该问题。
- [X] 我非常确定这是 mosdns 核心的问题。(如果是通过第三方衍生软件使用 mosdns 核心，不确定问题源头时，请先向衍生软件开发者提交问题。)

### mosdns 版本

v4.1.8

### 操作系统

docker

### Bug 描述和复现步骤

创建容器不设置TZ，也是默认Asia/Shanghai，发现时间不对。重建容器并设置了TZ，容器内部还是UTC。
![msedge_sDc28DGHG0](https://user-images.githubusercontent.com/44975278/182376343-f20bdebd-4537-4410-b98b-6cd141b0e2e7.png)
![msedge_21WNVCPYHW](https://user-images.githubusercontent.com/44975278/182376355-c61a7b4a-7909-48b1-ba89-e7a9c4fd810f.png)
好像alpine 默认不包含时区数据包
虽然利用apk add tzdata 命令安装了tzdata，并利用cp /usr/share/zoneinfo/Asia/Shanghai /etc/loacltime 做了映射后，解决了。但是不能每次都这样，希望开发者闲暇之余，能够关注下，如果能够解决掉，就再好不过了。在此拜谢。

### 使用的配置文件

```yaml
log:
  level: warn
  file: ""

# 数据源
data_providers:
  - tag: geoip
    file: /etc/mosdns/geoip.dat
  - tag: geosite
    file: /etc/mosdns/geosite.dat


plugins:
  ################# 可执行插件 ################
  # 缓存
  - tag: "mem_cache"
    type: "cache"
    args:
      size: 1024 # 条目数量
      lazy_cache_ttl: 86400 # lazy cache 生存时间 一天
      lazy_cache_reply_ttl: 30 # 返回过期应答的 TTL
      cache_everything: true # 有大量 edns 时启用

  - tag: "ecs-cn"
    type: "ecs"
    args:
      auto: false # 仅适用于公网的服务器。本地运行不要启用这个功能。
      ipv4: "202.120.35.132"
      ipv6: "2001:da8:8000:1:202:120:2:101"
      force_overwrite: true # 强制覆盖
      mask4: 24 # 用于 ipv4 地址的掩码 默认: 24。
      mask6: 48 # 用于 ipv6 地址的掩码 默认: 48。

  # 修改应答 ttl
  - tag: "modify_ttl"
    type: "ttl"
    args:
      minimal_ttl: 300
      maximum_ttl: 3600

  ################ DNS #################
  # 阿里 dns
  - tag: ali
    type: forward
    args:
      upstream:
        - addr: "https://dns.alidns.com/dns-query" # 服务器地址
          ip_addr: # 手动指定服务器的 IP 地址 可以配置多个
            - "223.5.5.5"
            - "223.6.6.6"
            - "2400:3200:baba::1"
            - "2400:3200::1"
          trusted: true # 是否是可信服务器
        - addr: "tls://dns.alidns.com" # 服务器地址
          ip_addr: # 手动指定服务器的 IP 地址 可以配置多个
            - "223.5.5.5"
            - "223.6.6.6"
            - "2400:3200:baba::1"
            - "2400:3200::1"
          trusted: true # 是否是可信服务器

      bootstrap:
        - "tls://1.1.1.1"
        - "https://223.5.5.5/dns-query"
      timeout: 5 # 请求超时时间秒

  # dnspod
  - tag: dnspod
    type: forward
    args:
      upstream:
        - addr: "https://doh.pub/dns-query" # 服务器地址
          ip_addr: # 手动指定服务器的 IP 地址 可以配置多个
            - "2402:4e00::"
            - "119.29.29.29"
          trusted: true # 是否是可信服务器
        - addr: "tls://dot.pub" # 服务器地址
          ip_addr: # 手动指定服务器的 IP 地址 可以配置多个
            - "2402:4e00::"
            - "119.29.29.29"
          trusted: true # 是否是可信服务器

      bootstrap:
        - "tls://1.1.1.1"
        - "https://223.5.5.5/dns-query"
      timeout: 5 # 请求超时时间秒

  # 本地 dns 备用
  - tag: localdns
    type: forward
    args:
      upstream:
        - addr: "192.168.1.1"

  # google dns
  - tag: google
    type: forward
    args:
      upstream:
        - addr: "https://dns.google/dns-query" # 服务器地址
          ip_addr: # 手动指定服务器的 IP 地址 可以配置多个
            - "2001:4860:4860::8844"
            - "8.8.4.4"
            - "2001:4860:4860::8888"
            - "8.8.8.8"
          trusted: true # 是否是可信服务器

  # cloudflare
  - tag: cloudflare
    type: forward
    args:
      upstream:
        - addr: "https://cloudflare-dns.com/dns-query" # 服务器地址
          ip_addr: # 手动指定服务器的 IP 地址 可以配置多个
            - "2606:4700:4700::1001"
            - "1.0.0.1"
            - "2606:4700:4700::1111"
            - "1.1.1.1"
          trusted: true # 是否是可信服务器

  # google dns
  - tag: google_dot
    type: fast_forward
    args:
      upstream:
        - addr: "tls://dns.google"
          dial_addr: "8.8.4.4"
          trusted: true
          enable_pipeline: true
        - addr: "tls://dns.google"
          dial_addr: "2001:4860:4860::8888"
          trusted: true
          enable_pipeline: true
        - addr: "tls://dns.google"
          dial_addr: "8.8.8.8"
          trusted: true
          enable_pipeline: true

  # cloudflare
  - tag: cloudflare_dot
    type: fast_forward
    args:
      upstream:
        - addr: "tls://1dot1dot1dot1.cloudflare-dns.com"
          dial_addr: "2606:4700:4700::1001"
          trusted: true
          enable_pipeline: true
        - addr: "tls://1dot1dot1dot1.cloudflare-dns.com"
          dial_addr: "1.0.0.1"
          trusted: true
          enable_pipeline: true
        - addr: "tls://1dot1dot1dot1.cloudflare-dns.com"
          dial_addr: "2606:4700:4700::1111"
          trusted: true
          enable_pipeline: true
        - addr: "tls://1dot1dot1dot1.cloudflare-dns.com"
          dial_addr: "1.0.0.1"
          trusted: true
          enable_pipeline: true

  - tag: google_h3
    type: "fast_forward"
    args:
      # 上游服务器。至少要配置一个。可配置多个，会并发请求全部服务器。
      upstream:
        - addr: "https://dns.google/dns-query"
          dial_addr: "2001:4860:4860::8844"
          trusted: true
          enable_http3: true
        - addr: "https://dns.google/dns-query"
          dial_addr: "8.8.4.4"
          trusted: true
          enable_http3: true
        - addr: "https://dns.google/dns-query"
          dial_addr: "2001:4860:4860::8888"
          trusted: true
          enable_http3: true
        - addr: "https://dns.google/dns-query"
          dial_addr: "8.8.8.8"
          trusted: true
          enable_http3: true

  - tag: cloudflare_h3
    type: "fast_forward"
    args:
      upstream:
        - addr: "https://cloudflare-dns.com/dns-query"
          dial_addr: "2606:4700:4700::1001"
          trusted: true
          enable_http3: true
        - addr: "https://cloudflare-dns.com/dns-query"
          dial_addr: "1.0.0.1"
          trusted: true
          enable_http3: true
        - addr: "https://cloudflare-dns.com/dns-query"
          dial_addr: "2606:4700:4700::1111"
          trusted: true
          enable_http3: true
        - addr: "https://cloudflare-dns.com/dns-query"
          dial_addr: "1.1.1.1"
          trusted: true
          enable_http3: true

  # doq 备用
  - tag: adguard
    type: forward
    args:
      upstream:
        - addr: "quic://dns-unfiltered.adguard.com" # 服务器地址
          ip_addr: # 手动指定服务器的 IP 地址 可以配置多个
            - "2a10:50c0::1:ff"
            - "94.140.14.140"
            - "2a10:50c0::2:ff"
            - "94.140.14.141"
          trusted: true # 是否是可信服务器

  ################ 匹配器 #################

  # 查询 - cn 域名
  - tag: query_cn
    type: query_matcher
    args:
      domain:
        - "provider:geosite:cn"

  # 查询 - gfw
  - tag: query_gfw
    type: query_matcher
    args:
      domain:
        - "provider:geosite:gfw"

  # 查询 - 非 cn 域名
  - tag: query_notcn
    type: query_matcher
    args:
      domain:
        - "provider:geosite:geolocation-!cn"

  # 查询 - ad
  - tag: query_ad
    type: query_matcher
    args:
      domain:
        - "provider:geosite:category-ads-all"

  # 返回 - cn IP
  - tag: response_cnip
    type: response_matcher
    args:
      ip:
        - "provider:geoip:cn"

  ################ 序列 #################

  # local 序列
  - tag: local
    type: sequence
    args:
      exec:
        # - primary:
        - parallel: # 并行
            - - "ali" # 执行序列 #1。
            - - "dnspod" # 执行序列 #2。
        # secondary:
        #   - localdns # 备用本地
        # fast_fallback: 600 # 这里建议设置成 primary 服务器正常延时的 2~5 倍 单位: 毫秒。
        # always_standby: true

  # remote 序列
  - tag: remote
    type: sequence
    args:
      exec:
        # - primary:
        - parallel: # 并行
            - - google
            - - cloudflare
            - - google_dot # 执行序列 #1。
            - - cloudflare_dot # 执行序列 #2。
            - - adguard # 备用 adguard
            - - google_h3
            - - cloudflare_h3
        # secondary:
        #   - adguard # 备用 adguard
        # fast_fallback: 600 # 这里建议设置成 primary 服务器正常延时的 2~5 倍 单位: 毫秒。
        # always_standby: true

  # main_sequence
  - tag: main_sequence
    type: sequence
    args:
      exec:
        - if: query_ad # ad
          exec:
            - _new_nxdomain_response # 空应答
            - _return

        - if: "query_cn" # cn域名
          exec:
            - ecs-cn
            - _pad_query
            - local # 用本地服务器
            - if: "response_cnip" # 结果是 cnip
              exec:
                - _return # 结束

        - if: query_notcn # 已知的 非cn域名
          exec:
            - _prefer_ipv4 # 优先 IPv4
            - _pad_query
            - remote # 无污染
            - if: "!response_cnip" # 结果是 非cnip
              exec:
                - _return # 结束

        - primary: #其他所有情况
            - _prefer_ipv4
            - _pad_query
            - remote
          secondary:
            - _prefer_ipv4
            - _pad_query
            - local
          fast_fallback: 400 # 这里建议设置成 local 服务器正常延时的 2~5 倍 单位: 毫秒
          always_standby: true

  - tag: sequence
    type: sequence
    args:
      exec:
        - mem_cache # 缓存
        - main_sequence # 运行主执行序列
        - modify_ttl # 修改 ttl

servers:
  - exec: sequence
    listeners:
      - protocol: udp
        addr: ":53"
      - protocol: tcp
        addr: ":53"
```

### mosdns 的 log 记录

```txt
2022-08-02T12:27:48.060Z        info    coremain/run.go:107     working directory changed       {"path": "/etc/mosdns"}
2022-08-02T12:47:01.661Z        warn    executable_seq/utils.go:37      sequence failed {"query": "youtube.com. IN A 46483 5 127.0.0.1", "sequence": 0, "error": "requesting https://dns.google:443/dns-query: Get \"https://dns.google:443/dns-query?dns=tZMBIAABAAAAAAABB3lvdXR1YmUDY29tAAABAAEAACkQAAAAAAAAWAAKAAiCjbP92PPmqAAMAEgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\": read tcp [240e:3a1:365c:252::2a2]:55254->[2001:4860:4860::8844]:443: read: connection reset by peer"}
2022-08-02T12:47:23.362Z        warn    bundled_upstream/bundled_upstream.go:93 upstream failed {"query": "google.com. IN A 45842 6 127.0.0.1", "from": "tls://dns.google", "error": "read tcp 192.168.50.211:55846->8.8.4.4:853: read: connection reset by peer"}
```
