### ISSUE TITLE
[Bug] 访问Onedirver, sharepoint等网站，日志报错

### ISSUE THREAD

**Issue by xuesumin** [IrineSistiana/mosdns#460]
### 在提交之前，请确认

- [X] 我已经尝试搜索过 Issue ，但没有找到相关问题。
- [X] 我正在使用最新的 mosdns 版本(或者最新的 commit)，问题依旧存在。
- [X] 我仔细看过 wiki 后仍然无法自行解决该问题。
- [X] 我非常确定这是 mosdns 核心的问题。(如果是通过第三方衍生软件使用 mosdns 核心，不确定问题源头时，请先向衍生软件开发者提交问题。)

### mosdns 版本

v4.1.9

### 操作系统

OpenWrt

### Bug 描述和复现步骤

	upstream failed	{"query": "api.onedrive.com. IN AAAA 44588 230184 127.0.0.1", "from": "tls://8.8.8.8", "error": "EOF"}
2022-08-11T20:51:59.167Z	warn	cache/cache.go:217	failed to update lazy cache	{"query": "api.onedrive.com. IN AAAA 44588 230184 127.0.0.1", "error": "no response"}
2022-08-11T20:51:59.170Z	warn	bundled_upstream/bundled_upstream.go:93	upstream failed	{"query": "api.onedrive.com. IN A 44569 230183 127.0.0.1", "from": "tls://8.8.8.8", "error": "EOF"}
2022-08-11T20:51:59.170Z	warn	cache/cache.go:217	failed to update lazy cache	{"query": "api.onedrive.com. IN A 44569 230183 127.0.0.1", "error": "no response"}
2022-08-11T20:52:00.335Z	warn	bundled_upstream/bundled_upstream.go:93	upstream failed	{"query": "www.google.com. IN A 11211 230213 127.0.0.1", "from": "tls://1.1.1.1", "error": "EOF"}
2022-08-11T20:52:00.356Z	warn	bundled_upstream/bundled_upstream.go:93	upstream failed	{"query": "www.google.com. IN A 11211 230213 127.0.0.1", "from": "tls://8.8.8.8", "error": "EOF"}
2022-08-11T20:52:00.356Z	warn	cache/cache.go:217	failed to update lazy cache	{"query": "www.google.com. IN A 11211 230213 127.0.0.1", "error": "no response"}
2022-08-11T20:52:01.088Z	warn	bundled_upstream/bundled_upstream.go:93	upstream failed	{"query": "utler-my.sharepoint.com. IN AAAA 50868 230229 127.0.0.1", "from": "tls://8.8.8.8", "error": "EOF"}
2022-08-11T20:52:01.110Z	warn	bundled_upstream/bundled_upstream.go:93	upstream failed	{"query": "utler-my.sharepoint.com. IN A 50868 230229 127.0.0.1", "from": "tls://1.1.1.1", "error": "EOF"}

### 使用的配置文件

```yaml
log:
  level: info
  file: "/tmp/mosdns.log"

include: []

data_providers:
  - tag: geoip
    file: "/usr/share/v2ray/geoip.dat"
    auto_reload: true

  - tag: geosite
    file: "/usr/share/v2ray/geosite.dat"
    auto_reload: true

  - tag: whitelist
    file: "/etc/mosdns/rule/whitelist.txt"
    auto_reload: true

  - tag: blocklist
    file: "/etc/mosdns/rule/blocklist.txt"
    auto_reload: true

  - tag: greylist
    file: "/etc/mosdns/rule/greylist.txt"
    auto_reload: true

  - tag: hosts
    file: "/etc/mosdns/rule/hosts.txt"
    auto_reload: true

  - tag: redirect
    file: "/etc/mosdns/rule/redirect.txt"
    auto_reload: true

  - tag: local_ptr
    file: "/etc/mosdns/rule/local-ptr.txt"
    auto_reload: true

plugins:
  - tag: lazy_cache
    type: cache
    args:
      size: 200000
      lazy_cache_ttl: 259200

  - tag: modify_ttl
    type: ttl
    args:
      minimal_ttl: 0
      maximum_ttl: 0

  - tag: "forward_local"
    type: fast_forward
    args:
      upstream:
        - addr: 218.85.152.99
        - addr: 218.85.157.99

  - tag: "forward_remote"
    type: fast_forward
    args:
      upstream:
        - addr: tls://8.8.8.8
          enable_pipeline: false
        - addr: tls://1.1.1.1
          enable_pipeline: false

  - tag: query_is_whitelist_domain
    type: query_matcher
    args:
      domain:
        - "provider:whitelist"

  - tag: query_is_blocklist_domain
    type: query_matcher
    args:
      domain:
        - "provider:blocklist"

  - tag: query_is_greylist_domain
    type: query_matcher
    args:
      domain:
        - "provider:greylist"

  - tag: query_is_hosts_domain
    type: hosts
    args:
      hosts:
        - "provider:hosts"

  - tag: query_is_redirect_domain
    type: redirect
    args:
      rule:
        - "provider:redirect"

  - tag: query_is_local_domain
    type: query_matcher
    args:
      domain:
        - "provider:geosite:cn,apple-cn,icloud,google-cn,tld-cn"

  - tag: query_is_non_local_domain
    type: query_matcher
    args:
      domain:
        - "provider:geosite:geolocation-!cn"

  - tag: response_has_local_ip
    type: response_matcher
    args:
      ip:
        - "provider:geoip:cn"

  - tag: query_is_ad_domain
    type: query_matcher
    args:
      domain:
        - "full:disable-category-ads-all.null"

  - tag: match_local_ptr
    type: query_matcher
    args:
      qtype: [12]
      domain:
        - "provider:local_ptr"

  - tag: match_qtype65
    type: query_matcher
    args:
      qtype: [65]

  - tag: "main_sequence"
    type: "sequence"
    args:
      exec:
        - query_is_hosts_domain
        - query_is_redirect_domain

        - if: query_is_whitelist_domain
          exec:
            - forward_local
            - modify_ttl
            - _return

        - if: "query_is_blocklist_domain || query_is_ad_domain || match_local_ptr || match_qtype65"
          exec:
            - _new_nxdomain_response
            - _return

        - lazy_cache

        - if: query_is_greylist_domain
          exec:
            - forward_remote
            - modify_ttl
            - _return

        - if: query_is_local_domain
          exec:
            - forward_local
            - modify_ttl
            - _return

        - if: query_is_non_local_domain
          exec:
            - _prefer_ipv4
            - forward_remote
            - modify_ttl
            - _return
        - primary:
            - forward_local
            - if: "(! response_has_local_ip) && [_response_valid_answer]"
              exec:
                - _drop_response
          secondary:
            - _prefer_ipv4
            - forward_remote
            - modify_ttl
          fast_fallback: 200

servers:
  - exec: main_sequence
    listeners:
      - protocol: udp
        addr: ":5335"
      - protocol: tcp
        addr: ":5335"
```

### mosdns 的 log 记录

```txt
upstream failed	{"query": "api.onedrive.com. IN AAAA 44588 230184 127.0.0.1", "from": "tls://8.8.8.8", "error": "EOF"}
2022-08-11T20:51:59.167Z	warn	cache/cache.go:217	failed to update lazy cache	{"query": "api.onedrive.com. IN AAAA 44588 230184 127.0.0.1", "error": "no response"}
2022-08-11T20:51:59.170Z	warn	bundled_upstream/bundled_upstream.go:93	upstream failed	{"query": "api.onedrive.com. IN A 44569 230183 127.0.0.1", "from": "tls://8.8.8.8", "error": "EOF"}
2022-08-11T20:51:59.170Z	warn	cache/cache.go:217	failed to update lazy cache	{"query": "api.onedrive.com. IN A 44569 230183 127.0.0.1", "error": "no response"}
2022-08-11T20:52:00.335Z	warn	bundled_upstream/bundled_upstream.go:93	upstream failed	{"query": "www.google.com. IN A 11211 230213 127.0.0.1", "from": "tls://1.1.1.1", "error": "EOF"}
2022-08-11T20:52:00.356Z	warn	bundled_upstream/bundled_upstream.go:93	upstream failed	{"query": "www.google.com. IN A 11211 230213 127.0.0.1", "from": "tls://8.8.8.8", "error": "EOF"}
2022-08-11T20:52:00.356Z	warn	cache/cache.go:217	failed to update lazy cache	{"query": "www.google.com. IN A 11211 230213 127.0.0.1", "error": "no response"}
2022-08-11T20:52:01.088Z	warn	bundled_upstream/bundled_upstream.go:93	upstream failed	{"query": "utler-my.sharepoint.com. IN AAAA 50868 230229 127.0.0.1", "from": "tls://8.8.8.8", "error": "EOF"}
2022-08-11T20:52:01.110Z	warn	bundled_upstream/bundled_upstream.go:93	upstream failed	{"query": "utler-my.sharepoint.com. IN A 50868 230229 127.0.0.1", "from": "tls://1.1.1.1", "error": "EOF"}
```
