### ISSUE TITLE
[Bug] unexpected character, want colon (at "xt:/etc/mosdns")

### ISSUE THREAD

**Issue by kinist** [IrineSistiana/mosdns#467]
### 在提交之前，请确认

- [X] 我已经尝试搜索过 Issue ，但没有找到相关问题。
- [X] 我正在使用最新的 mosdns 版本(或者最新的 commit)，问题依旧存在。
- [X] 我仔细看过 wiki 后仍然无法自行解决该问题。
- [X] 我非常确定这是 mosdns 核心的问题。(如果是通过第三方衍生软件使用 mosdns 核心，不确定问题源头时，请先向衍生软件开发者提交问题。)

### mosdns 版本

4.19

### 操作系统

docker

### Bug 描述和复现步骤

启动的时候报错
fatal	v4/main.go:48	mosdns exited, failed to init plugin #4, failed to load data ext:/etc/mosdns/geoip.dat:cn, netip.ParsePrefix("ext:/etc/mosdns/geoip.dat:cn"): ParseAddr("ext:/etc/mosdns"): unexpected character, want colon (at "xt:/etc/mosdns")
geoip.dat文件已经放在/etc/mosdns下面了。

### 使用的配置文件

```yaml
- tag: response_has_local_ip
    type: response_matcher
    args:
      ip:
        # 使用默认geoip.dat文件
        - "ext:/etc/mosdns/geoip.dat:cn"
```
