### ISSUE TITLE
[Bug] 循环递归了？希望能给个选项禁止 mosdns 自身的 dns_search 

### ISSUE THREAD

**Issue by Zerorigin** [IrineSistiana/mosdns#476]
### 在提交之前，请确认

- [X] 我已经尝试搜索过 Issue ，但没有找到相关问题。
- [X] 我正在使用最新的 mosdns 版本(或者最新的 commit)，问题依旧存在。
- [X] 我仔细看过 wiki 后仍然无法自行解决该问题。
- [X] 我非常确定这是 mosdns 核心的问题。(如果是通过第三方衍生软件使用 mosdns 核心，不确定问题源头时，请先向衍生软件开发者提交问题。)

### mosdns 版本

v4.1.9

### 操作系统

docker container

### Bug 描述和复现步骤

```
version: '3.8'
services:
  mosdns:                     # 服务名称
    build:                    # 镜像构建
      context: .              # Dockerfile 与 docker-compose.yml 的相对目录
      dockerfile: Dockerfile  # Dockerfile 文件名
    dns_search: .             # 搜索域
    container_name: mosdns    # 容器名称
    domainname: example.com   # 主机域
    hostname: mosdns          # 主机名
    image: irinesistiana/mosdns:latest
    mac_address: "02:42:0a:01:01:35"
    restart: always
    environment:              # 坏境变量
      TZ: Asia/Shanghai
    volumes:                  # 卷映射
      - "./conf.d/:/opt/mosdns/conf.d/"
      - "/etc/localtime:/etc/localtime:ro"
    networks:                 # 网络配置
      pub:
        aliases:              # 网络别名
          - mosdns.example.com
        ipv4_address: "10.1.0.53"

networks:
  pub:                        # 网络名称
    external: true
```

### 使用的配置文件

```yaml
# 日志设置
log:
    level: warn
    file: ""

# 数据提供器
data_providers:
    - tag: hosts
      file: "./conf.d/hosts.txt"
      auto_reload: true
    - tag: geosite
      file: "./conf.d/geosite.dat"
      auto_reload: true
    - tag: geoip
      file: "./conf.d/geoip.dat"
      auto_reload: true

# 插件定义
plugins:
    ################ 转发器插件 #################

    # 转发请求至本地服务器的插件
    - tag: forward_local
      type: fast_forward
      args:
          upstream:
              - addr: https://223.5.5.5/dns-query
                dial_addr: "223.5.5.5:443"
                enable_pipeline: true
                max_conns: 3
              - addr: https://223.6.6.6/dns-query
                dial_addr: "223.6.6.6:443"
                enable_pipeline: true
                max_conns: 3

    # 转发请求至远程服务器的插件
    - tag: forward_remote
      type: fast_forward
      args:
          upstream:
              - addr: https://1.1.1.1/dns-query
                dial_addr: "1.1.1.1:443"
                enable_pipeline: true
                max_conns: 3
              - addr: https://1.0.0.1/dns-query
                dial_addr: "1.0.0.1:443"
                enable_pipeline: true
                max_conns: 3
              - addr: https://9.9.9.11/dns-query
                dial_addr: "9.9.9.11:443"
                enable_pipeline: true
                max_conns: 3
              - addr: https://149.112.112.11/dns-query
                dial_addr: "149.112.112.11:443"
                enable_pipeline: true
                max_conns: 3

    # 转发请求 Docker local DNS Server
    - tag: forward_docker
      type: fast_forward
      args:
          upstream:
              - addr: "127.0.0.11"
                enable_pipeline: true
                max_conns: 3


    ################ 匹配器插件 #################

    # 匹配本地域名的插件
    - tag: query_is_local_domain
      type: query_matcher
      args:
          domain:
              - "provider:geosite:cn"

    # 匹配非本地域名的插件
    - tag: query_is_non_local_domain
      type: query_matcher
      args:
          domain:
              - "provider:geosite:geolocation-!cn"

    # 匹配广告域名的插件
    - tag: query_is_ad_domain
      type: query_matcher
      args:
          domain:
              - "provider:geosite:category-ads-all"

    # 匹配本地 IP 的插件
    - tag: response_has_local_ip
      type: response_matcher
      args:
          ip:
              - "provider:geoip:cn"

    # 匹配特定域(本地域)
    - tag: query_is_local_lan_domain
      type: query_matcher
      args:
          domain:
              - "example.com"

    ################ 其它可执行插件 #################

    # 附加自定义 hosts 列表
    - tag: "custom_hosts"
      type: "hosts"
      args:
          hosts:
              - "provider:hosts"

    # 附加自定义的 ECS IP
    - tag: "client_ecs"
      type: "ecs" # ECS 插件
      args:
          auto: false # 是否自动将客户端请求的来源地址作为 ECS 附加到请求。如果为 true，则预设地址不会被使用。(仅适用于公网的服务器，本地运行不要启用这个功能)
          force_overwrite: true # 如果请求已有 ECS，是否强制覆盖。
          ipv4: "xxx.xxx.xxx.xxx" # 预设的 IPv4 地址。会优先附加在 A 请求里。
          ipv6: "xxx:xxx:x::" # 预设的 IPv6 地址。会优先附加在 AAAA 请求里。
          mask4: 14 # 用于 ipv4 地址的掩码。默认: 24。
          mask6: 56 # 用于 ipv6 地址的掩码。默认: 48。

    # 缓存 DNS 查询到 Redis
    - tag: "cache_to_redis"
      type: "cache" # 缓存插件
      args:
          # 内存缓存。
          size: 40960 # 缓存大小。单位: 条。默认: 1024。1w 条缓存大约会占用 1M 内存。
          # cleaner_interval: 120 # 回收器全局扫描间隔。单位: 秒。默认: 120。一般无需修改。

          # redis 外部缓存地址。
          # 如果非空，将使用 redis 作为缓存。上面的参数将不会有用。
          # 缓存大小，清除方式等，全部由 redis 控制。需在 redis 里设置。
          # TCP 连接: `redis://<user>:<password>@<host>:<port>/<db_number>`
          # Unix 连接: `unix://<user>:<password>@</path/to/redis.sock>?db=<db_number>`
          redis: "redis://default:p@ssw0rd@redis:6379/5"

    # 包含分流的逻辑的插件
    - tag: main_forward
      type: sequence
      args:
          exec:
              - if: query_is_ad_domain
                exec:
                    - _new_nxdomain_response
                    - _return

              - if: query_is_local_lan_domain
                exec:
                    - forward_docker
                    - _return

              # 已知的本地域名用本地服务器解析
              - if: query_is_local_domain
                exec:
                    - forward_local
                    - _return

              # 已知的非本地域名用远程服务器解析
              - if: query_is_non_local_domain
                exec:
                    - forward_remote
                    - _return

                # 剩下的未知域名用 IP 分流。
                # 这里借助了 `fallback` 工作机制。分流原理请参考 `fallback`
                # 的工作流程。
                # primary 从本地服务器获取应答，丢弃非本地 IP 的结果。
              - primary:
                    - forward_local
                    - if: "(! response_has_local_ip) && [_response_valid_answer]"
                      # - if: "[_response_valid_answer]"
                      exec:
                          - _drop_response
                # secondary 从远程服务器获取应答。
                secondary:
                    - forward_remote
                # 这里建议设置成 local 服务器正常延时的 2~5 倍。
                # 这个延时保证了 local 延时偶尔变高时，其结果不会被 remote 抢答。
                # 如果 local 超过这个延时还没响应，可以假设 local 出现了问题。
                # 这时用就采用 remote 的应答。单位: 毫秒。
                fast_fallback: 80

    # 改写应答的生存时间
    - tag: "rewrite_ttl"
      type: "ttl"
      args:
          minimal_ttl: 900 # 最小TTL。如果非零，小于这个数的应答的TTL会被修改成这个值。
          maximum_ttl: 3600 # 最大TTL。如果非零，大于这个数的应答的TTL会被修改成这个值。

    ################# 编排(排序)服务序列 ################

    # 定义服务序列
    - tag: main_sequence
      type: sequence
      args:
          exec:
              - custom_hosts # 检测是否命中自定义 hosts
              - client_ecs # EDNS Client Subnet - CDN 友好
              - _default_cache # 缓存
              - cache_to_redis # DNS 缓存命中检查及存储
              # - _single_flight
              - main_forward # DNS 查询分流逻辑
              - rewrite_ttl # 改写应答的生存时间

# 服务监听设置
servers:
    - exec: main_sequence
      listeners:
          - protocol: udp
            addr: ":53"
          - protocol: tcp
            addr: ":53"


api:
    http: 0.0.0.0:80
```

### mosdns 的 log 记录

```txt
# docker logs mosdns
2022-09-01T09:27:25.725+0800    warn    dns_handler/server_handler.go:86        entry returned an err   {"query": "api.ad.xiaomi.com.example.com. IN AAAA 753 1482 10.1.0.53", "error": "context deadline exceeded"}
2022-09-01T09:29:13.049+0800    warn    dns_handler/server_handler.go:86        entry returned an err   {"query": "data.mistat.xiaomi.com.example.com. IN AAAA 744 3196 10.1.0.53", "error": "context deadline exceeded"}
2022-09-01T09:29:13.050+0800    warn    dns_handler/server_handler.go:86        entry returned an err   {"query": "data.mistat.xiaomi.com.example.com. IN A 133 3197 10.1.0.53", "error": "context deadline exceeded"}
2022-09-01T09:29:33.100+0800    warn    dns_handler/server_handler.go:86        entry returned an err   {"query": "tracking.miui.com.example.com. IN AAAA 1550 4424 10.1.0.53", "error": "context deadline exceeded"}
2022-09-01T09:29:33.100+0800    warn    dns_handler/server_handler.go:86        entry returned an err   {"query": "tracking.miui.com.example.com. IN A 1549 4425 10.1.0.53", "error": "context deadline exceeded"}
```
