### ISSUE TITLE
[Bug] "if"判断中，比对的插件的名称，如果包含减号，启动就会报错。 

### ISSUE THREAD

**Issue by wy16W2pIilK1xgqN** [IrineSistiana/mosdns#479]
### 在提交之前，请确认

- [X] 我已经尝试搜索过 Issue ，但没有找到相关问题。
- [X] 我正在使用最新的 mosdns 版本(或者最新的 commit)，问题依旧存在。
- [X] 我仔细看过 wiki 后仍然无法自行解决该问题。
- [X] 我非常确定这是 mosdns 核心的问题。(如果是通过第三方衍生软件使用 mosdns 核心，不确定问题源头时，请先向衍生软件开发者提交问题。)

### mosdns 版本

v4.1.9-0-g24d0c8d

### 操作系统

windows 10 x64

### Bug 描述和复现步骤

插件的” tag “ 也就是标签，如果该值中包含减号，比如 tag: "qt-ype65"
在” if “中 调用就会报错。

文档中我并没有发现这个语法限制，如果是不是特性请修复。

终端回显
 
```
.\mosdns.exe start

Error: mosdns exited, failed to init plugin #1, cannot build sequence: invalid cmd at #0: invalid if section: cannot find matcher qt
2022-09-08T17:54:05.018+0800    fatal   v4/main.go:48   mosdns exited, failed to init plugin #1, cannot build sequence: invalid cmd at #0: invalid if section: cannot find matcher qt
```

### 使用的配置文件

```yaml
log:
  level: debug
  file: "./mosdns.log"

plugins:
  - tag: "qt-ype65"
    type: query_matcher
    args:
      qtype: [65]

  - tag: "my_sequence"
    type: sequence
    args:
      exec:
        - if: "( qt-ype65)"
          exec:
            - _new_nxdomain_response
            - _return

servers:
  - exec: "my_sequence"
    listeners:
      - protocol: udp
        addr: ":123"
```

### mosdns 的 log 记录

```txt
2022-09-08T17:54:05.011+0800	info	coremain/mosdns.go:123	loading plugin	{"tag": "qt-ype65", "type": "query_matcher"}
2022-09-08T17:54:05.018+0800	info	coremain/mosdns.go:123	loading plugin	{"tag": "my_sequence", "type": "sequence"}
```

**Comment by BozhanL** [comment]
你试试 ```[qt-ype65]``` 看看行不行

**Comment by wy16W2pIilK1xgqN** [comment]
> 你试试 `[qt-ype65]` 看看行不行

`tag: [qt-ype65] `或者 `if: [qt-ype65]`，进行排列组合，刚刚试验了一下，都报错。

**Comment by BozhanL** [comment]
> > 你试试 `[qt-ype65]` 看看行不行
> 
> `tag: [qt-ype65] `或者 `if: [qt-ype65]`，进行排列组合，刚刚试验了一下，都报错。

这样```if: "[qt-ype65]"```不行?
完整配置如下:
```yaml
log:
  level: debug
  file: "./mosdns.log"

plugins:
  - tag: "qt-ype65"
    type: query_matcher
    args:
      qtype: [65]

  - tag: "my_sequence"
    type: sequence
    args:
      exec:
        - if: "[qt-ype65]"
          exec:
            - _new_nxdomain_response
            - _return

servers:
  - exec: "my_sequence"
    listeners:
      - protocol: udp
        addr: ":123"
```
