### ISSUE TITLE
[Feature request]跳过不支持递归查询的上游DNS

### ISSUE THREAD

**Issue by zhaibin18** [IrineSistiana/mosdns#493]
之前202.14.67.14/202.14.67.4两个服务器支持递归查询，能得到正确的解析地址，但是突然不支持后DNS就解析不到结果了。
修改一下逻辑，如果上游DNS服务器返回不支持递归查询，就尝试其他的上游DNS。

```
  - tag: forward_hk
    type: fast_forward
    args:
      upstream:
        - addr: 202.14.67.14
        - addr: 202.14.67.4
        - addr: 202.130.97.65
```
