### ISSUE TITLE
client_limiter 插件应该如何使用？

### ISSUE THREAD

**Issue by pmkol** [IrineSistiana/mosdns#496]
```
- tag: client_limiter
   type: client_limiter
   args:
      max_qps: 100
```
这样定义插件后，是应该在main_sequence中的第一行，加入- client_limiter么（如下）
```
  - tag: main_sequence
    type: sequence
    args:
      exec:
        - client_limiter
 ......
```
还是应该加其它位置？
