### ISSUE TITLE
[BUG] Plugin: blackhole IPv6 setting: is an invalid ipv6 addr

### ISSUE THREAD

**Issue by CalmLong** [IrineSistiana/mosdns#50]
**出现了什么问题**

描述一下问题的表现。可以直接附上截图或log。建议配置`logger`插件使用`debug`级别获取更详细的调试log。

```txt
2021-01-26T16:04:06.555+0800	info	mosdns/main.go:136	mosdns ver: v1.2.0-0-ga0c57e1
2021-01-26T16:04:06.555+0800	info	mosdns/main.go:137	arch: amd64, os: linux, go: go1.15.7
2021-01-26T16:04:06.555+0800	info	coremain/run.go:61	loading config	{"file": "config.yaml"}
2021-01-26T16:04:06.556+0800	info	coremain/run.go:97	loading plugin	{"tag": "block"}
2021-01-26T16:04:06.556+0800	fatal	coremain/run.go:38	loading config	{"error": "failed to register plugin #1 block: failed to init plugin [block], [::1] is an invalid ipv6 addr"}
```

---

**如何重现**

描述一下如何重现该问题。请尽可能的包含：

mosdns 的版本号(`mosdns -v`)：

v1.2.0-0-ga0c57e1

使用的启动参数或启动方式：

./mosdns -c config.yaml

操作系统和平台：

The latest version of CentOS7, AMD64

进行了什么操作导致了问题的出现：

`blackhole` 插件中的 IPv6 设置，只要填写了 IP 就会出现如上的日志中的错误；试过好几个有效的 IPv6 地址都会报错，移除此项则正常

使用的配置文件：

```yaml
plugin:
  - log:
      level: debug

  - tag: "block"
    type: blackhole
    args:
      ipv4: 0.0.0.0
      ipv6: "[::1]"
      rcode: 0

  - tag: "main_sequence"
    type: sequence
    args:
      exec:
        - _default_cache
        - if:
            - isAds
          exec:
            - block
            - _end

        - if:
            - isCN
          exec:
            - forward_local
            - _end

        - forward_remote
  - tag: main
    type: server
    args:
      entry: main_sequence
      server:
        - protocol: udp
          addr: "127.0.0.1:53"
        - protocol: tcp
          addr: "127.0.0.1:53"

  - tag: forward_local
    type: fast_forward
    args:
      upstream:
        - protocol: udp
          addr: 223.5.5.5:53
          timeout: 2
          trusted: true
        - protocol: udp
          addr: 223.6.6.6:53
          timeout: 2
          trusted: true

  - tag: forward_remote
    type: fast_forward
    args:
      upstream:
        - protocol: dot
          addr: 8.8.8.8
          timeout: 3
          trusted: true
          server_name: dns.google
          insecure_skip_verify: false

  - tag: isAds
    type: query_matcher
    args:
        domain:
          - ./geosite.dat:ads

  - tag: isCN
    type: query_matcher
    args:
      domain:
        - ./geosite.dat:cn
````
