### ISSUE TITLE
[Bug] response_matcher 插件中的 rcode: [2] 存在问题

### ISSUE THREAD

**Issue by pmkol** [IrineSistiana/mosdns#502]
### 在提交之前，请确认

- [X] 我已经尝试搜索过 Issue ，但没有找到相关问题。
- [X] 我正在使用最新的 mosdns 版本(或者最新的 commit)，问题依旧存在。
- [X] 我仔细看过 wiki 后仍然无法自行解决该问题。
- [X] 我非常确定这是 mosdns 核心的问题。(如果是通过第三方衍生软件使用 mosdns 核心，不确定问题源头时，请先向衍生软件开发者提交问题。)

### mosdns 版本

4.1-4.2

### 操作系统

centos

### Bug 描述和复现步骤

我理解 rcode: [2] 就是 Server failed

我希望当用IP分流时，如果用DNS1查询没有记录，返回 Server failed ，则此时用DNS2查询，

实际遇到的问题：

判断并不生效，导致无论是否返回 Server failed，都会使用DNS2解析

配置文件如下，是我写法有问题么？

### 使用的配置文件

```yaml
# 匹配RCODE2的插件
  - tag: response_server_failed
    type: response_matcher
    args:
      rcode: [2]

        # DNS转发
        - primary:
            - forward_dns1
            - if: "[response_server_failed]"
              exec:
                - forward_dns2
                - _return
          secondary:
            - forward_dns3
          fast_fallback: 2500
          always_standby: false
```
