### ISSUE TITLE
[建议] fallback的always_standby问题

### ISSUE THREAD

**Issue by pmkol** [IrineSistiana/mosdns#503]
### 在提交之前，请确认

- [X] 我已经尝试搜索过 Issue ，但没有找到相关问题。
- [X] 我正在使用最新的 mosdns 版本(或者最新的 commit)，问题依旧存在。
- [X] 我仔细看过 wiki 后仍然无法自行解决该问题。
- [X] 我非常确定这是 mosdns 核心的问题。(如果是通过第三方衍生软件使用 mosdns 核心，不确定问题源头时，请先向衍生软件开发者提交问题。)

### mosdns 版本

4.1-4.2

### 操作系统

centos

### Bug 描述和复现步骤

先描述下使用场景，有两个上游DNS，分别国外与国内
DNS1=国外
DNS2=国内

当IP分流时，为了防止DNS泄露，使用了以下配置文件

当 always_standby: false 时，secondary 建议应该在fast_fallback的时间后再工作，或者增加一个参数，来限制secondary 启动的时间。

理想中的情况，在DNS检测网站中， secondary 应不再工作，检测DNS时应该只看到primary中的dns1

但实际情况是，检测时会看到dns2，只有将fast_fallback设置成约2500以上，在检测DNS时才看不到 secondary 中的dns2

显然在实际使用中，如果将fast_fallback设置过高，DNS2会等待DNS1太久，当DNS1不能返回结果时，会导致DNS输出结果卡顿，是不合理的，但设置太短，在DNS检测网站中又会泄露DNS2

想知道能否改进功能，或者这个问题有什么其它方法解决？

### 使用的配置文件

```yaml
- primary:
            - forward_dns1
          secondary:
            - forward_dns2
          fast_fallback: 200
          always_standby: false
```
