### ISSUE TITLE
[Feature request]能否为不同的监听ip/端口来设置不同的规则

### ISSUE THREAD

**Issue by Franinc** [IrineSistiana/mosdns#518]
```
servers:
  - exec: main_sequence
    timeout: 5
    listeners:
      - protocol: udp
        addr: "127.0.0.2:53"
      - protocol: tcp
        addr: "127.0.0.2:53"
      - protocol: udp
        addr: "127.0.0.3:53"
      - protocol: tcp
        addr: "127.0.0.3:53"
```
如上，能否让从`127.0.0.2`进入mosdns的流量执行某一个插件，而从`127.0.0.3`进入的流量执行另一个插件？

比如mosdns设置了两个插件：`special_sequence`和`main_sequence`
从`127.0.0.2`进入mosdns的流量执行`special_sequence`，从`127.0.0.3`进入的则执行`main_sequence`

当然端口也行，比如mos监听`127.0.0.4`的53和54端口，从53端口进来的流量执行`special_sequence`，而54端口进来的则执行`main_sequence`。

目前我本地只能同时开着两个mosdns.exe（不同文件夹）：一个只监听`127.0.0.2`，只配了国外dns；另一个只`127.0.0.3`，有国内/外dns并且分流。
本地跑了一个能单独设置dns的程序[ghostcp](https://github.com/macronut/ghostcp)用`127.0.0.2`（只用国外dns）
win10网卡设置dns为`127.0.0.3`，也就是浏览器等一般程序都用这个dns（有国内外分流）

这种情况对于mosdns来说，浏览器与ghostcp发起的dns查询都来自`127.0.0.1`，`query_matcher`插件无法区分，所以我只能同时开两个exe😥

**Comment by mengxinz** [comment]
> ```
> servers:
>   - exec: main_sequence
>     timeout: 5
>     listeners:
>       - protocol: udp
>         addr: "127.0.0.2:53"
>       - protocol: tcp
>         addr: "127.0.0.2:53"
>       - protocol: udp
>         addr: "127.0.0.3:53"
>       - protocol: tcp
>         addr: "127.0.0.3:53"
> ```
> 
> 如上，能否让从进入mosdns的流量执行某一个插件，而从进入的流量执行另一个插件？`127.0.0.2``127.0.0.3`
> 
> 比如mosdns设置了两个插件：和 从进入mosdns的流量执行，从进入的则执行`special_sequence``main_sequence``127.0.0.2``special_sequence``127.0.0.3``main_sequence`
> 
> 当然端口也行，比如mos监听的53和54端口，从53端口进来的流量执行，而54端口进来的则执行。`127.0.0.4``special_sequence``main_sequence`
> 
> 目前我本地只能同时开着两个mosdns.exe（不同文件夹）：一个只监听，只配了国外dns;另一个只，有国内/外dns并且分流。 本地跑了一个能单独设置dns的程序[ghostcp](https://github.com/macronut/ghostcp)用（只用国外dns） win10网卡设置dns为，也就是浏览器等一般程序都用这个dns（有国内外分流）`127.0.0.2``127.0.0.3``127.0.0.2``127.0.0.3`
> 
> 这种情况对于mosdns来说，浏览器与ghostcp发起的dns查询都来自，插件无法区分，所以我只能同时开两个exe`127.0.0.1``query_matcher`😥

创建出两个sequrnce各自监听就行

**Comment by Franinc** [comment]
😂不好意思，发完issue才发现可以多个`exec`，之前傻了只想着尝试多个`servers`
```
servers:
  - exec: special_sequence
    timeout: 5
    listeners:
      - protocol: udp
        addr: "127.0.0.2:53"
      - protocol: tcp
        addr: "127.0.0.2:53"
  - exec: main_sequence
    timeout: 5
    listeners:
      - protocol: udp
        addr: "127.0.0.3:53"
      - protocol: tcp
        addr: "127.0.0.3:53"
```
