### ISSUE TITLE
[Bug] api配置信息

### ISSUE THREAD

**Issue by gkl1368** [IrineSistiana/mosdns#524]
### 在提交之前，请确认

- [X] 我已经尝试搜索过 Issue ，但没有找到相关问题。
- [X] 我正在使用最新的 mosdns 版本(或者最新的 commit)，问题依旧存在。
- [X] 我仔细看过 wiki 后仍然无法自行解决该问题。
- [X] 我非常确定这是 mosdns 核心的问题。(如果是通过第三方衍生软件使用 mosdns 核心，不确定问题源头时，请先向衍生软件开发者提交问题。)

### mosdns 版本

v4.4.2

### 操作系统

Docker

### Bug 描述和复现步骤

Docker下 api不能启动，端口没有监听

### 使用的配置文件

```yaml
# API 入口设置
api:
  http: ":8080" # 在该地址启动 api 接口
```
