### ISSUE TITLE
[Bug] API为什么都是返回404呢？

### ISSUE THREAD

**Issue by aa51513** [IrineSistiana/mosdns#530]
### 在提交之前，请确认

- [X] 我已经尝试搜索过 Issue ，但没有找到相关问题。
- [X] 我正在使用最新的 mosdns 版本(或者最新的 commit)，问题依旧存在。
- [X] 我仔细看过 wiki 后仍然无法自行解决该问题。
- [X] 我非常确定这是 mosdns 核心的问题。(如果是通过第三方衍生软件使用 mosdns 核心，不确定问题源头时，请先向衍生软件开发者提交问题。)

### mosdns 版本

v4.4.2

### 操作系统

RockyLinux

### Bug 描述和复现步骤

配置了API，但是访问什么都是404
API文档也没有在WiKi里找到，个人猜测是Restful风格
但是请求啥都是返回404

### 使用的配置文件

```yaml
log:
    file: "/var/log/mosdns/warn.log"
    level: warn
plugins:
    - args:
        upstream:
            - addr: https://1.12.12.12/dns-query
      tag: forward_google
      type: fast_forward
servers:
    - exec: forward_google
      listeners:
        - addr: 127.0.0.1:1053
          protocol: udp
api:
  http: "127.0.0.1:5380"
```

### mosdns 的 log 记录

```txt
curl http://127.0.0.1:5380/plugins/forward_google
返回404
```
