### ISSUE TITLE
[Bug] response_matcher 插件 IP 参数配置多行 IP 段的时候，运行报错。

### ISSUE THREAD

**Issue by jzp820927** [IrineSistiana/mosdns#536]
### 在提交之前，请确认

- [X] 我已经尝试搜索过 Issue ，但没有找到相关问题。
- [X] 我正在使用最新的 mosdns 版本(或者最新的 commit)，问题依旧存在。
- [X] 我仔细看过 wiki 后仍然无法自行解决该问题。
- [X] 我非常确定这是 mosdns 核心的问题。(如果是通过第三方衍生软件使用 mosdns 核心，不确定问题源头时，请先向衍生软件开发者提交问题。)

### mosdns 版本

v4.5.2

### 操作系统

windows server 2008 R2

### Bug 描述和复现步骤

使用的最新版本的软件，只要 response_matcher 插件的 IP 参数配置多行 IP 段，启动就报错，只配置一行 IP 段，可以正常启动，一模一样的多行IP格式配置到 blackhole 插件的 IP 参数下面，软件就可以正常启动，由此可以确定 response_matcher 插件不支持配置多行 IP 段地址？不知道是软件的 BUG？还是本身这个插件就不支持配置多行IP段？如果是 BUG 希望能尽快修复，如果是插件本身不支持，不知道能否添加支持配置多行IP段，因为我觉得匹配多个IP段，应该是最基本的功能。另外我知道可以用 provider 引用外部文件实现，但是我只需要匹配3个固定的IP段，感觉引入外部文件太麻烦，直接写在配置文件比较方便，希望作者能尽快处理这个问题，非常感谢！

### 使用的配置文件

```yaml
log:
  level: debug

plugins:
  - tag: cache
    type: cache
    args:
      size: 1024

  - tag: forward_google
    type: fast_forward
    args:
      upstream:
        - addr: https://8.8.8.8/dns-query

  - tag: response_ip
    type: response_matcher
    args:
      ip:
        - "192.168.0.0/24"
	- "10.0.0.0/24"
	- "100.100.0.0/24"

  - tag: my_ip
    type: blackhole
    args:
      ipv4:
        - "127.0.0.1"

  - tag: my_sequence
    type: sequence
    args:
      exec:
        # 缓存
        - cache

        # 转发至 Google 获取应答
        - forward_google

        # 条件匹配
        - if: response_ip
          exec:
            - my_ip
            - _return

servers:
  - exec: my_sequence
    listeners:
      - protocol: udp
        addr: ":53"
      - protocol: tcp
        addr: ":53"
```

### mosdns 的 log 记录

```txt
E:\mosdns-windows-amd64>mosdns.exe start -c config.yaml
Error: failed to read config file, While parsing config: yaml: line 21: found character that cannot start any token
2022-10-25T00:32:13.870+0800    fatal   v4/main.go:48   failed to read config file, While parsing config: yaml: line 21: found character that cannot start any token
```
