### ISSUE TITLE
[BUG]  arbitrary 插件，SRV 大小写敏感问题。

### ISSUE THREAD

**Issue by wy16W2pIilK1xgqN** [IrineSistiana/mosdns#537]
版本：v4.5.2 
发现 arbitrary 插件的 SRV 记录是区分大小写的，而常见的做法是不区分的。
比如 :
```
 - tag: "kms"
   type: "arbitrary"  
   args:
     rr:
       - kms.lan. 86400 IN A 192.168.1.1       
       -  _VLMCS._TCP.lan. 86400 IN SRV 0 100 1688  kms.lan.
# 成功
nslookup -type=srv  _VLMCS._TCP
# 失败
nslookup -type=srv  _vlmcs._tcp
```
另外这个情况因该修复过。
https://github.com/IrineSistiana/mosdns/issues/110
