### ISSUE TITLE
[Bug] 貌似是有ipset方面的bug

### ISSUE THREAD

**Issue by PHCSJC** [IrineSistiana/mosdns#553]
### 在提交之前，请确认

- [X] 我已经尝试搜索过 Issue ，但没有找到相关问题。
- [X] 我正在使用最新的 mosdns 版本(或者最新的 commit)，问题依旧存在。
- [X] 我仔细看过 wiki 后仍然无法自行解决该问题。
- [X] 我非常确定这是 mosdns 核心的问题。(如果是通过第三方衍生软件使用 mosdns 核心，不确定问题源头时，请先向衍生软件开发者提交问题。)

### mosdns 版本

v4.4.2

### 操作系统

arm64

### Bug 描述和复现步骤

大佬主要看下primary和secondary那块，意思是对于未知的域名，如果解析出的ip是非国内的，就加到ipset里，就是走代理，但实际上并未加到ipset里，找了半天也不知道原因在哪，大佬看看是哪里的问题呢？

另外我一直在用早期的v3.7.3版本，同样逻辑的配置，并没有这个问题，就是今天想转换成v4版本遇到了这问题。

### 使用的配置文件

```yaml
log:
  level: info
  file: "/tmp/mosdns.log"

data_providers:
  - tag: hosts
    file: ./hosts
    auto_reload: true
  - tag: geosite
    file: ./geosite.dat
    auto_reload: true
  - tag: geoip
    file: ./geoip.dat
    auto_reload: true
  - tag: adhosts
    file: ./adhosts
    auto_reload: true


plugins:

  - tag: hosts
    type: hosts
    args:
      hosts:
        - "provider:hosts"   

  # 转发至本地服务器的插件
  - tag: forward_local
    type: fast_forward
    args:
      upstream:
        - addr: tls://120.53.53.53:853
          enable_pipeline: true
          trusted: true

        - addr: tls://223.5.5.5:853
          enable_pipeline: false
          trusted: true


  # 转发至远程服务器的插件
  - tag: forward_remote
    type: fast_forward
    args:
      upstream:
        - addr: tcp://8.8.8.8
          enable_pipeline: true
          trusted: true

        - addr: tcp://1.1.1.1
          enable_pipeline: true
          trusted: true

  - tag: redirect
    type: redirect
    args:
      rule:
        - www.cnbeta.com www.cnbeta.com.cdn.cloudflare.net
        - m.cnbeta.com www.cnbeta.com.cdn.cloudflare.net


  # 匹配本地域名的插件
  - tag: query_is_local_domain
    type: query_matcher
    args:
      domain:
        - 'provider:geosite:cn'
        - 'provider:geosite:apple-cn'
        - 'provider:geosite:icloud'

  # 匹配非本地域名的插件
  - tag: query_is_non_local_domain
    type: query_matcher
    args:
      domain:
        - 'provider:geosite:geolocation-!cn'

  # 匹配广告域名的插件
  - tag: query_is_ad_domain
    type: query_matcher
    args:
      domain:
        - 'provider:adhosts'

  # 匹配本地 IP 的插件
  - tag: response_has_local_ip
    type: response_matcher
    args:
      ip:
        - 'provider:geoip:cn'

  - tag: ipset
    type: ipset
    args:
      set_name4: 'gfwlist'
      set_name6: ''
      mask4: 32
      mask6: 0

  - tag: cache
    type: cache
    args:
      size: 20000

      lazy_cache_ttl: 86400
      lazy_cache_reply_ttl: 2
      cache_everything: false

  # 修改应答 ttl
  - tag: modify_ttl
    type: ttl
    args:
      minimal_ttl: 600
      maximum_ttl: 3600


  # 主要的运行逻辑插件
  # sequence 插件中调用的插件 tag 必须在 sequence 前定义，
  # 否则 sequence 找不到对应插件。
  - tag: main_sequence
    type: sequence
    args:
      exec:

        - hosts
        - cache
        - redirect
        - _prefer_ipv4

        # 屏蔽广告域名
        - if: query_is_ad_domain
          exec:
            - _new_nxdomain_response
            - _return


        # 已知的本地域名用本地服务器解析
        - if: query_is_local_domain
          exec:
            - forward_local
            - modify_ttl
            - _return

        # 已知的非本地域名用远程服务器解析
        - if: query_is_non_local_domain
          exec:
            - _no_ecs
            - forward_remote
            - modify_ttl
            - ipset
            - _return

        # 剩下的未知域名用 IP 分流。
        # 这里借助了 `fallback` 工作机制。分流原理请参考 `fallback`
        # 的工作流程。
          # primary 从本地服务器获取应答，丢弃非本地 IP 的结果。
        - primary:
            - forward_local
            - modify_ttl
            - if: "(! response_has_local_ip) || [_response_valid_answer]"
              exec:
                - _drop_response
          # secondary 从远程服务器获取应答。
          secondary:
            - _no_ecs
            - forward_remote
            - modify_ttl
            - if: ! response_has_local_ip
              exec:
                - ipset
          # 这里建议设置成 local 服务器正常延时的 2~5 倍。
          # 这个延时保证了 local 延时偶尔变高时，其结果不会被 remote 抢答。
          # 如果 local 超过这个延时还没响应，可以假设 local 出现了问题。
          # 这时用就采用 remote 的应答。单位: 毫秒。
          fast_fallback: 200


servers:
  - exec: main_sequence
    listeners:
      - protocol: udp
        addr: :53
      - protocol: tcp
        addr: :53
```

### mosdns 的 log 记录

```txt
2022-11-18T16:13:19.388+0800	info	coremain/run.go:88	loading plugin	{"tag": "server"}
2022-11-18T16:13:19.389+0800	info	coremain/run.go:88	loading plugin	{"tag": "main_sequence"}
2022-11-18T16:13:19.389+0800	info	server	server/server.go:205	server started	{"proto": "udp", "addr": "127.0.0.1:53"}
2022-11-18T16:13:19.390+0800	info	coremain/run.go:88	loading plugin	{"tag": "mem_cache"}
2022-11-18T16:13:19.390+0800	info	server	server/server.go:205	server started	{"proto": "tcp", "addr": "192.168.21.1:53"}
2022-11-18T16:13:19.390+0800	info	server	server/server.go:205	server started	{"proto": "tcp", "addr": "127.0.0.1:53"}
2022-11-18T16:13:19.390+0800	info	server	server/server.go:205	server started	{"proto": "udp", "addr": "192.168.21.1:53"}
2022-11-18T16:13:19.390+0800	info	coremain/run.go:88	loading plugin	{"tag": "modify_ttl"}
2022-11-18T16:13:19.390+0800	info	coremain/run.go:88	loading plugin	{"tag": "forward_local"}
2022-11-18T16:13:19.391+0800	info	coremain/run.go:88	loading plugin	{"tag": "forward_remote"}
2022-11-18T16:13:19.391+0800	info	coremain/run.go:88	loading plugin	{"tag": "query_is_myself"}
2022-11-18T16:13:19.392+0800	info	query_is_myself	query_matcher/query_matcher.go:107	domain matcher loaded	{"length": 4}
2022-11-18T16:13:19.392+0800	info	coremain/run.go:88	loading plugin	{"tag": "query_is_local_domain"}
```
