### ISSUE TITLE
[Feature request] 清空 cache 的 API

### ISSUE THREAD

**Issue by urlesistiana** [IrineSistiana/mosdns#555]
### Discussed in https://github.com/IrineSistiana/mosdns/discussions/549

<div type='discussions-op-text'>

<sup>Originally posted by **ihipop** November 16, 2022</sup>
提出这个问题的前提是**如果provider加载的规则如果数据库文件有更新，应该不会invalid 所有cache吧？**
这样就存在一个尴尬的问题：我的规则文件更新了，但是因为cache没失效，导致我编写的流程（IPSET维护）得等到cache自己过期后才能触发或者重启程序。

如果上述问题不存在，此问题close,否则是否有必要做一个cache invalid但是不需要重启程序的方法？
比如：
通过`kill -INT` 或者API请求？</div>

**Comment by emptyteeth** [comment]
这样如何
```yaml

tag: ""
type: "cache"
args:
  # 用户设置一个自定义域名来触发清空缓存
  cleantrigger: "clean.cache.trigger"

```
