### ISSUE TITLE
感谢又出了v5，求个国内国外分流的配置

### ISSUE THREAD

**Issue by PHCSJC** [IrineSistiana/mosdns#561]
一直在用v3，没什么毛病，v4还没用上就到v5了，感谢大佬的付出，求个下面的配置怎么转换成v5的呢？就是国内国外域名分流查询用v5怎么写呢？

log:
  level: info
  file: '/tmp/mosdns.log'

plugin:
  - tag: server
    type: server
    args:
      entry:
        - main_sequence
        - modify_ttl
      server:
        - protocol: udp
          addr: 127.0.0.1:53
        - protocol: udp
          addr: 192.168.2.1:53
        - protocol: tcp
          addr: 127.0.0.1:53
        - protocol: tcp
          addr: 192.168.2.1:53

  # 包含分流的逻辑的插件
  - tag: main_sequence
    type: sequence
    args:
      exec:

        - hosts
        - redirect

        - _prefer_ipv4

        - if:
            - query_is_ad_domain    # 已知的广告域名
          exec:
            - _block_with_nxdomain
            - _return               # 返回。不再执行后续插件。

        - mem_cache

        - if:
            - query_is_local_domain   # 已知的本地域名
            - '!_query_is_common'     # 和不常见的请求类型
          exec:
            - forward_local           # 用本地服务器
            - _return

        - if:
            - query_is_non_local_domain  # 已知的非本地域名
          exec:
            - forward_remote             # 用远程服务器
            - if:
                - '!response_has_myvps_ip'
              exec:
                - ipset
            - _return

        # 剩下的未知域名用 IP 分流。原理类似 ChinaDNS，但更稳定。
        # 详细分流原理请参考 `fallback` 的工作流程。
        - primary:
            - forward_local     # 本地服务器为主。
            - if:
                - '!response_has_local_ip'  # 过滤掉非本地的 IP。
              exec:
                - _drop_response
          secondary:
            - forward_remote
            - if:
                - '!response_has_local_ip'
              exec:
                - ipset
          fast_fallback: 200  # 这里建议设置成 local 服务器正常延时的 2~5 倍。
                              # 这个延时保证了 local 延时偶尔变高时，其结果不会被 remote 抢答。
                              # 如果 local 超过这个延时还没响应，可以假设 local 出现了问题。
                              # 这时用就采用 remote 的应答。单位: 毫秒。
          always_standby: true

  # 缓存
  - tag: 'mem_cache'
    type: 'cache'
    args:
      size: 10000
      lazy_cache_ttl: 86400
      lazy_cache_reply_ttl: 2
      cache_everything: false

  # 修改应答 ttl
  - tag: 'modify_ttl'
    type: 'ttl'
    args:
      minimal_ttl: 300
      maximum_ttl: 3600

  # 转发请求至本地服务器的插件
  - tag: forward_local
    type: forward
    args:
      upstream:
        - addr: tls://dot.pub
        - addr: tls://223.5.5.5
      bootstrap:
            - 119.29.29.29
            - 223.5.5.5

  # 转发请求至远程服务器的插件
  - tag: forward_remote
    type: fast_forward
    args:
      upstream:
        - addr: tcp://8.8.8.8
        - addr: tcp://1.1.1.1

  ################ 匹配器插件 #################

  # 匹配本地域名的插件
  - tag: query_is_local_domain
    type: query_matcher
    args:
      domain:
        - 'ext:./geosite.dat:cn'
        - 'ext:./geosite.dat:apple-cn'
        - 'ext:./geosite.dat:icloud'

  # 匹配非本地域名的插件
  - tag: query_is_non_local_domain
    type: query_matcher
    args:
      domain:
        - 'ext:./geosite.dat:geolocation-!cn'

  # 匹配本地 IP 的插件
  - tag: response_has_local_ip
    type: response_matcher
    args:
      ip:
        - 'ext:./geoip.dat:cn'
		
  - tag: response_has_myvps_ip
    type: response_matcher
    args:
      ip:
        - 'ext:./myvpsip.conf'

  - tag: redirect
    type: redirect
    args:
      rule:
        - www.cnbeta.com www.cnbeta.com.cdn.cloudflare.net
        - m.cnbeta.com www.cnbeta.com.cdn.cloudflare.net

  # 匹配广告域名的插件
  - tag: query_is_ad_domain
    type: query_matcher
    args:
      domain:
        - 'ext:./adhosts'

  - tag: 'blackhole'
    type: 'blackhole'
    args:
      rcode: 0
      ipv4: '127.0.0.1'
      ipv6: '::1'

  - tag: 'ipset'
    type: 'ipset'
    args:
      set_name4: 'gfwlist'
      set_name6: ''
      mask4: 32
      mask6: 0

  - tag: 'hosts'
    type: 'hosts'
    args:
      hosts:
        - 'ext:./hosts'

**Comment by PHCSJC** [comment]
其实我觉得v3的配置还是很好理解的，v4就有点蒙了，v5更不懂了，理解力有限抱歉

**Comment by w22gb8** [comment]
> 其实我觉得v3的配置还是很好理解的，v4就有点蒙了，v5更不懂了，理解力有限抱歉

俺也一样，v3版本几台稳定运行快一年了没重启过，稳的很。

**Comment by nil-ca** [comment]
```
log:
  level: "error"

plugins:

  - tag: "cache"
    type: "cache"
    args:
      size: "1024"
      
  - tag: "geosite"
    type: "domain_set"
    args:
      files:
        - path: "/etc/mosdns/geosite.dat"
          type: "geosite"
          args: "cn,private"
          
  - tag: "geoip"
    type: "ip_set"
    args:
      files:
        - path: "/etc/mosdns/geoip-only-cn-private.dat"
          type: "geoip"
          args: "cn,private"
          

  - tag: "local_dnsdoh"
    type: "fast_forward"
    args:
      concurrent: 2
      upstreams:
      - addr: "https://1.12.12.12/dns-query"
      - addr: "https://120.53.53.53/dns-query"
      - addr: "https://223.5.5.5/dns-query"
      - addr: "https://223.6.6.6/dns-query"

  - tag: "local_dnstls"
    type: "fast_forward"
    args:
      concurrent: 2
      upstreams:
      - addr: "tls://dns.alidns.com"
        dial_addr: "223.5.5.5:853"
      - addr: "tls://dot.pub"
        dial_addr: "1.12.12.12:853"
        
  - tag: "local_dnstcp"
    type: "fast_forward"
    args:
      concurrent: 2
      upstreams:
      - addr: "tcp://223.5.5.5"
      - addr: "tcp://119.29.29.29"
      - addr: "tcp://114.114.114.114"
        
  - tag: "remote_dnsdoh"
    type: "fast_forward"
    args:
      concurrent: 2
      upstreams:
        - addr: "https://dns.google/dns-query"
          dial_addr: "8.8.8.8:443"
          socks5: "127.0.0.1:7891"
        - addr: "https://cloudflare-dns.com/dns-query"
          dial_addr: "1.1.1.1:443"
          socks5: "127.0.0.1:7891"

  - tag: "remote_dnstls"
    type: "fast_forward"
    args:
      concurrent: 2
      upstreams:
        - addr: "tls://dns.google"
          dial_addr: "8.8.8.8:853"
          socks5: "127.0.0.1:7891"
        - addr: "tls://1dot1dot1dot1.cloudflare-dns.com"
          dial_addr: "1.1.1.1:853"
          socks5: "127.0.0.1:7891"
        
  - tag: "remote_dnstcp"
    type: "fast_forward"
    args:
      concurrent: 2
      upstreams:
        - addr: "udp://1.1.1.1"
          socks5: "127.0.0.1:7891"
        - addr: "udp://8.8.8.8"
          socks5: "127.0.0.1:7891"
  
  - tag: "my_sequence"
    type: "sequence"
    args:

      - exec: $cache
      - matches:
        - has_resp
        exec: accept
      - matches:
        - qname $geosite
        - has_resp
        - resp_ip $geoip
        - has_resp
        exec: accept

      - exec: $local_dnsdoh
      - exec: $local_dnstls
      - exec: $local_dnstcp

      - exec: ttl 300-3600
      
      - matches:
        - has_resp
        exec: accept

      - matches:
        - qname $geosite
        - resp_ip $geoip
        - has_resp
        exec: reject
      - exec: prefer_ipv4
      - exec: $remote_dnsdoh
      - exec: $remote_dnstls
      - exec: $remote_dnstcp

      - exec: ttl 300-3600
      
      - matches:
        - has_resp
        exec: accept
      


  - tag: "multi_udp"
    type: "udp_server"
    args:
      entry: "my_sequence"
      listen: "127.0.0.1:33333"
  
  - tag: "multi_tcp"
    type: "tcp_server"
    args:
      entry: "my_sequence"
      listen: "127.0.0.1:33333"

```

看了一会文档，能用，没有去广告。但是应该有的地方不用写，不是程序员所以不专业，发出来看看哪些地方可以改一改吧。
