### ISSUE TITLE
[Bug] v5 cache panic

### ISSUE THREAD

**Issue by howxcheng** [IrineSistiana/mosdns#569]
### 在提交之前，请确认

- [X] 我已经尝试搜索过 Issue ，但没有找到相关问题。
- [X] 我正在使用最新的 mosdns 版本(或者最新的 commit)，问题依旧存在。
- [X] 我仔细看过 wiki 后仍然无法自行解决该问题。
- [X] 我非常确定这是 mosdns 核心的问题。(如果是通过第三方衍生软件使用 mosdns 核心，不确定问题源头时，请先向衍生软件开发者提交问题。)

### mosdns 版本

v5.0.0-alpha.2-0-gcbe141b

### 操作系统

debian11

### Bug 描述和复现步骤

**dig AAAA github.com**

因为github没有v6地址，第一次dig时没有返回值，正常。
```
root@Debian-VMware-Machine:~# dig AAAA github.com

; <<>> DiG 9.16.33-Debian <<>> AAAA github.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 2520
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1408
;; QUESTION SECTION:
;github.com.			IN	AAAA

;; AUTHORITY SECTION:
github.com.		434	IN	SOA	dns1.p08.nsone.net. hostmaster.nsone.net. 1656468023 43200 7200 1209600 3600

;; Query time: 16 msec
;; SERVER: 192.168.10.4#53(192.168.10.4)
;; WHEN: Sun Dec 04 01:18:58 CST 2022
;; MSG SIZE  rcvd: 123
```
第二次执行，程序报错退出
```
panic: runtime error: slice bounds out of range [-1:]

goroutine 22 [running]:
github.com/IrineSistiana/mosdns/v5/plugin/executable/cache.shuffleIP(0xc00019f200?)
	github.com/IrineSistiana/mosdns/v5/plugin/executable/cache/cache.go:389 +0x114
github.com/IrineSistiana/mosdns/v5/plugin/executable/cache.(*cachePlugin).Exec(0xc00019f200, {0xead180, 0xc0002c32c0}, 0xc0002c8e40, {0x1, {0xc000264cc0, 0x3, 0x3}, 0x0})
	github.com/IrineSistiana/mosdns/v5/plugin/executable/cache/cache.go:155 +0x38a
github.com/IrineSistiana/mosdns/v5/plugin/executable/sequence.(*ChainWalker).ExecNext(0xc0003a7ae8, {0xead180, 0xc0002c32c0}, 0x0?)
	github.com/IrineSistiana/mosdns/v5/plugin/executable/sequence/chain.go:80 +0x196
github.com/IrineSistiana/mosdns/v5/plugin/executable/sequence.(*sequence).Exec(0xead110?, {0xead180?, 0xc0002c32c0?}, 0x12a05f200?)
	github.com/IrineSistiana/mosdns/v5/plugin/executable/sequence/sequence.go:78 +0x55
github.com/IrineSistiana/mosdns/v5/pkg/server/dns_handler.(*EntryHandler).ServeDNS(0xc00019b9a0, {0xead110, 0xc000034d00}, 0xc0002c8e40)
	github.com/IrineSistiana/mosdns/v5/pkg/server/dns_handler/entry_handler.go:90 +0xd1
github.com/IrineSistiana/mosdns/v5/pkg/server.(*UDPServer).ServeUDP.func1()
	github.com/IrineSistiana/mosdns/v5/pkg/server/udp.go:101 +0x20f
created by github.com/IrineSistiana/mosdns/v5/pkg/server.(*UDPServer).ServeUDP
	github.com/IrineSistiana/mosdns/v5/pkg/server/udp.go:98 +0x80c
```
我同时测试了只有ipv6地址的 `dig A speed.neu6.edu.cn` ，第二次同样报错退出，感觉是cache命中了信息，但只有v4 v6的其中一种，想拿另一种不存在的信息导致错误

### 使用的配置文件

```yaml
log:
  level: debug
  production: false

plugins:
  - tag: cache
    type: cache
    args:
      size: 1024000
      lazy_cache_ttl: 259200
      lazy_cache_reply_ttl: 60
      dump_file: "/opt/mosdns/cache.dump"
      dump_interval: 3600

  - tag: forward_alidns
    type: fast_forward
    args:
      concurrent: 1
      upstreams:
        - addr: 223.5.5.5
        - addr: 223.6.6.6

  - tag: main_sequence
    type: sequence
    args:
      - exec: $cache
      - matches:
          - has_resp
        exec: accept

      - exec: $forward_alidns

  - tag: udp_server
    type: udp_server
    args:
      entry: main_sequence # 收到的请求会执行上面的逻辑
      listen: 0.0.0.0:53
```

### mosdns 的 log 记录

```txt
panic: runtime error: slice bounds out of range [-1:]

goroutine 22 [running]:
github.com/IrineSistiana/mosdns/v5/plugin/executable/cache.shuffleIP(0xc00021f170?)
	github.com/IrineSistiana/mosdns/v5/plugin/executable/cache/cache.go:389 +0x114
github.com/IrineSistiana/mosdns/v5/plugin/executable/cache.(*cachePlugin).Exec(0xc00021f170, {0xead180, 0xc0003805a0}, 0xc0000a41c0, {0x1, {0xc0002e4ca8, 0x3, 0x3}, 0x0})
	github.com/IrineSistiana/mosdns/v5/plugin/executable/cache/cache.go:155 +0x38a
github.com/IrineSistiana/mosdns/v5/plugin/executable/sequence.(*ChainWalker).ExecNext(0xc00009fae8, {0xead180, 0xc0003805a0}, 0x0?)
	github.com/IrineSistiana/mosdns/v5/plugin/executable/sequence/chain.go:80 +0x196
github.com/IrineSistiana/mosdns/v5/plugin/executable/sequence.(*sequence).Exec(0xead110?, {0xead180?, 0xc0003805a0?}, 0x12a05f200?)
	github.com/IrineSistiana/mosdns/v5/plugin/executable/sequence/sequence.go:78 +0x55
github.com/IrineSistiana/mosdns/v5/pkg/server/dns_handler.(*EntryHandler).ServeDNS(0xc00021b9a0, {0xead110, 0xc0000a4000}, 0xc0000a41c0)
	github.com/IrineSistiana/mosdns/v5/pkg/server/dns_handler/entry_handler.go:90 +0xd1
github.com/IrineSistiana/mosdns/v5/pkg/server.(*UDPServer).ServeUDP.func1()
	github.com/IrineSistiana/mosdns/v5/pkg/server/udp.go:101 +0x20f
created by github.com/IrineSistiana/mosdns/v5/pkg/server.(*UDPServer).ServeUDP
	github.com/IrineSistiana/mosdns/v5/pkg/server/udp.go:98 +0x80c
```
