### ISSUE TITLE
[Bug] 无法设定服务器参数 tcp_server.idle_timeout 

### ISSUE THREAD

**Issue by Hades-001** [IrineSistiana/mosdns#588]
### 在提交之前，请确认

- [X] 我已经尝试搜索过 Issue ，但没有找到相关问题。
- [X] 我正在使用最新的 mosdns 版本(或者最新的 commit)，问题依旧存在。
- [X] 我仔细看过 wiki 后仍然无法自行解决该问题。
- [X] 我非常确定这是 mosdns 核心的问题。(如果是通过第三方衍生软件使用 mosdns 核心，不确定问题源头时，请先向衍生软件开发者提交问题。)

### mosdns 版本

v5.0.0

### 操作系统

windows

### Bug 描述和复现步骤

tcp_server 配置 dot 时设置参数 idle_timeout，启动时会报错

### 使用的配置文件

```yaml
log:
  level: debug
  file: "./mosdns.log"

plugins:
  - tag: "custom_cache"
    type: "cache"
    args:
      size: 40960
      lazy_cache_ttl: 86400
      dump_file: "./cache.dump"
      dump_interval: 600

  - tag: "custom_hosts"
    type: "hosts"
    args:
      files:
        - "./hosts"

  - tag: "forward_local"
    type: "forward"
    args:
      concurrent: 1
      upstreams:
        - tag: "alidns"
          addr: "tls://223.5.5.5"
          idle_timeout: 10
          enable_pipeline: false
          enable_http3: false
          max_conns: 2
          insecure_skip_verify: false
        - tag: "dnspod"
          addr: "https://doh.pub/dns-query"
          dial_addr: "1.12.12.12"
          idle_timeout: 30
          enable_pipeline: false
          enable_http3: false
          max_conns: 2
          insecure_skip_verify: false
  - tag: "forward_remote"
    type: "forward"
    args:
      concurrent: 3
      upstreams:
        - tag: "google_dot"
          addr: "tls://dns.google"
          dial_addr: "8.8.8.8"
          idle_timeout: 10
          enable_pipeline: true
          enable_http3: true
          max_conns: 2
          insecure_skip_verify: false
        - tag: "cloudflare_dot"
          addr: "tls://1.1.1.1"
          idle_timeout: 10
          enable_pipeline: true
          enable_http3: true
          max_conns: 2
          insecure_skip_verify: false
        - tag: "opendns"
          addr: "tcp://208.67.222.222:5353"
          idle_timeout: 10
          enable_pipeline: true
          enable_http3: true
          max_conns: 2
          insecure_skip_verify: false

  - tag: ads_domain
    type: "domain_set"
    args:
      files: "./oisd_dbl_full.txt"
  - tag: "local_domain"
    type: "domain_set"
    args:
      files: "./direct-list.txt"
  - tag: "non_local_domain"
    type: "domain_set"
    args:
      files: "./proxy-list.txt"
  - tag: "local_ip"
    type: "ip_set"
    args:
      files: "./china_ip_list.txt"

  - tag: "local"
    type: "sequence"
    args:
      - exec: $forward_local
      - matches:
          - "!resp_ip $local_ip"
        exec: drop_resp
  
  - tag: "remote"
    type: "sequence"
    args:
      - exec: prefer_ipv4
      - exec: $forward_remote
  
  


  
  - tag: "main"
    type: "sequence"
    args:
      - matches:
          - qname $ads_domain
        exec: reject 3
      - exec: $custom_hosts
      - matches: has_resp
        exec: accept
      - exec: $custom_cache
      - matches: has_resp
        exec: accept
      - matches:
          - qname $local_domain
        exec: $forward_local
      - matches: has_resp
        exec: accept
      - matches:
          - qname $non_local_domain
        exec: $forward_remote
      - matches: has_resp
        exec: accept
      - exec: $forward_local
      - matches:
          - "!resp_ip $local_ip"
        exec: drop_resp
      - exec: prefer_ipv4
      - exec: $forward_remote
      

  
  
  
  
  - type: "udp_server"
    args:
      entry: main
      listen: 0.0.0.0:53
  - type: "tcp_server"
    args:
      entry: main
      listen: 0.0.0.0:53
  - tag: "dot"
    type: "tcp_server"
    args:
      entry: main
      listen: "0.0.0.0:853"
      cert: "xxx"
      key: "xxx"
    idle_timeout: 10
  - tag: "doh"
    type: "http_server"
    args:
      entries:
        - path: /dns-query
          exec: main
      src_ip_header: "X-Forwarded-For"
      listen: "0.0.0.0:5443"
      cert: "xxx"
      key: "xxx"
```
```


### mosdns 的 log 记录

启动时报错，无 debug log

控制台显示的错误日志


Error: fail to load config, failed to unmarshal config: 1 error(s) decoding:

* 'plugins[13]' has invalid keys: idle_timeout
2023-01-15T21:50:19.440+0800    FATAL   fail to load config, failed to unmarshal config: 1 error(s) decoding:

* 'plugins[13]' has invalid keys: idle_timeout

**Comment by Hades-001** [comment]
还有一个问题，同时绑定 53 端口和 5353 端口时会报错。

配置文件

```
log:
  level: debug
  file: "./mosdns.log"

plugins:
  - tag: "custom_cache"
    type: "cache"
    args:
      size: 40960
      lazy_cache_ttl: 86400
      dump_file: "./cache.dump"
      dump_interval: 600

  - tag: "custom_hosts"
    type: "hosts"
    args:
      files:
        - "./hosts"

  - tag: "forward_local"
    type: "forward"
    args:
      concurrent: 1
      upstreams:
        - tag: "alidns"
          addr: "tls://223.5.5.5"
          idle_timeout: 10
          enable_pipeline: false
          enable_http3: false
          max_conns: 2
          insecure_skip_verify: false
        - tag: "dnspod"
          addr: "https://doh.pub/dns-query"
          dial_addr: "1.12.12.12"
          idle_timeout: 30
          enable_pipeline: false
          enable_http3: false
          max_conns: 2
          insecure_skip_verify: false
  - tag: "forward_remote"
    type: "forward"
    args:
      concurrent: 3
      upstreams:
        - tag: "google_dot"
          addr: "tls://dns.google"
          dial_addr: "8.8.8.8"
          idle_timeout: 10
          enable_pipeline: true
          enable_http3: true
          max_conns: 2
          insecure_skip_verify: false
        - tag: "cloudflare_dot"
          addr: "tls://1.1.1.1"
          idle_timeout: 10
          enable_pipeline: true
          enable_http3: true
          max_conns: 2
          insecure_skip_verify: false
        - tag: "opendns"
          addr: "tcp://208.67.222.222:5353"
          idle_timeout: 10
          enable_pipeline: true
          enable_http3: true
          max_conns: 2
          insecure_skip_verify: false

  - tag: ads_domain
    type: "domain_set"
    args:
      files: "./oisd_dbl_full.txt"
  - tag: "local_domain"
    type: "domain_set"
    args:
      files: "./direct-list.txt"
  - tag: "non_local_domain"
    type: "domain_set"
    args:
      files: "./proxy-list.txt"
  - tag: "local_ip"
    type: "ip_set"
    args:
      files: "./china_ip_list.txt"

  - tag: "local"
    type: "sequence"
    args:
      - exec: $forward_local
      - matches:
          - "!resp_ip $local_ip"
        exec: drop_resp
  
  - tag: "remote"
    type: "sequence"
    args:
      - exec: prefer_ipv4
      - exec: $forward_remote
  
  


  
  - tag: "main"
    type: "sequence"
    args:
      - matches:
          - qname $ads_domain
        exec: reject 3
      - exec: $custom_hosts
      - matches: has_resp
        exec: accept
      - exec: $custom_cache
      - matches: has_resp
        exec: accept
      - matches:
          - qname $local_domain
        exec: $forward_local
      - matches: has_resp
        exec: accept
      - matches:
          - qname $non_local_domain
        exec: $forward_remote
      - matches: has_resp
        exec: accept
      - exec: $forward_local
      - matches:
          - "!resp_ip $local_ip"
        exec: drop_resp
      - exec: prefer_ipv4
      - exec: $forward_remote
      

  
  
  
  
  - type: "udp_server"
    args:
      entry: main
      listen: 0.0.0.0:53
  - type: "tcp_server"
    args:
      entry: main
      listen: 0.0.0.0:53
  - type: "udp_server"
    args:
      entry: main
      listen: 0.0.0.0:5353
  - type: "tcp_server"
    args:
      entry: main
      listen: 0.0.0.0:5353
```

控制台日志：

```
2023-01-15T22:08:34.359+0800    INFO    main config loaded      {"file": "config.yaml"}
Error: failed to init plugin #13 , failed to init plugin: failed to create socket, listen udp 0.0.0.0:5353: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.
2023-01-15T22:08:35.463+0800    FATAL   failed to init plugin #13 , failed to init plugin: failed to create socket, listen udp 0.0.0.0:5353: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.
```

**Comment by urlesistiana** [comment]
1. 格式错了。
2. 端口冲突。

**Comment by Hades-001** [comment]
按照 wiki 改完格式后还是报错。

```
2023-01-16T14:08:30.738+0800    INFO    main config loaded      {"file": "config.yaml"}
Error: failed to init plugin #13 tcp_53, unable to decode plugin args: 1 error(s) decoding:

* '' has invalid keys: idle_timeout
2023-01-16T14:08:31.952+0800    FATAL   failed to init plugin #13 tcp_53, unable to decode plugin args: 1 error(s) decoding:

* '' has invalid keys: idle_timeout
```

现在用的配置

```
log:
  level: info
  file: "./mosdns.log"

plugins:
  - tag: "custom_cache"
    type: "cache"
    args:
      size: 40960
      lazy_cache_ttl: 86400
      dump_file: "./cache.dump"
      dump_interval: 600

  - tag: "custom_hosts"
    type: "hosts"
    args:
      files:
        - "./hosts"

  - tag: "forward_local"
    type: "forward"
    args:
      concurrent: 1
      upstreams:
        - tag: "alidns"
          addr: "tls://223.5.5.5"
          idle_timeout: 10
          enable_pipeline: false
          enable_http3: false
          max_conns: 2
          insecure_skip_verify: false
        - tag: "dnspod"
          addr: "https://doh.pub/dns-query"
          dial_addr: "1.12.12.12"
          idle_timeout: 30
          enable_pipeline: false
          enable_http3: false
          max_conns: 2
          insecure_skip_verify: false
  - tag: "forward_remote"
    type: "forward"
    args:
      concurrent: 3
      upstreams:
        - tag: "google_dot"
          addr: "tls://dns.google"
          dial_addr: "8.8.8.8"
          idle_timeout: 10
          enable_pipeline: true
          enable_http3: true
          max_conns: 2
          insecure_skip_verify: false
        - tag: "cloudflare_dot"
          addr: "tls://1.1.1.1"
          idle_timeout: 10
          enable_pipeline: true
          enable_http3: true
          max_conns: 2
          insecure_skip_verify: false
        - tag: "opendns"
          addr: "tcp://208.67.222.222:5353"
          idle_timeout: 10
          enable_pipeline: true
          enable_http3: true
          max_conns: 2
          insecure_skip_verify: false

  - tag: "ads_domain"
    type: "domain_set"
    args:
      files:
        - "./oisd_dbl_full.txt"
  - tag: "local_domain"
    type: "domain_set"
    args:
      files:
        - "./direct-list.txt"
  - tag: "non_local_domain"
    type: "domain_set"
    args:
      files:
        - "./proxy-list.txt"
  - tag: "local_ip"
    type: "ip_set"
    args:
      files:
        - "./china_ip_list.txt"

  - tag: "local"
    type: "sequence"
    args:
      - exec: $forward_local
      - matches:
          - "!resp_ip $local_ip"
          - "!has_wanted_ans"
        exec: drop_resp
  - tag: "remote"
    type: "sequence"
    args:
      - exec: prefer_ipv4
      - exec: $forward_remote

  - tag: "custom_fallback"
    type: "fallback"
    args:
      primary: local
      secondary: remote
      threshold: 500
      always_standby: true

  - tag: "main"
    type: "sequence"
    args:
      - matches:
          - qname $ads_domain
        exec: reject 3
      - exec: $custom_hosts
      - matches: has_resp
        exec: accept
      - exec: $custom_cache
      - matches: has_resp
        exec: accept
      - matches:
          - qname $local_domain
        exec: $forward_local
      - matches: has_wanted_ans
        exec: accept
      - matches:
          - qname $non_local_domain
        exec: $forward_remote
      - matches: has_wanted_ans
        exec: accept
      - exec: $custom_fallback

  - tag: "udp_53"
    type: "udp_server"
    args:
      entry: main
      listen: "0.0.0.0:53"
  - tag: "tcp_53"
    type: "tcp_server"
    args:
      entry: main
      listen: "0.0.0.0:53"
      idle_timeout: 10
```

删除  idle_timeout 参数后这个配置可以正常运行。
