### ISSUE TITLE
[Bug] has_wanted_resp 无法正常运行

### ISSUE THREAD

**Issue by Hades-001** [IrineSistiana/mosdns#589]
### 在提交之前，请确认

- [X] 我已经尝试搜索过 Issue ，但没有找到相关问题。
- [X] 我正在使用最新的 mosdns 版本(或者最新的 commit)，问题依旧存在。
- [X] 我仔细看过 wiki 后仍然无法自行解决该问题。
- [X] 我非常确定这是 mosdns 核心的问题。(如果是通过第三方衍生软件使用 mosdns 核心，不确定问题源头时，请先向衍生软件开发者提交问题。)

### mosdns 版本

v5.0.0

### 操作系统

windows

### Bug 描述和复现步骤

使用 has_wanted_resp 匹配器后启动报错

### 使用的配置文件

```yaml
log:
  level: debug
  file: "./mosdns.log"

plugins:
  - tag: "custom_cache"
    type: "cache"
    args:
      size: 40960
      lazy_cache_ttl: 86400
      dump_file: "./cache.dump"
      dump_interval: 600

  - tag: "custom_hosts"
    type: "hosts"
    args:
      files:
        - "./hosts"

  - tag: "forward_local"
    type: "forward"
    args:
      concurrent: 1
      upstreams:
        - tag: "alidns"
          addr: "tls://223.5.5.5"
          idle_timeout: 10
          enable_pipeline: false
          enable_http3: false
          max_conns: 2
          insecure_skip_verify: false
        - tag: "dnspod"
          addr: "https://doh.pub/dns-query"
          dial_addr: "1.12.12.12"
          idle_timeout: 30
          enable_pipeline: false
          enable_http3: false
          max_conns: 2
          insecure_skip_verify: false
  - tag: "forward_remote"
    type: "forward"
    args:
      concurrent: 3
      upstreams:
        - tag: "google_dot"
          addr: "tls://dns.google"
          dial_addr: "8.8.8.8"
          idle_timeout: 10
          enable_pipeline: true
          enable_http3: true
          max_conns: 2
          insecure_skip_verify: false
        - tag: "cloudflare_dot"
          addr: "tls://1.1.1.1"
          idle_timeout: 10
          enable_pipeline: true
          enable_http3: true
          max_conns: 2
          insecure_skip_verify: false
        - tag: "opendns"
          addr: "tcp://208.67.222.222:5353"
          idle_timeout: 10
          enable_pipeline: true
          enable_http3: true
          max_conns: 2
          insecure_skip_verify: false

  - tag: ads_domain
    type: "domain_set"
    args:
      files: "./oisd_dbl_full.txt"
  - tag: "local_domain"
    type: "domain_set"
    args:
      files: "./direct-list.txt"
  - tag: "non_local_domain"
    type: "domain_set"
    args:
      files: "./proxy-list.txt"
  - tag: "local_ip"
    type: "ip_set"
    args:
      files: "./china_ip_list.txt"

  - tag: "local"
    type: "sequence"
    args:
      - exec: $forward_local
      - matches:
          - "!resp_ip $local_ip"
        exec: drop_resp
  
  - tag: "remote"
    type: "sequence"
    args:
      - exec: prefer_ipv4
      - exec: $forward_remote
  
  


  
  - tag: "main"
    type: "sequence"
    args:
      - matches:
          - qname $ads_domain
        exec: reject 3
      - exec: $custom_hosts
      - matches: has_resp
        exec: accept
      - exec: $custom_cache
      - matches: has_resp
        exec: accept
      - matches:
          - qname $local_domain
        exec: $forward_local
      - matches: has_resp
        exec: accept
      - matches:
          - qname $non_local_domain
        exec: $forward_remote
      - matches: has_wanted_resp
        exec: accept
      - exec: $forward_local
      - matches:
          - "!resp_ip $local_ip"
        exec: drop_resp
      - exec: prefer_ipv4
      - exec: $forward_remote
      

  
  
  
  
  - type: "udp_server"
    args:
      entry: main
      listen: 0.0.0.0:53
  - type: "tcp_server"
    args:
      entry: main
      listen: 0.0.0.0:53
```

### mosdns 的 log 记录

```txt
2023-01-15T22:12:57.403+0800    INFO    main config loaded      {"file": "config.yaml"}
Error: failed to init plugin #10 main, failed to init plugin: failed to init rule #8, failed to init matcher #0, invalid matcher type has_wanted_resp
2023-01-15T22:12:58.509+0800    FATAL   failed to init plugin #10 main, failed to init plugin: failed to init rule #8, failed to init matcher #0, invalid matcher type has_wanted_resp
```
