### ISSUE TITLE
[Bug] 监听地址填写 0.0.0.0 时，只监听了 IPV6

### ISSUE THREAD

**Issue by ghost** [IrineSistiana/mosdns#591]
### 在提交之前，请确认

- [X] 我已经尝试搜索过 Issue ，但没有找到相关问题。
- [X] 我正在使用最新的 mosdns 版本(或者最新的 commit)，问题依旧存在。
- [X] 我仔细看过 wiki 后仍然无法自行解决该问题。
- [X] 我非常确定这是 mosdns 核心的问题。(如果是通过第三方衍生软件使用 mosdns 核心，不确定问题源头时，请先向衍生软件开发者提交问题。)

### mosdns 版本

1月16日自行编译的 v5 分支

### 操作系统

ubuntu 20.04

### Bug 描述和复现步骤

写出配置文件，监听地址 `0.0.0.0:53` ，然后利用 `service` 功能启动。接着，通过 `lsof -i :53` 查看端口占用情况，发现只监听了 IPV6。由于我启用了 tcp，所以尝试使用端口检测工具检测，发现无法通过 IPV4 连接。

其他端口也无法使用。

```
mosdns  2168 root    3u  IPv6  29180      0t0  UDP *:domain 
mosdns  2168 root    7u  IPv6  29181      0t0  TCP *:domain (LISTEN)
```

### 使用的配置文件

```yaml
log:
  level: warn

plugins:
  - tag: google
    type: forward
    args:
      upstreams:
        - addr: https://8.8.8.8/dns-query

  - type: udp_server
    args:
      entry: google
      listen: 0.0.0.0:53

  - type: tcp_server
    args:
      entry: google
      listen: 0.0.0.0:53

  - type: "http_server"
    args:
      listen: 0.0.0.0:8880
      src_ip_header: "X-Forwarded-For"
      entries:
        - path: /dns-query
          exec: google

  - type: tcp_server
    args:
      entry: google
      listen: 0.0.0.0:853
      cert: "/cert/cert.crt"
      key: "/cert/key.key"
```

**Comment by suienzan** [comment]
```yaml
  - type: udp_server
    args:
      entry: google
      listen: 0.0.0.0:53

  - type: tcp_server
    args:
      entry: google
      listen: 0.0.0.0:53

  - type: udp_server
    args:
      entry: google
      listen: "[::1]:53"

  - type: tcp_server
    args:
      entry: google
      listen: "[::1]:53"
```
