### ISSUE TITLE
不懂就问：请问v5 当前以什么形式读取 v2ray-geodata？ 或是不再支持？

### ISSUE THREAD

**Issue by sbwml** [IrineSistiana/mosdns#594]
V4 可以用这样的方式
```yaml
data_providers:
  - tag: geosite
    file: "geosite.dat"

plugins:
  - tag: query_cn_domain
    type: query_matcher
    args:
      domain:
        - "provider:geosite:cn"
```

但是V5 似乎不再接受这种使用方式，在 wiki 数据插件未找到任何相关信息 https://irine-sistiana.gitbook.io/mosdns-wiki/mosdns-v5/ru-he-pei-zhi-mosdns/shu-ju-cha-jian

在线等一个大佬！！！
