### ISSUE TITLE
v5不支持直接读取geosite.dat了吗？那非cn怎么配置呢？

### ISSUE THREAD

**Issue by PHCSJC** [IrineSistiana/mosdns#596]
打算升v5，v3有个这样的配置，已知的非cn域名直接走forward_remote解析，那v5怎么实现这个呢？主要是域名文件怎么匹配呢？我把geosite.dat解包后发现里面有好几百个文件

```yaml
  # 匹配非本地域名的插件
  - tag: query_is_non_local_domain
    type: query_matcher
    args:
      domain:
        - 'ext:./geosite.dat:geolocation-!cn
```

**Comment by PHCSJC** [comment]
再请教2个问题，就不新开issue了
1.redirect在sequence里怎么用呢？文档里没看见哈
2.支持ipset吗？文档里也没看见呢，大佬

其实v3真的挺好的，也很稳定，在v3上面小修小补，个人觉得就完全足够了，大佬不喜请忽略，抱歉了！

**Comment by kunish** [comment]
> 

按V5的格式改一下不就得了

```yaml
plugins:
  - tag: "geolocation-!cn"
    type: domain_set
    args:
      files: ./geolocation-!cn.txt

  - tag: main_sequence
    type: sequence
    args:
      # ...省略
      - matches:
          - "qname $geolocation-!cn"
        exec: "forward 8.8.8.8"
      # ...省略
```
