### ISSUE TITLE
请教下配置文件的编写

### ISSUE THREAD

**Issue by Hades-001** [IrineSistiana/mosdns#6]
以下是我的配置文件

```
log:
  level: ""
  file: ""
server:
  bind:
    - udp://127.0.0.1:53300
    - tcp://127.0.0.1:53300
  max_udp_size: 1472
plugin:
  entry:
    - "route1"
  router: []
  matcher: []
  functional: []
  plugin:
    - tag: "local_ecs"
      type: ecs
      args:
        auto: false
        force_overwrite: false
        ipv4: ""
        ipv6: ""
        mask4: 24
        mask6: 32
    - tag: "local_dnsserver"
      type: forward
      args:
        bootstrap:
          - https://223.5.5.5/dns-query
        deduplicate: false
        insecure_skip_verify: false
        timeout: 10
        upstream:
          - addr: tcp://101.6.6.6:5353
            ip_addr: []
          - addr: https://dns.alidns.com/dns-query
            ip_addr:
              - 223.5.5.5
              - 223.6.6.6
    - tag: "remote_dnsserver"
      type: forward
      args:
        bootstrap:
          - https://223.5.5.5/dns-query
          - https://1.1.1.1/dns-query
        deduplicate: false
        insecure_skip_verify: false
        timeout: 10
        upstream:
          - addr: https://dns.google/dns-query
            ip_addr:
              - 8.8.8.8
              - 8.8.4.4
          - addr: https://cloudflare-dns.com/dns-query
            ip_addr:
              - 1.1.1.1
              - 1.0.0.1
    - tag: "chn_domain"
      type: domain_matcher
      args:
        check_cname: true
        check_question: true
        domain:
          - "./chn_domain.list"
          - "./geosite.dat:cn"
    - tag: "non_chn_domain"
      type: domain_matcher
      args:
        check_cname: true
        check_question: true
        domain:
          - "./non_chn_domain.list"
          - "./geosite.dat:geolocation-!cn"
    - tag: "chn_ip"
      type: ip_matcher
      args:
        ip:
          - "./chn_ip.list"
          - "./geoip.dat:cn"
    - tag: "qtype_A_AAAA"
      type: qtype_matcher
      args:
        type:
          - 1
          - 28
    - tag: "route1"
      type: sequence
      args:
        exec:
          - if:
              - "!match_qtype_A_AAAA"
            exec:
              - forward_local_dnsserver
            goto: end
          - if:
              - "match_chn_domain"
              - "match_chn_ip"
            exec:
              - add_local_ecs
              - forward_local_dnsserver
            goto: end
          - if:
              - "match_non_chn_domain"
            exec:
              - forward_remote_dnsserver
            goto: end
          - forward_remote_dnsserver
        next: end
    - tag: "block"
      type: blackhole
      args:
        rcode: 0
```

运行时会提示以下内容

```
WARN[0003] [{www.baidu.com. 1 1}], from: 192.168.0.196:63279: query failed: plugin tag route1 not not defined 
WARN[0016] [{www.youtube.com. 1 1}], from: 192.168.0.196:63280: query failed: plugin tag route1 not not defined
```

请教下这份配置要怎么改才能正常使用？
