### ISSUE TITLE
问一下matches 怎么实现 “或”呢？

### ISSUE THREAD

**Issue by wangmice** [IrineSistiana/mosdns#607]
多个条件是and的关系，如果要实现或的关系怎么处理？
比如 if A and B or C 后执行一条规则D。
如果分成两个matches写：
```
- matches:
   - A
   - B
   exec: D
 - matches: C
    exec: D
```
还是达不到上述的效果，如果两个matches都匹配的话，D要执行两次了。
