### ISSUE TITLE
[Bug] fast_forward不过滤refused的结果

### ISSUE THREAD

**Issue by zhaibin18** [IrineSistiana/mosdns#635]
### 在提交之前，请确认

- [X] 我已经尝试搜索过 Issue ，但没有找到相关问题。
- [X] 我正在使用最新的 mosdns 版本(或者最新的 commit)，问题依旧存在。
- [X] 我仔细看过 wiki 后仍然无法自行解决该问题。
- [X] 我非常确定这是 mosdns 核心的问题。(如果是通过第三方衍生软件使用 mosdns 核心，不确定问题源头时，请先向衍生软件开发者提交问题。)

### mosdns 版本

v4.5.3-0-g760a660

### 操作系统

openwrt

### Bug 描述和复现步骤

根据 #493 的反馈，当上游返回refused时，fast_forward会过滤其结果，但是当上游返回refused不支持递归，或者 #621 不支持ecs时，fast_forward都没有过滤refused的结果。

### 使用的配置文件

```yaml
- tag: 'ecs0'
    type: 'ecs'
    args:
      auto: false
      ipv4: '193.110.202.3'
      force_overwrite: true
      mask4: 24


        - forward_local
        - if: response_has_local_ip
          exec:
            - _return
        - ecs0
        - forward_remote
```
