### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by fengguowudi** [IrineSistiana/mosdns#639]
### 在提交之前，请确认

- [X] 我已经尝试搜索过 Issue ，但没有找到相关问题。
- [X] 我正在使用最新的 mosdns 版本(或者最新的 commit)，问题依旧存在。
- [X] 我仔细看过 wiki 后仍然无法自行解决该问题。
- [ ] 我非常确定这是 mosdns 核心的问题。(如果是通过第三方衍生软件使用 mosdns 核心，不确定问题源头时，请先向衍生软件开发者提交问题。)

### mosdns 版本

v5.1.1

### 操作系统

openwrt

### Bug 描述和复现步骤

![image](https://user-images.githubusercontent.com/55879152/224459207-2ba59d34-9aa4-44af-bcee-6e4699d5861f.png)

于第一次访问dns泄露测试时，不会出现dns泄露问题，log中有访问记录出现。但是当第n次访问时，疑似命中缓存，log里并没有访问该网站的记录，并且dns全部变成国内dns，出现dns泄露问题。
![image](https://user-images.githubusercontent.com/55879152/224459474-065339c4-e37f-48bd-98b4-08f9d266f986.png)

第一次访问情况如上

稳定复现

### 使用的配置文件

```yaml
log:
  level: info
  production: true

plugins: 
  - tag: "direct_domain"
    type: domain_set
    args:
      files:
        - "/etc/mosdns/rule/geosite_cn.txt"

  - tag: "direct_ip"
    type: ip_set
    args:
      files:
        - "/etc/mosdns/rule/geoip_cn.txt"         

  - tag: "cache"
    type: cache
    args:
      size: 65536
      lazy_cache_ttl: 86400

  - tag: "remote_forward"
    type: forward
    args:
      concurrent: 2
      upstreams: 
        - addr: "tls://1.0.0.1"
          socks5: "127.0.0.1:1080"
          idle_timeout: 86400     
        - addr: "tls://8.8.4.4"
          socks5: "127.0.0.1:1080"
          idle_timeout: 86400

  - tag: "local_forward"
    type: forward
    args:
      concurrent: 2
      upstreams: 
        - addr: "https://223.5.5.5/dns-query"
          idle_timeout: 86400 

  - tag: "ttl_sequence"
    type: sequence
    args:
      - exec: ttl 600-3600
      - exec: accept

  - tag: "local_sequence"
    type: sequence
    args:
      - exec: query_summary local_forward
      - exec: $local_forward
      - exec: goto ttl_sequence

  - tag: "remote_sequence"
    type: sequence
    args:
      - exec: query_summary remote_forward
      - exec: $remote_forward
      - matches: "resp_ip $direct_ip"
        exec: goto local_sequence
      - exec: goto ttl_sequence

  - tag: "main_sequence"
    type: sequence
    args:
      - exec: prefer_ipv4
      - exec: $cache
      - matches: has_resp
        exec: accept
      - matches: "qname $direct_domain"
        exec: goto local_sequence
      - exec: goto remote_sequence

  - type: udp_server
    args:
      entry: main_sequence 
      listen: 0.0.0.0:5335
```

### mosdns 的 log 记录

```txt
{"level":"info","ts":1678500551.7012308,"logger":"remote_sequence.r0","msg":"remote_forward","uqid":286,"client":"::ffff:127.0.0.1","qname":"txqul02plad0jbw4wsk77eagcn9k3r3dq1zopnjt-17.ipleak.net.","qtype":65,"qclass":1,"rcode":0,"elapsed":0.257054314}
{"level":"info","ts":1678500551.7133152,"logger":"remote_sequence.r0","msg":"remote_forward","uqid":285,"client":"::ffff:127.0.0.1","qname":"txqul02plad0jbw4wsk77eagcn9k3r3dq1zopnjt-17.ipleak.net.","qtype":1,"qclass":1,"rcode":0,"elapsed":0.269706984}
{"level":"info","ts":1678500552.3001478,"logger":"remote_sequence.r0","msg":"remote_forward","uqid":288,"client":"::ffff:127.0.0.1","qname":"txqul02plad0jbw4wsk77eagcn9k3r3dq1zopnjt-18.ipleak.net.","qtype":65,"qclass":1,"rcode":0,"elapsed":0.263946097}
{"level":"info","ts":1678500552.3013601,"logger":"remote_sequence.r0","msg":"remote_forward","uqid":287,"client":"::ffff:127.0.0.1","qname":"txqul02plad0jbw4wsk77eagcn9k3r3dq1zopnjt-18.ipleak.net.","qtype":1,"qclass":1,"rcode":0,"elapsed":0.266439763}
{"level":"info","ts":1678500552.8592772,"logger":"remote_sequence.r0","msg":"remote_forward","uqid":290,"client":"::ffff:127.0.0.1","qname":"txqul02plad0jbw4wsk77eagcn9k3r3dq1zopnjt-19.ipleak.net.","qtype":65,"qclass":1,"rcode":0,"elapsed":0.25530841}
{"level":"info","ts":1678500552.8793385,"logger":"remote_sequence.r0","msg":"remote_forward","uqid":289,"client":"::ffff:127.0.0.1","qname":"txqul02plad0jbw4wsk77eagcn9k3r3dq1zopnjt-19.ipleak.net.","qtype":1,"qclass":1,"rcode":0,"elapsed":0.275878463}
```
