### ISSUE TITLE
[Feature request] 从远程地址获取 domain_set 和 ip_set

### ISSUE THREAD

**Issue by pcmid** [IrineSistiana/mosdns#662]
### 希望添加的功能

目前 `domain_set` 和 `ip_set` 两种只支持从本地文件获取配置, 同时也没有 reload 机制, 希望加上能启动时从远程如 http 获取对应配置的功能, 并提供定时刷新的能力.

当前设想了配置格式是
```yaml
- tag: local_ip
  type: ip_set
  args:
    files:
    - /etc/mosdns/ip_list.txt
    - /etc/mosdns/myvpsip.txt
    remote:
    - http://example.com/iplist.txt # 远程的 iplist
    interval: 1h # 定时刷新时间
```
亦或是在一个 `files` 块中
```yaml
- tag: local_ip
  type: ip_set
  args:
    files:
    - /etc/mosdns/ip_list.txt
    - /etc/mosdns/myvpsip.txt
    - http://example.com/iplist.txt # 远程的 iplist
    interval: 1h # 定时刷新时间
```
