### ISSUE TITLE
[Bug] windows关机的时候，“dump_file: ./cache.dump”不会生成缓存文件

### ISSUE THREAD

**Issue by yeezylife** [IrineSistiana/mosdns#666]
### 在提交之前，请确认

- [X] 我已经尝试搜索过 Issue ，但没有找到相关问题。
- [X] 我正在使用最新的 mosdns 版本(或者最新的 commit)，问题依旧存在。
- [X] 我仔细看过 wiki 后仍然无法自行解决该问题。
- [X] 我非常确定这是 mosdns 核心的问题。(如果是通过第三方衍生软件使用 mosdns 核心，不确定问题源头时，请先向衍生软件开发者提交问题。)

### mosdns 版本

v5.1.3

### 操作系统

windows 11 64bit

### Bug 描述和复现步骤

使用如下配置文件，（查询几个之前未查询过的域名喂给缓存，）windows点击关机，cache.dump文件不会生成/刷新，试过几次都是这样。要不是有“dump_interval”默认的自动保存，windows下只靠关机岂不是永远无法生成cache.dump文件了。。。
这不太符合“# 缓存将在 mosdns 被关闭时保存。”的描述。

" # (实验性) 自动保存间隔。单位秒。默认 600。" 
这个自动保存，默认600秒，但是我实测也没有10分钟就保存一次。。再加上关机的时候也不保存，一天可能就自动保存了两三次，不知道为什么会这样。（https://github.com/IrineSistiana/mosdns/discussions/652 这里有人碰到类似的问题）

另外手动使用“mosdns service stop” 是可以生成cache.dump文件的。

### 使用的配置文件

```yaml
log:
  level: info
  production: true

plugins: 
  - tag: "direct_domain"
    type: domain_set
    args:
      files:
        - "./accelerated-domains.china.txt"

  - tag: "direct_ip"
    type: ip_set
    args:
      files:
        - "./CN-ip-cidr.txt"

  - tag: "cache"
    type: cache
    args:
      size: 65536
      lazy_cache_ttl: 86400
      dump_file: ./cache.dump
      
  - tag: "remote_forward"
    type: forward
    args:
      concurrent: 2
      upstreams: 
        - addr: "https://mozilla.cloudflare-dns.com/dns-query"
          dial_addr: "104.16.248.249"
          socks5: "192.168.0.1:7891"
          idle_timeout: 86400
        - addr: "https://dns.google/dns-query"
          dial_addr: "8.8.4.4"
          socks5: "192.168.0.1:7891"
          idle_timeout: 86400

  - tag: "local_forward"
    type: forward
    args:
      concurrent: 2
      upstreams: 
        - addr: "https://223.5.5.5/dns-query"
          idle_timeout: 86400 
        - addr: "https://120.53.53.53/dns-query"
          idle_timeout: 86400

  - tag: "ttl_sequence"
    type: sequence
    args:
      - exec: ttl 600-3600
      - exec: accept

  - tag: "local_sequence"
    type: sequence
    args:
      - exec: query_summary local_forward
      - exec: $local_forward
      - exec: goto ttl_sequence

  - tag: "drop_sequence"
    type: sequence
    args:
      - exec: drop_resp
      - exec: goto local_sequence

  - tag: "remote_sequence"
    type: sequence
    args:
      - exec: query_summary remote_forward
      - exec: $remote_forward
      - matches: "resp_ip $direct_ip"
        exec: goto drop_sequence
      - exec: goto ttl_sequence

  - tag: "main_sequence"
    type: sequence
    args:
      - exec: prefer_ipv4
      - exec: $cache
      - matches: has_resp
        exec: accept
      - matches: "qname $direct_domain"
        exec: goto local_sequence
      - exec: goto remote_sequence
   
  - type: udp_server
    args:
      entry: main_sequence 
      listen: 0.0.0.0:53
```
