### ISSUE TITLE
[Bug] nftset mask not work as expected

### ISSUE THREAD

**Issue by Dachtire** [IrineSistiana/mosdns#667]
### 在提交之前，请确认

- [x] 我已经尝试搜索过 Issue ，但没有找到相关问题。
- [X] 我正在使用最新的 mosdns 版本(或者最新的 commit)，问题依旧存在。
- [X] 我仔细看过 wiki 后仍然无法自行解决该问题。
- [X] 我非常确定这是 mosdns 核心的问题。(如果是通过第三方衍生软件使用 mosdns 核心，不确定问题源头时，请先向衍生软件开发者提交问题。)

### mosdns 版本

v5.1.3-0-gac99eb1

### 操作系统

linux-amd64

### Bug 描述和复现步骤

for example, cloudflare.com get ipv4: 1.1.1.1, ipv6: 2606:4700::1111,
when the mask set to ipv4/32, ipv6/128, 
wrong result in nftables is {1.1.1.1-255.255.255.255}, {2606:4700::1111-ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff},
which supposed to be {1.1.1.1}, {2606:4700::1111}.

### 使用的配置文件

```yaml
- tag: seq
    type: sequence
    args:
      - exec: forward 192.168.1.1
      - exec: nftset inet,table,set4,ipv4_addr,32 inet,table,set6,ipv6_addr,128
      - exec: accept

  - tag: srv
    type: udp_server
    args:
      entry: seq
      listen: "127.0.0.1:53"
```
