### ISSUE TITLE
[Bug] 小娱C5刷的openwrt，安装mosdns后采用自定义模式，无法启动，后台有报错，mosdns无日志。

### ISSUE THREAD

**Issue by zsdfz1406** [IrineSistiana/mosdns#695]
### 在提交之前，请确认

- [X] 我已经尝试搜索过 Issue ，但没有找到相关问题。
- [X] 我正在使用最新的 mosdns 版本(或者最新的 commit)，问题依旧存在。
- [X] 我仔细看过 wiki 后仍然无法自行解决该问题。
- [X] 我非常确定这是 mosdns 核心的问题。(如果是通过第三方衍生软件使用 mosdns 核心，不确定问题源头时，请先向衍生软件开发者提交问题。)

### mosdns 版本

V5.1.3

### 操作系统

openwrt

### Bug 描述和复现步骤

小娱C5刷的openwrt，安装mosdns后采用自定义模式，无法启动，后台有报错，mosdns无日志。
![image](https://github.com/IrineSistiana/mosdns/assets/71330673/0b35e4a9-5033-4fdc-a5d1-34f26fbb806c)
用了网上多个自定义配置都是这样的问题

### 使用的配置文件

```yaml
log:
  level: info

plugins:
  # 缓存
  - tag: cache
    type: cache
    args:
      size: 1024
      lazy_cache_ttl: 86400

  # 转发至本地服务器 DNSPod
  - tag: forward_local
    type: forward
    args:
      upstreams:
        - addr: https://1.12.12.12/dns-query

  # 转发至远程服务器 DNS.SB
  - tag: forward_remote
    type: forward
    args:
      upstreams:
        - addr: 45.11.45.11
        - addr: https://45.11.45.11/dns-query

  # fallback 用本地服务器 sequence
  # 返回不包含本地 ip 则 reject
  - tag: local_ip_sequence
    type: sequence
    args:
      - exec: $forward_local
      - matches: resp_ip &/etc/mosdns/CN-ip-cidr.txt
        exec: accept
      - exec: drop_resp # v5.1.2 以后不能用 reject

  # fallback 用远程服务器 sequence
  - tag: remote_sequence
    type: sequence
    args:
      - exec: $forward_remote
      - exec: accept

  # fallback 用远程服务器 sequence
  - tag: "fallback"
    type: "fallback"
    args:
      primary: local_ip_sequence
      secondary: remote_sequence
      threshold: 500
      always_standby: true

  # 主要的运行逻辑插件
  # sequence 插件中调用的插件 tag 必须在 sequence 前定义，
  # 否则 sequence 找不到对应插件。
  - tag: main_sequence
    type: sequence
    args:
      - matches: qname &/etc/mosdns/reject-list.txt
        exec: reject
      - exec: $cache
      - matches: has_resp
        exec: accept
      - matches: qname &/etc/mosdns/direct-list.txt
        exec: $forward_local
      - matches: has_resp
        exec: accept
      - exec: $fallback

  # 启动 udp 服务器。
  - tag: udp_server
    type: udp_server
    args:
      entry: main_sequence
      listen: 127.0.0.1:5335

  - tag: udp_server_v6
    type: udp_server
    args:
      entry: main_sequence
      listen: "[::1]:5335"
```

### mosdns 的 log 记录

```txt
Sun Jul  9 21:56:01 2023 daemon.info uwsgi-luci: Respawned uWSGI worker 1 (new pid: 23839)
Sun Jul  9 21:56:16 2023 daemon.info uwsgi-luci: uWSGI worker 2 cheaped.
Sun Jul  9 21:56:53 2023 daemon.info uwsgi-luci: Command failed: ubus call
Sun Jul  9 21:56:53 2023 daemon.info uwsgi-luci: service
Sun Jul  9 21:56:53 2023 daemon.info uwsgi-luci: delete
Sun Jul  9 21:56:53 2023 daemon.info uwsgi-luci: { "name": "mosdns" }
Sun Jul  9 21:56:53 2023 daemon.info uwsgi-luci: (Not found)
Sun Jul  9 21:56:53 2023 daemon.info uwsgi-luci: Respawned uWSGI worker 2 (new pid: 25302)
Sun Jul  9 21:56:54 2023 daemon.info uwsgi-luci: /etc/rc.common:
Sun Jul  9 21:56:54 2023 daemon.info uwsgi-luci: line 162:
Sun Jul  9 21:56:54 2023 daemon.info uwsgi-luci: can't create : nonexistent directory
Sun Jul  9 21:56:54 2023 daemon.info uwsgi-luci:
```

**Comment by kkkgo** [comment]
你这个是luci的日志，也许你可以去luci相关的作者问问

**Comment by sensec** [comment]
你的op也不是原版，建议换个版本试试。

**Comment by lengfwong** [comment]
没有log一般都是配置格式的问题，比如对齐不对，还有这里“- matches: resp_ip &/etc/mosdns/CN-ip-cidr.txt”，我不确定引用能带路径不，改成这样试试：
```
 - tag: CN-ip-cidr
    type: ip_set
    args:
      files:
        - "/etc/mosdns/CN-ip-cidr.txt"

  - tag: local_ip_sequence
    type: sequence
    args:
      - exec: $forward_local
      - matches: resp_ip &CN-ip-cidr
        exec: accept
      - exec: drop_resp # v5.1.2 以后不能用 reject
```
其他地方参照修改看看。
