### ISSUE TITLE
[Bug] 当后端DNS服务器只给出别名回应时，不对别名进行A解析

### ISSUE THREAD

**Issue by ltokok** [IrineSistiana/mosdns#703]
### 在提交之前，请确认

- [X] 我已经尝试搜索过 Issue ，但没有找到相关问题。
- [X] 我正在使用最新的 mosdns 版本(或者最新的 commit)，问题依旧存在。
- [X] 我仔细看过 wiki 后仍然无法自行解决该问题。
- [X] 我非常确定这是 mosdns 核心的问题。(如果是通过第三方衍生软件使用 mosdns 核心，不确定问题源头时，请先向衍生软件开发者提交问题。)

### mosdns 版本

v5.1.3-0-gac99eb1

### 操作系统

debian 11

### Bug 描述和复现步骤

mosdns 作为单位内部的DNS转发服务器，将指定的域名如   domain.edu.cn 指向内部权威DNS服务器(BIND9)，其余域名指向公共DNS服务器，工作一切正常。直到这种情况的出现：
在权威服务器上，有个别别名是指向CDN的，类似    test.domian.edu.cn   -->  xxx.cdn.com
此时，从互联网解析 test.domian.edu.cn ，返回 xxx.cdn.com 对应的IP地址。从mosdns解析 test.domian.edu.cn ，返回的是 xxx.cdn.com 的名称 而没有IP地址。
为了对比验证，使用unbound做转发服务器测试，unbound则对返回的别名进行解析。
请问这是否需要在mosdns上进行相应的配置，还是说mosdns设计时没有考虑这种情况？

### 使用的配置文件

```yaml
log:
   level: error
   production: false
   file: "/var/log/mosdns.log"

 api:
   http: "172.17.1.34:8080"

 plugins:
  # cache
  - tag: cache
    type: cache
    args:
      size: 1024000
      lazy_cache_ttl: 86400

  - tag: forward_local
    type: forward
    args:
      concurrent: 2
      upstreams:
        - addr: udp://172.17.1.45
        - addr: udp://172.17.1.46

  - tag: forward_ali
    type: forward
    args:
      concurrent: 2
      upstreams:
        - addr: "https://223.5.5.5/dns-query"
        - addr: "https://223.6.6.6/dns-query"

  - tag: "hosts"
    type: hosts
    args:
      files:
        - "/etc/mosdns/hosts.txt"

  - tag: "local_domain"
    type: domain_set
    args:
      files:
        - "/etc/mosdns/local-list.txt"


  - tag: main_sequence
    type: sequence
    args:
      - exec: metrics_collector metrics
      - exec: $hosts
      - exec: query_summary hosts
      - matches: has_wanted_ans
        exec: accept

      - matches: qname $local_domain
        exec: $forward_local
      - matches: has_resp
        exec: accept

      - exec: $cache
      - exec: query_summary cache
      - matches: has_wanted_ans
        exec: accept
      - exec: query_summary qtype65
      - matches:
        - qtype 65
        exec: reject 0
      - exec: prefer_ipv4
      - exec: $forward_ali
      - matches: has_wanted_ans
        exec: accept
  # listen_services
  - tag: udp_server
    type: udp_server
    args:
      entry: main_sequence
      listen: :53
```

### mosdns 的 log 记录

```txt
C:\Users\ltoko>nslookup oauth2.api.domain.edu.cn. 172.17.1.45
服务器:   内部权威DNS服务器
Address:  172.17.1.45

名称:    oauth2.api.domain.edu.cn


C:\Users\ltoko>nslookup oauth2.api.domain.edu.cn. 172.17.1.34
服务器:  MOSDNS 转发服务器
Address:  172.17.1.34

名称:    oauth2.api.domain.edu.cn


C:\Users\ltoko>nslookup oauth2.api.domain.edu.cn. 172.17.1.31
服务器:  UNBOUND 转发服务器
Address:  172.17.1.31

非权威应答:
名称:    d-qasokpl971.execute-api.cn-north-1.amazonaws.com.cn
Addresses:  71.131.212.189
          140.179.104.111
Aliases:  oauth2.api.domain.edu.cn


C:\Users\ltoko>nslookup oauth2.api.domain.edu.cn. 8.8.8.8
服务器:  dns.google
Address:  8.8.8.8

非权威应答:
名称:    d-qasokpl971.execute-api.cn-north-1.amazonaws.com.cn
Addresses:  71.132.14.158
          54.222.187.101
Aliases:  oauth2.api.domain.edu.cn
```
