### ISSUE TITLE
[Bug] forward 插件当启用 enable_http3 协议时，`bootstrap` 不起作用

### ISSUE THREAD

**Issue by sbwml** [IrineSistiana/mosdns#708]
### 在提交之前，请确认

- [X] 我已经尝试搜索过 Issue ，但没有找到相关问题。
- [X] 我正在使用最新的 mosdns 版本(或者最新的 commit)，问题依旧存在。
- [X] 我仔细看过 wiki 后仍然无法自行解决该问题。
- [x] 我非常确定这是 mosdns 核心的问题。(如果是通过第三方衍生软件使用 mosdns 核心，不确定问题源头时，请先向衍生软件开发者提交问题。)

### mosdns 版本

v5.1.3

### 操作系统

openwrt

### Bug 描述和复现步骤

`https://dns.alidns.com/dns-query` 阿里云公共 DNS 支持 DNS-over-HTTP/3 协议，但启用 `enable_http3: true` 后，bootstrap dns 无法解析出`dns.alidns.com` 域名的 IP 地址，导致无法正常使用。当禁用 HTTP3 协议后 `enable_http3: false`，bootstrap dns 可以正常解析出`dns.alidns.com` 域名 IP 地址。

目前反人类的解决方法只有设置一个hosts 规则写死 ip 地址 `dns.alidns.com 223.5.5.5 223.6.6.6`，才能正常通过 `enable_http3: true` 去使用 DNS-over-HTTP/3。

### 使用的配置文件

```yaml
- tag: forward_local
    type: forward
    args:
      concurrent: 1
      upstreams:
        - addr: "https://dns.alidns.com/dns-query"
          bootstrap: 119.29.29.29
          max_conns: 2
          enable_http3: true
```
