### ISSUE TITLE
[Feature request] cache 可以跳过不缓存

### ISSUE THREAD

**Issue by skill7899** [IrineSistiana/mosdns#735]
### 希望添加的功能

- tag: main_sequence
    type: sequence
    args:
      - exec: $hosts
      - exec: jump has_resp_sequence
      - matches:
        - "!qname $ddnslist"
        - "!qname $blocklist"
        - "!qname $adlist"
        - "!qname $local_ptr"
        exec: $lazy_cache
      - exec: $redirect
      - exec: jump has_resp_sequence
      - exec: $query_is_apple_domain
      - exec: jump has_resp_sequence
      - exec: $query_is_ddns_domain
      - exec: jump has_resp_sequence
      - exec: $query_is_whitelist_domain
      - exec: jump has_resp_sequence
      - exec: $query_is_reject_domain
      - exec: jump has_resp_sequence
      - exec: $query_is_greylist_domain
      - exec: jump has_resp_sequence
      - exec: $query_is_local_domain
      - exec: jump has_resp_sequence
      - exec: $query_is_no_local_domain
      - exec: jump has_resp_sequence
      - exec: $fallback

希望cache可以更灵活，比如远程的dns结果，我不要缓存，
执行到$query_is_no_local_domain 的时候，我不想缓存他的结果，按目前配置是做不到的。
因为我远程的dns是一个fakeIp，缓存起来可能会导致异常。又或者我远程到的ip是一个cdn ip。
我也有曲线求国的办法，就是，cache 成功后判断一下响应结果，要是fakeIp就drop掉，继续执行。
可以exec: !cache 代表这次响应的结果不缓存
比如

    - exec: $query_is_no_local_domain
    - exec: !cache 
    - exec: jump has_resp_sequence

**Comment by skill7899** [comment]
或者添加cache的作用域，只在当前的sequence

**Comment by qingtian110** [comment]
```yaml
- matches:
  - "!qname $ddnslist"
  - "!qname $blocklist"
  - "!qname $adlist"
  - "!qname $local_ptr"
  exec: $lazy_cache
```

按你贴出来的配置，你这不是已经会条件缓存了吗？为什么还会问远程DNS不缓存的问题，这不是和你上面的意思一样的吗？

**Comment by qingtian110** [comment]
在你这个基础上直接把 `$query_is_no_local_domain` 所使用的数据库 `tag` 名称添加上去，它不就跳过缓存操作了吗？

**Comment by qingtian110** [comment]
> 希望cache可以更灵活，比如远程的dns结果，我不要缓存

另外 mosdns 是完全支持灵活缓存的，只要在需要的地方（比如国内）给它使用 sequence 内建操作的 `exec: cache` 就可以了，而不是使用独立的 lazy cache 插件。灵不灵活，主要体验在你怎么写配置文件！


最傻瓜的方法：扔掉你现有所有缓存操作，只在响应中做匹配，命中国内 IP 就缓存。

```yaml
  - tag: has_resp_sequence
    type: sequence
    args:
      - matches: "resp_ip $geoip_cn"
        exec: $lazy_cache
      - matches: has_resp
        exec: accept
```
