### ISSUE TITLE
[Feature request] 请求屏蔽 any 请求的插件功能加入

### ISSUE THREAD

**Issue by sbwml** [IrineSistiana/mosdns#737]
### 希望添加的功能

屏蔽 ANY 在公网部署 MosDNS 可以有效屏蔽对服务器的恶意消耗。[RFC8482](https://datatracker.ietf.org/doc/html/rfc8482)

CoreDNS 实现插件参考：https://github.com/coredns/coredns/tree/master/plugin/any

其效果为：
```txt
[root@centos ~]# q "@https://mydns.com/dns-query" www.qq.com any
www.qq.com. 2h21m22s HINFO "ANY obsoleted" "See RFC 8482"
```

虽然 mosdns 可以通过丢弃 255 (any) 请求类型的方式来实现，但是如果做成现成插件，会变得非常方便。

```yaml
  - tag: ""
    type: sequence
    args:
      - matches: qtype 255
        exec: reject 3
```

**Comment by IrineSistiana** [comment]
> 如果做成现成插件，会变得非常方便。

直接 match 255 需要两行配置

做成插件需要写三行。

```yaml
    args:
      - exec: reject_any
      - match: has_resp
         exec: accept
```
