### ISSUE TITLE
[BUG]forward 插件中args添加 fastest_ip 属性并设置为true后程序错误，设置为false后程序正常运行。

### ISSUE THREAD

**Issue by CooperChen453** [IrineSistiana/mosdns#74]
**出现了什么问题**
forward插件中args添加fastest_ip : true后程序出错，设置为false后程序正常运行。

描述一下问题的表现。可以直接附上截图或log。建议配置`logger`插件使用`debug`级别获取更详细的调试log。
![image](https://user-images.githubusercontent.com/46716251/107843611-8b8c8280-6e07-11eb-82ff-e3bb10c0277c.png)

```mosdns-winsw.err.log
2021-02-13T14:23:46.641+0800	debug	main_server	server/udp.go:87	new query	{"query": "www.baidu.com. 1 1 47684 41", "from": "[::1]:64114"}
2021-02-13T14:23:46.641+0800	debug	main_server	executable_seq/executable_cmd_sequence.go:40	exec executable plugin	{"query": "www.baidu.com. 1 1 47684 41", "exec": "_default_cache"}
2021-02-13T14:23:46.641+0800	debug	main_server	executable_seq/executable_cmd_sequence.go:40	exec executable plugin	{"query": "www.baidu.com. 1 1 47684 41", "exec": "main_sequence"}
2021-02-13T14:23:46.641+0800	debug	main_sequence	executable_seq/executable_cmd_sequence.go:130	exec matcher plugin	{"query": "www.baidu.com. 1 1 47684 41", "exec": "query_is_ad_domain", "result": false}
2021-02-13T14:23:46.641+0800	debug	main_sequence	executable_seq/executable_cmd_sequence.go:130	exec matcher plugin	{"query": "www.baidu.com. 1 1 47684 41", "exec": "query_is_local_domain", "result": true}
2021-02-13T14:23:46.641+0800	debug	main_sequence	executable_seq/executable_cmd_sequence.go:40	exec executable plugin	{"query": "www.baidu.com. 1 1 47684 41", "exec": "forward_local"}
2021-02-13T14:23:48.640+0800	debug	main_sequence	executable_seq/executable_cmd_sequence.go:40	exec executable plugin	{"query": "www.baidu.com. 1 1 47684 33", "exec": "_end"}
2021-02-13T14:23:48.640+0800	warn	main_server	server_handler/server_handler.go:95	entry returned an err	{"query": "www.baidu.com. 1 1 47684 33", "error": "main_sequence: context deadline exceeded"}
```

---

**如何重现**

描述一下如何重现该问题。请尽可能的包含：

mosdns 的版本号(`mosdns -v`)：
1.4.0
使用的启动参数或启动方式：
无特殊启动参数
操作系统和平台：
Windows 10 V1909
进行了什么操作导致了问题的出现：
forward 插件中args添加 fastest_ip 属性并设置为true后程序错误，设置为false后程序正常运行。
使用的配置文件：

```yaml
include: [ ]

log:
  level: debug
  file: ""

plugin:

  ################# 服务插件 ################

  - tag: main_server      # 启动服务器
    type: server
    args:
      entry:
        - _default_cache  # 缓存
        - main_sequence
      max_concurrent_queries: 0
      server:
        - protocol: udp
          addr: 127.0.0.1:53
        - protocol: tcp
          addr: 127.0.0.1:53
        - protocol: udp
          addr: "[::1]:53"
        - protocol: tcp
          addr: "[::1]:53"

  ################# 可执行插件 ################

  - tag: main_sequence
    type: sequence
    args:
      exec:
        - if:
            - query_is_ad_domain    # 已知的广告域名
          exec:
            - _block_with_nxdomain  # 屏蔽
            - _end

        - if:
            - query_is_local_domain   # 已知的本地域名
            - "!_query_is_common"     # 和不常见的请求类型
          exec:
            - forward_local           # 用本地服务器
            - _end

        - if:
            - query_is_non_local_domain  # 已知的非本地域名
          exec:
            - forward_remote             # 用远程服务器
            - _end

          # 剩下的域名用 IP 分流。
          # 有两种方案："顺序分流"或"并发分流"。
          # 下面的是"顺序分流"的配置。

        - forward_local               # 先请求转发至本地服务器
        - if:
            - response_has_local_ip   # 如果应答包含本地 IP
          goto: _end                  # 就直接采用结果
        - forward_remote              # 否则用远程服务器的结果

          # 如果想用"并发分流"逻辑。将上面的配置注释掉，然后从下面选择一个方式。
          # 注意: 如果上游支持连接复用(tcp,dot,doh)，谨慎使用并发分流。
          # 因为服务器响应延时不可预测，不正确配置会导致分流出错。详见下文`补充`。

          # 1. 使用 parallel 实现的"并发分流"逻辑。很像 ChinaDNS 的逻辑。
          #    用于 local 的 ping 延时远小于 remote 的场景。

        # - parallel:
        #     - - forward_local
        #       - if:
        #           - "!response_has_local_ip"  # 如果本地服务器返回的非本地 IP
        #         exec:
        #           - _drop_response            # 应答会被丢弃
        #     - - forward_remote

          # 2. 使用 fallback 实现的"并发分流"逻辑。
          #    用于 local 使用了连接复用的协议，或 ping 延时接近 remote 的场景。

        # - primary:
        #   - forward_local
        #   - if:
        #       - "!response_has_local_ip"
        #     exec:
        #       - _drop_response
        #   secondary:
        #     - forward_remote
        #   stat_length: 0        # 禁用常规的 fallback
        #   threshold: 0
        #   fast_fallback: 200    # 建议配置成 local 最大响应延时(注意:不是 ping 延时)的 2 倍。
        #   always_standby: true

  - tag: forward_local # 转发至本地服务器的插件
    type: forward
    args:
      upstream:
        - addr: https://223.5.5.5/dns-query
        - addr: 101.7.8.9:53

      fastest_ip: true            # 最快 IP 模式。

  - tag: forward_remote # 转发至远程服务器的插件
    type: forward
    args:
      upstream:
        - addr: quic://dns.adguard.com
        - addr: tls://cloudflare-dns.com
          ip_addr:
            - 1.1.1.1
        - addr: tls://dns.google
          ip_addr: # 服务器的 IP 地址。可以配置多个。如果配置了，则不会使用 bootstrap 服务器。
            - 8.8.8.8
        - addr: https://1.0.0.1/dns-query
          ip_addr:
            - 1.1.1.1
        - addr: https://8.8.8.8/dns-query
          ip_addr: # 服务器的 IP 地址。可以配置多个。如果配置了，则不会使用 bootstrap 服务器。
            - 8.8.8.8
      bootstrap:
        - tls://1.1.1.1
        - https://223.5.5.5/dns-query
      fastest_ip: true            # 最快 IP 模式。

  ################ 匹配器插件 #################

  - tag: query_is_local_domain         # 匹配本地域名的插件
    type: query_matcher
    args:
      domain:
        - "ext:./geosite.dat:cn"

  - tag: query_is_non_local_domain    # 匹配非本地域名的插件
    type: query_matcher
    args:
      domain:
        - "ext:./geosite.dat:geolocation-!cn"

  - tag: query_is_ad_domain           # 匹配广告域名的插件
    type: query_matcher
    args:
      domain:
        - "ext:./geosite.dat:category-ads-all"

  - tag: response_has_local_ip        # 匹配本地 IP的插件
    type: response_matcher
    args:
      ip:
        - "ext:./geoip.dat:cn"

````
