### ISSUE TITLE
[Feature request] 希望增加 ecs 内建匹配器

### ISSUE THREAD

**Issue by qingtian110** [IrineSistiana/mosdns#747]
### 希望添加的功能

在 v4 版本中，可以通过以下方式匹配 ecs ip 

```yaml
  - tag: query_ecs_has_cn_ip
    type: query_matcher
    args:
      ecs:
        - "provider:geoip:cn"

  - tag: "main_sequence"
    type: "sequence"
    args:
      exec:
        - if: "query_ecs_has_cn_ip"
          exec:
            - `do something`
```

在最新版本中新增了 ecs、EDNS0 转发的支持，在公网部署得到非常大的便捷，希望重新添加 v4 版本那种 ecs 匹配器，可以让公网部署的情况下，拥有更大的 DIY 空间。
