### ISSUE TITLE
[BUG] "query_matcher" doesn't work as expected after "ext:" introduced in 1.4.0

### ISSUE THREAD

**Issue by laggardkernel** [IrineSistiana/mosdns#76]
Update2:

Pre-release 1.5.0 中可能存在同样的 if 逻辑问题。

```
exec plugin     {"query": "image01.oneplus.cn. 1 1 47790 13", "exec": "match_local_src"}
exec plugin     {"query": "image01.oneplus.cn. 1 1 47790 13", "exec": "add_ecs"}
exec plugin     {"query": "image01.oneplus.cn. 1 1 47790 13", "exec": "forward_dnspod"}

```

之所以说”看起来“是因为 1.5.0 中日志格式变了，省去了匹配结果部分，如 `"result": false`。这个部分能不能保留一下？感觉还蛮有用的。

---

Update 1:

好像是 fallback 中 if exec 逻辑错误。明明 if 结果为 false，还是执行了 add_ecs。再简化一下日志

```
  - tag: forward_domestic
    type: fallback
    args:
      primary:
        - if:
          - '!match_local_src'
          exec:
            - add_ecs
```

```
exec matcher plugin     {"query": "image01.oneplus.cn. 1 1 13301 7", "exec": "match_local_src", "result": false}
exec executable plugin  {"query": "image01.oneplus.cn. 1 1 13301 7", "exec": "add_ecs"}
```

---

**出现了什么问题**

升级 1.4.0 后，在文件加入 `ext:` 前缀（唯一变化），启动后 `query_matcher` 不能正常工作。以下面 `add_ecs` 为例，配置为在非 local ip 时执行 add_ecs。本地请求原本不会执行 add_ecs 现在反而执行。

取消 `ext:` 前缀，回退 1.3.4 没有出现错误添加 ECS client ip 问题。

```txt
new query       {"query": "image01.oneplus.cn. 1 1 57040 1", "from": "127.0.0.1:50619"}
exec executable plugin  {"query": "image01.oneplus.cn. 1 1 57040 1", "exec": "chinadns_entry"}
exec executable plugin  {"query": "image01.oneplus.cn. 1 1 57040 1", "exec": "match_hosts"}
exec executable plugin  {"query": "image01.oneplus.cn. 1 1 57040 1", "exec": "_default_cache"}
exec executable plugin  {"query": "image01.oneplus.cn. 1 1 57040 1", "exec": "chinadns_before_request"}
exec matcher plugin     {"query": "image01.oneplus.cn. 1 1 57040 1", "exec": "no_domain", "result": false}
exec matcher plugin     {"query": "image01.oneplus.cn. 1 1 57040 1", "exec": "match_default_refuse", "result": false}
exec matcher plugin     {"query": "image01.oneplus.cn. 1 1 57040 1", "exec": "match_block_domain", "result": false}
exec matcher plugin     {"query": "image01.oneplus.cn. 1 1 57040 1", "exec": "match_domestic_domain", "result": true}
exec executable plugin  {"query": "image01.oneplus.cn. 1 1 57040 1", "exec": "forward_domestic"}
exec matcher plugin     {"query": "image01.oneplus.cn. 1 1 57040 1", "exec": "match_local_src", "result": false}
####### 此处错误添加了 ecs client ip，1.3.4 中不会执行此步骤
exec executable plugin  {"query": "image01.oneplus.cn. 1 1 57040 1", "exec": "add_ecs"}
exec executable plugin  {"query": "image01.oneplus.cn. 1 1 57040 1", "exec": "forward_dnspod"}
received response       {"query": "image01.oneplus.cn. 1 1 57040 1", "from": "tls://dns.pub:853"}
goto plugin     {"query": "image01.oneplus.cn. 1 1 57040 1", "goto": "chinadns_after_request"}
exec matcher plugin     {"query": "image01.oneplus.cn. 1 1 57040 1", "exec": "match_bogus_ip", "result": false}
entry returned  {"query": "image01.oneplus.cn. 1 1 57040 1", "status": "responded"}

```

必要配置（如果需要完整配置请再联系）

```yaml
  - tag: forward_114
    type: fast_forward
    args:
      deduplicate: false
      upstream:
        - protocol: udp
          addr: 114.114.114.114
          trusted: false
          timeout: 5
          idle_timeout: 10
          max_conns: 1
  - tag: forward_dnspod
    type: forward
    args:
      bootstrap:
        - tls://223.5.5.5
      deduplicate: false
      insecure_skip_verify: false
      timeout: 3
      upstream:
        - addr: tls://dns.pub
          trusted: false

  - tag: forward_domestic
    type: fallback
    args:
      primary:
        - if:
          - '!match_local_src'
          exec:
            - add_ecs
        - forward_dnspod
      secondary:
        - forward_114
      stat_length: 10     # 统计长度。默认 10。
      threshold: 3        # 触发阈值。不可大于统计长度。默认 5。
      fast_fallback: 0
      always_standby: false

  - tag: match_local_src
    type: query_matcher
    args:
      logical_and: true
      client_ip:
        - "ext:./local_ip.list"

  - tag: add_ecs
    type: ecs
    args:
      auto: true # 是否自动将客户端地址作为 ECS 附加到请求。如果为 true，则预设地址不会被使用。
      force_overwrite: false  # 如果请求已有 ECS，是否覆盖。
      mask4: 24               # 用于 ipv4 地址的掩码。
      mask6: 48               # 用于 ipv6 地址的掩码。
      # ipv4: "1.2.3.4"         # 预设的 ipv4 地址。如果非空，会附加在 A 请求中。
      # ipv6: "2001:dd8:1a::"   # 预设的 ipv6 地址。如果非空，会附加在 AAAA 请求中。
```

`local_ip.list`

```
# https://zh.wikipedia.org/zh-hans/%E4%BF%9D%E7%95%99IP%E5%9C%B0%E5%9D%80
0.0.0.0/8
0.255.255.255
10.0.0.0/8
100.64.0.0/10
127.0.0.0/8
169.254.0.0/16
172.16.0.0/12
192.0.0.0/24
192.0.2.0/24
192.168.0.0/16
198.18.0.0/15
198.51.100.0/24
203.0.113.0/24
224.0.0.0/4
240.0.0.0/4
255.255.255.255/32

::/128
::1/128
100::/64
2001::/32
2001:10::/28
2001:20::/28
2001:db8::/32
fc00::/7
fe80::/10
ff00::/8
```

---

**如何重现**

描述一下如何重现该问题。请尽可能的包含：

mosdns 的版本号(`mosdns -v`)：1.4.0

使用的启动参数或启动方式：mosdns -c config.yaml

操作系统和平台：macOS 10.14.6

进行了什么操作导致了问题的出现：升级 1.4.0
