### ISSUE TITLE
[Bug] IPv6 DNS Server [2620:fe::fe] 识别问题

### ISSUE THREAD

**Issue by FrankLiangCN** [IrineSistiana/mosdns#772]
### 在提交之前，请确认

- [X] 我已经尝试搜索过 Issue ，但没有找到相关问题。
- [X] 我正在使用最新的 mosdns 版本(或者最新的 commit)，问题依旧存在。
- [X] 我仔细看过 wiki 后仍然无法自行解决该问题。
- [X] 我非常确定这是 mosdns 核心的问题。(如果是通过第三方衍生软件使用 mosdns 核心，不确定问题源头时，请先向衍生软件开发者提交问题。)

### mosdns 版本

v5.3.1

### 操作系统

ubantu/apline Docker

### Bug 描述和复现步骤

在上游服务器中使用- addr: "2620:fe::fe" 格式配置，会将最后的 :fe 识别为端口，导致错误
如果 将IPv6地址加上括号后，- addr: "[2620:fe::fe]"，服务器地址识别正常，其它的IPv6地址不加 [] 均能正常识别

### 使用的配置文件

```yaml
- tag: forward_remote
    type: forward
    args:
      concurrent: 3
      upstreams:
        - addr: "https://dns10.quad9.net/dns-query"    # Quad9 DNS
        - addr: "2620:fe::fe"       # Quad9 IPv6 DNS
        - addr: "2620:fe::9"        # Quad9 IPv6 DNS
```

### mosdns 的 log 记录

```txt
failed to init plugin: failed to init upstream #5: invalid server address, parse "udp://2620:fe::fe": invalid port ":fe" after host
```
