### ISSUE TITLE
[BUG]mosdns的fast_forward模块不能正确地处理IPv6地址

### ISSUE THREAD

**Issue by PussAzuki** [IrineSistiana/mosdns#79]
如题
当用 "[" 和 "]" 将IPv6地址包裹进去的话会出现如下错误：
` 'upstream[0].addr' expected type 'string', got unconvertible type '[]interface {}', value: '[2001:4860:4860::8844]'
`
当用 ' ’ (一堆英文单引号)将其包裹进去地话，会出现如下错误：
`dial tcp: address 2606:4700:4700::1001:443: too many colons in address"`

本想看看从forward切到fast_forward 能不能减少内存占用（目前遇到AGH和mosdns都是越用内存占用越多的情况，对比开启时能达到两倍的大小）结果意外的发现了bug 

1.3.4 时就测出来了

**Comment by IrineSistiana** [comment]
> 当用 "[" 和 "]" 将IPv6地址包裹进去的话会出现如下错误：

我用 ipv6 没有问题。

> 本想看看从forward切到fast_forward 能不能减少内存占用（目前遇到AGH和mosdns都是越用内存占用越多的情况，对比开启时能达到两倍的大小）

这个不好查。有条件的话，启动 mosdns 时候 加 -pprof 参数 `mosdns -pprof 127.0.0.1:8080`，然后 浏览器访问，去抓一下 heap?

或者你把完整的配置和系统配置发一下。

**Comment by PussAzuki** [comment]
那么我能先请教一下在 fast_forward 那边怎么设置IPv6的DNS上游？

```
tag: "forward_remote_dns"
type: fast_forward
args:
  deduplicate: true
  ca: [ ] 
  upstream:
    - protocol: doh
      addr: [2001:4860:4860:8888]
      timeout: 6
      idle_timeout: 120
      trusted: true
      server_name: dns.google
      url: https://dns.google/dns-query
      max_conns: 3
      insecure_skip_verify: false
```

这样子或者在addr那里加 ' ' 在我这都会出现上面说的第一个错误

```
tag: "forward_remote_dns"
type: fast_forward
args:
  deduplicate: true
  ca: [ ] 
  upstream:
    - protocol: doh
      addr: 2001:4860:4860:8888
      timeout: 6
      idle_timeout: 120
      trusted: true
      server_name: dns.google
      url: https://dns.google/dns-query
      max_conns: 3
      insecure_skip_verify: false
```

这样子或加上 ' ' 会出现第二个错误

**Comment by IrineSistiana** [comment]
emmmm, 应该同时套..

像这样， `addr:  '[2001:4860:4860:8888]'`

**Comment by PussAzuki** [comment]
我试过了，不管用

**Comment by PussAzuki** [comment]
我试过了，不管用

**Comment by PussAzuki** [comment]
'[2001:4860:4860:8888]' 与 [2001:4860:4860:8888] 同一个效果

**Comment by IrineSistiana** [comment]
```yaml  
- tag: forward_local                # 转发至本地服务器的插件
    type: fast_forward
    args:
      upstream:
        - protocol: udp
          addr: '[2400:3200::1]'
```
神奇。但我这样用没遇到问题。
