### ISSUE TITLE
配置问题请教

### ISSUE THREAD

**Issue by douglas-lee** [IrineSistiana/mosdns#8]
看到示例配置的这一段：
          

>           # 非 A AAAA 的请求另行处理
>           - if:
>               - "!match_qtype_A_AAAA" # 匹配非 A AAAA 的请求(插件类型: qtype_matcher)
>             exec:
>               - forward_local         # 转发至本地服务器(插件类型: forward)
>             goto: end                 # 结束(不再执行后续插件。立即返回应答至客户端)
> 
>           - forward_local             # 转发至本地服务器
> 
>           # 过滤出本地结果
>           - if:
>               - match_local_domain      # 匹配已知的本地域名
>               - match_local_ip          # 或应答包含本地 IP
>             goto: end                 # 结束
> 
>           # 剩余请求(既不是已知的本地域名，也没有返回本地 IP)
>           - forward_remote    # 转发至远程服务器
>         next: end             # 结束

有几个问题有点没明白：
1. 为何第二个forward_local不是放在exec里，而是在外面？
2. 为何过滤本地结果没有exec，且没有forward_local？

按照我的理解，这个按顺序从上至下执行的话，那这样写，执行起来好像会有问题？所以还请作者详细解释一下这部分的执行过程？以便更好的理解配置。

**Comment by IrineSistiana** [comment]
> 为何第二个forward_local不是放在exec里，而是在外面？

在exec里啊。这是个嵌套。外层是exec(往上看几行)。

wiki里有

```yaml
args:
  exec: # 执行序列，由多个命令构成。执行顺序为从上到下。
    - do_something # 命令可以直接是要执行的功能性插件。
    - do_something

    # 也可以是 if 条件命令块。
    - if: # 运行命令块的条件，必须是匹配器插件。可配置多个匹配器，关系为或运算。任意匹配器为真命令块就会被执行。
        - match_something
        - '!match_something' # `!` 前缀可实现取反。
      exec: [] # 嵌套的执行序列，可以为空。
      goto: other_sequence # 如果非空，重定向到此路由插件。如果为空，则不重定向(继续执行后面的序列)。
```

> 为何过滤本地结果没有exec，且没有forward_local？

上一步的forward_local请求完上游会产生一个应答，这个应答可以直接返回。不需要再请求一次。直接 end 就好了。

后面的forward_remote会对复写之前的应答。

**Comment by douglas-lee** [comment]
那我去掉外面那个forward_local，直接写在match_chn_domain里的exec是不是也是等效的？

**Comment by IrineSistiana** [comment]
不行。你要先请求上游，拿到应答后，match_local_ip 才生效。

**Comment by douglas-lee** [comment]
啊？那你帮我看下我现在这样配置有何问题？但是我现在这样配，貌似也能正常使用啊。

```
args:
        exec:
          # 非 A AAAA 的请求另行处理
          - if:
              - "!match_qtype_A_AAAA"
            exec:
              - forward_chn
              - add_ipset_chn
            goto: end

          - if:
              - match_nf_domain
            exec:
              - forward_nf
              - add_ipset_nf
            goto: end

          - if:
              - match_jp_domain
            exec:
              - forward_jp
              - add_ipset_jp
            goto: end

          - if:
              - match_us_domain
            exec:
              - forward_us
              - add_ipset_us
            goto: end
            
          - if:
              - match_chn_domain
              - match_chn_ip
            exec:
              - forward_chn
              - add_ipset_chn
            goto: end

          # 剩余请求(既不是已知的本地域名，也没有返回本地 IP)
          - forward_us                # 转发至远程服务器
          - add_ipset_us
        next: end                     # 结束
```

**Comment by IrineSistiana** [comment]
能用是能用，但只有域名分流。

match_local_ip 没起作用，因为没有应答给它匹配，所以永远返回 false。

**Comment by douglas-lee** [comment]
那要怎么改合适？就是把外面那个forward加上即可？

**Comment by IrineSistiana** [comment]
forward_chn 移上去

**Comment by Hades-001** [comment]
借楼请教下配置问题，我目前使用的配置文件如下：

```
exec:
  - if:
      - "!match_qtype_A_AAAA"
    exec:
      - forward_local_dnsserver
    goto: end
  - if:
      - "match_chn_domain"
      - "match_chn_ip"
    exec:
      - add_local_ecs
      - forward_local_dnsserver
    goto: end
  - if:
      - "match_non_chn_domain"
    exec:
      - forward_remote_dnsserver
    goto: end
  - forward_remote_dnsserver
next: end
```

根据该issue，要使 match_chn_ip 起作用，需要把 add_local_ecs 和 forward_local_dnsserver 提到上面去，但这样会使转发到 forward_remote_dnsserver 的请求也带上 ECS，我现在想实现仅转发到 forward_local_dnsserver 的请求带上 ECS，这个配置文件应该怎么修改下？

**Comment by IrineSistiana** [comment]
@Hades-001 这问题好像真的无解。

目前没有去掉ECS的方法。可能只能再加个 add_remote_ecs 把之前的ECS覆盖掉。

以后可能有.(几小时以后?)

**Comment by Hades-001** [comment]
@IrineSistiana 能不能把 ECS 功能部分加到 forward 插件上，这样好设置也更直观一点。

**Comment by IrineSistiana** [comment]
@Hades-001 不行。

**Comment by terrytw** [comment]
```
  - if:
      - "match_non_chn_domain"
    exec:
      - forward_remote_dnsserver
    goto: end

      - forward_local_dnsserver
  - if:
      - "match_chn_domain"
      - "match_chn_ip"
    exec:
      - add_local_ecs
    goto: end

  - forward_remote_dnsserver
next: end
```

这种写法不知道有什么问题不

**Comment by christaikobo** [comment]
```
      - forward_local_dnsserver

  - if:
      - "match_chn_domain"
      - "match_chn_ip"
    exec:
      - add_local_ecs
      - forward_local_dnsserver
    goto: end
```

这种写法会用第二次forward_local_dnsserver的结果覆盖第一次的结果吗？
