### ISSUE TITLE
用sequence模拟fallback，出现context deadline exceeded时程序会中断。

### ISSUE THREAD

**Issue by blog2i2j** [IrineSistiana/mosdns#800]
我用sequence模拟fallback，在某个DNS不通的时候，就会出现context deadline exceeded报错，然后程序就会再往下运行导致DNS无法解析了。
恳求修复网络引起的context deadline exceeded时能够按照不能获取继续往下正常流转程序。

===================================================
以下是原文

用途，某些内网域名先用内网DNS解析， 如果解析不成功再使用外网解析（内部域名内外网都可用，入口不同）
现在想先用10.66.60.22解析，不成功换119.29.29.29解析，内网解析没有问题。到外网的时候，结果都是在10.66这步结束了。程序不再流下去。

```
log:
  production: false
  level: info

plugins:

  - tag: "company_domain"
    type: domain_set
    args:
      files: "./company_domain.txt"

  - tag: "local_cn_forward"
    type: forward
    args:
        upstreams:
          - addr: "119.29.29.29"

  - tag: "company_forward"
    type: forward
    args:
        upstreams:
          - addr: "10.66.60.22"

  - tag: "company_sequence"
    type: sequence
    args:
      - exec: $company_forward
      - exec: query_summary

  - tag: "local_cn_sequence"
    type: sequence
    args:
      - exec: $local_cn_forward

  - tag: "company_sequence_1"
    type: sequence
    args:

      - exec: jump company_sequence
      - matches: "!has_resp"
        exec: jump local_cn_sequence


#main sequence
  - tag: "main_sequence"
    type: sequence
    args:
      - exec: prefer_ipv4

      #match company domain
      - matches: "qname $company_domain"
        exec: jump company_sequence_1


#dns server
  - tag: udp_server
    type: udp_server
    args:
      entry: main_sequence
      listen: 127.0.0.1:353
```

log如下：
2024-03-11T17:09:51.922+0800    WARN    udp_server      entry err       {"query": {"uqid": 1, "client": "127.0.0.1", "qname": "s04.sdec.com.", "qtype": 1, "qclass": 1, "elapsed": "5.0131446s"}, "edes": [{"info_code": 0, "extra_text": "context deadline exceeded"}]}
2024-03-11T17:09:51.922+0800    WARN    company_forward upstream error  {"uqid": 1, "qname": "s04.sdec.com.", "qtype": 1, "qclass": 1, "upstream": "10.66.60.22", "error": "context deadline exceeded"}
2024-03-11T17:09:56.923+0800    WARN    company_forward upstream error  {"uqid": 2, "qname": "s04.sdec.com.", "qtype": 1, "qclass": 1, "upstream": "10.66.60.22", "error": "context deadline exceeded"}
2024-03-11T17:09:56.923+0800    WARN    udp_server      entry err       {"query": {"uqid": 2, "client": "127.0.0.1", "qname": "s04.sdec.com.", "qtype": 1, "qclass": 1, "elapsed": "5.0002939s"}, "edes": [{"info_code": 0, "extra_text": "context deadline exceeded"}]}

_Originally posted by @blog2i2j in https://github.com/IrineSistiana/mosdns/discussions/799_

**Comment by sbwml** [comment]
如果稍微转圜一下呢？比如：

```yaml
log:
  production: false
  level: info

plugins:

  - tag: "company_domain"
    type: domain_set
    args:
      files: "./company_domain.txt"

  - tag: "local_cn_forward"
    type: forward
    args:
        upstreams:
          - addr: "119.29.29.29"

  - tag: "company_forward"
    type: forward
    args:
        upstreams:
          - addr: "10.66.60.22"

  - tag: "company_sequence"
    type: sequence
    args:
      - exec: $company_forward
      - exec: query_summary

  - tag: "local_cn_sequence"
    type: sequence
    args:
      - exec: $local_cn_forward

  - tag: company_sequence_1
    type: fallback
    args:
      primary: company_sequence
      secondary: local_cn_sequence
      threshold: 500
      always_standby: true

#main sequence
  - tag: "main_sequence"
    type: sequence
    args:
      - exec: prefer_ipv4

      #match company domain
      - matches: "qname $company_domain"
        exec: $company_sequence_1


#dns server
  - tag: udp_server
    type: udp_server
    args:
      entry: main_sequence
      listen: 127.0.0.1:353
```

直接让命中 `company_domain.txt` 列表的域名走 `fallback` 策略，而 fallback 首先查询 `10.66.60.22` ，在 500 毫秒内没有得到响应马上应答 `119.29.29.29` 的查询结果。
