### ISSUE TITLE
[Bug] 我的5.3.1的配置对于5.3.3不生效

### ISSUE THREAD

**Issue by zzaolv** [IrineSistiana/mosdns#855]
### 在提交之前，请确认

- [X] 我已经尝试搜索过 Issue ，但没有找到相关问题。
- [X] 我正在使用最新的 mosdns 版本(或者最新的 commit)，问题依旧存在。
- [X] 我仔细看过 wiki 后仍然无法自行解决该问题。
- [X] 我非常确定这是 mosdns 核心的问题。(如果是通过第三方衍生软件使用 mosdns 核心，不确定问题源头时，请先向衍生软件开发者提交问题。)

### mosdns 版本

V5.3.3

### 操作系统

openwrt

### Bug 描述和复现步骤

我在5.3.1版本能够生效的配置，在5.3.3无法启动

### 使用的配置文件

```yaml
log:
  level: info
  file: "/var/log/mosdns.log"

api:
  http: "0.0.0.0:9091"

plugins:
  # 缓存配置
  - tag: cache_local
    type: cache
    args:
      size: 1
      lazy_cache_ttl: 86400
      dump_file: /var/mosdns/cache.dump
      dump_interval: 3600

  - tag: hosts
    type: hosts
    args:
      files:
        - "/var/mosdns/hosts.txt"

  - tag: ddnslist
    type: domain_set
    args:
      files:
        - "/var/mosdns/ddnslist.txt"

  - tag: local_ptr
    type: domain_set
    args:
      files:
        - "/var/mosdns/local-ptr.txt"

  - tag: geosite_cn
    type: domain_set
    args:
      files:
        - /var/mosdns/cn.txt
        - /var/mosdns/CN.txt

  # 域名集合
  - tag: geosite_no_cn
    type: domain_set
    args:
      files:
        - /var/mosdns/gw.txt
        - /var/mosdns/GW.txt
        
  - tag: geoip_cn
    type: ip_set
    args:
      files:
        - /var/mosdns/cnip.txt
        - /var/mosdns/geoip_cn.txt

  # DNS转发配置
  - tag: forward_local
    type: forward
    args:
      concurrent: 1
      upstreams:
        - addr: "127.0.0.1:6153"
          bootstrap: 211.136.192.6
          enable_pipeline: false
          insecure_skip_verify: false
          idle_timeout: 30
          
  - tag: forward_remote
    type: forward
    args:
      concurrent: 1
      upstreams:
        - addr: "127.0.0.1:7874"
          bootstrap: 8.8.4.4
          enable_pipeline: false
          insecure_skip_verify: false
          idle_timeout: 60

  - tag: query_is_ddns_domain
    type: sequence
    args:
      - matches: qname $ddnslist
        exec: $forward_local
        
  # 本地查询序列
  - tag: sequence_local
    type: sequence
    args:
      - exec: $forward_local
      - matches: resp_ip $geoip_cn
        exec: ipset wlist,inet,24 wlist6,inet6,32
 #       exec: ipset wlist6,inet6,32
      - exec: accept
#      - matches:
#          - "rcode 0"
#          - "qtype 1 28"
#        exec: ttl 10-3600

  # 远程查询序列
  - tag: sequence_remote
    type: sequence
    args:
      - exec: prefer_ipv4
      - exec: $forward_remote
      - matches: "!resp_ip $geoip_cn"
        exec: ipset gfwlist,inet,24
      - exec: accept

  - tag: reject_domain
    type: sequence
    args:
      - matches:
        - qtype 12
        - qname $local_ptr
        exec: reject 3
      - matches: qtype 65
        exec: reject 3

  - tag: has_resp_sequence
    type: sequence
    args:
      - matches: qname $ddnslist
        exec: ttl 5-5
      - matches: "!qname $ddnslist"
        exec: ttl 10-3600
      - matches: has_resp
        exec: accept

  - tag: fallback
    type: fallback
    args:
      primary: sequence_local
      secondary: sequence_local
 #     secondary: sequence_remote
      threshold: 150
      always_standby: true

  # 主分流序列
  - tag: main_sequence
    type: sequence
    args:
      - exec: $hosts
      - exec: jump has_resp_sequence
      
      - matches:
        - "!qname $ddnslist"
        - "!qname $local_ptr" 
        exec: $cache_local
      
      - exec: $query_is_ddns_domain
      - exec: jump has_resp_sequence
      
      - exec: $reject_domain
      - exec: jump has_resp_sequence
      
      - matches: qname $geosite_cn
        exec: $sequence_local
      - exec: jump has_resp_sequence
      
      - matches: qname $geosite_no_cn
        exec: $sequence_remote
      - exec: jump has_resp_sequence
      
      - matches: "!resp_ip $geoip_cn"
        exec: $sequence_remote
      - exec: jump has_resp_sequence
      
      - matches: resp_ip $geoip_cn
        exec: $sequence_local
      - exec: jump has_resp_sequence
      - exec: $fallback
  # 服务器配置
  - tag: udp_server
    type: udp_server
    args:
      entry: main_sequence
      listen: ":5335"

  - tag: tcp_server
    type: tcp_server
    args:
      entry: main_sequence
      listen: ":5335"
```

### mosdns 的 log 记录

```txt
2024-11-14 02:16:22	INFO	loading plugin	{"tag": "cache_local", "type": "cache"}
2024-11-14 02:16:22	INFO	cache_local	cache dump loaded	{"entries": 0}
2024-11-14 02:16:22	INFO	loading plugin	{"tag": "hosts", "type": "hosts"}
2024-11-14 02:16:22	INFO	loading plugin	{"tag": "ddnslist", "type": "domain_set"}
2024-11-14 02:16:22	INFO	loading plugin	{"tag": "local_ptr", "type": "domain_set"}
2024-11-14 02:16:22	INFO	loading plugin	{"tag": "geosite_cn", "type": "domain_set"}
2024-11-14 02:16:22	INFO	starting api http server	{"addr": "0.0.0.0:9091"}
2024-11-14 02:16:22	INFO	starting shutdown sequences
2024-11-14 02:16:22	INFO	closing plugin	{"tag": "cache_local"}
2024-11-14 02:16:22	INFO	cache_local	cache dumped	{"entries": 0}
2024-11-14 02:16:22	INFO	all plugins were closed
```
