### ISSUE TITLE
[Bug] http3 forwarder keepalive timeout

### ISSUE THREAD

**Issue by hshh** [IrineSistiana/mosdns#868]
### 在提交之前，请确认

- [X] 我已经尝试搜索过 Issue ，但没有找到相关问题。
- [X] 我正在使用最新的 mosdns 版本(或者最新的 commit)，问题依旧存在。
- [X] 我仔细看过 wiki 后仍然无法自行解决该问题。
- [X] 我非常确定这是 mosdns 核心的问题。(如果是通过第三方衍生软件使用 mosdns 核心，不确定问题源头时，请先向衍生软件开发者提交问题。)

### mosdns 版本

v5.3.3-4-g525c394

### 操作系统

Ubuntu 23.10

### Bug 描述和复现步骤

There is keepalive timeout error log while enabled enable_http3 for forwarder.

### 使用的配置文件

```yaml
- tag: forwarder_1
    type: forward
    args:
      upstreams:
        - addr: https://host.domain/dns-query
          dial_addr: xx.xx.xx.xx
          enable_http3: true
```

### mosdns 的 log 记录

```txt
"error": "http request failed: Application error 0x100 (remote): keepalive timeout"}
```
