### ISSUE TITLE
[Bug] 下游收到的ECS scope一直为0，初步判断原因为上游响应被截断

### ISSUE THREAD

**Issue by jqyisbest** [IrineSistiana/mosdns#871]
### 在提交之前，请确认

- [x] 我已经尝试搜索过 Issue ，但没有找到相关问题。
- [x] 我正在使用最新的 mosdns 版本(或者最新的 commit)，问题依旧存在。
- [x] 我仔细看过 wiki 后仍然无法自行解决该问题。
- [x] 我非常确定这是 mosdns 核心的问题。(如果是通过第三方衍生软件使用 mosdns 核心，不确定问题源头时，请先向衍生软件开发者提交问题。)

### mosdns 版本

v5.3.3

### 操作系统

debian12

### Bug 描述和复现步骤

5.3版本中，mosdns似乎会截断上游返回的内容，进而导致下游认为ecs scope为0，如下图所示（1.12.12.12为mosdns上游，mosdns监听5353端口）：

![Image](https://github.com/user-attachments/assets/5c3a0114-e546-46a1-b7e3-fa23e52de893)
![Image](https://github.com/user-attachments/assets/bba40860-f3ad-458a-9bd7-231e6a6b18c4)

### 使用的配置文件

```yaml
# 日志设置
log:
  level: "debug"   # 日志级别。可选 "debug" "info" "warn" "error"。默认 "info"。
  file: "/var/log/mosdns/mosdns.log"
  production: false            # 纯 json 输出。


# []string, 从其他配置文件载入 plugins 插件设置。
# include 的插件会比本配置文件中的插件先初始化。
include: ["/etc/mosdns/config/mosdns_upstream.yml","/etc/mosdns/config/mosdns_rules.yml"]

# 插件设置
plugins:

  # ################ ECS序列 #################
  # 参见：https://irine-sistiana.gitbook.io/mosdns-wiki/mosdns-v5/ru-he-pei-zhi-mosdns/ke-zhi-xing-cha-jian#ecs_handler
  - tag: ecs_on
    type: "ecs_handler"
    args:
      forward: true # 是否转发来自下游的 ecs
      preset: "" # 发送预设 ecs
      send: false # 是否发送 ecs（发送客户端地址）
      mask4: 24 # ipv4 掩码。默认 24 | 12
      mask6: 48 # ipv6 掩码。默认 48 | 32

  - tag: ecs_local
    type: "ecs_handler"
    args:
      forward: false # 是否转发来自下游的 ecs
      preset: "154.26.190.88" # 发送本机公网IP
      send: false # 是否发送 ecs
      mask4: 24
      mask6: 48 

  - tag: ecs_off
    type: "ecs_handler"
    args:
      forward: false # 是否转发来自下游的 ecs
      preset: "" # 发送预设 ecs
      send: false # 是否发送 ecs
      mask4: 24
      mask6: 48 

  ################ 解析操作序列 #################

  # 响应操作
  - tag: has_resp_sequence
    type: sequence
    args:
      - matches: has_resp
        exec: accept

  # 国外解析
  - tag: resolve_global
    type: sequence
    args:
      - exec: query_summary resolve_global
      - exec: $ecs_local
      - exec: $forward_global

  # 国内解析
  # 返回非国内IP则 drop_resp
  - tag: resolve_cn
    type: sequence
    args:
      - exec: query_summary resolve_cn
      - exec: $ecs_on
      - exec: prefer_ipv4
      - exec: $forward_cn_tx
      # - matches: "!resp_ip $geoip_cn"
      #   exec: drop_resp
  
  # 兜底解析
  - tag: resolve_fallback
    type: sequence
    args:
      - exec: query_summary resolve_fallback
      - exec: $ecs_local
      - exec: prefer_ipv4
      - exec: $forward_global

  # ################ 分流判断序列 #################
  
  # 匹配本地域名
  - tag: query_for_cn_domain
    type: sequence
    args:
      - matches: qname $geosite_cn
        exec: $resolve_cn

 # 匹配国外域名
  - tag: query_for_global_domain
    type: sequence
    args:
      - matches: qname $geosite_global
        exec: $resolve_global

 # 匹配阻断域名
  - tag: query_for_reject_domain
    type: sequence
    args:
      # 屏蔽DNSSEC，解决ios系统的一些问题 ptr 12
      - matches: qtype 65
        exec: reject 0
      
      # 屏蔽广告
      - matches: qname $geosite_ad
        exec: black_hole 10.10.10.10 ::1

  # ################ 主序列 #################
  - tag: main_sequence
    type: sequence
    args:
      # 尝试命中自定义解析
      - exec: $hosts
      - exec: jump has_resp_sequence
      # 尝试命中阻断解析
      - exec: $query_for_reject_domain
      - exec: jump has_resp_sequence
      # 尝试命中国内解析
      - exec: $query_for_cn_domain
      - exec: jump has_resp_sequence
      # 尝试命中国外解析
      - exec: $query_for_global_domain
      - exec: jump has_resp_sequence
      # 命中兜底解析
      - exec: $resolve_fallback

  # mosdns监听localhost:5353
  # 此插件应位于最低部
  - tag: "udp_server"
    type: "udp_server"
    args:
      entry: main_sequence  # 可执行插件的 tag。
      listen: localhost:5353 # 监听地址。
```

### mosdns 的 log 记录

```txt

```
