### ISSUE TITLE
[BUG]proto: mismatching end group marker

### ISSUE THREAD

**Issue by x1iu** [IrineSistiana/mosdns#89]
**出现了什么问题**

描述一下问题的表现。可以直接附上截图或log。建议配置`logger`插件使用`debug`级别获取更详细的调试log。

```txt
2021-03-03T13:57:51.601Z	info	coremain/run.go:111	loading plugin	{"tag": "main_sequence"}
2021-03-03T13:57:51.601Z	info	coremain/run.go:111	loading plugin	{"tag": "forward_local"}
2021-03-03T13:57:51.601Z	info	coremain/run.go:111	loading plugin	{"tag": "forward_local_udp"}
2021-03-03T13:57:51.601Z	info	coremain/run.go:111	loading plugin	{"tag": "server"}
2021-03-03T13:57:51.601Z	info	coremain/run.go:111	loading plugin	{"tag": "forward_local_doh"}
2021-03-03T13:57:51.602Z	info	coremain/run.go:111	loading plugin	{"tag": "forward_remote"}
2021-03-03T13:57:51.602Z	info	coremain/run.go:111	loading plugin	{"tag": "query_is_local_domain"}
2021-03-03T13:57:51.603Z	info	coremain/run.go:111	loading plugin	{"tag": "query_is_non_local_domain"}
2021-03-03T13:57:51.605Z	fatal	coremain/run.go:113	failed to register plugin #7 query_is_non_local_domain: failed to init plugin [query_is_non_local_domain], failed to load file ext:./geosite.dat:geolocation-!cn: proto: mismatching end group marker
2021-03-03T13:57:51.603Z	fatal	coremain/run.go:113	failed to register plugin #6 query_is_local_domain: failed to init plugin [query_is_local_domain], failed to load file ext:./geosite.dat:cn: proto: mismatching end group marker
```

---

**如何重现**

描述一下如何重现该问题。请尽可能的包含：

mosdns 的版本号(`mosdns -v`)：1.6.1

使用的启动参数或启动方式：CMD [ "/opt/mosdns", "-c", "/config/config.yaml"]

操作系统和平台：docker, arm64

进行了什么操作导致了问题的出现：启动容器，就会报错

使用的配置文件：

```yaml
log:
  level: debug
  file: "/config/mosdns.log"
library: []
plugin:

################# 服务器 ################

  - tag: server
    type: server
    args:
      entry:
        - _default_cache
        - main_sequence
      server:
        - addr: 0.0.0.0:53
          protocol: udp
        - addr: 0.0.0.0:53
          protocol: tcp
        # - addr: '[::1]:53'
        #   protocol: udp
        # - addr: '[::1]:53'
        #   protocol: tcp

################# 可执行插件 ################

  - tag: main_sequence
    type: sequence
    args:
      exec:
        # - if:
        #     - query_is_ad_domain    # 已知的广告域名
        #   exec:
        #     - _block_with_nxdomain  # 屏蔽
        #     - _end
        # - if:
        #     # - query_is_local_domain   # 已知的本地域名
        #     - '!_query_is_common'     # 和不常见的请求类型
        #   exec:
        #     - forward_local_doh           # 用本地服务器
        #     - _end

        - if:
            - query_is_local_domain   # 已知的本地域名
            - '!_query_is_common'     # 和不常见的请求类型
          exec:
            - forward_local           # 用本地服务器
            - _end

        - if:
            - query_is_non_local_domain  # 已知的非本地域名
          exec:
            - forward_remote             # 用远程服务器
            - _end

        # 剩下的未知域名用 IP 分流。以下是"顺序分流"的逻辑。很稳定，不易出错。
        # 如果想用"并发分流"逻辑，从下文的 <并发分流示例> 里选择一个方案，
        # 然后将下面几行替换掉。
        - forward_local               # 先请求转发至本地服务器
        - if:
            - response_has_local_ip   # 如果(本地)应答包含本地 IP
          exec:
            - _end                    # 就直接采用结果
        - forward_remote              # 否则去请求远程服务器的结果

  - tag: forward_local                # 转发至本地服务器的插件
    type: sequence
    args:
      exec:
        - primary:
            - forward_local_udp
            - if:
                - '!response_has_local_ip'
              exec:
                - _drop_response
          secondary:
            - forward_local_doh
          stat_length: 10      # 统计长度。默认 0。禁用常规 fallback。可省略。
          threshold: 0        # 常规 fallback 触发阈值。不可大于统计长度。默认 0。可省略。

  - tag: forward_local_udp                # 转发至本地服务器的插件
    type: fast_forward
    args:
      deduplicate: true  # 是否请求去重。
      ca: [ ]             # 用于 TLS 验证的 CA 证书。仅适用于 `dot`，`doh` 协议。为空默认使用系统证书。
      upstream:           # 上游服务器。至少要配置一个。可配置多个，会并发请求全部服务器。
        - protocol: udp       # 服务器协议。可以是 `udp`, `tcp`, `dot/tls`, `doh/https`。
          addr: 192.168.3.1:53   # 服务器地址。不可为空。格式 `host:port`。
          timeout: 1          # 服务器响应超时时间。单位: 秒。默认 5。
          trusted: false       # 是否是可信服务器。
          max_conns: 5                      # 最大连接数。适用于全部协议。默认: 1。
        - protocol: udp       # 服务器协议。可以是 `udp`, `tcp`, `dot/tls`, `doh/https`。
          addr: 202.119.248.66:53   # 服务器地址。不可为空。格式 `host:port`。
          timeout: 1          # 服务器响应超时时间。单位: 秒。默认 5。
          trusted: false       # 是否是可信服务器。
          max_conns: 5                      # 最大连接数。适用于全部协议。默认: 1。

  - tag: forward_local_doh                # 转发至本地服务器的插件
    type: fast_forward
    args:
      deduplicate: true  # 是否请求去重。
      ca: [ ]             # 用于 TLS 验证的 CA 证书。仅适用于 `dot`，`doh` 协议。为空默认使用系统证书。
      upstream:           # 上游服务器。至少要配置一个。可配置多个，会并发请求全部服务器。
        - protocol: doh       # 服务器协议。可以是 `udp`, `tcp`, `dot/tls`, `doh/https`。
          addr: 223.5.5.5:443   # 服务器地址。不可为空。格式 `host:port`。
          timeout: 2          # 服务器响应超时时间。单位: 秒。默认 5。
          idle_timeout: 30    # 空连接超时时间。单位: 秒。默认值: `doh`: 30
                              # `tcp`,`dot`: 0 (禁用连接重用)。
          trusted: false       # 是否是可信服务器。
          socks5: ""  # socks5 服务器地址。格式 `host:port`。不支持用户名密码认证。不支持 `udp` 协议。
          server_name: alidns           # 服务器(证书)名。仅适用于 `dot` 协议。不可为空。
          url: https://223.5.5.5/dns-query # 服务器 URL。仅适用于 `doh` 协议。不可为空。
          max_conns: 5                      # 最大连接数。适用于全部协议。默认: 1。
          insecure_skip_verify: false # 是否禁用 TLS 验证。仅适用于 `dot`，`doh` 协议。

  - tag: forward_remote                # 转发至本地服务器的插件
    type: fast_forward
    args:
      deduplicate: true  # 是否请求去重。
      ca: [ ]             # 用于 TLS 验证的 CA 证书。仅适用于 `dot`，`doh` 协议。为空默认使用系统证书。
      upstream:           # 上游服务器。至少要配置一个。可配置多个，会并发请求全部服务器。
        - protocol: doh       # 服务器协议。可以是 `udp`, `tcp`, `dot/tls`, `doh/https`。
          addr: 45.77.180.10:443   # 服务器地址。不可为空。格式 `host:port`。
          timeout: 2          # 服务器响应超时时间。单位: 秒。默认 5。
          idle_timeout: 30    # 空连接超时时间。单位: 秒。默认值: `doh`: 30
                              # `tcp`,`dot`: 0 (禁用连接重用)。
          trusted: false       # 是否是可信服务器。
          socks5: ""  # socks5 服务器地址。格式 `host:port`。不支持用户名密码认证。不支持 `udp` 协议。
          server_name: alidns           # 服务器(证书)名。仅适用于 `dot` 协议。不可为空。
          url: https://dns.containerpi.com/dns-query # 服务器 URL。仅适用于 `doh` 协议。不可为空。
          max_conns: 5                      # 最大连接数。适用于全部协议。默认: 1。
          insecure_skip_verify: false # 是否禁用 TLS 验证。仅适用于 `dot`，`doh` 协议。
        - protocol: doh       # 服务器协议。可以是 `udp`, `tcp`, `dot/tls`, `doh/https`。
          addr: 104.28.16.209:443   # 服务器地址。不可为空。格式 `host:port`。
          timeout: 2          # 服务器响应超时时间。单位: 秒。默认 5。
          idle_timeout: 30    # 空连接超时时间。单位: 秒。默认值: `doh`: 30
                              # `tcp`,`dot`: 0 (禁用连接重用)。
          trusted: false       # 是否是可信服务器。
          socks5: ""  # socks5 服务器地址。格式 `host:port`。不支持用户名密码认证。不支持 `udp` 协议。
          server_name: alidns           # 服务器(证书)名。仅适用于 `dot` 协议。不可为空。
          url: https://doh.dns.sb/dns-query # 服务器 URL。仅适用于 `doh` 协议。不可为空。
          max_conns: 5                      # 最大连接数。适用于全部协议。默认: 1。
          insecure_skip_verify: false # 是否禁用 TLS 验证。仅适用于 `dot`，`doh` 协议。
        - protocol: doh       # 服务器协议。可以是 `udp`, `tcp`, `dot/tls`, `doh/https`。
          addr: 104.27.185.84:443   # 服务器地址。不可为空。格式 `host:port`。
          timeout: 2          # 服务器响应超时时间。单位: 秒。默认 5。
          idle_timeout: 30    # 空连接超时时间。单位: 秒。默认值: `doh`: 30
                              # `tcp`,`dot`: 0 (禁用连接重用)。
          trusted: false       # 是否是可信服务器。
          socks5: ""  # socks5 服务器地址。格式 `host:port`。不支持用户名密码认证。不支持 `udp` 协议。
          server_name: alidns           # 服务器(证书)名。仅适用于 `dot` 协议。不可为空。
          url: https://hhh.kkn.workers.dev/dns-query # 服务器 URL。仅适用于 `doh` 协议。不可为空。
          max_conns: 5                      # 最大连接数。适用于全部协议。默认: 1。
          insecure_skip_verify: false # 是否禁用 TLS 验证。仅适用于 `dot`，`doh` 协议。
        - protocol: doh       # 服务器协议。可以是 `udp`, `tcp`, `dot/tls`, `doh/https`。
          addr: 8.8.8.8:443   # 服务器地址。不可为空。格式 `host:port`。
          timeout: 2          # 服务器响应超时时间。单位: 秒。默认 5。
          idle_timeout: 30    # 空连接超时时间。单位: 秒。默认值: `doh`: 30
                              # `tcp`,`dot`: 0 (禁用连接重用)。
          trusted: false       # 是否是可信服务器。
          socks5: "192.168.3.4:20170"  # socks5 服务器地址。格式 `host:port`。不支持用户名密码认证。不支持 `udp` 协议。
          server_name: alidns           # 服务器(证书)名。仅适用于 `dot` 协议。不可为空。
          url: https://dns.google/dns-query # 服务器 URL。仅适用于 `doh` 协议。不可为空。
          max_conns: 5                      # 最大连接数。适用于全部协议。默认: 1。
          insecure_skip_verify: false # 是否禁用 TLS 验证。仅适用于 `dot`，`doh` 协议。

  ################ 匹配器插件 #################

  - tag: query_is_local_domain         # 匹配本地域名的插件
    type: query_matcher
    args:
      domain:
        - 'ext:./geosite.dat:cn'
        - 'ext:./geosite.dat:apple-cn'

  - tag: query_is_non_local_domain    # 匹配非本地域名的插件
    type: query_matcher
    args:
      domain:
        - 'ext:./geosite.dat:geolocation-!cn'

  - tag: query_is_ad_domain           # 匹配广告域名的插件
    type: query_matcher
    args:
      domain:
        - 'ext:./geosite.dat:category-ads-all'

  - tag: response_has_local_ip        # 匹配本地 IP的插件
    type: response_matcher
    args:
      ip:
        - 'ext:./geoip.dat:cn'
include: []

````
