### ISSUE TITLE
[Bug] ecs_handler 根本不会生效！

### ISSUE THREAD

**Issue by BaeKey** [IrineSistiana/mosdns#893]
### 在提交之前，请确认

- [x] 我已经尝试搜索过 Issue ，但没有找到相关问题。
- [x] 我正在使用最新的 mosdns 版本(或者最新的 commit)，问题依旧存在。
- [x] 我仔细看过 wiki 后仍然无法自行解决该问题。
- [x] 我非常确定这是 mosdns 核心的问题。(如果是通过第三方衍生软件使用 mosdns 核心，不确定问题源头时，请先向衍生软件开发者提交问题。)

### mosdns 版本

v5.3.3-0-g025823c

### 操作系统

debian12

### Bug 描述和复现步骤

配置如下：

  - tag: ecs
    type: "ecs_handler"
    args:
      forward: true
      preset: ""
      send: false
      mask4: 24
      mask6: 48

根本不会调用本地的IP，网上所有的配置我都测试过了，如果后来人看到了，不用试了，别浪费时间在这上面

### 使用的配置文件

```yaml
log:
    level: debug

plugins:
######################## 可执行插件 start ########################
  # 国内应答DNS
  - tag: cn_forward
    type: forward
    args:
      concurrent: 2
      upstreams:
        - addr: "223.5.5.5"
        - addr: "119.29.29.29"

  # 启用ECS 
  - tag: ecs
    type: "ecs_handler"
    args:
      forward: true
      send: false
      mask4: 24
      mask6: 48

######################## 数据插件 ########################

  # 国内IP
  - tag: geoip_cn
    type: ip_set
    args:
      files:
        - "/etc/mosdns/CN-ip-cidr.txt"

######################## Sequence 插件 ########################

  # 全部域名解析
  - tag: domain_sequence
    type: sequence
    args:
      - exec: ecs
      - exec: $cn_forward

  # 按顺序执行 
  - tag: main_sequence
    type: sequence
    args:
      - exec: $domain_sequence

######################## 服务器插件 ########################

  # http服务
  - tag: http
    type: "http_server"
    args:
      entries:
        - path: /dns-query
          exec: main_sequence
      src_ip_header: "X-Forwarded-For"
      listen: 127.0.0.1:8080
      idle_timeout: 10
```

### mosdns 的 log 记录

```txt

```
